In [2]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [3]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785 entries, 0 to 784
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       785 non-null    object
 1   hostname                        785 non-null    object
 2   platform                        785 non-null    object
 3   system                          785 non-null    object
 4   release                         785 non-null    object
 5   version                         785 non-null    object
 6   machine                         785 non-null    object
 7   processor                       785 non-null    object
 8   cpu_count_logical               785 non-null    int64
 9   cpu_count_physical              785 non-null    int64
 10  cpu_freq_max                    785 non-null    float64
 11  cpu_freq_current                785 non-null    float64
 12  memory_total_gb                 785 non-null    float64
 13  memory_available_gb             785 non-null    float64
 14  python_version                  785 non-null    object
 15  python_implementation           785 non-null    object
 16  cpu_brand                       785 non-null    object
 17  cpu_arch                        785 non-null    object
 18  dataset_size                    785 non-null    int64
 19  dataset_name                    785 non-null    object
 20  dataset_format                  785 non-null    object
 21  filter_group_pandas_seconds     784 non-null    float64
 22  filter_group_polars_seconds     785 non-null    float64
 23  filter_group_duckdb_seconds     785 non-null    float64
 24  filter_group_fireducks_seconds  398 non-null    float64
 25  statistics_pandas_seconds       784 non-null    float64
 26  statistics_polars_seconds       785 non-null    float64
 27  statistics_duckdb_seconds       785 non-null    float64
 28  statistics_fireducks_seconds    398 non-null    float64
 29  complex_join_pandas_seconds     784 non-null    float64
 30  complex_join_polars_seconds     785 non-null    float64
 31  complex_join_duckdb_seconds     785 non-null    float64
 32  complex_join_fireducks_seconds  398 non-null    float64
 33  timeseries_pandas_seconds       784 non-null    float64
 34  timeseries_polars_seconds       785 non-null    float64
 35  timeseries_duckdb_seconds       785 non-null    float64
 36  timeseries_fireducks_seconds    398 non-null    float64
 37  script_name                     785 non-null    object
dtypes: float64(20), int64(3), object(15)
memory usage: 233.2+ KB

In [4]:
# Removing fireduck for now because there is not data(yet)
#fireduck_columns = [col for col in b_df.columns if 'fireducks_' in col]
#b_df.drop(columns=fireduck_columns, inplace=True)

#b_df.info()

In [5]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(780, 38)

In [6]:
# Clean platform-based analysis now possible
wsl2_data = b_df[b_df['system'] == 'WSL2']
native_linux = b_df[b_df['system'] == 'Linux'] 
windows_data = b_df[b_df['system'] == 'Windows']

# Example: Compare FireDucks performance
fireducks_wsl2 = wsl2_data['filter_group_fireducks_seconds']
fireducks_linux = native_linux['filter_group_fireducks_seconds']

In [7]:
# Filtering by platform
#b_df = windows_data # Focus on Windows data for now

In [8]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(6) # Round to microseconds for better readability
b_df.head(3)

,timestamp,hostname,platform,system,release,version,machine,processor,cpu_count_logical,cpu_count_physical,...,statistics_fireducks_seconds,complex_join_pandas_seconds,complex_join_polars_seconds,complex_join_duckdb_seconds,complex_join_fireducks_seconds,timeseries_pandas_seconds,timeseries_polars_seconds,timeseries_duckdb_seconds,timeseries_fireducks_seconds,script_name
0,2025-08-28T19:37:29.241650,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,44.743244,6.037812,26.736806,NaN,22.656234,7.020198,3.894986,NaN,benchmark_01.py
1,2025-08-28T21:16:05.419895,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,23.235775,1.426380,4.835438,NaN,12.861529,2.425745,0.614240,NaN,benchmark.py
2,2025-08-28T21:25:30.654371,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,28.530276,1.482855,5.431484,NaN,16.994786,2.902070,0.595494,NaN,benchmark_02.py

In [9]:
def rank_methods(df, operation_col_prefix):
    time_cols = [col for col in df.columns if col.startswith(operation_col_prefix) and col.endswith('_seconds')]
    rank_df = pd.DataFrame()
    rank_df['hostname'] = df['hostname']
    rank_df['cpu_brand'] = df['cpu_brand'] 
    rank_df['dataset_size'] = df['dataset_size']
    rank_df['dataset_format'] = df['dataset_format']
    
    for col in time_cols:
        rank_col = f"rank_{col}"
        # Only rank non-zero values, assign max rank to zeros
        mask = df[col] > 0
        rank_df[rank_col] = df[col].where(mask).rank(method='min')
        max_rank = rank_df[rank_col].max()
        rank_df[rank_col] = rank_df[rank_col].fillna(max_rank + 1)
    
    return rank_df

In [10]:
filter_group_ranks = rank_methods(b_df, 'filter_group_')
sort_values_cols = [col for col in filter_group_ranks.columns if col.startswith('rank_filter_group_')]
filter_group_ranks[sort_values_cols] = filter_group_ranks[sort_values_cols].astype(int)
filter_group_ranks = filter_group_ranks.sort_values(by=sort_values_cols + ['hostname', 'dataset_format'])
filter_group_ranks

,hostname,cpu_brand,dataset_size,dataset_format,rank_filter_group_pandas_seconds,rank_filter_group_polars_seconds,rank_filter_group_duckdb_seconds,rank_filter_group_fireducks_seconds
585,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,csv,1,257,191,69
783,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,10000000,parquet,2,49,9,51
778,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,10000000,csv,3,89,418,270
782,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,10000000,csv,4,36,113,8
777,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,10000000,csv,5,74,405,356
...,...,...,...,...,...,...,...,...
16,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,776,752,517,399
46,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,777,775,623,399
32,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,778,753,612,399
33,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,779,770,626,399
0,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,780,779,745,399

In [11]:
def get_df_by_test(df: pd.DataFrame, cols_to_group: list, metric: str) -> pd.DataFrame:
    # Properly combine columns - create a new list instead of using append
    columns_to_select = cols_to_group + [metric]
    
    # Select the relevant columns
    df_subset = df[columns_to_select]
    
    # Remove rows where the metric is null/zero 
    df_filtered = df_subset[df_subset[metric] > 0]  # or use .notna() 
    
    # Group by the specified columns and get minimum values
    grouped = df_filtered.groupby(cols_to_group)
    return grouped.min().reset_index().sort_values(by=metric)

In [12]:
cols_to_group = [ "dataset_format","hostname", "cpu_brand", "system", "memory_total_gb"]
with pd.option_context('display.max_rows', None):
    for col_to_rank in time_cols:
        print(f"Ranking by: {col_to_rank}")
        df_by_test = get_df_by_test(b_df, cols_to_group, col_to_rank).reset_index(drop=True)
        display(df_by_test)
        print("\n")

Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.176201
1,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.178515
2,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.179644
3,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.188335
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.189167
5,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.189469
6,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.194035
7,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.194325
8,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.204102
9,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.205537
10,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.205929
11,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.210462
12,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.214854
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.230181
14,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.230830
15,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.236677
16,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.239010
17,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.239222
18,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.239936
19,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.242897
20,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.245038
21,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.249029
22,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.252594
23,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.252882
24,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.255371
25,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.255536
26,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.257193
27,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.257924
28,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.259799
29,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.260106
30,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.261258
31,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.264356
32,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.267180
33,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.267274
34,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.267586
35,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.268126
36,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.269150
37,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.269462
38,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.269707
39,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.270451
40,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.270499
41,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.271542
42,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.273162
43,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.273861
44,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.274816
45,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.275933
46,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.278754
47,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.278784
48,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.278926
49,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.279343
50,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.282793
51,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.283666
52,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.284732
53,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.284936
54,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.288474
55,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.293107
56,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.293178
57,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.293566
58,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.294839
59,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.295494
60,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.296013
61,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.298231
62,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.299906
63,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.300393
64,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.304548
65,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.304917
66,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.307013
67,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.307098
68,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.307888
69,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.312222
70,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.313211
71,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.314343
72,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.315864
73,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.316038
74,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.320001
75,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.321065
76,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.325910
77,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.335269
78,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.335481
79,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.359498
80,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.365571
81,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.367142
82,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.369146
83,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.372711
84,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.374583
85,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.379084
86,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.379735
87,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.380978
88,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.382879
89,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.383956
90,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.389362
91,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.393282
92,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.397570
93,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.409041
94,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.409166
95,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.415871
96,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.416637
97,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.421023
98,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.425848
99,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.428233
100,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.434067
101,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.447669
102,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.450492
103,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.453049
104,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.461787
105,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.463888
106,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.465891
107,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.468646
108,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.475752
109,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.475849
110,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.492413
111,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.493353
112,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.506782
113,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.514984
114,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.528547
115,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.535098
116,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.555320
117,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.583145
118,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.591544
119,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.617913
120,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.637270
121,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.641110
122,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.663562
123,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.692138
124,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.702786
125,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.703566
126,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.731955
127,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.962332
128,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,5.358341
129,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,10.411298

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_polars_seconds
0,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.071505
1,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.085730
2,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.085799
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.086000
4,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.086550
5,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.086587
6,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.089034
7,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.089723
8,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.094960
9,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.097477
10,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.098239
11,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.098410
12,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.099523
13,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.101135
14,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.102704
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.105863
16,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.107952
17,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.113670
18,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.116799
19,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.117693
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.118766
21,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.119589
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.125012
23,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.125330
24,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.126928
25,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.127720
26,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.127974
27,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.128240
28,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.129033
29,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.131098
30,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.132450
31,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.132462
32,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.133582
33,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.133691
34,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.134381
35,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.135089
36,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.136902
37,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.139211
38,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.140502
39,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.141459
40,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.144457
41,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.144622
42,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.147632
43,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.148480
44,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.148520
45,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.152259
46,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.153641
47,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.154450
48,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.157515
49,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.160327
50,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.160666
51,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.161578
52,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.165737
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.165866
54,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.168699
55,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.176206
56,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.177092
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.180809
58,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.183723
59,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.185390
60,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.188349
61,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.188720
62,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.191101
63,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.192195
64,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.194010
65,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.194452
66,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.195381
67,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.199044
68,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.201567
69,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.203178
70,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.204266
71,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.204483
72,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.206960
73,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.208076
74,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.208222
75,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.215265
76,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.216848
77,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.218959
78,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.219885
79,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.226329
80,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.230266
81,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.234705
82,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.239710
83,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.243947
84,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.245735
85,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.250173
86,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.250457
87,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.253067
88,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.264340
89,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.267077
90,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.268869
91,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.269017
92,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.272008
93,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.273836
94,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.275828
95,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.280271
96,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.281430
97,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.286957
98,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.291214
99,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.294835
100,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.297577
101,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.297603
102,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.302873
103,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.306664
104,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.315507
105,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.322647
106,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.330961
107,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.331924
108,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.332424
109,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.340602
110,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.345873
111,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.355334
112,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.371280
113,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.376640
114,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.394636
115,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.431944
116,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.432383
117,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.433407
118,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.445868
119,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.447058
120,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.486967
121,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.488726
122,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.510137
123,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.542422
124,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.553279
125,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.565336
126,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.614996
127,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.625782
128,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.690226
129,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.823694

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.026820
1,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.031740
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.031890
3,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.031958
4,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.032062
5,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.032152
6,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.032623
7,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.033227
8,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.033242
9,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.034698
10,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.034815
11,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.035718
12,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.035930
13,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.036465
14,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.036850
15,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.036903
16,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.036922
17,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.037508
18,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.038045
19,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.038939
20,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.039717
21,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.039799
22,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.040865
23,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.041783
24,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.041897
25,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.042423
26,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.042440
27,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.042528
28,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.042714
29,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.043635
30,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.045527
31,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.046066
32,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.046270
33,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.046697
34,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.047376
35,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.047544
36,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.047603
37,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.047966
38,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.047970
39,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.048604
40,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.048618
41,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.048940
42,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.049098
43,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.049256
44,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.049330
45,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.049567
46,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.049598
47,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.049785
48,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.049786
49,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.050001
50,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.050120
51,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.051058
52,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.051560
53,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.052113
54,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.053021
55,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.053767
56,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.054035
57,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.054782
58,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.055147
59,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.055306
60,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.056555
61,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.057080
62,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.057113
63,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.057115
64,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.057278
65,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.058527
66,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.058952
67,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.060054
68,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.061755
69,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.062675
70,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.062731
71,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.064128
72,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.065138
73,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.065795
74,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.066707
75,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.066937
76,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.067097
77,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.068272
78,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.068845
79,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.072017
80,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.072401
81,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.073407
82,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.074056
83,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.075990
84,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.080767
85,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.082814
86,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.083453
87,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.084105
88,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.085639
89,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.086627
90,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.092058
91,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.094551
92,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.095555
93,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.096380
94,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.103483
95,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.113281
96,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.115737
97,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.116693
98,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.116821
99,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.119607
100,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.119977
101,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.122297
102,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.124491
103,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.126611
104,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.128099
105,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.133032
106,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.136810
107,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.137175
108,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.139353
109,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.141584
110,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.143259
111,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.146962
112,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.155095
113,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.156793
114,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.160650
115,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.168784
116,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.173057
117,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.173424
118,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.173585
119,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.175472
120,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.194292
121,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.217084
122,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.224818
123,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.233033
124,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.233598
125,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.238558
126,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.239716
127,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.261815
128,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.337646
129,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.501835

Ranking by: filter_group_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.001347
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.001380
2,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.001393
3,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.001396
4,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.001445
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.001484
6,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.001491
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.001497
8,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.001519
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.001550
10,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.001559
11,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.001573
12,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.001586
13,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.001589
14,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.001595
15,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.001598
16,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.001606
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.001609
18,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.001614
19,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.001644
20,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.001654
21,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.001656
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.001698
23,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.001710
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.001743
25,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.001753
26,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.001764
27,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.001776
28,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.001779
29,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.001840
30,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.001841
31,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.001853
32,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.001858
33,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.001923
34,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.001940
35,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.001991
36,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.001995
37,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.002010
38,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.002106
39,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.002157
40,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.002165
41,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.002271
42,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.002401
43,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.002427
44,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.002445
45,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.002453
46,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.002483
47,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.002528
48,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.002592
49,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.002678
50,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.002729
51,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.002809
52,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.002961
53,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.002979
54,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.003022
55,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.003029
56,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.003122
57,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.003213
58,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.003224
59,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.003372
60,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.003474
61,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.003905
62,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.003935
63,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.004023
64,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.004917
65,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.010577

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.148611
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.156536
2,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.160063
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.161277
4,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.161432
5,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.167602
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.168088
7,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.169622
8,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.171951
9,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.172934
10,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.178686
11,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.180868
12,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.180947
13,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.182035
14,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.184240
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.186431
16,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.187811
17,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.191251
18,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.192398
19,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.192725
20,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.192739
21,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.195542
22,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.199262
23,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.201684
24,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.201802
25,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.203179
26,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.204514
27,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.207913
28,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.208003
29,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.208207
30,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.213067
31,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.214802
32,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.215019
33,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.215042
34,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.216869
35,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.218891
36,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.219370
37,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.219511
38,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.219855
39,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.221023
40,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.221441
41,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.222419
42,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.222874
43,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.222962
44,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.223908
45,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.224155
46,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.224219
47,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.224676
48,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.224676
49,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.224875
50,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.224946
51,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.225383
52,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.226260
53,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.227171
54,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.227811
55,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.228520
56,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.228664
57,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.228935
58,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.231631
59,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.232281
60,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.232309
61,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.232864
62,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.232911
63,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.233630
64,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.234241
65,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.238018
66,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.238547
67,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.239711
68,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.240540
69,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.241225
70,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.241319
71,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.244071
72,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.251238
73,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.252322
74,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.254285
75,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.256198
76,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.261322
77,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.263139
78,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.265091
79,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.268410
80,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.268450
81,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.277762
82,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.287178
83,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.291042
84,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.294749
85,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.303906
86,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.312264
87,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.324660
88,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.333868
89,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.336234
90,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.338446
91,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.339025
92,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.339472
93,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.340918
94,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.343622
95,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.359289
96,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.360390
97,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.361939
98,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.367291
99,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.370749
100,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.371494
101,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.375648
102,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.377876
103,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.387176
104,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.391305
105,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.396269
106,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.397330
107,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.407656
108,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.432261
109,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.465929
110,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.471190
111,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.474622
112,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.479291
113,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.502419
114,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.505736
115,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.513319
116,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.524030
117,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.580449
118,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.600673
119,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.625986
120,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.652209
121,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.669447
122,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.673124
123,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.676553
124,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.684314
125,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.752458
126,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.837387
127,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.850339
128,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,6.423730
129,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,10.376254

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.054323
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.057185
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.057959
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.061096
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.061169
5,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.063687
6,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.066585
7,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.068867
8,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.072699
9,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.081498
10,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.085318
11,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.086847
12,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.087296
13,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.087507
14,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.088038
15,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.088249
16,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.089538
17,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.091074
18,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.091635
19,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.092394
20,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.093786
21,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.093914
22,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.094251
23,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.094802
24,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.095288
25,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.095524
26,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.095553
27,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.095885
28,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.096383
29,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.097667
30,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.098535
31,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.098646
32,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.101301
33,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.101981
34,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.103099
35,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.104160
36,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.104290
37,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.108512
38,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.109605
39,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.110336
40,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.110767
41,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.112284
42,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.112821
43,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.116079
44,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.116513
45,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.116968
46,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.117172
47,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.117725
48,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.118668
49,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.121048
50,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.123976
51,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.127979
52,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.129778
53,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.133953
54,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.134012
55,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.134561
56,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.134709
57,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.135417
58,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.136704
59,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.139852
60,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.140574
61,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.142213
62,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.143918
63,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.144932
64,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.145582
65,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.154213
66,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.157966
67,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.160681
68,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.164934
69,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.164970
70,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.168137
71,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.175646
72,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.181394
73,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.188093
74,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.191556
75,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.195593
76,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.196279
77,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.199275
78,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.201458
79,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.205388
80,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.207037
81,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.210085
82,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.222970
83,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.225668
84,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.225771
85,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.228205
86,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.228700
87,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.232830
88,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.234784
89,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.238894
90,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.248640
91,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.256583
92,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.273801
93,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.275371
94,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.303131
95,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.305176
96,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.307027
97,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.309664
98,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.311508
99,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.314736
100,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.319131
101,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.322771
102,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.327670
103,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.330587
104,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.332090
105,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.339440
106,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.339904
107,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.357911
108,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.363951
109,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.365960
110,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.366613
111,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.373520
112,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.375136
113,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.383513
114,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.383970
115,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.392614
116,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.395479
117,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.398507
118,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.404778
119,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.418672
120,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.422337
121,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.425459
122,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.438670
123,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.443669
124,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.450185
125,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.480064
126,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.510830
127,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.516206
128,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.516427
129,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.645693

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.036783
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.038060
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.048504
3,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.049224
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.049645
5,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.050027
6,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.051478
7,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.051746
8,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.052067
9,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.052469
10,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.053194
11,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.054845
12,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.055085
13,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.056630
14,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.057525
15,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.057667
16,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.058021
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.058118
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.059392
19,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.059622
20,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.059756
21,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.061105
22,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.062178
23,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.065039
24,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.065420
25,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.066542
26,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.066727
27,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.067213
28,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.067360
29,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.067506
30,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.068152
31,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.068492
32,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.068837
33,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.069108
34,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.069300
35,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.069782
36,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.070140
37,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.070597
38,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.071529
39,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.071951
40,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.072261
41,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.073422
42,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.073599
43,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.073689
44,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.073785
45,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.074120
46,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.075092
47,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.076049
48,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.077940
49,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.079261
50,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.079360
51,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.080334
52,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.081314
53,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.081412
54,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.081628
55,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.082255
56,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.083700
57,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.083737
58,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.085253
59,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.085688
60,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.085934
61,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.088910
62,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.089430
63,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.090133
64,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.090168
65,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.090312
66,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.090960
67,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.092868
68,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.093565
69,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.095744
70,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.095846
71,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.096858
72,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.097076
73,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.099953
74,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.102470
75,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.103057
76,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.103255
77,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.106214
78,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.106493
79,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.108964
80,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.109509
81,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.110594
82,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.114537
83,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.118487
84,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.121890
85,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.124516
86,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.131306
87,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.134772
88,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.140150
89,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.143583
90,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.149406
91,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.150332
92,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.164641
93,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.167851
94,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.195986
95,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.196961
96,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.198998
97,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.210103
98,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.211529
99,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.222407
100,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.251149
101,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.252737
102,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.252801
103,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.253880
104,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.295498
105,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.304877
106,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.323197
107,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.328502
108,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.329382
109,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.332450
110,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.344468
111,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.352225
112,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.354550
113,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.355642
114,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.358730
115,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.370384
116,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.375684
117,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.382014
118,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.382476
119,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.398099
120,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.445769
121,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.447324
122,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.460195
123,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.494045
124,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.498727
125,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.536384
126,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.572973
127,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.574453
128,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.660862
129,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.673051

Ranking by: statistics_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.000125
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.000133
2,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000140
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000141
4,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.000142
5,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000145
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000146
7,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000148
8,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000152
9,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.000169
10,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.000176
11,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.000182
12,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000187
13,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.000188
14,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.000191
15,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000193
16,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000195
17,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.000195
18,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.000195
19,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.000196
20,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000197
21,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000204
22,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000205
23,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000213
24,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.000218
25,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000220
26,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.000221
27,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.000222
28,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.000227
29,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000227
30,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000232
31,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.000234
32,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.000235
33,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.000237
34,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000239
35,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.000240
36,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000246
37,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000249
38,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000250
39,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.000258
40,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.000271
41,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.000272
42,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.000283
43,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.000287
44,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000289
45,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000291
46,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000309
47,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000312
48,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.000319
49,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000338
50,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000347
51,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000364
52,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000381
53,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.000384
54,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000414
55,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.000420
56,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000469
57,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000484
58,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.000490
59,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000491
60,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.000549
61,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.000555
62,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.000564
63,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.000571
64,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.000573
65,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.000893

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_pandas_seconds
0,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,1.425085
1,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,1.493157
2,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,1.600232
3,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,1.686373
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.703667
5,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,1.738139
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,1.740872
7,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,1.741788
8,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,1.743906
9,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,1.750485
10,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,1.756985
11,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,1.764612
12,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.783565
13,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,1.800952
14,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.812609
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.826722
16,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.845459
17,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,1.858019
18,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,1.858767
19,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,1.867475
20,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.885700
21,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.032971
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,2.039433
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.063363
24,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,2.068671
25,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,2.072243
26,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,2.086920
27,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.143273
28,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,2.146466
29,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.148765
30,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,2.155096
31,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,2.156851
32,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,2.157476
33,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,2.158110
34,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.159110
35,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.190334
36,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,2.195587
37,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,2.205681
38,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,2.207379
39,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,2.208451
40,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,2.212902
41,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,2.218156
42,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,2.220050
43,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,2.221370
44,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,2.259400
45,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.295366
46,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.309064
47,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.310993
48,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.313880
49,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.321239
50,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,2.325525
51,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.337842
52,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.399702
53,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,2.410965
54,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.419912
55,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,2.436286
56,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.460799
57,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.486614
58,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.501646
59,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,2.502459
60,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,2.570981
61,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,2.584196
62,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,2.588128
63,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,2.599715
64,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.599806
65,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.681270
66,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.690762
67,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,2.704473
68,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,2.710402
69,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,2.731822
70,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,2.745317
71,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,2.769056
72,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,2.772811
73,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,2.799186
74,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,2.836061
75,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.862606
76,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,2.897614
77,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,2.920474
78,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.937153
79,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,3.039260
80,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,3.052452
81,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,3.066234
82,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.101532
83,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,3.175220
84,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.193744
85,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,3.226381
86,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,3.328890
87,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.379374
88,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,3.404619
89,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,3.418511
90,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,3.425977
91,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,3.534181
92,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,3.618343
93,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,3.637755
94,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,3.735163
95,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,3.748340
96,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,3.944685
97,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.956058
98,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,3.981980
99,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,3.982410
100,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,4.005578
101,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,4.029502
102,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,4.149068
103,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,4.155437
104,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,4.253906
105,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,4.384282
106,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,4.393550
107,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,4.425937
108,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,4.435003
109,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,4.461058
110,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,4.466859
111,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,4.541414
112,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,4.699407
113,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,4.933718
114,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,5.147182
115,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,5.252674
116,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,5.443431
117,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,5.558602
118,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,5.630370
119,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,5.688737
120,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,5.708399
121,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,5.822155
122,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,6.052842
123,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,6.501427
124,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,6.842711
125,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,6.970424
126,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,8.353409
127,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,8.903364
128,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,9.781901
129,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,23.235775

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.351187
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.368932
2,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.392026
3,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.409226
4,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.410883
5,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.422013
6,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.433622
7,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.440721
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.444010
9,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.450646
10,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.459607
11,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.460579
12,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.460666
13,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.466874
14,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.470777
15,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.476252
16,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.476298
17,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.479752
18,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.482777
19,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.483583
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.491799
21,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.495044
22,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.496640
23,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.497127
24,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.503293
25,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.504567
26,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.506174
27,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.511116
28,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.511853
29,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.513071
30,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.513687
31,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.515251
32,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.516911
33,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.522545
34,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.528029
35,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.536883
36,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.537555
37,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.539736
38,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.541118
39,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.543734
40,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.544344
41,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.558314
42,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.561642
43,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.563187
44,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.570331
45,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.571349
46,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.575433
47,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.584511
48,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.591883
49,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.599055
50,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.612234
51,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.634905
52,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.653027
53,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.661196
54,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.669629
55,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.671255
56,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.680029
57,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.682576
58,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.688653
59,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.703326
60,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.706446
61,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.707446
62,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.711675
63,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.719540
64,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.731640
65,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.772013
66,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.793599
67,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.797163
68,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.798026
69,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.802114
70,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.825475
71,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.844970
72,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.850386
73,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.853281
74,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.857206
75,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.862862
76,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.864403
77,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.875540
78,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.883997
79,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.893444
80,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.896909
81,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.896957
82,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.919303
83,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.921715
84,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.954018
85,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.982904
86,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.988101
87,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.990866
88,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.997258
89,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,1.004030
90,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,1.008530
91,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,1.029172
92,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,1.043388
93,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,1.079245
94,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,1.091032
95,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,1.144325
96,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,1.151101
97,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,1.165587
98,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,1.166113
99,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,1.284159
100,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.338042
101,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,1.344523
102,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,1.390336
103,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.394849
104,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,1.424004
105,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,1.426380
106,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.451908
107,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.453339
108,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,1.469501
109,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.510888
110,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,1.530308
111,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.530371
112,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,1.544476
113,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.550958
114,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,1.555928
115,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,1.566457
116,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,1.595030
117,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.603825
118,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.618368
119,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.646886
120,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.673843
121,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.794887
122,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.805672
123,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.848436
124,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,1.869724
125,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,2.062053
126,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,2.212631
127,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,2.232569
128,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,2.617505
129,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,2.735544

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_duckdb_seconds
0,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,3.285292
1,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,3.594456
2,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,4.237417
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,4.595454
4,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,4.715118
5,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,4.746880
6,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,4.874635
7,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,5.140088
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,6.219584
9,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,8.127482
10,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,8.367620
11,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,8.425919
12,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,8.651267
13,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,8.814859
14,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,9.107234
15,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,9.114352
16,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,9.330056
17,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,9.515945
18,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,9.528923
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,9.572599
20,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,9.602663
21,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,9.626689
22,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,9.712315
23,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,9.816590
24,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,9.850003
25,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,9.906787
26,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,10.033608
27,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,10.091561
28,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,10.093951
29,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,10.099078
30,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,10.123247
31,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,10.282482
32,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,10.311187
33,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,10.421291
34,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,10.433864
35,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,10.574243
36,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,10.624296
37,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,10.669228
38,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,10.729680
39,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,10.849791
40,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,10.860894
41,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,10.972182
42,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,10.989343
43,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,11.082227
44,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,11.087266
45,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,11.124308
46,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,11.249223
47,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,11.251413
48,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,11.385188
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,11.430921
50,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,11.699034
51,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,11.788498
52,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,12.164969
53,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,12.372747
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,12.757002
55,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,12.812437
56,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,13.439244
57,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,13.504328
58,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,13.602092
59,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,13.681071
60,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,13.723165
61,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,13.766659
62,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,13.824431
63,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,14.045449
64,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,14.232566
65,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,14.325541
66,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,14.327818
67,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,14.392363
68,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,14.769567
69,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,14.798437
70,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,14.920127
71,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,14.973497
72,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,15.014801
73,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,15.041581
74,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,15.141552
75,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,15.266155
76,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,15.402990
77,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,15.683895
78,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,15.756632
79,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,15.984449
80,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,16.000711
81,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,16.624110
82,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,16.771762
83,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,17.002785
84,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,17.248082
85,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,17.261537
86,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,17.445712
87,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,17.489565
88,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,17.644917
89,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,17.805404
90,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,18.121879
91,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,18.288855
92,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,18.515142
93,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,19.050351
94,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,19.118344
95,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,19.524039
96,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,20.342126
97,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,21.596404
98,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,21.775294
99,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,21.924554
100,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,22.506948
101,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,22.578155
102,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,22.634748
103,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,22.790639
104,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,23.239070
105,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,23.916556
106,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,24.085375
107,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,24.754321
108,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,25.211426
109,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,25.560013
110,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,25.567625
111,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,25.815095
112,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,26.185457
113,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,26.225853
114,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,26.324829
115,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,26.952746
116,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,27.339530
117,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,27.425043
118,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,27.764083
119,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,27.868051
120,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,28.009790
121,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,30.442195
122,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,31.624210
123,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,32.850278
124,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,36.837714
125,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,37.671142
126,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,37.993901
127,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,41.291982
128,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,43.052157
129,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,43.799303

Ranking by: complex_join_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.000377
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000384
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.000392
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000400
4,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000409
5,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.000410
6,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000413
7,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.000456
8,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000456
9,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000457
10,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.000474
11,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000482
12,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.000499
13,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000505
14,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.000507
15,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000508
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000517
17,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.000520
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000522
19,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000524
20,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000532
21,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.000533
22,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000539
23,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.000542
24,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000556
25,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000562
26,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000571
27,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.000578
28,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.000581
29,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.000584
30,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.000593
31,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.000605
32,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.000605
33,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.000610
34,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000614
35,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.000617
36,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000653
37,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000663
38,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.000680
39,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.000680
40,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.000684
41,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000702
42,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000707
43,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.000719
44,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000744
45,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.000754
46,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.000774
47,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000801
48,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000854
49,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.000859
50,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000936
51,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000946
52,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000962
53,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000969
54,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.001120
55,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.001124
56,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.001163
57,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.001174
58,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.001273
59,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.001411
60,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.001441
61,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.001456
62,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.001499
63,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.001595
64,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.001850
65,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.001865

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_pandas_seconds
0,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.300144
1,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.311347
2,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.317437
3,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.322537
4,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.328552
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.331649
6,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.332970
7,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.333227
8,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.335873
9,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.339370
10,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.349165
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.350374
12,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.351937
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.357184
14,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.357856
15,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.358497
16,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.358569
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.360182
18,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.360459
19,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.360709
20,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.386752
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.390335
22,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.398909
23,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.403801
24,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.406380
25,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.408165
26,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.410205
27,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.410970
28,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.414054
29,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.414082
30,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.414989
31,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.415971
32,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.416419
33,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.417122
34,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.417857
35,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.417985
36,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.418780
37,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.419210
38,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.421920
39,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.427478
40,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.442156
41,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.453307
42,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.455722
43,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.461030
44,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.461086
45,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.465839
46,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.467282
47,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.467711
48,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.478672
49,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.487813
50,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.488623
51,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.492836
52,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.493485
53,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.496890
54,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.496995
55,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.499842
56,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.502207
57,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.503815
58,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.508785
59,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.508836
60,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.508849
61,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.508894
62,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.511875
63,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.512593
64,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.516602
65,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.517817
66,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.518303
67,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.520747
68,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.521243
69,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.525714
70,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.525932
71,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.532064
72,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.535084
73,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.539807
74,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.542584
75,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.544533
76,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.544602
77,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.552929
78,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.557196
79,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.561544
80,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.563131
81,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.563665
82,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.566226
83,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.571089
84,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.574874
85,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.575575
86,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.582320
87,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.585583
88,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.590429
89,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.594944
90,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.618460
91,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.627129
92,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.634316
93,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.647076
94,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.653648
95,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.654633
96,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.689184
97,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.693135
98,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.694507
99,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.701162
100,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.709507
101,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.731495
102,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.735251
103,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.748335
104,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.751010
105,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.769225
106,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.778732
107,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.832497
108,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.835348
109,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.851114
110,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.880524
111,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.906153
112,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.924786
113,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.937737
114,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.010463
115,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.022419
116,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,1.052686
117,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,1.142008
118,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.205137
119,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.270681
120,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.311182
121,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.345003
122,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,1.383846
123,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.411530
124,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.438896
125,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.468229
126,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,1.524298
127,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.528268
128,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,8.824875
129,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,12.861529

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_polars_seconds
0,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,1.835762
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.836724
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,1.848274
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.848299
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,1.858056
5,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,1.858462
6,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,1.879104
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.899370
8,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.899804
9,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,1.914749
10,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,1.916424
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,1.916629
12,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,1.922158
13,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,1.928277
14,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,1.930856
15,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,1.944967
16,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.951676
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,1.965067
18,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.967512
19,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,1.974526
20,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,1.974907
21,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.019306
22,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,2.031511
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,2.035647
24,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,2.036167
25,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,2.038363
26,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.066553
27,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.070447
28,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,2.080549
29,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,2.081131
30,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,2.099917
31,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.110350
32,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.115645
33,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,2.131042
34,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,2.135119
35,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,2.168447
36,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,2.168542
37,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,2.176932
38,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.177278
39,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,2.179002
40,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,2.201313
41,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,2.205108
42,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,2.205589
43,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.216953
44,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,2.222237
45,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,2.223873
46,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.224582
47,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.225481
48,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.243550
49,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,2.261237
50,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,2.270337
51,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,2.289053
52,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,2.305301
53,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,2.323153
54,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,2.346289
55,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,2.397435
56,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,2.401860
57,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,2.408907
58,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,2.421620
59,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,2.439029
60,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.442789
61,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.447037
62,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,2.450257
63,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,2.467428
64,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,2.476689
65,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.505193
66,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,2.518807
67,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,2.540311
68,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,2.541366
69,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,2.549006
70,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,2.555468
71,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,2.568238
72,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.582026
73,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,2.601538
74,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,2.631081
75,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,2.646084
76,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,2.669038
77,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,2.683827
78,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,2.699992
79,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,2.718911
80,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,2.756714
81,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,2.774699
82,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,2.782137
83,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.793840
84,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,2.826220
85,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.842163
86,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,2.995052
87,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,3.202793
88,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,3.217056
89,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,3.243892
90,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,3.291802
91,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,3.539412
92,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,3.595803
93,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.607012
94,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.646706
95,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.677016
96,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.686936
97,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,3.778609
98,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,3.794873
99,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,3.878324
100,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,3.897610
101,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,3.960917
102,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.260854
103,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,4.261347
104,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,4.268188
105,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,4.303385
106,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,4.304416
107,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.347602
108,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,4.352973
109,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.393107
110,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.532263
111,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,4.544037
112,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,4.750237
113,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,4.836412
114,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.928691
115,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.979773
116,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,5.020040
117,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,5.045245
118,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,5.068176
119,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,5.156621
120,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,6.247831
121,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,6.251081
122,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,6.260561
123,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,6.267411
124,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,6.761818
125,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,7.017137
126,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,7.324557
127,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,8.000622
128,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,8.178485
129,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,8.300135

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.098952
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.104968
2,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.110413
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.111596
4,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.113430
5,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.113817
6,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.120747
7,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.122152
8,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.123296
9,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.125199
10,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.126457
11,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.127927
12,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.137403
13,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.140360
14,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.140363
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.140741
16,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.141526
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.142895
18,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.146148
19,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.147814
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.147826
21,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.148341
22,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.150845
23,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.151960
24,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.152020
25,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.152542
26,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.152933
27,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.154963
28,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.156028
29,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.156701
30,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.159512
31,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.160707
32,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.161141
33,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.162418
34,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.165653
35,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.169913
36,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.170429
37,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.170882
38,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.175055
39,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.175164
40,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.175907
41,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.179042
42,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.179130
43,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.180224
44,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.181075
45,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.185639
46,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.185991
47,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.186022
48,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.188238
49,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.189987
50,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.191223
51,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.191417
52,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.192199
53,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.193187
54,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.195156
55,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.195624
56,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.196289
57,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.199264
58,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.200557
59,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.204456
60,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.205527
61,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.207283
62,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.210747
63,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.213198
64,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.214164
65,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.216630
66,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.218942
67,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.225275
68,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.228301
69,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.230046
70,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.231366
71,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.231962
72,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.232153
73,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.234352
74,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.235709
75,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.238715
76,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.244460
77,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.262852
78,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.263333
79,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.264716
80,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.268142
81,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.271172
82,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.277293
83,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.284303
84,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.294979
85,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.313320
86,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.327826
87,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.362893
88,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.374270
89,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.377764
90,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.381150
91,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.386797
92,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.395654
93,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.396655
94,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.400789
95,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.408385
96,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.451360
97,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.501223
98,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.561461
99,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.579472
100,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.592204
101,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.604427
102,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.639191
103,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.674492
104,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.679273
105,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.709106
106,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.726991
107,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.741153
108,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.757588
109,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.809643
110,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.829284
111,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.844055
112,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.850289
113,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.899609
114,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.986644
115,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.987728
116,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.991282
117,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,1.011922
118,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.043566
119,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.050404
120,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.063147
121,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.145382
122,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.178603
123,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.187024
124,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.253193
125,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.270166
126,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.321530
127,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.425144
128,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,1.461500
129,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,1.522405

Ranking by: timeseries_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.258856
1,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.261453
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.265580
3,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.273113
4,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.275606
5,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.301512
6,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.302325
7,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.303971
8,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Linux,62.11,0.305193
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.306496
10,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.312555
11,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.312878
12,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.315209
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.321205
14,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.334185
15,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.336483
16,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.338578
17,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.343629
18,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.345705
19,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.362512
20,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.362805
21,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.363199
22,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.367393
23,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.377237
24,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.379336
25,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.381611
26,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.387547
27,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.395374
28,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.416866
29,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.418874
30,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.421252
31,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.421610
32,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.424503
33,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.425058
34,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.425627
35,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.431295
36,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.433576
37,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.448926
38,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.462007
39,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.464249
40,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.464570
41,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.481442
42,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.483188
43,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.501116
44,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.510475
45,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.529562
46,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.537955
47,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.542455
48,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.559417
49,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.564873
50,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.577054
51,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.583606
52,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.585731
53,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.592294
54,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.595607
55,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.622113
56,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.651473
57,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.667169
58,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.682481
59,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.745909
60,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.777140
61,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.936820
62,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.942361
63,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.983110
64,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.986897
65,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,1.421789

In [13]:
# Filter Group Pandas
fg_p = b_df[["hostname", "cpu_brand","dataset_size", "dataset_format", "filter_group_pandas_seconds"]]
fg_p = fg_p.groupby(by=["hostname", "cpu_brand","dataset_size", "dataset_format"]).min().reset_index()
fg_p = fg_p.rename(columns={"filter_group_pandas_seconds": "min_time_seconds"})
fg_p = fg_p.sort_values(by=["dataset_size","min_time_seconds", "hostname",  "dataset_format"])
fg_p

,hostname,cpu_brand,dataset_size,dataset_format,min_time_seconds
42,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,csv,0.176201
29,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,10000000,parquet,0.178515
28,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,10000000,csv,0.179644
43,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,parquet,0.188335
20,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,0.189167
...,...,...,...,...,...
13,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,10000000,parquet,0.583145
16,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,csv,0.731955
17,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,parquet,0.962332
47,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,parquet,5.358341
46,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,10.411298

In [16]:
# Calculate the average operation time per row for each library
library_suffixes = ['pandas', 'polars', 'duckdb', 'fireducks']  # Add 'fireducks' if/when data is available

for lib in library_suffixes:
    lib_cols = [col for col in b_df.columns if col.endswith(f'_{lib}_seconds')]
    b_df[f'{lib}_avg_time'] = b_df[lib_cols].mean(axis=1)

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)+ ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each library
host_lib_avg = b_df.groupby('host_cpu')[[f'{lib}_avg_time' for lib in library_suffixes]].mean().reset_index()

# Sort each library's ranking and display
with pd.option_context('display.max_rows', None,'display.max_colwidth', None):
    for lib in library_suffixes:
        print(f"Ranking by average {lib} time (ascending):")
        display(host_lib_avg[['host_cpu', f'{lib}_avg_time']].sort_values(f'{lib}_avg_time'))
        print("\n")
# Optionally, display the full table

#host_lib_avg

Ranking by average pandas time (ascending):

,host_cpu,pandas_avg_time
25,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.593089
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.728984
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.785434
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.787330
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.790206
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.828231
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.831400
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.853110
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.859686
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.872365
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.883562
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.906213
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.939625
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.961443
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,1.023193
60,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.024209
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,1.031235
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,1.076431
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.083468
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.089557
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.098229
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.119797
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.127908
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.172261
26,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,1.174671
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,1.237555
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.239831
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.292812
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.340711
30,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,1.461463
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.491011
45,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.524103
43,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.575672
32,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.706588
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.710795
36,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,1.732686
47,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.787122
39,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,1.813134
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.932938
27,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,1.951614
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,1.978228
52,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.985968
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,2.045975
48,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.144046
59,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.251039
56,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,2.404644
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,2.424514
41,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,2.492094
50,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.506687
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.578181
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.735169
54,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,2.740769
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.968245
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,3.109042
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,3.110269
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,3.131222
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,3.681693
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,3.991704
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,5.444306
35,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,7.885764
46,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,15.408611

Ranking by average polars time (ascending):

,host_cpu,polars_avg_time
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.626101
43,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.671769
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.680239
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.719946
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.742445
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.770126
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.772193
32,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.783669
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.784100
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.792830
25,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.797963
41,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.799042
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.809536
39,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.812354
30,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.835478
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.846254
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.869688
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.876530
60,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.880083
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.880961
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.883038
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.901357
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.904037
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.906222
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.908087
26,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.910013
45,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.948109
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.950398
27,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.974428
36,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,1.033573
35,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.069344
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.069611
56,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,1.089643
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.107845
47,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.160133
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.184756
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.205978
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.236139
59,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.291333
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.310720
54,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.445962
52,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.505774
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.512683
48,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,1.578317
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.694340
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.736730
46,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.760348
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,1.880185
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.889734
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.914736
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.981489
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.013492
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.132537
50,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.245336
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,2.273989
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.419061
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.429050
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.576411
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.154671
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,3.323331
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,3.513165

Ranking by average duckdb time (ascending):

,host_cpu,duckdb_avg_time
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.333418
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,2.363975
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,2.427523
43,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,2.555037
41,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,2.704064
25,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,2.736482
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,2.746406
32,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,2.823045
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.991300
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,3.000192
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,3.040607
45,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,3.051764
39,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,3.059756
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,3.155746
35,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.158985
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,3.167542
60,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,3.179870
46,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.188277
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,3.258649
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,3.299193
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,3.355343
30,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,3.488175
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,3.711097
27,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,3.750847
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,3.871603
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,3.873748
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,3.992685
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,4.006463
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,4.055661
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,4.088932
56,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,4.129771
36,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,4.290595
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,4.330357
47,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,4.469477
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,4.599465
59,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,4.709456
26,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,4.885168
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,5.087844
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,5.198686
52,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,5.212134
54,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,5.468166
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,5.643569
48,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,6.429801
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,6.473828
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,6.655530
50,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,6.951640
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.171884
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,7.451571
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,7.832607
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.991622
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,8.051619
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,8.588737
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,9.097915
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.127482
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.242403
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,9.858046
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.192535
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,11.993303
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,12.402753
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,13.486665
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,16.960324

Ranking by average fireducks time (ascending):

,host_cpu,fireducks_avg_time
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.156754
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.158445
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.167420
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.175636
25,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.196769
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.199306
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.202127
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.239988
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.240043
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.271662
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.313481
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.324229
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.359409
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.370742
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.378425
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.383598
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.396031
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.403118
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.408981
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.412192
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.493129
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.493435
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.515272
60,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.520348
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.528912
26,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.612096
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.627516
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.695349
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.701282
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.780069
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.794866
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,1.062613
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,NaN
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,NaN
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,NaN
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,NaN
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,NaN
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,NaN
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,NaN
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,NaN
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,NaN
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,NaN
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,NaN
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,NaN
27,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,NaN
30,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,NaN
32,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,NaN
35,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,NaN
36,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,NaN
39,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,NaN
41,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,NaN
43,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,NaN
45,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,NaN
46,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,NaN
47,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,NaN
48,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,NaN
50,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,NaN
52,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,NaN
54,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,NaN
56,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,NaN
59,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,NaN

In [17]:
# Rank hosts (host + CPU) by the average time across all libraries (pandas, polars, duckdb)
#all_lib_time_cols = [col for col in b_df.columns if col.endswith('_pandas_seconds') or col.endswith('_polars_seconds') or col.endswith('_duckdb_seconds')]

b_df['all_libs_avg_time'] = b_df[time_cols].mean(axis=1)

# Group by host+cpu and get the mean
host_alllibs_avg = b_df.groupby('host_cpu')['all_libs_avg_time'].mean().reset_index()

# Sort to get the fastest overall
host_alllibs_avg_sorted = host_alllibs_avg.sort_values('all_libs_avg_time', ascending=True).reset_index(drop=True)

print("Ranking by average time across all libraries (fastest PC overall):")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(host_alllibs_avg_sorted)

Ranking by average time across all libraries (fastest PC overall):

,host_cpu,all_libs_avg_time
0,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,1.057614
1,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,1.081076
2,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,1.094910
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,1.184287
4,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,1.199354
5,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,1.252605
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,1.268143
7,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,1.326765
8,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,1.400005
9,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.401128
10,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,1.404093
11,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,1.408530
12,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,1.476203
13,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,1.489834
14,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.600826
15,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.644896
16,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.655497
17,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,1.690209
18,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.766031
19,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.771101
20,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.841325
21,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,1.894291
22,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,1.895082
23,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,1.895487
24,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,1.928372
25,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.946110
26,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.951453
27,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.977244
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.998400
29,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,2.222590
30,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,2.225630
31,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.334309
32,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,2.352285
33,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,2.391290
34,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,2.393767
35,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,2.398192
36,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,2.472244
37,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,2.541353
38,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.606110
39,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.750609
40,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.893920
41,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.900572
42,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.901292
43,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,3.100964
44,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.171048
45,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.172915
46,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.188409
47,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,3.218299
48,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,3.384055
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.901221
50,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,3.973162
51,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,4.013706
52,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,4.038031
53,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.306442
54,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,4.845665
55,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,5.087752
56,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,5.172890
57,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,6.332776
58,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,6.341653
59,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.785746
60,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,7.449210

In [19]:
# Calculate the average operation time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  # Fixed: startswith
    b_df[f'{test}_avg_time'] = b_df[test_cols].mean(axis=1)  # Fixed: use test, not lib

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each test
test_avg_cols = [f'{test}_avg_time' for test in test_prefixes]
host_test_avg = b_df.groupby('host_cpu')[test_avg_cols].mean().reset_index()

# Sort each test's ranking and display
# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by average {test} time (ascending):")
    with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
        display(host_test_avg[['host_cpu', f'{test}_avg_time']].sort_values(f'{test}_avg_time'))
    print("\n")

# Display the full table
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(host_test_avg)

Ranking by average filter_group time (ascending):

,host_cpu,filter_group_avg_time
25,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.153555
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.199375
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.201356
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.209489
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.210105
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.224723
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.232272
43,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.235091
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.242138
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.245565
45,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.255735
32,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.257783
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.260246
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.264002
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.265074
60,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.269770
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.271585
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.271687
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.277032
30,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.294546
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.300022
39,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.305850
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.308836
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.315131
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.322511
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.325251
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.332087
27,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.334513
26,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.350148
36,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.366369
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.368343
47,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.382449
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.392711
56,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.417065
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.438459
54,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.442778
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.463158
48,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.475525
59,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.477886
52,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.480865
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.513317
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.550806
41,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.597730
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.609594
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.611797
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.693557
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.694441
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.746890
50,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.749385
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.804758
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.812564
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.821436
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.831888
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.036371
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.072774
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.135896
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.287018
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.342407
35,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.508202
46,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.823748

Ranking by average statistics time (ascending):

,host_cpu,statistics_avg_time
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.141072
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.147452
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.149658
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.150956
25,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.164831
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.168026
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.172467
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.176746
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.180325
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.182122
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.185441
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.197254
43,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.203319
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.206597
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.207104
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.207238
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.216774
45,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.225698
32,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.225851
60,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.237845
26,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.243413
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.256736
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.258530
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.260196
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.261445
30,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.263565
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.271939
39,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.275028
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.282742
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.289064
27,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.297120
36,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.332374
47,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.351958
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.368919
56,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.387384
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395596
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.396304
59,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.415645
48,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.430578
52,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.440528
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.459804
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.534456
54,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.578091
41,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.588329
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.624623
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.662899
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.669798
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.689494
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.791946
50,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.861385
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.869160
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.908945
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.914073
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.931412
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.097377
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.140910
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.163339
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.360749
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.448765
35,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,2.612892
46,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,4.208320

Ranking by average complex_join time (ascending):

,host_cpu,complex_join_avg_time
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,3.043056
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,3.093814
25,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,3.174487
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,3.500320
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,3.604662
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,3.682625
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,3.750240
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,3.870069
60,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,3.961250
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,4.136510
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,4.218467
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,4.271681
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,4.544823
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,4.637280
43,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,4.897682
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,4.902261
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,5.005017
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,5.125440
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,5.223634
32,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,5.350801
41,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,5.362735
45,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,5.567900
39,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,5.638994
26,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,5.858662
30,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,5.947107
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,5.981846
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,6.091291
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,6.142236
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,6.190292
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,6.302954
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,6.342929
27,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,6.829715
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,7.040301
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,7.085135
36,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,7.117847
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,7.248586
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,7.622959
56,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,7.659173
47,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,7.703487
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.756925
59,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,8.375969
35,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,8.456072
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,8.619418
52,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,8.817132
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,9.057651
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.301819
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.384543
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,9.791986
54,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,9.969111
48,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,10.487334
50,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,10.943079
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,11.430337
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.718066
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,12.467298
46,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,13.052801
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,14.181277
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,14.193325
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,14.483172
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,17.847316
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,18.834236
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,24.791240

Ranking by average timeseries time (ascending):

,host_cpu,timeseries_avg_time
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.768042
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.781308
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.826957
25,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.831431
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.888004
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.909459
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.909704
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.920432
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.931719
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.937399
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.974662
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.980473
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,1.019426
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,1.048131
43,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.067212
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.071617
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.080760
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,1.119582
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.125433
26,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,1.129725
60,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.135645
30,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,1.208271
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.224979
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.235237
32,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.249969
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,1.254550
45,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.315969
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.340433
39,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,1.360454
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,1.376781
27,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,1.441172
41,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.444806
47,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.451081
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.582553
36,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,1.592549
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.645263
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,1.651231
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.665469
56,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,1.701790
59,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.732938
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.744553
52,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.866644
54,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.883217
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.935096
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.027155
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.108246
48,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.142782
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,2.376920
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.496969
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.646161
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.748607
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,3.031831
50,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.051035
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.275654
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.327298
35,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.574959
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,3.880878
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.310571
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,4.326716
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,4.816141
46,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.058113

,host_cpu,filter_group_avg_time,statistics_avg_time,complex_join_avg_time,timeseries_avg_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.277032,0.216774,5.005017,1.080760
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.392711,0.368919,7.248586,1.582553
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.821436,0.869160,11.718066,2.646161
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.210105,0.141072,3.604662,0.781308
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.693557,0.689494,6.302954,1.651231
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.694441,0.624623,9.057651,2.376920
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.036371,1.163339,14.181277,4.310571
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.611797,0.669798,9.301819,2.108246
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.609594,0.662899,9.384543,2.027155
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.342407,1.360749,17.847316,4.816141
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.831888,0.791946,14.483172,3.275654
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.812564,0.914073,12.467298,3.031831
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.463158,0.459804,7.756925,1.744553
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.746890,0.931412,24.791240,3.327298
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.072774,1.097377,18.834236,4.326716
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.438459,0.396304,7.085135,1.645263
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.804758,0.908945,11.430337,2.748607
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.209489,0.150956,3.043056,0.826957
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.260246,0.168026,4.544823,0.931719
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.315131,0.260196,7.622959,1.376781
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.232272,0.180325,4.637280,0.909459
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.264002,0.258530,6.190292,1.071617
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.135896,1.140910,14.193325,3.880878
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090,0.149658,3.682625,0.768042
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.287018,1.448765,6.342929,2.496969
25,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.153555,0.164831,3.174487,0.831431
26,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.350148,0.243413,5.858662,1.129725
27,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.334513,0.297120,6.829715,1.441172
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.201356,0.185441,6.142236,1.048131
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.265074,0.197254,3.870069,0.974662
30,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.294546,0.263565,5.947107,1.208271
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.368343,0.256736,7.040301,1.224979
32,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.257783,0.225851,5.350801,1.249969
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.245565,0.207104,3.500320,1.119582
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.224723,0.147452,3.750240,0.888004
35,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.508202,2.612892,8.456072,3.574959
36,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.366369,0.332374,7.117847,1.592549
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.199375,0.176746,3.093814,0.909704
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.271585,0.206597,4.136510,1.019426
39,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.305850,0.275028,5.638994,1.360454
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.242138,0.182122,4.271681,0.920432
41,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.597730,0.588329,5.362735,1.444806
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.271687,0.172467,4.218467,0.937399
43,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.235091,0.203319,4.897682,1.067212
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.308836,0.207238,5.125440,0.980473
45,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.255735,0.225698,5.567900,1.315969
46,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.823748,4.208320,13.052801,6.058113
47,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.382449,0.351958,7.703487,1.451081
48,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.475525,0.430578,10.487334,2.142782
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.513317,0.534456,8.619418,1.935096
50,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.749385,0.861385,10.943079,3.051035
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.325251,0.261445,5.981846,1.340433
52,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.480865,0.440528,8.817132,1.866644
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.550806,0.395596,9.791986,1.665469
54,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.442778,0.578091,9.969111,1.883217
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.332087,0.271939,4.902261,1.254550
56,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.417065,0.387384,7.659173,1.701790
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.322511,0.282742,5.223634,1.235237
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.300022,0.289064,6.091291,1.125433
59,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.477886,0.415645,8.375969,1.732938
60,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.269770,0.237845,3.961250,1.135645

In [ ]:
# Calculate the minumum time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  
    b_df[f'{test}_min_time'] = b_df[test_cols].min(axis=1)  

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the min per host+cpu for each test
test_min_cols = [f'{test}_min_time' for test in test_prefixes]
host_test_min = b_df.groupby('host_cpu')[test_min_cols].min().reset_index()

# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by minimum time {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_min[['host_cpu', f'{test}_min_time']].sort_values(f'{test}_min_time'))
    print("\n")

# Display the full table
host_test_min

:

In [ ]:
# Calculate the minimum time per row for each test and annotate which library achieved it (NaN-safe)

test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries']

for test in test_prefixes:
    # Raw timing columns only
    test_cols = [
        col for col in b_df.columns
        if col.startswith(f'{test}_') and col.endswith('_seconds')
    ]
    if not test_cols:
        b_df[f'{test}_min_time'] = float('nan')
        b_df[f'{test}_min_library'] = None
        continue

    # Convert to numeric (coerce 'N/A', blanks, etc. to NaN)
    numeric = b_df[test_cols].apply(pd.to_numeric, errors='coerce')

    # Row-wise min ignoring NaNs
    min_times = numeric.min(axis=1, skipna=True)

    # Identify the column name (library) producing the min ignoring NaNs.
    # pandas idxmin(skipna=True) returns NaN if the entire row is NaN.
    min_cols = numeric.idxmin(axis=1, skipna=True)

    suffix_len = len('_seconds')
    min_libs = []
    for col_name, all_nan in zip(min_cols, numeric.isna().all(axis=1)):
        if all_nan or pd.isna(col_name):
            min_libs.append(None)
        else:
            # column pattern: <test>_<library>_seconds
            lib_name = col_name[len(test) + 1: -suffix_len]
            min_libs.append(lib_name)

    b_df[f'{test}_min_time'] = min_times
    b_df[f'{test}_min_library'] = min_libs

# Unique host identifier
b_df['host_cpu'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['system'].astype(str)
)

# Aggregate: pick min time & corresponding library per host
host_rows = []
for host, g in b_df.groupby('host_cpu'):
    row = {'host_cpu': host}
    for test in test_prefixes:
        time_col = f'{test}_min_time'
        lib_col = f'{test}_min_library'
        if time_col not in g.columns or lib_col not in g.columns:
            row[time_col] = float('nan')
            row[lib_col] = None
            continue
        # valid rows for this test
        g_valid = g.dropna(subset=[time_col])
        if g_valid.empty:
            row[time_col] = float('nan')
            row[lib_col] = None
        else:
            # take the first row with minimal time
            min_idx = g_valid[time_col].idxmin()
            row[time_col] = g_valid.loc[min_idx, time_col]
            row[lib_col] = g_valid.loc[min_idx, lib_col]
    host_rows.append(row)

host_test_min = pd.DataFrame(host_rows)

# Display rankings per test including which library produced the min
for test in test_prefixes:
    time_col = f'{test}_min_time'
    lib_col = f'{test}_min_library'
    if time_col not in host_test_min.columns:
        continue
    print(f"Ranking by minimum {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(
            host_test_min[['host_cpu', time_col, lib_col]]
            .sort_values(time_col, na_position='last')
        )
    print("\n")

# Optional summary: frequency of fastest library per test
summary_rows = []
for test in test_prefixes:
    lib_col = f'{test}_min_library'
    if lib_col in host_test_min.columns:
        counts = host_test_min[lib_col].value_counts(dropna=True)
        for lib, cnt in counts.items():
            summary_rows.append({'test': test, 'library': lib, 'wins': cnt})
fastest_summary = pd.DataFrame(summary_rows).sort_values(['test', 'wins'], ascending=[True, False])
print("Fastest library counts per test:")
display(fastest_summary)

# Full aggregated table (one row per host with min times + libraries per test)
host_test_min

: