In [1]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [2]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       114 non-null    object
 1   hostname                        114 non-null    object
 2   platform                        114 non-null    object
 3   system                          114 non-null    object
 4   release                         114 non-null    int64
 5   version                         114 non-null    object
 6   machine                         114 non-null    object
 7   processor                       114 non-null    object
 8   cpu_count_logical               114 non-null    int64
 9   cpu_count_physical              114 non-null    int64
 10  cpu_freq_max                    114 non-null    float64
 11  cpu_freq_current                114 non-null    float64
 12  memory_total_gb                 114 non-null    float64
 13  memory_available_gb             114 non-null    float64
 14  python_version                  114 non-null    object
 15  python_implementation           114 non-null    object
 16  cpu_brand                       114 non-null    object
 17  cpu_arch                        114 non-null    object
 18  dataset_size                    114 non-null    int64
 19  dataset_name                    114 non-null    object
 20  dataset_format                  114 non-null    object
 21  filter_group_pandas_seconds     114 non-null    float64
 22  filter_group_polars_seconds     114 non-null    float64
 23  filter_group_duckdb_seconds     114 non-null    float64
 24  filter_group_fireducks_seconds  0 non-null      float64
 25  statistics_pandas_seconds       114 non-null    float64
 26  statistics_polars_seconds       114 non-null    float64
 27  statistics_duckdb_seconds       114 non-null    float64
 28  statistics_fireducks_seconds    0 non-null      float64
 29  complex_join_pandas_seconds     114 non-null    float64
 30  complex_join_polars_seconds     114 non-null    float64
 31  complex_join_duckdb_seconds     114 non-null    float64
 32  complex_join_fireducks_seconds  0 non-null      float64
 33  timeseries_pandas_seconds       114 non-null    float64
 34  timeseries_polars_seconds       114 non-null    float64
 35  timeseries_duckdb_seconds       114 non-null    float64
 36  timeseries_fireducks_seconds    0 non-null      float64
 37  script_name                     114 non-null    object
dtypes: float64(20), int64(4), object(14)
memory usage: 34.0+ KB

In [3]:
# Removing fireduck for now because there is not data(yet)
fireduck_columns = [col for col in b_df.columns if 'fireducks_' in col]
b_df.drop(columns=fireduck_columns, inplace=True)

b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   timestamp                    114 non-null    object
 1   hostname                     114 non-null    object
 2   platform                     114 non-null    object
 3   system                       114 non-null    object
 4   release                      114 non-null    int64
 5   version                      114 non-null    object
 6   machine                      114 non-null    object
 7   processor                    114 non-null    object
 8   cpu_count_logical            114 non-null    int64
 9   cpu_count_physical           114 non-null    int64
 10  cpu_freq_max                 114 non-null    float64
 11  cpu_freq_current             114 non-null    float64
 12  memory_total_gb              114 non-null    float64
 13  memory_available_gb          114 non-null    float64
 14  python_version               114 non-null    object
 15  python_implementation        114 non-null    object
 16  cpu_brand                    114 non-null    object
 17  cpu_arch                     114 non-null    object
 18  dataset_size                 114 non-null    int64
 19  dataset_name                 114 non-null    object
 20  dataset_format               114 non-null    object
 21  filter_group_pandas_seconds  114 non-null    float64
 22  filter_group_polars_seconds  114 non-null    float64
 23  filter_group_duckdb_seconds  114 non-null    float64
 24  statistics_pandas_seconds    114 non-null    float64
 25  statistics_polars_seconds    114 non-null    float64
 26  statistics_duckdb_seconds    114 non-null    float64
 27  complex_join_pandas_seconds  114 non-null    float64
 28  complex_join_polars_seconds  114 non-null    float64
 29  complex_join_duckdb_seconds  114 non-null    float64
 30  timeseries_pandas_seconds    114 non-null    float64
 31  timeseries_polars_seconds    114 non-null    float64
 32  timeseries_duckdb_seconds    114 non-null    float64
 33  script_name                  114 non-null    object
dtypes: float64(16), int64(4), object(14)
memory usage: 30.4+ KB

In [4]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(110, 34)

In [5]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(4)
b_df.head(3)

,timestamp,hostname,platform,system,release,version,machine,processor,cpu_count_logical,cpu_count_physical,...,statistics_pandas_seconds,statistics_polars_seconds,statistics_duckdb_seconds,complex_join_pandas_seconds,complex_join_polars_seconds,complex_join_duckdb_seconds,timeseries_pandas_seconds,timeseries_polars_seconds,timeseries_duckdb_seconds,script_name
0,2025-08-20T22:58:21.887566,TS-P350-01,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"Intel64 Family 6 Model 167 Stepping 1, Genuine...",16,8,...,21.2685,1.2646,1.0251,37.7647,2.7836,10.7206,25.6413,3.3484,1.0100,benchmark.py
1,2025-08-21T15:09:54.202383,WL5022,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"Intel64 Family 6 Model 140 Stepping 1, Genuine...",8,4,...,44.5267,4.2818,4.1815,75.8036,6.4908,22.1753,48.5759,8.0436,4.2604,benchmark.py
2,2025-08-21T18:10:27.497627,MSI,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,17.3882,1.0778,0.9855,34.0420,1.7733,7.4427,21.0240,4.0653,0.7738,benchmark.py

In [6]:
def rank_methods(df, operation_col_prefix):
    time_cols = [col for col in df.columns if col.startswith(operation_col_prefix) and col.endswith('_seconds')]
    rank_df = pd.DataFrame()
    rank_df['hostname'] = df['hostname']
    rank_df['cpu_brand'] = df['cpu_brand'] 
    rank_df['dataset_size'] = df['dataset_size']
    rank_df['dataset_format'] = df['dataset_format']
    
    for col in time_cols:
        rank_col = f"rank_{col}"
        # Only rank non-zero values, assign max rank to zeros
        mask = df[col] > 0
        rank_df[rank_col] = df[col].where(mask).rank(method='min')
        max_rank = rank_df[rank_col].max()
        rank_df[rank_col] = rank_df[rank_col].fillna(max_rank + 1)
    
    return rank_df

In [7]:
filter_group_ranks = rank_methods(b_df, 'filter_group_')
sort_values_cols = [col for col in filter_group_ranks.columns if col.startswith('rank_filter_group_')]
filter_group_ranks[sort_values_cols] = filter_group_ranks[sort_values_cols].astype(int)
filter_group_ranks = filter_group_ranks.sort_values(by=sort_values_cols + ['hostname', 'dataset_format'])
filter_group_ranks

,hostname,cpu_brand,dataset_size,dataset_format,rank_filter_group_pandas_seconds,rank_filter_group_polars_seconds,rank_filter_group_duckdb_seconds
89,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,1,20,65
93,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,2,11,16
91,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,3,16,64
88,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,4,26,57
81,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,5,5,48
...,...,...,...,...,...,...,...
64,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,106,105,99
65,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,107,86,82
17,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,108,102,102
73,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,109,88,83
4,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,10000000,csv,110,110,109

In [8]:
def get_df_by_test(df: pd.DataFrame, cols_to_group: list, metric: str) -> pd.DataFrame:
    # Properly combine columns - create a new list instead of using append
    columns_to_select = cols_to_group + [metric]
    
    # Select the relevant columns
    df_subset = df[columns_to_select]
    
    # Remove rows where the metric is null/zero (assuming you want valid measurements)
    df_filtered = df_subset[df_subset[metric] > 0]  # or use .notna() if you want non-null values
    
    # Group by the specified columns and get minimum values
    grouped = df_filtered.groupby(cols_to_group)
    return grouped.min().reset_index().sort_values(by=metric)

In [9]:
cols_to_group = [ "dataset_format","hostname", "cpu_brand"]
for col_to_rank in time_cols:
    print(f"Ranking by: {col_to_rank}")
    df_by_test = get_df_by_test(b_df, cols_to_group, col_to_rank)
    display(df_by_test)
    print("\n")

Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,filter_group_pandas_seconds
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.2705
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.2947
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.2991
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.3015
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.3077
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.3208
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.5351
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,5.0307
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,5.3583
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,6.1023
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,8.6615
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10.4113
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,10.6675
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,11.9636
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,14.2333
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,14.7335
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.0980
9,csv,WL5022,Unknown (cpuinfo not available),22.8431
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,23.8160

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,filter_group_polars_seconds
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.0715
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0849
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0889
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.0950
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.1049
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1406
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1411
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1489
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1557
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.1603
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.3406
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.4887
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.5050
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.6154
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.7971
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.8318
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,0.9487
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.0421
9,csv,WL5022,Unknown (cpuinfo not available),2.8214

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,filter_group_duckdb_seconds
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0338
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0348
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0356
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.0419
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0430
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0481
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0524
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.0629
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.0631
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.0734
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.1433
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.5018
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.5556
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.6685
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.7598
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.7791
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.9475
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,1.5988
9,csv,WL5022,Unknown (cpuinfo not available),3.9740

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,statistics_pandas_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.2192
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.2242
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.2246
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.2270
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.2342
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.2445
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.7148
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,5.3573
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,6.1282
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,6.4237
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10.1561
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10.3763
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,11.5511
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,16.3682
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,17.3882
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.4169
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,19.7669
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,29.1227
9,csv,WL5022,Unknown (cpuinfo not available),44.5267

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,statistics_polars_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0601
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0639
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0959
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1046
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1212
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1214
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.2497
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.2887
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.3147
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.3955
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.4998
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.6457
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.7147
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.9183
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.9779
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,1.2646
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.3273
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,1.4594
9,csv,WL5022,Unknown (cpuinfo not available),4.2818

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,statistics_duckdb_seconds
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0505
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0611
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0622
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0641
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0776
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0810
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.1095
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.1146
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.1409
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.1463
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.2756
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.5730
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.6790
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.7805
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.8558
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,1.0251
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.2164
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,1.9137
9,csv,WL5022,Unknown (cpuinfo not available),4.1815

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,complex_join_pandas_seconds
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,2.2346
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,2.3353
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.5018
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,2.5049
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.5058
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,2.5658
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,7.5601
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,8.0883
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.3534
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10.2450
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,16.4438
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,16.4700
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,23.2358
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,29.2015
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,32.4280
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,34.1476
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,35.2504
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,51.7238
9,csv,WL5022,Unknown (cpuinfo not available),75.8036

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,complex_join_polars_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.4833
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.5019
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.5207
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.5228
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5432
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5581
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.8486
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.9389
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,1.2282
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,1.2649
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,1.3903
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,1.4264
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,1.4961
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,1.6359
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.7277
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,1.9152
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,2.3456
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,3.3951
9,csv,WL5022,Unknown (cpuinfo not available),6.4908

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,complex_join_duckdb_seconds
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,3.1954
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,3.2853
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,3.5813
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,3.5945
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,4.2374
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.5955
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,4.7151
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,4.7469
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,4.8746
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,5.1401
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,6.1227
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,6.2196
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,7.1560
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,8.1853
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.4259
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,9.1299
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,9.5153
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,12.9485
9,csv,WL5022,Unknown (cpuinfo not available),22.1753

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,timeseries_pandas_seconds
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.4935
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.5183
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5674
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5731
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.5954
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.6008
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,7.0802
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,7.8940
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.8249
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,8.9016
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,12.8615
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,13.2594
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,14.2759
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,18.4051
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,19.6064
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,22.3014
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,25.4716
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,33.3294
9,csv,WL5022,Unknown (cpuinfo not available),48.5759

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,timeseries_polars_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,1.9154
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,1.9309
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,1.9436
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,1.9651
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,2.0356
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.1359
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.1381
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,2.2170
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,2.3974
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,2.4011
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,2.4089
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,2.6612
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,2.8416
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,3.3484
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,3.4880
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,4.2395
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,4.5425
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,4.7033
9,csv,WL5022,Unknown (cpuinfo not available),8.0436

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,timeseries_duckdb_seconds
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.1140
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.1271
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1462
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1478
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1697
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.1864
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1962
16,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.2055
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.2427
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.3469
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.4278
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.5615
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.6399
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.6735
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.8311
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,1.0100
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.1351
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,2.2325
9,csv,WL5022,Unknown (cpuinfo not available),4.2604

In [10]:
# Filter Group Pandas
fg_p = b_df[["hostname", "cpu_brand","dataset_size", "dataset_format", "filter_group_pandas_seconds"]]
fg_p = fg_p.groupby(by=["hostname", "cpu_brand","dataset_size", "dataset_format"]).min().reset_index()
fg_p = fg_p.rename(columns={"filter_group_pandas_seconds": "min_time_seconds"})
fg_p = fg_p.sort_values(by=["dataset_size","min_time_seconds", "hostname",  "dataset_format"])
fg_p

,hostname,cpu_brand,dataset_size,dataset_format,min_time_seconds
10,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,0.2705
2,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,0.2947
1,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,parquet,0.2991
11,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,parquet,0.3015
3,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,parquet,0.3077
0,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,0.3208
6,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,4.5351
8,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,parquet,5.0307
13,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,parquet,5.3583
15,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,parquet,6.1023
18,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,parquet,8.6615
12,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,10.4113
5,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,csv,10.6675
7,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,11.9636
14,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,csv,14.2333
9,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,14.7335
4,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,10000000,csv,19.0980
16,WL5022,Unknown (cpuinfo not available),10000000,csv,22.8431
17,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,23.8160

In [11]:
print(f"The fastest filter_group_pandas_seconds is {fg_p['min_time_seconds'].min()} seconds")

The fastest filter_group_pandas_seconds is 0.2705 seconds