In [18]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [19]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 769 entries, 0 to 768
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       769 non-null    object
 1   hostname                        769 non-null    object
 2   platform                        769 non-null    object
 3   system                          769 non-null    object
 4   release                         769 non-null    object
 5   version                         769 non-null    object
 6   machine                         769 non-null    object
 7   processor                       769 non-null    object
 8   cpu_count_logical               769 non-null    int64
 9   cpu_count_physical              769 non-null    int64
 10  cpu_freq_max                    769 non-null    float64
 11  cpu_freq_current                769 non-null    float64
 12  memory_total_gb                 769 non-null    float64
 13  memory_available_gb             769 non-null    float64
 14  python_version                  769 non-null    object
 15  python_implementation           769 non-null    object
 16  cpu_brand                       769 non-null    object
 17  cpu_arch                        769 non-null    object
 18  dataset_size                    769 non-null    int64
 19  dataset_name                    769 non-null    object
 20  dataset_format                  769 non-null    object
 21  filter_group_pandas_seconds     768 non-null    float64
 22  filter_group_polars_seconds     769 non-null    float64
 23  filter_group_duckdb_seconds     769 non-null    float64
 24  filter_group_fireducks_seconds  390 non-null    float64
 25  statistics_pandas_seconds       768 non-null    float64
 26  statistics_polars_seconds       769 non-null    float64
 27  statistics_duckdb_seconds       769 non-null    float64
 28  statistics_fireducks_seconds    390 non-null    float64
 29  complex_join_pandas_seconds     768 non-null    float64
 30  complex_join_polars_seconds     769 non-null    float64
 31  complex_join_duckdb_seconds     769 non-null    float64
 32  complex_join_fireducks_seconds  390 non-null    float64
 33  timeseries_pandas_seconds       768 non-null    float64
 34  timeseries_polars_seconds       769 non-null    float64
 35  timeseries_duckdb_seconds       769 non-null    float64
 36  timeseries_fireducks_seconds    390 non-null    float64
 37  script_name                     769 non-null    object
dtypes: float64(20), int64(3), object(15)
memory usage: 228.4+ KB

In [20]:
# Removing fireduck for now because there is not data(yet)
#fireduck_columns = [col for col in b_df.columns if 'fireducks_' in col]
#b_df.drop(columns=fireduck_columns, inplace=True)

#b_df.info()

In [21]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(764, 38)

In [22]:
# Clean platform-based analysis now possible
wsl2_data = b_df[b_df['system'] == 'WSL2']
native_linux = b_df[b_df['system'] == 'Linux'] 
windows_data = b_df[b_df['system'] == 'Windows']

# Example: Compare FireDucks performance
fireducks_wsl2 = wsl2_data['filter_group_fireducks_seconds']
fireducks_linux = native_linux['filter_group_fireducks_seconds']

In [23]:
# Filtering by platform
#b_df = windows_data # Focus on Windows data for now

In [24]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(6) # Round to microseconds for better readability
b_df.head(3)

,timestamp,hostname,platform,system,release,version,machine,processor,cpu_count_logical,cpu_count_physical,...,statistics_fireducks_seconds,complex_join_pandas_seconds,complex_join_polars_seconds,complex_join_duckdb_seconds,complex_join_fireducks_seconds,timeseries_pandas_seconds,timeseries_polars_seconds,timeseries_duckdb_seconds,timeseries_fireducks_seconds,script_name
0,2025-08-28T19:37:29.241650,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,44.743244,6.037812,26.736806,NaN,22.656234,7.020198,3.894986,NaN,benchmark_01.py
1,2025-08-28T21:16:05.419895,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,23.235775,1.426380,4.835438,NaN,12.861529,2.425745,0.614240,NaN,benchmark.py
2,2025-08-28T21:25:30.654371,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,28.530276,1.482855,5.431484,NaN,16.994786,2.902070,0.595494,NaN,benchmark_02.py

In [25]:
def rank_methods(df, operation_col_prefix):
    time_cols = [col for col in df.columns if col.startswith(operation_col_prefix) and col.endswith('_seconds')]
    rank_df = pd.DataFrame()
    rank_df['hostname'] = df['hostname']
    rank_df['cpu_brand'] = df['cpu_brand'] 
    rank_df['dataset_size'] = df['dataset_size']
    rank_df['dataset_format'] = df['dataset_format']
    
    for col in time_cols:
        rank_col = f"rank_{col}"
        # Only rank non-zero values, assign max rank to zeros
        mask = df[col] > 0
        rank_df[rank_col] = df[col].where(mask).rank(method='min')
        max_rank = rank_df[rank_col].max()
        rank_df[rank_col] = rank_df[rank_col].fillna(max_rank + 1)
    
    return rank_df

In [26]:
filter_group_ranks = rank_methods(b_df, 'filter_group_')
sort_values_cols = [col for col in filter_group_ranks.columns if col.startswith('rank_filter_group_')]
filter_group_ranks[sort_values_cols] = filter_group_ranks[sort_values_cols].astype(int)
filter_group_ranks = filter_group_ranks.sort_values(by=sort_values_cols + ['hostname', 'dataset_format'])
filter_group_ranks

,hostname,cpu_brand,dataset_size,dataset_format,rank_filter_group_pandas_seconds,rank_filter_group_polars_seconds,rank_filter_group_duckdb_seconds,rank_filter_group_fireducks_seconds
585,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,csv,1,241,184,64
587,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,parquet,2,301,161,170
723,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,3,30,388,15
728,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,parquet,4,8,2,14
586,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,parquet,5,315,80,101
...,...,...,...,...,...,...,...,...
16,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,760,736,501,391
46,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,761,759,607,391
32,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,762,737,596,391
33,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,763,754,610,391
0,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,764,763,729,391

In [27]:
def get_df_by_test(df: pd.DataFrame, cols_to_group: list, metric: str) -> pd.DataFrame:
    # Properly combine columns - create a new list instead of using append
    columns_to_select = cols_to_group + [metric]
    
    # Select the relevant columns
    df_subset = df[columns_to_select]
    
    # Remove rows where the metric is null/zero 
    df_filtered = df_subset[df_subset[metric] > 0]  # or use .notna() 
    
    # Group by the specified columns and get minimum values
    grouped = df_filtered.groupby(cols_to_group)
    return grouped.min().reset_index().sort_values(by=metric)

In [28]:
cols_to_group = [ "dataset_format","hostname", "cpu_brand", "system", "memory_total_gb"]
with pd.option_context('display.max_rows', None):
    for col_to_rank in time_cols:
        print(f"Ranking by: {col_to_rank}")
        df_by_test = get_df_by_test(b_df, cols_to_group, col_to_rank).reset_index(drop=True)
        display(df_by_test)
        print("\n")

Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.176201
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.188335
2,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.189167
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.189469
4,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.194035
5,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.194325
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.204102
7,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.205537
8,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.205929
9,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.210462
10,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.214854
11,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.230181
12,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.230830
13,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.236677
14,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.239010
15,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.239222
16,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.239936
17,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.242897
18,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.245038
19,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.249029
20,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.252594
21,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.252882
22,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.255371
23,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.255536
24,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.257193
25,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.257924
26,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.259799
27,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.260106
28,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.261258
29,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.267274
30,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.267586
31,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.268126
32,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.269150
33,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.269462
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.269707
35,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.270451
36,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.270499
37,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.271542
38,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.273162
39,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.273861
40,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.274816
41,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.275933
42,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.278754
43,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.278784
44,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.278926
45,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.279343
46,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.282793
47,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.283666
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.284732
49,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.284936
50,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.288474
51,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.292675
52,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.293107
53,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.293178
54,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.293566
55,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.294839
56,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.295494
57,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.296013
58,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.298231
59,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.299906
60,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.300393
61,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.304548
62,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.304917
63,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.307013
64,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.307098
65,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.307888
66,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.312222
67,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.313211
68,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.314343
69,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.315864
70,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.316029
71,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.316038
72,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.320001
73,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.321065
74,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.325910
75,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.335269
76,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.335481
77,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.359498
78,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.365571
79,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.367142
80,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.369146
81,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.372711
82,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.374583
83,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.379084
84,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.379735
85,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.380978
86,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.382879
87,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.383956
88,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.389362
89,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.393282
90,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.397570
91,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.409041
92,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.409166
93,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.415871
94,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.416637
95,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.421023
96,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.425848
97,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.428233
98,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.434067
99,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.447669
100,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.450492
101,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.453049
102,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.461787
103,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.463888
104,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.465891
105,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.468646
106,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.475752
107,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.475849
108,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.492413
109,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.493353
110,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.506782
111,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.514984
112,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.528547
113,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.535098
114,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.555320
115,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.583145
116,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.591544
117,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.617913
118,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.637270
119,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.641110
120,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.663562
121,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.692138
122,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.702786
123,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.703566
124,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.731955
125,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.962332
126,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,5.358341
127,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,10.411298

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_polars_seconds
0,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.071505
1,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.085730
2,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.085799
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.086000
4,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.086550
5,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.086587
6,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.089034
7,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.089723
8,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.094960
9,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.097477
10,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.098239
11,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.098410
12,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.101247
13,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.105863
14,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.107952
15,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.113670
16,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.116799
17,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.117693
18,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.118766
19,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.119589
20,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.125012
21,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.125330
22,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.126928
23,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.127720
24,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.127974
25,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.128240
26,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.129033
27,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.131098
28,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.132450
29,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.132462
30,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.133582
31,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.133691
32,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.134381
33,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.135089
34,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.136902
35,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.139211
36,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.140502
37,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.141459
38,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.144457
39,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.144622
40,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.147632
41,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.148480
42,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.148520
43,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.152259
44,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.153641
45,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.154450
46,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.157515
47,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.160327
48,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.160666
49,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.161578
50,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.165737
51,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.165866
52,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.168699
53,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.176206
54,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.177092
55,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.180809
56,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.183723
57,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.185390
58,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.188349
59,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.188720
60,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.191101
61,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.192195
62,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.194010
63,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.194452
64,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.195381
65,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.199044
66,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.201567
67,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.203178
68,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.204266
69,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.204483
70,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.206960
71,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.208076
72,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.208222
73,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.215265
74,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.216848
75,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.218959
76,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.219885
77,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.226329
78,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.230266
79,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.234705
80,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.239710
81,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.243947
82,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.245735
83,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.250173
84,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.250457
85,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.253067
86,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.264340
87,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.267077
88,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.268869
89,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.269017
90,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.272008
91,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.273836
92,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.275828
93,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.280271
94,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.281430
95,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.286957
96,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.291214
97,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.294835
98,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.297577
99,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.297603
100,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.302873
101,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.306664
102,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.315507
103,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.322647
104,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.330961
105,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.331924
106,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.332424
107,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.340602
108,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.345873
109,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.355334
110,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.371280
111,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.376640
112,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.394636
113,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.431944
114,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.432383
115,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.433407
116,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.445868
117,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.447058
118,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.486967
119,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.488726
120,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.510137
121,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.542422
122,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.553279
123,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.565336
124,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.614996
125,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.625782
126,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.690226
127,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.823694

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.026820
1,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.031740
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.031890
3,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.031958
4,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.032062
5,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.032623
6,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.033227
7,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.033242
8,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.034698
9,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.034815
10,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.035718
11,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.035930
12,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.036465
13,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.036850
14,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.036903
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.036922
16,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.037508
17,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.038045
18,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.038939
19,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.039717
20,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.039799
21,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.040865
22,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.041783
23,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.041897
24,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.042423
25,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.042440
26,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.042528
27,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.042714
28,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.043635
29,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.045527
30,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.046066
31,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.046270
32,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.046697
33,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.047376
34,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.047544
35,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.047966
36,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.047970
37,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.048604
38,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.048618
39,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.048940
40,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.049098
41,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.049256
42,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.049330
43,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.049567
44,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.049598
45,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.049785
46,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.049786
47,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.050001
48,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.050120
49,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.051058
50,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.051560
51,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.052113
52,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.053021
53,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.053767
54,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.054035
55,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.054782
56,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.055147
57,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.055306
58,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.056555
59,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.057080
60,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.057113
61,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.057115
62,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.057278
63,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.058527
64,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.058952
65,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.060054
66,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.061755
67,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.062675
68,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.062731
69,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.064128
70,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.065138
71,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.065795
72,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.066707
73,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.066937
74,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.067097
75,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.068272
76,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.068845
77,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.072017
78,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.072401
79,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.073407
80,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.074056
81,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.075990
82,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.080767
83,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.082814
84,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.083453
85,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.084105
86,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.085639
87,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.086627
88,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.092058
89,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.094551
90,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.095555
91,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.096380
92,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.103483
93,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.113281
94,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.115737
95,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.116693
96,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.116821
97,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.119607
98,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.119977
99,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.122297
100,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.124491
101,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.126611
102,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.128099
103,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.133032
104,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.136810
105,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.137175
106,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.139353
107,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.141584
108,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.143259
109,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.146962
110,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.155095
111,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.156793
112,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.160650
113,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.168784
114,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.173057
115,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.173424
116,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.173585
117,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.175472
118,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.194292
119,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.217084
120,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.224818
121,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.233033
122,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.233598
123,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.238558
124,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.239716
125,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.261815
126,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.337646
127,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.501835

Ranking by: filter_group_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.001347
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.001380
2,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.001393
3,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.001396
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.001484
5,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.001491
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.001497
7,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.001519
8,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.001550
9,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.001573
10,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.001586
11,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.001589
12,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.001595
13,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.001598
14,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.001606
15,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.001609
16,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.001614
17,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.001644
18,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.001654
19,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.001656
20,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.001698
21,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.001710
22,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.001743
23,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.001753
24,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.001764
25,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.001776
26,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.001779
27,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.001840
28,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.001841
29,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.001853
30,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.001858
31,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.001923
32,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.001940
33,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.001991
34,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.001995
35,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.002010
36,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.002106
37,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.002157
38,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.002165
39,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.002271
40,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.002401
41,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.002427
42,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.002445
43,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.002453
44,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.002483
45,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.002528
46,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.002592
47,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.002678
48,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.002729
49,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.002809
50,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.002961
51,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.002979
52,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.003022
53,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.003029
54,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.003122
55,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.003213
56,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.003224
57,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.003372
58,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.003474
59,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.003905
60,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.003935
61,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.004023
62,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.004917
63,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.010577

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.148611
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.156536
2,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.160063
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.161277
4,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.161432
5,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.167602
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.168088
7,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.169622
8,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.171951
9,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.172934
10,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.178686
11,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.180868
12,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.180947
13,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.182035
14,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.184240
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.186431
16,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.187811
17,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.191251
18,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.192398
19,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.192725
20,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.199262
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.201684
22,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.201802
23,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.203179
24,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.204514
25,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.207913
26,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.208003
27,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.208207
28,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.213067
29,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.214802
30,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.215019
31,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.215042
32,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.216869
33,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.218891
34,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.219370
35,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.219511
36,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.219855
37,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.221023
38,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.221441
39,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.222419
40,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.222962
41,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.223908
42,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.224155
43,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.224219
44,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.224676
45,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.224676
46,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.224875
47,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.224946
48,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.225383
49,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.226260
50,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.227171
51,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.227811
52,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.228520
53,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.228935
54,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.231631
55,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.232281
56,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.232309
57,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.232864
58,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.232911
59,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.233630
60,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.234241
61,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.238018
62,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.238547
63,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.239711
64,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.240540
65,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.241225
66,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.241319
67,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.244071
68,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.251238
69,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.252322
70,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.254285
71,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.256198
72,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.261322
73,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.261675
74,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.263139
75,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.263959
76,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.265091
77,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.268410
78,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.268450
79,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.277762
80,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.287178
81,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.291042
82,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.294749
83,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.303906
84,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.312264
85,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.324660
86,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.333868
87,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.336234
88,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.338446
89,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.339025
90,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.339472
91,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.340918
92,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.343622
93,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.359289
94,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.360390
95,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.361939
96,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.367291
97,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.370749
98,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.371494
99,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.375648
100,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.377876
101,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.387176
102,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.391305
103,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.396269
104,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.397330
105,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.407656
106,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.432261
107,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.465929
108,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.471190
109,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.474622
110,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.479291
111,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.502419
112,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.505736
113,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.513319
114,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.524030
115,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.580449
116,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.600673
117,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.625986
118,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.652209
119,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.669447
120,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.673124
121,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.676553
122,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.684314
123,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.752458
124,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.837387
125,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.850339
126,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,6.423730
127,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,10.376254

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.054323
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.057185
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.057959
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.061096
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.061169
5,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.063687
6,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.066585
7,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.068867
8,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.072699
9,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.081498
10,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.085318
11,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.086847
12,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.087296
13,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.087507
14,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.088038
15,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.088249
16,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.089538
17,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.091074
18,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.091635
19,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.092394
20,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.093786
21,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.093914
22,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.094251
23,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.094802
24,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.095288
25,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.095524
26,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.095553
27,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.095885
28,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.096383
29,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.097667
30,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.098535
31,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.098646
32,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.101301
33,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.101981
34,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.103099
35,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.104160
36,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.104290
37,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.108512
38,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.109605
39,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.110336
40,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.110767
41,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.112284
42,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.112821
43,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.116079
44,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.116513
45,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.116968
46,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.117172
47,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.117725
48,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.118668
49,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.121048
50,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.123976
51,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.127979
52,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.132946
53,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.134012
54,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.134709
55,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.135417
56,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.136704
57,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.139852
58,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.140574
59,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.142213
60,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.143918
61,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.144932
62,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.145582
63,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.154213
64,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.157966
65,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.160681
66,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.164934
67,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.164970
68,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.168137
69,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.175646
70,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.181394
71,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.188093
72,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.191556
73,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.195593
74,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.196279
75,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.199275
76,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.201458
77,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.205388
78,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.207037
79,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.210085
80,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.222970
81,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.225668
82,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.225771
83,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.228205
84,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.228700
85,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.232830
86,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.234784
87,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.238894
88,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.248640
89,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.256583
90,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.273801
91,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.275371
92,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.303131
93,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.305176
94,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.307027
95,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.309664
96,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.311508
97,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.314736
98,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.319131
99,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.322771
100,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.327670
101,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.330587
102,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.332090
103,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.339440
104,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.339904
105,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.357911
106,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.363951
107,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.365960
108,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.366613
109,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.373520
110,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.375136
111,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.383513
112,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.383970
113,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.392614
114,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.395479
115,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.398507
116,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.404778
117,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.418672
118,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.422337
119,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.425459
120,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.438670
121,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.443669
122,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.450185
123,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.480064
124,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.510830
125,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.516206
126,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.516427
127,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.645693

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.036783
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.038060
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.048504
3,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.049224
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.049645
5,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.051478
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.051746
7,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.052067
8,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.052469
9,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.053194
10,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.054845
11,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.055085
12,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.056630
13,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.057525
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.057667
15,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.058021
16,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.058118
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.059392
18,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.059622
19,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.059756
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.061105
21,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.062178
22,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.065039
23,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.065420
24,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.066542
25,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.066727
26,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.067213
27,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.067360
28,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.067506
29,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.068152
30,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.068492
31,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.068837
32,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.069108
33,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.069300
34,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.069782
35,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.070140
36,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.070597
37,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.071951
38,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.072261
39,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.073422
40,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.073599
41,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.073689
42,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.073785
43,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.074120
44,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.075092
45,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.076049
46,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.077940
47,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.079261
48,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.079360
49,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.080334
50,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.081314
51,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.081628
52,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.082255
53,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.083700
54,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.083737
55,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.084394
56,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.085253
57,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.085688
58,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.085934
59,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.088910
60,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.089430
61,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.090133
62,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.090168
63,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.090312
64,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.090960
65,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.092868
66,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.093565
67,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.095744
68,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.095846
69,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.096858
70,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.097076
71,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.099953
72,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.103057
73,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.103255
74,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.106214
75,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.106493
76,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.108964
77,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.109509
78,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.110594
79,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.114472
80,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.114537
81,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.118487
82,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.121890
83,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.124516
84,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.131306
85,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.134772
86,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.140150
87,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.143583
88,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.149406
89,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.150332
90,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.164641
91,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.167851
92,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.195986
93,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.196961
94,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.198998
95,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.210103
96,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.211529
97,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.222407
98,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.251149
99,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.252737
100,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.252801
101,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.253880
102,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.295498
103,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.304877
104,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.323197
105,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.328502
106,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.329382
107,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.332450
108,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.344468
109,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.352225
110,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.354550
111,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.355642
112,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.358730
113,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.370384
114,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.375684
115,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.382014
116,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.382476
117,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.398099
118,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.445769
119,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.447324
120,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.460195
121,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.494045
122,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.498727
123,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.536384
124,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.572973
125,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.574453
126,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.660862
127,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.673051

Ranking by: statistics_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.000125
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.000133
2,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000140
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000141
4,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000145
5,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000146
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000148
7,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000152
8,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.000176
9,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.000182
10,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000187
11,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.000188
12,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.000191
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000193
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000195
15,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.000195
16,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.000195
17,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.000196
18,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000197
19,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000204
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000205
21,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000213
22,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.000218
23,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000220
24,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.000221
25,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.000222
26,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.000227
27,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000227
28,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000232
29,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.000234
30,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.000235
31,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.000237
32,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000239
33,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.000240
34,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000246
35,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000249
36,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000250
37,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.000258
38,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.000271
39,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.000272
40,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.000283
41,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.000287
42,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000289
43,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000291
44,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000309
45,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000312
46,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.000319
47,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000338
48,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000347
49,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000364
50,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000381
51,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.000384
52,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000414
53,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.000420
54,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000469
55,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000484
56,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.000490
57,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000491
58,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.000549
59,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.000555
60,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.000564
61,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.000571
62,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.000573
63,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.000893

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,1.600232
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,1.686373
2,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.703667
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,1.738139
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,1.740872
5,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,1.741788
6,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,1.743906
7,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,1.750485
8,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,1.756985
9,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,1.764612
10,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.783565
11,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,1.800952
12,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.812609
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.826722
14,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.845459
15,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,1.858019
16,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,1.858767
17,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,1.867475
18,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.885700
19,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.032971
20,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,2.039433
21,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.063363
22,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,2.068671
23,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,2.072243
24,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,2.086920
25,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.143273
26,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,2.146466
27,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.148765
28,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,2.155096
29,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,2.156851
30,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,2.157476
31,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,2.158110
32,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.159110
33,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.190334
34,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,2.195587
35,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,2.205681
36,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,2.207379
37,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,2.208451
38,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,2.212902
39,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,2.218156
40,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,2.220050
41,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,2.221370
42,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,2.259400
43,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.295366
44,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.309064
45,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.310993
46,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.313880
47,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.321239
48,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,2.325525
49,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.337842
50,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.399702
51,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.419912
52,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,2.436286
53,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.460799
54,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.486614
55,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.501646
56,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,2.502459
57,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,2.570981
58,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,2.584196
59,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,2.599715
60,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.599806
61,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.681270
62,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.690762
63,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,2.704473
64,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,2.710402
65,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,2.731822
66,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,2.745317
67,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,2.769056
68,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,2.772811
69,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,2.799186
70,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,2.836061
71,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.862606
72,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,2.897614
73,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,2.920474
74,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.937153
75,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,3.039260
76,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,3.052452
77,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,3.066234
78,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.101532
79,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,3.175220
80,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.193744
81,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,3.226381
82,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,3.328890
83,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.379374
84,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,3.404619
85,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,3.418511
86,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,3.425977
87,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,3.534181
88,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,3.618343
89,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,3.637755
90,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,3.735163
91,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,3.748340
92,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,3.944685
93,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.956058
94,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,3.981980
95,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,3.982410
96,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,4.005578
97,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,4.029502
98,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,4.149068
99,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,4.155437
100,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,4.253906
101,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,4.384282
102,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,4.393550
103,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,4.425937
104,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,4.435003
105,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,4.461058
106,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,4.466859
107,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,4.541414
108,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,4.699407
109,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,4.933718
110,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,5.147182
111,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,5.252674
112,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,5.443431
113,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,5.558602
114,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,5.630370
115,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,5.688737
116,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,5.708399
117,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,5.756413
118,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,5.822155
119,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,6.052842
120,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,6.176363
121,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,6.501427
122,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,6.842711
123,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,6.970424
124,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,8.353409
125,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,8.903364
126,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,9.781901
127,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,23.235775

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.351187
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.368932
2,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.392026
3,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.409226
4,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.433622
5,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.440721
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.444010
7,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.450646
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.459607
9,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.460579
10,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.460666
11,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.470777
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.476252
13,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.476298
14,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.479752
15,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.482777
16,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.483583
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.491799
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.495044
19,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.496640
20,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.497127
21,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.503293
22,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.504567
23,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.506174
24,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.511116
25,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.511853
26,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.513071
27,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.513687
28,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.515251
29,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.516911
30,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.516943
31,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.522545
32,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.528029
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.536883
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.537555
35,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.539736
36,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.541118
37,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.543734
38,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.544344
39,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.558314
40,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.561642
41,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.563187
42,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.570331
43,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.571349
44,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.575433
45,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.584511
46,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.591883
47,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.599055
48,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.612234
49,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.634905
50,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.653027
51,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.661196
52,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.669629
53,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.671255
54,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.680029
55,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.682576
56,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.688653
57,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.703326
58,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.706446
59,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.707446
60,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.711675
61,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.719540
62,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.731640
63,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.772013
64,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.793599
65,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.797163
66,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.798026
67,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.802114
68,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.825475
69,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.844970
70,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.850386
71,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.853281
72,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.857206
73,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.862862
74,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.864403
75,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.875540
76,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.883997
77,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.893444
78,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.896909
79,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.896957
80,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.919303
81,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.921715
82,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.954018
83,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.982904
84,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.988101
85,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.990866
86,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.997258
87,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,1.004030
88,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,1.008530
89,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,1.029172
90,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,1.043388
91,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,1.079245
92,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,1.091032
93,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,1.144325
94,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,1.151101
95,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,1.165587
96,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,1.166113
97,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,1.284159
98,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.338042
99,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,1.344523
100,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,1.390336
101,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.394849
102,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,1.424004
103,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,1.426380
104,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.451908
105,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.453339
106,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,1.469501
107,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.510888
108,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,1.530308
109,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.530371
110,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,1.544476
111,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.550958
112,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,1.555928
113,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,1.566457
114,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,1.595030
115,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.603825
116,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.618368
117,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.646886
118,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.673843
119,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.794887
120,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.805672
121,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.848436
122,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,1.869724
123,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,2.062053
124,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,2.212631
125,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,2.232569
126,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,2.617505
127,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,2.735544

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_duckdb_seconds
0,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,3.285292
1,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,3.594456
2,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,4.237417
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,4.595454
4,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,4.715118
5,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,4.746880
6,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,4.874635
7,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,5.140088
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,6.219584
9,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,8.127482
10,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,8.367620
11,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,8.425919
12,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,8.651267
13,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,8.814859
14,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,9.107234
15,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,9.114352
16,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,9.330056
17,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,9.515945
18,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,9.528923
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,9.572599
20,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,9.602663
21,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,9.626689
22,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,9.816590
23,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,9.906787
24,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,10.091561
25,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,10.099078
26,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,10.123247
27,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,10.282482
28,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,10.311187
29,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,10.421291
30,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,10.433864
31,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,10.574243
32,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,10.624296
33,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,10.669228
34,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,10.729680
35,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,10.849791
36,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,10.860894
37,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,10.866183
38,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,10.972182
39,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,10.989343
40,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,11.082227
41,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,11.087266
42,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,11.124308
43,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,11.249223
44,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,11.251413
45,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,11.385188
46,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,11.385642
47,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,11.430921
48,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,11.699034
49,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,11.788498
50,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,12.164969
51,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,12.372747
52,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,12.757002
53,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,12.812437
54,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,13.439244
55,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,13.504328
56,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,13.602092
57,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,13.681071
58,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,13.723165
59,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,13.766659
60,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,13.824431
61,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,14.045449
62,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,14.232566
63,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,14.325541
64,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,14.327818
65,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,14.392363
66,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,14.769567
67,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,14.798437
68,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,14.920127
69,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,14.973497
70,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,15.014801
71,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,15.041581
72,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,15.141552
73,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,15.266155
74,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,15.402990
75,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,15.683895
76,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,15.756632
77,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,15.984449
78,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,16.000711
79,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,16.624110
80,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,16.771762
81,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,17.002785
82,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,17.248082
83,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,17.261537
84,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,17.445712
85,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,17.489565
86,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,17.644917
87,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,17.805404
88,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,18.121879
89,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,18.288855
90,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,18.515142
91,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,19.050351
92,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,19.118344
93,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,19.524039
94,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,20.342126
95,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,21.596404
96,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,21.775294
97,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,21.924554
98,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,22.506948
99,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,22.578155
100,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,22.634748
101,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,22.790639
102,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,23.239070
103,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,23.916556
104,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,24.085375
105,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,24.754321
106,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,25.211426
107,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,25.560013
108,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,25.567625
109,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,25.815095
110,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,26.185457
111,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,26.225853
112,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,26.324829
113,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,26.952746
114,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,27.339530
115,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,27.425043
116,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,27.764083
117,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,27.868051
118,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,28.009790
119,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,30.442195
120,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,31.624210
121,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,32.850278
122,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,36.837714
123,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,37.671142
124,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,37.993901
125,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,41.291982
126,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,43.052157
127,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,43.799303

Ranking by: complex_join_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.000377
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000384
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.000392
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000400
4,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000409
5,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000413
6,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.000456
7,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000456
8,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000457
9,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.000474
10,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000482
11,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.000499
12,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000505
13,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.000507
14,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000508
15,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000517
16,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.000520
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000522
18,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000524
19,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000532
20,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.000533
21,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000539
22,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.000542
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000556
24,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000562
25,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000571
26,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.000578
27,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.000581
28,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.000584
29,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.000593
30,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.000605
31,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.000610
32,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000614
33,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.000617
34,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000653
35,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000663
36,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.000680
37,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.000680
38,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.000684
39,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000702
40,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000707
41,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.000719
42,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000744
43,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.000754
44,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.000774
45,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000801
46,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000854
47,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.000859
48,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000936
49,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000946
50,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000962
51,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000969
52,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.001120
53,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.001124
54,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.001163
55,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.001174
56,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.001273
57,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.001411
58,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.001441
59,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.001456
60,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.001499
61,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.001595
62,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.001850
63,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.001865

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_pandas_seconds
0,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.311347
1,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.322537
2,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.328552
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.331649
4,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.332970
5,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.333227
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.335873
7,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.339370
8,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.349165
9,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.350374
10,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.351937
11,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.357184
12,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.357856
13,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.358497
14,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.358569
15,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.360182
16,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.360459
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.360709
18,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.386752
19,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.390335
20,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.398909
21,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.403801
22,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.406380
23,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.408165
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.410205
25,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.410970
26,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.414054
27,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.414082
28,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.414989
29,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.415971
30,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.416419
31,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.417122
32,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.417857
33,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.417985
34,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.418780
35,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.419210
36,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.421920
37,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.427478
38,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.442156
39,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.453307
40,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.455722
41,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.461030
42,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.461086
43,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.465839
44,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.467282
45,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.467711
46,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.478672
47,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.487813
48,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.493485
49,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.496890
50,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.496995
51,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.499842
52,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.502207
53,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.503815
54,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.508785
55,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.508836
56,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.508849
57,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.508894
58,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.511875
59,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.512593
60,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.516602
61,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.517817
62,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.518303
63,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.520747
64,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.521243
65,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.525714
66,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.525932
67,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.532064
68,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.535084
69,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.539807
70,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.542584
71,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.544533
72,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.544602
73,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.545202
74,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.552929
75,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.557196
76,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.559618
77,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.561544
78,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.563131
79,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.563665
80,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.566226
81,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.571089
82,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.574874
83,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.575575
84,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.582320
85,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.585583
86,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.590429
87,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.594944
88,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.618460
89,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.627129
90,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.634316
91,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.647076
92,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.653648
93,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.654633
94,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.689184
95,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.693135
96,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.694507
97,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.701162
98,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.709507
99,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.731495
100,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.735251
101,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.748335
102,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.751010
103,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.769225
104,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.778732
105,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.832497
106,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.835348
107,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.851114
108,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.880524
109,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.906153
110,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.924786
111,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.937737
112,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.010463
113,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.022419
114,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,1.052686
115,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,1.142008
116,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.205137
117,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.270681
118,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.311182
119,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.345003
120,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,1.383846
121,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.411530
122,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.438896
123,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.468229
124,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,1.524298
125,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.528268
126,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,8.824875
127,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,12.861529

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_polars_seconds
0,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,1.835762
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.836724
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,1.848274
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.848299
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,1.858056
5,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,1.858462
6,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,1.879104
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.899370
8,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.899804
9,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,1.914749
10,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,1.916424
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,1.916629
12,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,1.922158
13,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,1.928277
14,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,1.930856
15,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,1.944967
16,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.951676
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,1.965067
18,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.967512
19,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,1.974526
20,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,1.974907
21,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.019306
22,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,2.031511
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,2.035647
24,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,2.036167
25,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,2.038363
26,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.066553
27,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.070447
28,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,2.080549
29,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,2.081131
30,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,2.099917
31,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.110350
32,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.115645
33,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,2.131042
34,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,2.135119
35,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,2.168447
36,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,2.168542
37,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,2.176932
38,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.177278
39,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,2.179002
40,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,2.201313
41,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,2.205108
42,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.216953
43,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,2.223873
44,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.224582
45,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.225481
46,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.243550
47,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,2.261237
48,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,2.289053
49,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,2.305301
50,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,2.346289
51,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,2.397435
52,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,2.401860
53,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,2.408907
54,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,2.421620
55,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,2.439029
56,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.442789
57,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.447037
58,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,2.450257
59,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,2.467428
60,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,2.476689
61,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.505193
62,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,2.518807
63,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,2.528523
64,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,2.540311
65,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,2.541366
66,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,2.549006
67,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,2.555468
68,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,2.556446
69,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,2.568238
70,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.582026
71,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,2.601538
72,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,2.631081
73,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,2.646084
74,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,2.669038
75,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,2.683827
76,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,2.699992
77,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,2.718911
78,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,2.756714
79,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,2.774699
80,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,2.782137
81,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.793840
82,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,2.826220
83,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.842163
84,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,2.995052
85,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,3.202793
86,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,3.217056
87,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,3.243892
88,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,3.291802
89,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,3.539412
90,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,3.595803
91,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.607012
92,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.646706
93,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.677016
94,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.686936
95,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,3.778609
96,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,3.794873
97,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,3.878324
98,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,3.897610
99,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,3.960917
100,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.260854
101,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,4.261347
102,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,4.268188
103,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,4.303385
104,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,4.304416
105,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.347602
106,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,4.352973
107,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.393107
108,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.532263
109,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,4.544037
110,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,4.750237
111,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,4.836412
112,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.928691
113,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.979773
114,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,5.020040
115,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,5.045245
116,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,5.068176
117,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,5.156621
118,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,6.247831
119,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,6.251081
120,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,6.260561
121,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,6.267411
122,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,6.761818
123,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,7.017137
124,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,7.324557
125,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,8.000622
126,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,8.178485
127,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,8.300135

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.098952
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.104968
2,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.110413
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.111596
4,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.113430
5,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.113817
6,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.120747
7,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.122152
8,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.123296
9,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.125199
10,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.126457
11,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.127927
12,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.137403
13,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.140360
14,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.140363
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.140741
16,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.141526
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.142895
18,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.147814
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.147826
20,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.148341
21,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.150845
22,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.151960
23,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.152020
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.152542
25,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.152933
26,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.154963
27,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.156028
28,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.156701
29,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.160707
30,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.161141
31,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.162418
32,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.165653
33,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.169913
34,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.170429
35,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.170882
36,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.175055
37,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.175164
38,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.175907
39,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.179042
40,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.179130
41,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.181075
42,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.185639
43,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.185991
44,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.186022
45,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.188238
46,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.189737
47,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.189987
48,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.191223
49,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,15.73,0.191417
50,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,Windows,23.69,0.192199
51,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.193187
52,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.195156
53,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.195624
54,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.196289
55,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.199264
56,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Windows,63.73,0.204456
57,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.205527
58,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.207283
59,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.210747
60,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,63.31,0.211920
61,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.213198
62,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.214164
63,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.216630
64,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Windows,63.70,0.218942
65,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.225275
66,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.228301
67,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.230046
68,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.231366
69,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.231962
70,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.232153
71,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.234352
72,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.235709
73,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.238715
74,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.244460
75,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.262852
76,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.263333
77,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.67,0.264716
78,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.268142
79,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.271172
80,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.277293
81,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,Windows,63.67,0.284303
82,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.294979
83,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.313320
84,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,Windows,15.31,0.327826
85,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.362893
86,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.374270
87,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.377764
88,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.381150
89,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.386797
90,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.395654
91,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.396655
92,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.400789
93,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.408385
94,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.451360
95,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.501223
96,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.561461
97,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.579472
98,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.592204
99,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.604427
100,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.639191
101,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.674492
102,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.679273
103,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.709106
104,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,0.726991
105,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.741153
106,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.757588
107,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.809643
108,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.829284
109,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.844055
110,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.850289
111,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.899609
112,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.986644
113,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.987728
114,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.991282
115,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,Windows,19.78,1.011922
116,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.043566
117,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.050404
118,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.063147
119,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.145382
120,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.178603
121,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.187024
122,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.253193
123,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.270166
124,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.321530
125,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.425144
126,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,1.461500
127,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,1.522405

Ranking by: timeseries_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.258856
1,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.261453
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Linux,30.78,0.265580
3,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.273113
4,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,Linux,62.49,0.275606
5,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.301512
6,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.302325
7,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.306496
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.312555
9,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.312878
10,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.315209
11,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Linux,62.50,0.321205
12,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.334185
13,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.06,0.336483
14,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.338578
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.343629
16,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.345705
17,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.362512
18,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.362805
19,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,WSL2,31.21,0.363199
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.367393
21,parquet,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.377237
22,csv,Optiplex-i5-13,13th Gen Intel(R) Core(TM) i5-13500,WSL2,31.19,0.379336
23,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.381611
24,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,Linux,15.34,0.387547
25,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.395374
26,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.416866
27,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.418874
28,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.421252
29,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.421610
30,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.424503
31,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.425058
32,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.425627
33,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,WSL2,31.18,0.431295
34,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Linux,31.02,0.433576
35,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.448926
36,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.462007
37,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.464249
38,parquet,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.464570
39,csv,LAPTOP-HOLV2OE3,AMD Ryzen 7 260 w/ Radeon 780M Graphics,WSL2,31.00,0.481442
40,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.483188
41,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.501116
42,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.510475
43,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.529562
44,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.537955
45,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.542455
46,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.45,0.559417
47,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.564873
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.577054
49,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.583606
50,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.585731
51,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.592294
52,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.595607
53,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.622113
54,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.651473
55,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.667169
56,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.682481
57,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.745909
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.777140
59,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.936820
60,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.942361
61,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.983110
62,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.986897
63,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,1.421789

In [29]:
# Filter Group Pandas
fg_p = b_df[["hostname", "cpu_brand","dataset_size", "dataset_format", "filter_group_pandas_seconds"]]
fg_p = fg_p.groupby(by=["hostname", "cpu_brand","dataset_size", "dataset_format"]).min().reset_index()
fg_p = fg_p.rename(columns={"filter_group_pandas_seconds": "min_time_seconds"})
fg_p = fg_p.sort_values(by=["dataset_size","min_time_seconds", "hostname",  "dataset_format"])
fg_p

,hostname,cpu_brand,dataset_size,dataset_format,min_time_seconds
42,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,csv,0.176201
43,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,parquet,0.188335
20,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,0.189167
21,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,parquet,0.189469
45,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,10000000,parquet,0.204102
...,...,...,...,...,...
13,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,10000000,parquet,0.583145
16,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,csv,0.731955
17,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,parquet,0.962332
47,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,parquet,5.358341
46,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,10.411298

In [30]:
# Calculate the average operation time per row for each library
library_suffixes = ['pandas', 'polars', 'duckdb', 'fireducks']  # Add 'fireducks' if/when data is available

for lib in library_suffixes:
    lib_cols = [col for col in b_df.columns if col.endswith(f'_{lib}_seconds')]
    b_df[f'{lib}_avg_time'] = b_df[lib_cols].mean(axis=1)

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)+ ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each library
host_lib_avg = b_df.groupby('host_cpu')[[f'{lib}_avg_time' for lib in library_suffixes]].mean().reset_index()

# Sort each library's ranking and display
with pd.option_context('display.max_colwidth', None):
    for lib in library_suffixes:
        print(f"Ranking by average {lib} time (ascending):")
        display(host_lib_avg[['host_cpu', f'{lib}_avg_time']].sort_values(f'{lib}_avg_time'))
        print("\n")
# Optionally, display the full table
host_lib_avg

Ranking by average pandas time (ascending):

,host_cpu,pandas_avg_time
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.728984
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.785434
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.787330
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.790206
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.828231
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.831400
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.853110
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.859686
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.872365
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.883562
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.906213
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.939625
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.961443
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,1.023193
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.024209
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,1.031235
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,1.076431
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.083468
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.089557
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.098229
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.119797
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.127908
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.172261
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,1.174671
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,1.237555
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.239831
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.292812
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.340711
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,1.461463
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.491011
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.524103
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.575672
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.706588
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.710795
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,1.732686
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.787122
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,1.813134
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.932938
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,1.978228
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.985968
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,2.045975
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,2.081345
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.144046
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.251039
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,2.404644
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,2.424514
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,2.492094
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.506687
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.578181
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.735169
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,2.740769
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.968245
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,3.109042
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,3.110269
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,3.131222
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,3.681693
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,3.991704
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,5.444306
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,7.885764
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,15.408611

Ranking by average polars time (ascending):

,host_cpu,polars_avg_time
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.626101
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.671769
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.680239
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.719946
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.742445
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.770126
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.772193
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.783669
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.784100
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.792830
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.799042
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.809536
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.812354
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.835478
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.846254
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.869688
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.876530
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.880083
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.880961
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.883038
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.901357
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.904037
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.906222
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.908087
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.910013
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.948109
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.950398
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,1.033573
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,1.063275
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.069344
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.069611
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,1.089643
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.107845
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.160133
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.184756
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.205978
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.236139
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.291333
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.310720
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.445962
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.505774
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.512683
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,1.578317
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.694340
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.736730
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.760348
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,1.880185
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.889734
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.914736
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.981489
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.013492
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.132537
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.245336
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,2.273989
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.419061
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.429050
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.576411
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.154671
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,3.323331
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,3.513165

Ranking by average duckdb time (ascending):

,host_cpu,duckdb_avg_time
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.333418
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,2.363975
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,2.427523
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,2.555037
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,2.704064
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,2.746406
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,2.823045
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.991300
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,3.000192
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,3.040607
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,3.051764
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,3.059756
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,3.155746
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.158985
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,3.167542
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,3.179870
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.188277
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,3.258649
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,3.299193
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,3.355343
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,3.488175
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,3.711097
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,3.871603
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,3.873748
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,3.992685
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,4.006463
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,4.055661
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,4.088932
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,4.129771
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,4.215270
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,4.290595
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,4.330357
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,4.469477
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,4.599465
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,4.709456
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,4.885168
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,5.087844
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,5.198686
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,5.212134
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,5.468166
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,5.643569
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,6.429801
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,6.473828
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,6.655530
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,6.951640
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.171884
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,7.451571
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,7.832607
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.991622
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,8.051619
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,8.588737
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,9.097915
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.127482
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.242403
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,9.858046
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.192535
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,11.993303
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,12.402753
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,13.486665
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,16.960324

Ranking by average fireducks time (ascending):

,host_cpu,fireducks_avg_time
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.156754
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.158445
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.167420
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.175636
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.199306
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.202127
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.239988
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.240043
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.271662
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.313481
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.324229
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.359409
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.370742
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.378425
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.383598
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.396031
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.403118
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.408981
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.412192
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.493129
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.493435
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.515272
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.520348
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.528912
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.612096
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.627516
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.695349
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.701282
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.780069
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.794866
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,1.062613
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,NaN
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,NaN
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,NaN
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,NaN
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,NaN
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,NaN
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,NaN
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,NaN
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,NaN
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,NaN
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,NaN
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,NaN
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,NaN
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,NaN
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,NaN
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,NaN
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,NaN
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,NaN
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,NaN
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,NaN
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,NaN
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,NaN
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,NaN
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,NaN
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,NaN
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,NaN
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,NaN
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,NaN
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,NaN

,host_cpu,pandas_avg_time,polars_avg_time,duckdb_avg_time,fireducks_avg_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.939625,1.069611,4.330357,0.239988
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,1.932938,1.205978,4.055661,NaN
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,1.491011,2.576411,11.192535,0.794866
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.785434,0.784100,3.000192,0.167420
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,3.110269,0.901357,2.991300,NaN
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,1.978228,1.880185,7.832607,1.062613
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,3.991704,2.429050,9.097915,NaN
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,1.172261,2.013492,9.127482,0.378425
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,1.089557,1.981489,9.242403,0.370742
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,3.109042,3.513165,12.402753,NaN
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,2.045975,3.154671,13.486665,0.695349
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,2.735169,2.132537,8.051619,NaN
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,1.119797,1.736730,7.171884,0.396031
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,2.968245,2.419061,16.960324,NaN
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,3.681693,3.323331,11.993303,NaN
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,1.083468,1.512683,6.655530,0.313481
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,2.578181,1.889734,7.451571,NaN
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.831400,0.626101,2.363975,0.408981
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.906213,0.792830,4.006463,0.199306
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,2.424514,0.883038,3.873748,NaN
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.883562,0.880961,3.992685,0.202127
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,1.710795,0.772193,3.355343,NaN
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU ...,3.131222,2.273989,9.858046,NaN
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.728984,0.742445,3.167542,0.158445
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,5.444306,0.904037,2.333418,NaN
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 78...,1.174671,0.910013,4.885168,0.612096
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 78...,2.081345,1.063275,4.215270,NaN
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,0.787330,0.906222,5.643569,0.240043
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,1.031235,0.719946,3.040607,0.515272
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,1.461463,0.835478,3.488175,NaN
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.872365,1.184756,6.473828,0.359409
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,1.706588,0.783669,2.823045,NaN
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,1.023193,0.809536,2.746406,0.493435
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.828231,0.869688,3.155746,0.156754
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,7.885764,1.069344,3.158985,NaN
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-1...,1.732686,1.033573,4.290595,NaN
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,0.859686,0.680239,2.427523,0.412192
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,1.076431,0.770126,3.258649,0.528912
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,1.813134,0.812354,3.059756,NaN
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.853110,0.876530,3.711097,0.175636
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,2.492094,0.799042,2.704064,NaN
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.961443,0.846254,3.299193,0.493129
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,1.575672,0.671769,2.555037,NaN
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.790206,0.908087,4.599465,0.324229
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,1.524103,0.948109,3.051764,NaN
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,15.408611,1.760348,3.188277,NaN
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,1.787122,1.160133,4.469477,NaN
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,2.144046,1.578317,6.429801,NaN
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,1.292812,1.914736,7.991622,0.403118
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,2.506687,2.245336,6.951640,NaN
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,1.127908,1.310720,5.198686,0.271662
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,1.985968,1.505774,5.212134,NaN
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,1.340711,1.694340,8.588737,0.780069
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,2.740769,1.445962,5.468166,NaN
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11...,1.237555,0.950398,3.871603,0.701282
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11...,2.404644,1.089643,4.129771,NaN
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,1.239831,1.107845,4.088932,0.627516
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,1.098229,1.236139,5.087844,0.383598
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,2.251039,1.291333,4.709456,NaN
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) ...,1.024209,0.880083,3.179870,0.520348

In [31]:
# Rank hosts (host + CPU) by the average time across all libraries (pandas, polars, duckdb)
#all_lib_time_cols = [col for col in b_df.columns if col.endswith('_pandas_seconds') or col.endswith('_polars_seconds') or col.endswith('_duckdb_seconds')]

b_df['all_libs_avg_time'] = b_df[time_cols].mean(axis=1)

# Group by host+cpu and get the mean
host_alllibs_avg = b_df.groupby('host_cpu')['all_libs_avg_time'].mean().reset_index()

# Sort to get the fastest overall
host_alllibs_avg_sorted = host_alllibs_avg.sort_values('all_libs_avg_time', ascending=True).reset_index(drop=True)

print("Ranking by average time across all libraries (fastest PC overall):")
with pd.option_context('display.max_colwidth', None):
    display(host_alllibs_avg_sorted)

Ranking by average time across all libraries (fastest PC overall):

,host_cpu,all_libs_avg_time
0,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,1.057614
1,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,1.094910
2,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,1.184287
3,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,1.199354
4,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,1.252605
5,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,1.268143
6,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,1.326765
7,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,1.400005
8,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.401128
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,1.404093
10,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,1.408530
11,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,1.476203
12,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,1.489834
13,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.600826
14,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.644896
15,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.655497
16,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,1.690209
17,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.766031
18,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.771101
19,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.841325
20,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,1.894291
21,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,1.895082
22,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,1.895487
23,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,1.928372
24,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.946110
25,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.951453
26,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.977244
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.998400
28,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,2.222590
29,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.334309
30,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,2.352285
31,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,2.391290
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,2.393767
33,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,2.398192
34,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,2.453297
35,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,2.472244
36,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,2.541353
37,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.606110
38,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.750609
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.893920
40,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.900572
41,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.901292
42,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,3.100964
43,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.171048
44,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.172915
45,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.188409
46,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,3.218299
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,3.384055
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.901221
49,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,3.973162
50,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,4.013706
51,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,4.038031
52,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.306442
53,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,4.845665
54,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,5.087752
55,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,5.172890
56,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,6.332776
57,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,6.341653
58,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.785746
59,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,7.449210

In [32]:
# Calculate the average operation time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  # Fixed: startswith
    b_df[f'{test}_avg_time'] = b_df[test_cols].mean(axis=1)  # Fixed: use test, not lib

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each test
test_avg_cols = [f'{test}_avg_time' for test in test_prefixes]
host_test_avg = b_df.groupby('host_cpu')[test_avg_cols].mean().reset_index()

# Sort each test's ranking and display
# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by average {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_avg[['host_cpu', f'{test}_avg_time']].sort_values(f'{test}_avg_time'))
    print("\n")

# Display the full table
host_test_avg

Ranking by average filter_group time (ascending):

,host_cpu,filter_group_avg_time
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.199375
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.201356
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.209489
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.210105
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.224723
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.232272
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.235091
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.242138
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.245565
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.255735
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.257783
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.260246
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.264002
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.265074
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.269770
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.271585
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.271687
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.277032
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.294546
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.300022
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.305850
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.308836
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.315131
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.322511
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.325251
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.332087
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.350148
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.366369
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.368343
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.382449
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.386476
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.392711
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.417065
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.438459
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.442778
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.463158
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.475525
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.477886
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.480865
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.513317
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.550806
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.597730
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.609594
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.611797
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.693557
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.694441
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.746890
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.749385
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.804758
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.812564
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.821436
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.831888
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.036371
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.072774
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.135896
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.287018
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.342407
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.508202
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.823748

Ranking by average statistics time (ascending):

,host_cpu,statistics_avg_time
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.141072
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.147452
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.149658
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.150956
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.168026
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.172467
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.176746
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.180325
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.182122
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.185441
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.197254
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.203319
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.206597
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.207104
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.207238
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.216774
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.225698
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.225851
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.237845
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.243413
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.256736
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.258530
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.260196
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.261445
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.263565
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.271939
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.275028
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.282742
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.289064
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.329079
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.332374
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.351958
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.368919
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.387384
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395596
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.396304
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.415645
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.430578
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.440528
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.459804
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.534456
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.578091
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.588329
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.624623
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.662899
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.669798
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.689494
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.791946
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.861385
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.869160
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.908945
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.914073
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.931412
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.097377
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.140910
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.163339
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.360749
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.448765
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,2.612892
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,4.208320

Ranking by average complex_join time (ascending):

,host_cpu,complex_join_avg_time
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,3.043056
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,3.093814
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,3.500320
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,3.604662
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,3.682625
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,3.750240
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,3.870069
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,3.961250
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,4.136510
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,4.218467
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,4.271681
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,4.544823
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,4.637280
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,4.897682
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,4.902261
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,5.005017
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,5.125440
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,5.223634
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,5.350801
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,5.362735
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,5.567900
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,5.638994
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,5.858662
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,5.947107
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,5.981846
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,6.091291
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,6.142236
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,6.190292
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,6.302954
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,6.342929
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,7.040301
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,7.085135
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,7.117847
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,7.248586
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,7.471914
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,7.622959
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,7.659173
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,7.703487
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.756925
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,8.375969
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,8.456072
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,8.619418
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,8.817132
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,9.057651
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.301819
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.384543
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,9.791986
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,9.969111
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,10.487334
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,10.943079
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,11.430337
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.718066
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,12.467298
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,13.052801
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,14.181277
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,14.193325
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,14.483172
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,17.847316
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,18.834236
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,24.791240

Ranking by average timeseries time (ascending):

,host_cpu,timeseries_avg_time
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.768042
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.781308
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.826957
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.888004
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.909459
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.909704
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.920432
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.931719
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.937399
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.974662
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.980473
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,1.019426
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,1.048131
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.067212
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.071617
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.080760
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,1.119582
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.125433
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,1.129725
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.135645
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,1.208271
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.224979
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.235237
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.249969
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,1.254550
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.315969
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.340433
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,1.360454
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,1.376781
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.444806
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.451081
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.582553
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,1.592549
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,1.625718
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.645263
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,1.651231
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.665469
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,1.701790
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.732938
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.744553
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.866644
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.883217
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.935096
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.027155
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.108246
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.142782
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,2.376920
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.496969
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.646161
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.748607
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,3.031831
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.051035
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.275654
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.327298
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.574959
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,3.880878
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.310571
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,4.326716
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,4.816141
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.058113

,host_cpu,filter_group_avg_time,statistics_avg_time,complex_join_avg_time,timeseries_avg_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.277032,0.216774,5.005017,1.080760
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.392711,0.368919,7.248586,1.582553
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.821436,0.869160,11.718066,2.646161
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.210105,0.141072,3.604662,0.781308
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.693557,0.689494,6.302954,1.651231
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,0.694441,0.624623,9.057651,2.376920
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,1.036371,1.163339,14.181277,4.310571
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,0.611797,0.669798,9.301819,2.108246
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.609594,0.662899,9.384543,2.027155
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,1.342407,1.360749,17.847316,4.816141
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.831888,0.791946,14.483172,3.275654
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.812564,0.914073,12.467298,3.031831
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.463158,0.459804,7.756925,1.744553
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.746890,0.931412,24.791240,3.327298
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,1.072774,1.097377,18.834236,4.326716
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.438459,0.396304,7.085135,1.645263
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.804758,0.908945,11.430337,2.748607
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.209489,0.150956,3.043056,0.826957
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.260246,0.168026,4.544823,0.931719
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.315131,0.260196,7.622959,1.376781
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.232272,0.180325,4.637280,0.909459
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.264002,0.258530,6.190292,1.071617
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU ...,1.135896,1.140910,14.193325,3.880878
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090,0.149658,3.682625,0.768042
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,1.287018,1.448765,6.342929,2.496969
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 78...,0.350148,0.243413,5.858662,1.129725
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 78...,0.386476,0.329079,7.471914,1.625718
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,0.201356,0.185441,6.142236,1.048131
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,0.265074,0.197254,3.870069,0.974662
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,0.294546,0.263565,5.947107,1.208271
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.368343,0.256736,7.040301,1.224979
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.257783,0.225851,5.350801,1.249969
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.245565,0.207104,3.500320,1.119582
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.224723,0.147452,3.750240,0.888004
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,1.508202,2.612892,8.456072,3.574959
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-1...,0.366369,0.332374,7.117847,1.592549
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,0.199375,0.176746,3.093814,0.909704
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,0.271585,0.206597,4.136510,1.019426
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,0.305850,0.275028,5.638994,1.360454
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.242138,0.182122,4.271681,0.920432
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.597730,0.588329,5.362735,1.444806
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.271687,0.172467,4.218467,0.937399
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.235091,0.203319,4.897682,1.067212
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.308836,0.207238,5.125440,0.980473
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.255735,0.225698,5.567900,1.315969
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,3.823748,4.208320,13.052801,6.058113
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.382449,0.351958,7.703487,1.451081
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.475525,0.430578,10.487334,2.142782
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.513317,0.534456,8.619418,1.935096
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.749385,0.861385,10.943079,3.051035
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.325251,0.261445,5.981846,1.340433
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.480865,0.440528,8.817132,1.866644
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.550806,0.395596,9.791986,1.665469
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.442778,0.578091,9.969111,1.883217
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11...,0.332087,0.271939,4.902261,1.254550
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11...,0.417065,0.387384,7.659173,1.701790
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.322511,0.282742,5.223634,1.235237
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.300022,0.289064,6.091291,1.125433
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.477886,0.415645,8.375969,1.732938
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) ...,0.269770,0.237845,3.961250,1.135645

In [33]:
# Calculate the minumum time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  
    b_df[f'{test}_min_time'] = b_df[test_cols].min(axis=1)  

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the min per host+cpu for each test
test_min_cols = [f'{test}_min_time' for test in test_prefixes]
host_test_min = b_df.groupby('host_cpu')[test_min_cols].min().reset_index()

# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by minimum time {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_min[['host_cpu', f'{test}_min_time']].sort_values(f'{test}_min_time'))
    print("\n")

# Display the full table
host_test_min

Ranking by minimum time filter_group time (ascending):

,host_cpu,filter_group_min_time
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.001347
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.001393
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.001396
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.001484
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.001589
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001595
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.001598
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001606
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.001644
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.001654
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.001698
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.001743
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.001753
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.001840
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.001853
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.001858
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.001940
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.001991
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.002106
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002165
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002401
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002427
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002445
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.002453
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002678
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002809
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.003122
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003213
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003474
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.031890
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.031958
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.032062
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.034698
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.035718
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.036903
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.039799
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.040865
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.041897
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.042423
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.046270
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.047376
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.048940
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.056555
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058527
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.073407
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.080767
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.113281
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.128099
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.133032
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.141584
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.173585
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558

Ranking by minimum time statistics time (ascending):

,host_cpu,statistics_min_time
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000125
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000140
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000145
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.000176
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000182
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000187
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.000188
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000191
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000193
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000195
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000197
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000204
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000213
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.000218
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.000221
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.000222
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000227
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.000235
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.000258
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000271
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000283
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000289
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000291
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000338
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000347
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000381
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000420
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000490
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000549
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000564
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.048504
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.058021
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.059756
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.061105
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.068152
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.068492
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.075092
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.081498
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.084394
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.085934
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.090133
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.090168
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.093565
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.099953
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.103255
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.109509
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.164641
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.167851
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.304877
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.328502
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.344468
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.352225
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.355642
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830

Ranking by minimum time complex_join time (ascending):

,host_cpu,complex_join_min_time
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000377
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000384
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000400
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.000456
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000457
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.000499
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000505
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000507
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000508
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000517
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000520
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000524
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000562
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.000578
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.000581
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.000593
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.000610
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000614
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000653
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000680
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.000684
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000744
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000854
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000859
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000936
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000962
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001124
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001273
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001411
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001499
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.450646
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.459607
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.460579
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.470777
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.476298
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.483583
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.496640
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.504567
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.506174
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.511853
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.544344
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.797163
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.802114
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.850386
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.893444
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.029172
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.079245
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.338042
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.390336
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.451908
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.510888
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.544476
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.646886
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631

Ranking by minimum time timeseries time (ascending):

,host_cpu,timeseries_min_time
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.098952
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.104968
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.110413
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.111596
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.113430
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.137403
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.140360
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.140363
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.140741
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.141526
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.147814
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.148341
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.150845
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.151960
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.152020
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.152933
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.161141
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.170429
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.175164
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.175907
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.179042
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.185991
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.186022
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.188238
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.189737
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.191223
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.195624
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.205527
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.210747
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.213198
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.214164
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.216630
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.230046
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.235709
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.238715
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.263333
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.268142
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.362893
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.374270
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.377764
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395654
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.464249
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.501116
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.503815
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.544602
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.557196
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.574874
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.592204
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.726991
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.741153
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.851114
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.986644
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.063147
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530

,host_cpu,filter_group_min_time,statistics_min_time,complex_join_min_time,timeseries_min_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.001940,0.000291,0.000653,0.210747
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.056555,0.099953,0.797163,0.263333
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.003029,0.000484,0.001163,0.667169
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.001589,0.000195,0.000524,0.147814
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.034815,0.062178,0.496640,0.140741
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,0.003213,0.000564,0.001411,0.557196
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,0.141584,0.352225,1.646886,1.063147
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,0.002445,0.000347,0.000962,0.574874
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.002427,0.000338,0.000936,0.501116
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.160650,0.510830,2.212631,1.321530
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.003474,0.000490,0.001499,0.851114
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.133032,0.355642,1.451908,0.986644
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.002678,0.000420,0.001124,0.503815
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.113281,0.304877,1.338042,0.741153
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,0.238558,0.358730,1.869724,0.844055
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.002453,0.000381,0.000854,0.464249
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.084105,0.211529,1.144325,0.604427
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.001347,0.000125,0.000377,0.104968
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.001484,0.000140,0.000384,0.098952
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.031890,0.048504,0.450646,0.113430
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.001853,0.000204,0.000562,0.268142
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.047376,0.081498,0.511853,0.195624
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU ...,0.173585,0.344468,1.544476,0.726991
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497,0.000213,0.000457,0.152020
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,0.033242,0.059392,0.482777,0.142895
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 78...,0.001644,0.000258,0.000684,0.175907
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 78...,0.040865,0.084394,0.504567,0.189737
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,0.001991,0.000218,0.000593,0.188238
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,0.001598,0.000188,0.000499,0.140363
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,0.035718,0.068492,0.470777,0.161141
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.002106,0.000227,0.000614,0.141526
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.034698,0.058021,0.483583,0.179042
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.001654,0.000221,0.000610,0.175164
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.001698,0.000193,0.000517,0.152933
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.042423,0.068152,0.459607,0.148341
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-1...,0.041897,0.103255,0.893444,0.191223
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,0.001393,0.000176,0.000456,0.150845
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,0.001840,0.000235,0.000578,0.151960
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,0.039799,0.085934,0.544344,0.186022
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.001743,0.000187,0.000508,0.170429
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.032062,0.061105,0.476298,0.147826
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.001753,0.000197,0.000505,0.110413
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.031958,0.059756,0.460579,0.140360
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.001396,0.000145,0.000400,0.111596
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.036903,0.075092,0.506174,0.137403
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,0.073407,0.109509,1.390336,0.205527
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.058527,0.093565,0.850386,0.238715
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.173057,0.140574,0.896909,0.386797
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.002809,0.000549,0.001273,0.544602
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.128099,0.328502,1.510888,0.592204
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.002401,0.000283,0.000859,0.374270
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.080767,0.164641,1.029172,0.362893
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.003122,0.000289,0.000744,0.395654
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.094551,0.167851,0.921715,0.377764
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11...,0.001858,0.000222,0.000581,0.213198
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11...,0.046270,0.090168,0.802114,0.235709
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.001606,0.000191,0.000520,0.185991
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.002165,0.000271,0.000680,0.230046
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.048940,0.090133,1.079245,0.216630
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) ...,0.001595,0.000182,0.000507,0.214164

In [34]:
# Calculate the minimum time per row for each test and annotate which library achieved it (NaN-safe)

test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries']

for test in test_prefixes:
    # Raw timing columns only
    test_cols = [
        col for col in b_df.columns
        if col.startswith(f'{test}_') and col.endswith('_seconds')
    ]
    if not test_cols:
        b_df[f'{test}_min_time'] = float('nan')
        b_df[f'{test}_min_library'] = None
        continue

    # Convert to numeric (coerce 'N/A', blanks, etc. to NaN)
    numeric = b_df[test_cols].apply(pd.to_numeric, errors='coerce')

    # Row-wise min ignoring NaNs
    min_times = numeric.min(axis=1, skipna=True)

    # Identify the column name (library) producing the min ignoring NaNs.
    # pandas idxmin(skipna=True) returns NaN if the entire row is NaN.
    min_cols = numeric.idxmin(axis=1, skipna=True)

    suffix_len = len('_seconds')
    min_libs = []
    for col_name, all_nan in zip(min_cols, numeric.isna().all(axis=1)):
        if all_nan or pd.isna(col_name):
            min_libs.append(None)
        else:
            # column pattern: <test>_<library>_seconds
            lib_name = col_name[len(test) + 1: -suffix_len]
            min_libs.append(lib_name)

    b_df[f'{test}_min_time'] = min_times
    b_df[f'{test}_min_library'] = min_libs

# Unique host identifier
b_df['host_cpu'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['system'].astype(str)
)

# Aggregate: pick min time & corresponding library per host
host_rows = []
for host, g in b_df.groupby('host_cpu'):
    row = {'host_cpu': host}
    for test in test_prefixes:
        time_col = f'{test}_min_time'
        lib_col = f'{test}_min_library'
        if time_col not in g.columns or lib_col not in g.columns:
            row[time_col] = float('nan')
            row[lib_col] = None
            continue
        # valid rows for this test
        g_valid = g.dropna(subset=[time_col])
        if g_valid.empty:
            row[time_col] = float('nan')
            row[lib_col] = None
        else:
            # take the first row with minimal time
            min_idx = g_valid[time_col].idxmin()
            row[time_col] = g_valid.loc[min_idx, time_col]
            row[lib_col] = g_valid.loc[min_idx, lib_col]
    host_rows.append(row)

host_test_min = pd.DataFrame(host_rows)

# Display rankings per test including which library produced the min
for test in test_prefixes:
    time_col = f'{test}_min_time'
    lib_col = f'{test}_min_library'
    if time_col not in host_test_min.columns:
        continue
    print(f"Ranking by minimum {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(
            host_test_min[['host_cpu', time_col, lib_col]]
            .sort_values(time_col, na_position='last')
        )
    print("\n")

# Optional summary: frequency of fastest library per test
summary_rows = []
for test in test_prefixes:
    lib_col = f'{test}_min_library'
    if lib_col in host_test_min.columns:
        counts = host_test_min[lib_col].value_counts(dropna=True)
        for lib, cnt in counts.items():
            summary_rows.append({'test': test, 'library': lib, 'wins': cnt})
fastest_summary = pd.DataFrame(summary_rows).sort_values(['test', 'wins'], ascending=[True, False])
print("Fastest library counts per test:")
display(fastest_summary)

# Full aggregated table (one row per host with min times + libraries per test)
host_test_min

Ranking by minimum filter_group time (ascending):

,host_cpu,filter_group_min_time,filter_group_min_library
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.001347,fireducks
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.001393,fireducks
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.001396,fireducks
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.001484,fireducks
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.001589,fireducks
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001595,fireducks
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.001598,fireducks
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001606,fireducks
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.001644,fireducks
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.001654,fireducks
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.001698,fireducks
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.001743,fireducks
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.001753,fireducks
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.001840,fireducks
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.001853,fireducks
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.001858,fireducks
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.001940,fireducks
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.001991,fireducks
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.002106,fireducks
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002165,fireducks
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002401,fireducks
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002427,fireducks
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002445,fireducks
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.002453,fireducks
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002678,fireducks
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002809,fireducks
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029,fireducks
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.003122,fireducks
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003213,fireducks
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003474,fireducks
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.031890,duckdb
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.031958,duckdb
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.032062,duckdb
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242,duckdb
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.034698,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815,duckdb
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.035718,duckdb
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.036903,duckdb
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.039799,duckdb
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.040865,duckdb
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.041897,duckdb
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.042423,duckdb
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.046270,duckdb
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.047376,duckdb
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.048940,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.056555,duckdb
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058527,duckdb
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.073407,duckdb
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.080767,duckdb
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105,duckdb
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551,duckdb
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.113281,duckdb
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.128099,duckdb
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.133032,duckdb
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.141584,duckdb
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650,duckdb
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057,duckdb
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.173585,duckdb
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558,duckdb

Ranking by minimum statistics time (ascending):

,host_cpu,statistics_min_time,statistics_min_library
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000125,fireducks
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000140,fireducks
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000145,fireducks
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.000176,fireducks
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000182,fireducks
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000187,fireducks
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.000188,fireducks
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000191,fireducks
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000193,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000195,fireducks
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000197,fireducks
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000204,fireducks
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000213,fireducks
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.000218,fireducks
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.000221,fireducks
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.000222,fireducks
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000227,fireducks
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.000235,fireducks
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.000258,fireducks
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000271,fireducks
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000283,fireducks
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000289,fireducks
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000291,fireducks
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000338,fireducks
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000347,fireducks
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000381,fireducks
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000420,fireducks
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484,fireducks
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000490,fireducks
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000549,fireducks
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000564,fireducks
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.048504,duckdb
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.058021,duckdb
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392,duckdb
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.059756,duckdb
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.061105,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178,duckdb
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.068152,duckdb
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.068492,duckdb
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.075092,duckdb
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.081498,polars
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.084394,duckdb
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.085934,duckdb
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.090133,duckdb
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.090168,duckdb
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.093565,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.099953,duckdb
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.103255,duckdb
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.109509,duckdb
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574,polars
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.164641,duckdb
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.167851,duckdb
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529,duckdb
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.304877,duckdb
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.328502,duckdb
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.344468,duckdb
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.352225,duckdb
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.355642,duckdb
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730,duckdb
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830,polars

Ranking by minimum complex_join time (ascending):

,host_cpu,complex_join_min_time,complex_join_min_library
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000377,fireducks
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000384,fireducks
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000400,fireducks
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.000456,fireducks
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000457,fireducks
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.000499,fireducks
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000505,fireducks
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000507,fireducks
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000508,fireducks
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000517,fireducks
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000520,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000524,fireducks
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000562,fireducks
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.000578,fireducks
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.000581,fireducks
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.000593,fireducks
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.000610,fireducks
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000614,fireducks
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000653,fireducks
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000680,fireducks
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.000684,fireducks
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000744,fireducks
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000854,fireducks
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000859,fireducks
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000936,fireducks
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000962,fireducks
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001124,fireducks
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163,fireducks
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001273,fireducks
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001411,fireducks
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001499,fireducks
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.450646,polars
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.459607,polars
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.460579,polars
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.470777,polars
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.476298,polars
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777,polars
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.483583,polars
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.496640,polars
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.504567,polars
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.506174,polars
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.511853,polars
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.544344,polars
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.797163,polars
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.802114,polars
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.850386,polars
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.893444,polars
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909,polars
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715,polars
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.029172,polars
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.079245,polars
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325,polars
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.338042,polars
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.390336,polars
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.451908,polars
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.510888,polars
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.544476,polars
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.646886,polars
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724,polars
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631,polars

Ranking by minimum timeseries time (ascending):

,host_cpu,timeseries_min_time,timeseries_min_library
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.098952,duckdb
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.104968,duckdb
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.110413,duckdb
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.111596,duckdb
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.113430,duckdb
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.137403,duckdb
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.140360,duckdb
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.140363,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.140741,duckdb
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.141526,duckdb
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895,duckdb
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.147814,duckdb
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826,duckdb
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.148341,duckdb
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.150845,duckdb
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.151960,duckdb
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.152020,duckdb
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.152933,duckdb
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.161141,duckdb
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.170429,duckdb
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.175164,duckdb
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.175907,duckdb
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.179042,duckdb
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.185991,duckdb
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.186022,duckdb
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.188238,duckdb
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.189737,duckdb
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.191223,duckdb
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.195624,duckdb
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.205527,duckdb
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.210747,duckdb
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.213198,duckdb
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.214164,duckdb
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.216630,duckdb
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.230046,duckdb
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.235709,duckdb
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.238715,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.263333,duckdb
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.268142,duckdb
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.362893,duckdb
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.374270,duckdb
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.377764,duckdb
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797,duckdb
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395654,duckdb
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.464249,fireducks
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.501116,fireducks
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.503815,pandas
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.544602,pandas
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.557196,pandas
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.574874,pandas
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.592204,duckdb
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427,duckdb
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169,fireducks
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.726991,duckdb
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.741153,duckdb
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055,duckdb
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.851114,pandas
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.986644,duckdb
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.063147,duckdb
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530,duckdb

Fastest library counts per test:

           test    library  wins
5  complex_join  fireducks    31
6  complex_join     polars    29
0  filter_group  fireducks    31
1  filter_group     duckdb    29
2    statistics  fireducks    31
3    statistics     duckdb    26
4    statistics     polars     3
7    timeseries     duckdb    52
8    timeseries     pandas     5
9    timeseries  fireducks     3

,host_cpu,filter_group_min_time,filter_group_min_library,statistics_min_time,statistics_min_library,complex_join_min_time,complex_join_min_library,timeseries_min_time,timeseries_min_library
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.001940,fireducks,0.000291,fireducks,0.000653,fireducks,0.210747,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.056555,duckdb,0.099953,duckdb,0.797163,polars,0.263333,duckdb
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.003029,fireducks,0.000484,fireducks,0.001163,fireducks,0.667169,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.001589,fireducks,0.000195,fireducks,0.000524,fireducks,0.147814,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.034815,duckdb,0.062178,duckdb,0.496640,polars,0.140741,duckdb
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,0.003213,fireducks,0.000564,fireducks,0.001411,fireducks,0.557196,pandas
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,0.141584,duckdb,0.352225,duckdb,1.646886,polars,1.063147,duckdb
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,0.002445,fireducks,0.000347,fireducks,0.000962,fireducks,0.574874,pandas
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.002427,fireducks,0.000338,fireducks,0.000936,fireducks,0.501116,fireducks
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.160650,duckdb,0.510830,polars,2.212631,polars,1.321530,duckdb
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.003474,fireducks,0.000490,fireducks,0.001499,fireducks,0.851114,pandas
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.133032,duckdb,0.355642,duckdb,1.451908,polars,0.986644,duckdb
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.002678,fireducks,0.000420,fireducks,0.001124,fireducks,0.503815,pandas
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.113281,duckdb,0.304877,duckdb,1.338042,polars,0.741153,duckdb
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,0.238558,duckdb,0.358730,duckdb,1.869724,polars,0.844055,duckdb
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.002453,fireducks,0.000381,fireducks,0.000854,fireducks,0.464249,fireducks
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.084105,duckdb,0.211529,duckdb,1.144325,polars,0.604427,duckdb
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.001347,fireducks,0.000125,fireducks,0.000377,fireducks,0.104968,duckdb
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.001484,fireducks,0.000140,fireducks,0.000384,fireducks,0.098952,duckdb
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.031890,duckdb,0.048504,duckdb,0.450646,polars,0.113430,duckdb
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.001853,fireducks,0.000204,fireducks,0.000562,fireducks,0.268142,duckdb
21,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.047376,duckdb,0.081498,polars,0.511853,polars,0.195624,duckdb
22,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU ...,0.173585,duckdb,0.344468,duckdb,1.544476,polars,0.726991,duckdb
23,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497,fireducks,0.000213,fireducks,0.000457,fireducks,0.152020,duckdb
24,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,0.033242,duckdb,0.059392,duckdb,0.482777,polars,0.142895,duckdb
25,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 78...,0.001644,fireducks,0.000258,fireducks,0.000684,fireducks,0.175907,duckdb
26,LAPTOP-HOLV2OE3 | AMD Ryzen 7 260 w/ Radeon 78...,0.040865,duckdb,0.084394,duckdb,0.504567,polars,0.189737,duckdb
27,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,0.001991,fireducks,0.000218,fireducks,0.000593,fireducks,0.188238,duckdb
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,0.001598,fireducks,0.000188,fireducks,0.000499,fireducks,0.140363,duckdb
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX...,0.035718,duckdb,0.068492,duckdb,0.470777,polars,0.161141,duckdb
30,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.002106,fireducks,0.000227,fireducks,0.000614,fireducks,0.141526,duckdb
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.034698,duckdb,0.058021,duckdb,0.483583,polars,0.179042,duckdb
32,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.001654,fireducks,0.000221,fireducks,0.000610,fireducks,0.175164,duckdb
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.001698,fireducks,0.000193,fireducks,0.000517,fireducks,0.152933,duckdb
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.042423,duckdb,0.068152,duckdb,0.459607,polars,0.148341,duckdb
35,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-1...,0.041897,duckdb,0.103255,duckdb,0.893444,polars,0.191223,duckdb
36,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,0.001393,fireducks,0.000176,fireducks,0.000456,fireducks,0.150845,duckdb
37,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,0.001840,fireducks,0.000235,fireducks,0.000578,fireducks,0.151960,duckdb
38,Optiplex-i5-13 | 13th Gen Intel(R) Core(TM) i5...,0.039799,duckdb,0.085934,duckdb,0.544344,polars,0.186022,duckdb
39,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.001743,fireducks,0.000187,fireducks,0.000508,fireducks,0.170429,duckdb
40,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.032062,duckdb,0.061105,duckdb,0.476298,polars,0.147826,duckdb
41,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.001753,fireducks,0.000197,fireducks,0.000505,fireducks,0.110413,duckdb
42,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.031958,duckdb,0.059756,duckdb,0.460579,polars,0.140360,duckdb
43,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.001396,fireducks,0.000145,fireducks,0.000400,fireducks,0.111596,duckdb
44,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.036903,duckdb,0.075092,duckdb,0.506174,polars,0.137403,duckdb
45,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,0.073407,duckdb,0.109509,duckdb,1.390336,polars,0.205527,duckdb
46,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.058527,duckdb,0.093565,duckdb,0.850386,polars,0.238715,duckdb
47,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.173057,duckdb,0.140574,polars,0.896909,polars,0.386797,duckdb
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.002809,fireducks,0.000549,fireducks,0.001273,fireducks,0.544602,pandas
49,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.128099,duckdb,0.328502,duckdb,1.510888,polars,0.592204,duckdb
50,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.002401,fireducks,0.000283,fireducks,0.000859,fireducks,0.374270,duckdb
51,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.080767,duckdb,0.164641,duckdb,1.029172,polars,0.362893,duckdb
52,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.003122,fireducks,0.000289,fireducks,0.000744,fireducks,0.395654,duckdb
53,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.094551,duckdb,0.167851,duckdb,0.921715,polars,0.377764,duckdb
54,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11...,0.001858,fireducks,0.000222,fireducks,0.000581,fireducks,0.213198,duckdb
55,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11...,0.046270,duckdb,0.090168,duckdb,0.802114,polars,0.235709,duckdb
56,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.001606,fireducks,0.000191,fireducks,0.000520,fireducks,0.185991,duckdb
57,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.002165,fireducks,0.000271,fireducks,0.000680,fireducks,0.230046,duckdb
58,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.048940,duckdb,0.090133,duckdb,1.079245,polars,0.216630,duckdb
59,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) ...,0.001595,fireducks,0.000182,fireducks,0.000507,fireducks,0.214164,duckdb