In [1]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [2]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 856 entries, 0 to 855
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       856 non-null    object
 1   hostname                        856 non-null    object
 2   platform                        856 non-null    object
 3   system                          856 non-null    object
 4   release                         856 non-null    object
 5   version                         856 non-null    object
 6   machine                         856 non-null    object
 7   processor                       856 non-null    object
 8   cpu_count_logical               856 non-null    int64
 9   cpu_count_physical              856 non-null    int64
 10  cpu_freq_max                    856 non-null    float64
 11  cpu_freq_current                856 non-null    float64
 12  memory_total_gb                 856 non-null    float64
 13  memory_available_gb             856 non-null    float64
 14  python_version                  856 non-null    object
 15  python_implementation           856 non-null    object
 16  cpu_brand                       856 non-null    object
 17  cpu_arch                        856 non-null    object
 18  dataset_size                    856 non-null    int64
 19  dataset_name                    856 non-null    object
 20  dataset_format                  856 non-null    object
 21  filter_group_pandas_seconds     856 non-null    float64
 22  filter_group_polars_seconds     856 non-null    float64
 23  filter_group_duckdb_seconds     856 non-null    float64
 24  filter_group_fireducks_seconds  438 non-null    float64
 25  statistics_pandas_seconds       856 non-null    float64
 26  statistics_polars_seconds       856 non-null    float64
 27  statistics_duckdb_seconds       856 non-null    float64
 28  statistics_fireducks_seconds    438 non-null    float64
 29  complex_join_pandas_seconds     856 non-null    float64
 30  complex_join_polars_seconds     856 non-null    float64
 31  complex_join_duckdb_seconds     856 non-null    float64
 32  complex_join_fireducks_seconds  438 non-null    float64
 33  timeseries_pandas_seconds       856 non-null    float64
 34  timeseries_polars_seconds       856 non-null    float64
 35  timeseries_duckdb_seconds       856 non-null    float64
 36  timeseries_fireducks_seconds    438 non-null    float64
 37  script_name                     856 non-null    object
dtypes: float64(20), int64(3), object(15)
memory usage: 254.3+ KB

In [3]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(852, 38)

In [4]:
# Filtering by platform
#b_df = windows_data # Focus on Windows data for now

In [5]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(6) # Round to microseconds for better readability
#b_df.head(3)

In [6]:
def get_df_by_test(
    df: pd.DataFrame,
    cols_to_group: list,
    metric: str,
    dedupe_on: list | None = None,
) -> pd.DataFrame:
    """
    Returns the fastest rows for a given metric.

    - If dedupe_on is None: returns one row per cols_to_group (min metric).
    - If dedupe_on is provided: returns one row per dedupe_on group,
      keeping the other columns (e.g., dataset_format) from the winning row.
    """
    # Select only needed columns
    columns_to_select = list(dict.fromkeys(cols_to_group + [metric]))
    df_subset = df[columns_to_select].copy()

    # Coerce metric to numeric and treat <=0 as missing
    df_subset[metric] = pd.to_numeric(df_subset[metric], errors="coerce")
    df_subset.loc[df_subset[metric] <= 0, metric] = pd.NA

    # Keep only rows with valid metric
    df_filtered = df_subset.dropna(subset=[metric])
    if df_filtered.empty:
        return df_filtered

    # If requested, dedupe across formats (or any other dimension) by picking the minimal row
    if dedupe_on:
        idx = df_filtered.groupby(dedupe_on)[metric].idxmin()
        result = df_filtered.loc[idx].copy()
    else:
        # One row per group: minimal metric
        result = df_filtered.groupby(cols_to_group, as_index=False)[metric].min()

    return result.sort_values(by=metric, ascending=True)

In [7]:
# Show rankings segregated by platform (fair comparison)
# Also de-duplicates CSV vs Parquet per host+cpu+mem by keeping only the fastest format.
cols_to_group = ["dataset_format", "hostname", "cpu_brand", "memory_total_gb"]

# Use a stable preferred order, but only keep platforms that exist in the data
preferred_system_order = ["Windows", "WSL2", "Linux"]
systems_present = [s for s in preferred_system_order if s in set(b_df["system"].dropna().unique())]

with pd.option_context("display.max_rows", None):
    for system in systems_present:
        print(f"\n====================\nPlatform: {system}\n====================")
        df_sys = b_df[b_df["system"] == system].copy()

        for col_to_rank in time_cols:
            # Make sure this metric actually has data on this platform
            metric_series = pd.to_numeric(df_sys[col_to_rank], errors="coerce").mask(lambda s: s <= 0)
            if metric_series.notna().sum() == 0:
                # No timings recorded for this library/test on this platform (e.g., FireDucks on Windows)
                continue

            # Use the cleaned numeric series for ranking
            df_sys[col_to_rank] = metric_series

            # Keep only ONE row per host+cpu+mem (but keep the winning dataset_format in the output)
            df_by_test = get_df_by_test(
                df_sys,
                cols_to_group,
                col_to_rank,
                dedupe_on=["hostname", "cpu_brand", "memory_total_gb"],
            ).reset_index(drop=True)

            if df_by_test.empty:
                continue

            print(f"Ranking by: {col_to_rank}")
            display(df_by_test)
            print("\n")

====================
Platform: Windows
====================
Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.194035
1,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.239222
2,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.246244
3,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.249029
4,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.257193
5,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.259799
6,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.264174
7,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.264356
8,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.269150
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.270499
10,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.278784
11,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.278926
12,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.279343
13,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.283666
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.293107
15,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.296013
16,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.304548
17,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.307098
18,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.307101
19,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.360832
20,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.369146
21,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.383956
22,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.393282
23,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.416637
24,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.434067
25,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.453049
26,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.463888
27,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.465891
28,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.493353
29,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.528547
30,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.617913
31,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.663562
32,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.692138
33,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.731955
34,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,5.358341

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_polars_seconds
0,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.071505
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.086000
2,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.094960
3,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.098239
4,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.099523
5,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.113670
6,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.117693
7,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.125330
8,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.128240
9,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.128621
10,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.129033
11,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.131098
12,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.136902
13,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.151938
14,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.152259
15,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.178636
16,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.180809
17,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.185390
18,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.188720
19,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.191101
20,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.192195
21,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.195381
22,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.201567
23,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.214153
24,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.245735
25,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.264340
26,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.268869
27,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.273836
28,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.275828
29,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.286957
30,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.306664
31,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.315507
32,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.331924
33,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,0.340602
34,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.542422

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.031890
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.031958
2,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.032062
3,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.033242
4,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.034698
5,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.034815
6,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.035718
7,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.036018
8,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.036321
9,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.036850
10,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.036903
11,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.039717
12,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.039799
13,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.040865
14,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.041897
15,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.042423
16,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.046270
17,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.047376
18,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.048940
19,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.056555
20,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.058446
21,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.062731
22,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,0.073407
23,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.073608
24,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.080767
25,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.084105
26,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.094551
27,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.113281
28,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.128099
29,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.133032
30,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.141584
31,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.160650
32,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.173057
33,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.173585
34,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.238558

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.167602
1,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.204128
2,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.207913
3,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.208003
4,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.208207
5,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.216158
6,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.219370
7,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.219855
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.222419
9,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.222874
10,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.224219
11,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.224676
12,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.225344
13,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.232309
14,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.233630
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.234241
16,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.238547
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.241225
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.254285
19,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.287178
20,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.287674
21,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.324660
22,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.338446
23,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.339025
24,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.343622
25,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.396269
26,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.432261
27,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.474622
28,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.513319
29,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.580449
30,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.625986
31,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.652209
32,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.673124
33,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.837387
34,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,6.423730

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.061096
1,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.072699
2,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.081498
3,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.085318
4,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.086847
5,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.087507
6,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.087829
7,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.091074
8,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.093786
9,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.095288
10,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.095885
11,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.101770
12,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.108512
13,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.116968
14,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.127979
15,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.134935
16,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.140574
17,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.164934
18,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.168137
19,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.188093
20,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.190012
21,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.191556
22,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.195593
23,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.225771
24,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.228205
25,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.273801
26,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.275371
27,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,0.314736
28,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.339440
29,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.363951
30,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.375136
31,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.383513
32,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.395479
33,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.443669
34,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.510830

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.048504
1,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.058021
2,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.058166
3,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.059392
4,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.059756
5,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.061105
6,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.062178
7,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.068152
8,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.068492
9,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.068837
10,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.075092
11,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.075277
12,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.081412
13,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.081628
14,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.085688
15,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.085934
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.089539
17,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.090133
18,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.090168
19,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.090960
20,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.097058
21,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.099953
22,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.103255
23,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,0.109509
24,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.149406
25,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.164641
26,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.167851
27,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.211529
28,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.304877
29,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.328502
30,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.344468
31,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.352225
32,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.355642
33,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.358730
34,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.536384

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_pandas_seconds
0,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,2.086920
1,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,2.126383
2,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,2.143273
3,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,2.155096
4,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,2.157476
5,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,2.158367
6,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,2.295366
7,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,2.410965
8,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,2.419912
9,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,2.481452
10,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,2.497151
11,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,2.502459
12,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,2.599806
13,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,2.710402
14,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,2.920474
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,3.226381
16,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,3.328890
17,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,3.379374
18,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,3.404619
19,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,3.534181
20,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,3.735163
21,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,3.981980
22,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,4.005578
23,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,4.253906
24,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,4.384282
25,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,4.393550
26,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,4.466859
27,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,4.933718
28,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,5.443431
29,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,5.558602
30,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,5.688737
31,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,5.822155
32,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,6.842711
33,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,8.353409
34,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,8.903364

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_polars_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.450646
1,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.459607
2,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.460579
3,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.466874
4,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.470777
5,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.476298
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.482777
7,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.483583
8,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.496640
9,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.506174
10,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.507359
11,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.511853
12,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.543734
13,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.544344
14,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.634905
15,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.658748
16,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.663780
17,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.736094
18,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.797163
19,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.802114
20,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.862862
21,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.893444
22,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.896909
23,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.921715
24,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,1.029172
25,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,1.079245
26,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,1.144325
27,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,1.338042
28,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,1.390336
29,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,1.451908
30,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,1.510888
31,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,1.544476
32,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,1.646886
33,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,1.869724
34,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,2.212631

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_duckdb_seconds
0,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,3.285292
1,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,3.594456
2,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,4.237417
3,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,4.715118
4,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,4.874635
5,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,9.107234
6,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,9.528923
7,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,9.572599
8,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,9.602663
9,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,9.850003
10,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,9.906787
11,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,9.962906
12,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,10.282482
13,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,10.421291
14,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,10.860894
15,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,11.733306
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,12.022990
17,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,13.602092
18,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,13.723165
19,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,13.766659
20,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,14.232566
21,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,14.581394
22,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,15.141552
23,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,15.756632
24,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,16.771762
25,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,17.261537
26,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,17.445712
27,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,19.524039
28,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,21.596404
29,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,22.578155
30,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,24.085375
31,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,24.754321
32,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,25.567625
33,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,36.837714
34,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,37.671142

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.421920
1,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.453116
2,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.461030
3,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.465839
4,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.467186
5,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.478672
6,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.488623
7,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.493485
8,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.496890
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.499842
10,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.502207
11,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.508849
12,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.517817
13,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.521243
14,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.563131
15,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.571089
16,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.585583
17,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.592101
18,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.598866
19,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.618460
20,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.653648
21,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.654633
22,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.701162
23,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.748335
24,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.751010
25,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.769225
26,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.880524
27,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,1.010463
28,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,1.052686
29,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,1.205137
30,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,1.270681
31,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,1.345003
32,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,1.383846
33,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,1.411530
34,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,8.824875

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_polars_seconds
0,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,1.835762
1,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,1.914749
2,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,1.916424
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,1.916629
4,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,1.965067
5,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,2.066553
6,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,2.110350
7,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,2.130288
8,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,2.135119
9,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,2.168447
10,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,2.176932
11,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,2.216953
12,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,2.222237
13,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,2.225871
14,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,2.389331
15,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,2.397435
16,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,2.442789
17,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,2.445297
18,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,2.476689
19,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,2.540311
20,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,2.601538
21,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,2.683827
22,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,2.718911
23,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,2.774699
24,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,3.539412
25,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,3.677016
26,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,3.778609
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,4.261347
28,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,4.750237
29,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,4.836412
30,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,5.020040
31,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,6.247831
32,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,6.260561
33,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,7.324557
34,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,8.178485

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.113430
1,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.137403
2,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.140360
3,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.140741
4,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.142895
5,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.147645
6,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.147826
7,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.148341
8,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.161141
9,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.179042
10,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.179130
11,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.180224
12,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.184264
13,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.186022
14,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.191223
15,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.195624
16,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.196289
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.205268
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,31.12,0.205527
19,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.216630
20,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.231366
21,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.235709
22,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.263333
23,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.341499
24,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.362893
25,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.377764
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.386797
27,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.592204
28,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.604427
29,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.726991
30,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.741153
31,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.844055
32,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.986644
33,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,1.063147
34,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,1.321530

====================
Platform: WSL2
====================
Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.176201
1,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.204102
2,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.214854
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.252882
4,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.255371
5,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.261258
6,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.267274
7,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.267586
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.269462
9,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.269707
10,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.270451
11,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.276595
12,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.284936
13,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.304917
14,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.307013
15,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.315864
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.316038
17,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.359498
18,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.367142
19,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.379735
20,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.397570
21,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.409041
22,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.415871
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.583145

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_polars_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.105863
1,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.116799
2,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.134381
3,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.140502
4,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.141459
5,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.147632
6,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.154450
7,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.157515
8,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.160666
9,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.161578
10,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.163870
11,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.165737
12,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.168699
13,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.183723
14,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.208076
15,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.226329
16,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.253067
17,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.280271
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.294835
19,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.330961
20,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.345873
21,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.433407
22,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.445868
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.690226

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.032623
1,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.036465
2,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.036922
3,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.038939
4,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.039224
5,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.041783
6,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.042528
7,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.043635
8,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.045527
9,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.047970
10,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.049256
11,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.049567
12,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.049785
13,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.049786
14,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.055306
15,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.057080
16,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.057115
17,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.065795
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.068845
19,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.082814
20,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.095555
21,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.115737
22,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.119977
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.139353

Ranking by: filter_group_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_fireducks_seconds
0,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.001396
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.001484
2,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.001497
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.001519
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.001589
5,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.001598
6,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.001644
7,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.001698
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.001743
9,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.001753
10,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.001840
11,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.001853
12,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.001858
13,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.001937
14,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.001940
15,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.002106
16,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.002165
17,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.002401
18,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.002453
19,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.002678
20,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.002809
21,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.003122
22,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.003213
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.003474

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.148611
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.160063
2,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.168088
3,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.170981
4,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.171951
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.180947
6,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.187811
7,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.191251
8,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.199262
9,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.201684
10,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.204514
11,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.213067
12,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.218891
13,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.226260
14,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.227811
15,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.232281
16,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.251238
17,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.265091
18,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.268450
19,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.291042
20,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.339472
21,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.375648
22,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.377876
23,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.502419

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.057959
1,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.094251
2,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.094802
3,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.097667
4,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.101301
5,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.101981
6,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.104290
7,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.110336
8,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.112284
9,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.117172
10,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.118002
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.134709
12,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.135417
13,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.143918
14,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.154213
15,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.175646
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.201458
17,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.225668
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.228700
19,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.303131
20,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.307027
21,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.330587
22,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.339904
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.373520

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.038060
1,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.045760
2,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.051478
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.051746
4,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.052067
5,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.052469
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.055085
7,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.057525
8,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.057667
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.058118
10,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.066727
11,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.067213
12,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.072261
13,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.073599
14,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.073689
15,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.074120
16,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.079261
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.110594
18,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.118487
19,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.143583
20,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.195986
21,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.252801
22,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.253880
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.382476

Ranking by: statistics_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.000140
1,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.000145
2,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.000148
3,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.000152
4,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.000187
5,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.000188
6,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.000193
7,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.000195
8,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.000197
9,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.000204
10,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.000213
11,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.000222
12,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.000227
13,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.000235
14,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.000258
15,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.000271
16,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.000283
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.000289
18,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.000291
19,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.000381
20,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.000420
21,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.000490
22,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.000549
23,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.000564

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,1.600232
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,1.703667
2,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,1.738139
3,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,1.740872
4,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,1.741788
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,1.812609
6,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,1.826722
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,2.032971
8,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,2.082020
9,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,2.146466
10,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,2.159110
11,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,2.207379
12,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,2.212902
13,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,2.221370
14,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,2.310993
15,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,2.313880
16,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,2.436286
17,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,2.599715
18,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,2.731822
19,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,2.745317
20,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,3.039260
21,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,3.101532
22,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,3.637755
23,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,4.435003

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.440721
1,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.503293
2,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.511116
3,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.513071
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.541118
5,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.575433
6,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.599055
7,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.633127
8,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.669629
9,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.680029
10,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.682576
11,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.688653
12,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.703326
13,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.706446
14,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.731640
15,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.857206
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.982904
17,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.988101
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.997258
19,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,1.008530
20,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,1.344523
21,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,1.424004
22,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,1.555928
23,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,2.232569

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_duckdb_seconds
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,10.099078
1,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,10.311187
2,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,10.433864
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,10.624296
4,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,10.729680
5,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,10.989343
6,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,11.385188
7,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,12.110937
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,12.164969
9,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,12.812437
10,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,13.504328
11,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,14.325541
12,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,14.327818
13,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,15.683895
14,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,17.248082
15,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,17.644917
16,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,18.121879
17,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,18.515142
18,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,21.775294
19,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,23.239070
20,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,25.211426
21,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,26.225853
22,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,27.868051
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,43.052157

Ranking by: complex_join_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.000384
1,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.000400
2,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.000409
3,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.000435
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.000457
5,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.000499
6,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.000505
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.000508
8,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.000517
9,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.000524
10,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.000562
11,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.000578
12,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.000581
13,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.000614
14,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.000653
15,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.000680
16,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.000684
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.000744
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.000854
19,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.000859
20,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.001124
21,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.001273
22,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.001411
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.001499

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_pandas_seconds
0,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.311347
1,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.322537
2,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.328552
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.349165
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.351937
5,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.357184
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.358497
7,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.386752
8,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.392796
9,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.403801
10,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.408165
11,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.410205
12,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.410970
13,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.414082
14,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.418780
15,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.455722
16,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.503815
17,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.508894
18,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.520747
19,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.539807
20,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.544602
21,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.557196
22,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.561544
23,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.851114

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_polars_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,1.836724
1,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,1.879104
2,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,1.899370
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,1.951676
4,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,1.980122
5,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,2.019306
6,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,2.031511
7,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,2.036167
8,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,2.080549
9,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,2.099917
10,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,2.179002
11,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,2.224582
12,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,2.261237
13,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,2.401860
14,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,2.505193
15,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,2.646084
16,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,2.793840
17,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,3.202793
18,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,3.243892
19,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,3.607012
20,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,3.878324
21,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,4.268188
22,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,4.303385
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,6.761818

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.098952
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.110413
2,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.111596
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.113817
4,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.118026
5,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.140363
6,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.141526
7,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.147814
8,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.151960
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.152020
10,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.152933
11,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.170429
12,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.175907
13,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.210747
14,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.213198
15,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.230046
16,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.268142
17,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.374270
18,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.395654
19,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.501223
20,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.579472
21,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.679273
22,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.709106
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,1.461500

Ranking by: timeseries_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_fireducks_seconds
0,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.273113
1,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.301512
2,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.306496
3,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.315209
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.343629
5,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.362805
6,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.367393
7,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.377237
8,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.389086
9,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.416866
10,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.418874
11,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.421252
12,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.424503
13,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.425058
14,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.462007
15,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.464249
16,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.464570
17,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.537955
18,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.542455
19,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.583606
20,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.585731
21,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.651473
22,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.942361
23,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.983110

====================
Platform: Linux
====================
Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_pandas_seconds
0,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.178515
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.189167
2,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.200073
3,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.205537
4,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.206417
5,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.226849
6,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.230181
7,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.239010
8,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.245038
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.249021
10,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.298231
11,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.335269
12,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.374583
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.447669

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_polars_seconds
0,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.085730
1,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.085799
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.086587
3,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.095369
4,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.101135
5,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.121813
6,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.131677
7,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.132462
8,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.139682
9,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.144622
10,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.250173
11,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.431944
12,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.432383
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.614996

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.026820
1,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.030477
2,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.030484
3,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.031740
4,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.032152
5,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.033227
6,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.034329
7,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.034566
8,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.035930
9,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.037508
10,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.038045
11,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.116693
12,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.122297
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.156793

Ranking by: filter_group_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_fireducks_seconds
0,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.001211
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.001347
2,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.001348
3,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.001393
4,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.001407
5,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.001445
6,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.001595
7,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.001606
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.001639
9,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.001654
10,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.001991
11,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.002427
12,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.002445
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.003029

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_pandas_seconds
0,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.158388
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.161277
2,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.174536
3,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.180868
4,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.192739
5,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.210814
6,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.217734
7,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.221441
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.223908
9,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.224155
10,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.225383
11,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.359289
12,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.371494
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.465929

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.054323
1,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.063687
2,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.075363
3,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.088038
4,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.090632
5,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.123976
6,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.133953
7,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.142213
8,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.148805
9,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.171966
10,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.322771
11,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.392614
12,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.418672
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.480064

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.036783
1,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.039666
2,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.045018
3,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.049224
4,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.050027
5,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.053194
6,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.055872
7,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.056630
8,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.059968
9,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.065039
10,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.067360
11,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.329382
12,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.332450
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.447324

Ranking by: statistics_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.000125
1,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.000136
2,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.000142
3,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.000157
4,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.000176
5,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.000176
6,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.000182
7,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.000183
8,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.000191
9,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.000218
10,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.000221
11,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.000338
12,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.000347
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.000484

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_pandas_seconds
0,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,1.407236
1,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,1.425085
2,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,1.498394
3,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,1.565279
4,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,1.693742
5,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,1.750485
6,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,1.756985
7,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,1.858019
8,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,2.068671
9,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,2.205681
10,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,2.309064
11,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,2.501646
12,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,2.570981
13,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,2.862606

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.351187
1,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.392026
2,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.403157
3,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.410883
4,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.433622
5,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.484981
6,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.489516
7,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.539736
8,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.549700
9,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.558314
10,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.875540
11,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,1.530371
12,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,1.603825
13,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,1.794887

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_duckdb_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,8.127482
1,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,8.574022
2,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,8.651267
3,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,9.315462
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,9.330056
5,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,9.712315
6,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,10.254478
7,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,10.901250
8,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,11.082227
9,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,11.788498
10,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,14.920127
11,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,26.185457
12,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,27.339530
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,31.624210

Ranking by: complex_join_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.000377
1,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.000385
2,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.000409
3,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.000410
4,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.000456
5,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.000484
6,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.000507
7,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.000520
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.000549
9,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.000593
10,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.000610
11,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.000936
12,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.000962
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.001163

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_pandas_seconds
0,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.300144
1,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.325803
2,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.331649
3,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.332970
4,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.334269
5,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.364259
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.390335
7,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.395478
8,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.406380
9,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.414989
10,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.496995
11,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.544533
12,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.574874
13,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.693135

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,1.848274
1,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,1.891680
2,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,1.945292
3,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,1.974526
4,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,2.205589
5,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,2.251292
6,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,2.312265
7,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,2.346289
8,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,2.450257
9,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,2.518807
10,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,2.541366
11,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,4.260854
12,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,4.347602
13,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,4.928691

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.104968
1,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.111030
2,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.144755
3,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.146148
4,parquet,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.150845
5,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.167849
6,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.169566
7,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.175164
8,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.185991
9,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.188238
10,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.214164
11,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.899609
12,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,1.043566
13,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,1.187024

Ranking by: timeseries_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.258856
1,csv,DellOpt7010-i5-13,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.261453
2,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.275695
3,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.291786
4,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.303971
5,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.312615
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.312878
7,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.330067
8,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.334185
9,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.362512
10,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.425627
11,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.501116
12,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.592294
13,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.667169

In [8]:
# Average performance per library, split by platform (avoid cross-platform comparisons)
library_suffixes = ['pandas', 'polars', 'duckdb', 'fireducks']  # fireducks may be missing on some platforms

# Stable preferred platform order
preferred_system_order = ["Windows", "WSL2", "Linux"]
systems_present = [s for s in preferred_system_order if s in set(b_df['system'].dropna().unique())]

# Host identifier excluding platform, including memory for fairness
b_df['host_cpu_mem'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['memory_total_gb'].astype(str) + 'GB'
 )

with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    for system in systems_present:
        print(f"\n====================\nPlatform: {system}\n====================")
        df_sys = b_df[b_df['system'] == system].copy()

        # Compute per-row average for each library (NaN/zero-safe)
        computed_avg_cols = []
        for lib in library_suffixes:
            lib_cols = [col for col in df_sys.columns if col.endswith(f'_{lib}_seconds')]
            if not lib_cols:
                continue
            numeric = df_sys[lib_cols].apply(pd.to_numeric, errors='coerce')
            numeric = numeric.mask(numeric <= 0)
            avg_col = f'{lib}_avg_time'
            df_sys[avg_col] = numeric.mean(axis=1, skipna=True)
            # Skip libs with no valid timings for this platform (e.g., FireDucks on Windows)
            if df_sys[avg_col].notna().any():
                computed_avg_cols.append(avg_col)
            else:
                df_sys.drop(columns=[avg_col], inplace=True)

        if not computed_avg_cols:
            print("No valid library timing data available for this platform.")
            continue

        # Aggregate per host+cpu+mem
        host_lib_avg = df_sys.groupby('host_cpu_mem')[computed_avg_cols].mean().reset_index()

        # Display per-library rankings within platform
        for avg_col in computed_avg_cols:
            lib = avg_col.replace('_avg_time', '')
            print(f"Ranking by average {lib} time (ascending):")
            display(host_lib_avg[['host_cpu_mem', avg_col]].sort_values(avg_col, na_position='last').reset_index(drop=True))
            print("\n")

====================
Platform: Windows
====================
Ranking by average pandas time (ascending):

,host_cpu_mem,pandas_avg_time
0,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.73GB,1.302471
1,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 31.21GB,1.404302
2,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 63.17GB,1.421150
3,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 15.17GB,1.502454
4,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 61.68GB,1.575672
5,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 63.73GB,1.620455
6,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.67GB,1.663958
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 31.46GB,1.678807
8,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 15.31GB,1.696537
9,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 31.19GB,1.706588
10,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 31.61GB,1.710795
11,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 23.69GB,1.732686
12,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 63.21GB,1.763706
13,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 63.7GB,1.813134
14,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 63.73GB,1.932938
15,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.72GB,1.985968
16,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 63.31GB,2.079153
17,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.63GB,2.144046
18,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.67GB,2.251039
19,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 63.67GB,2.404644
20,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 31.43GB,2.424514
21,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 63.7GB,2.492094
22,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 63.82GB,2.506687
23,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 63.69GB,2.578181
24,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.81GB,2.735169
25,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 31.28GB,2.740769
26,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.81GB,2.968245
27,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.88GB,3.109042
28,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | 127.71GB,3.110269
29,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | 19.78GB,3.131222
30,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | 15.69GB,3.681693
31,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 63.82GB,3.991704
32,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 63.7GB,5.444306
33,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 63.71GB,7.885764
34,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | 31.12GB,15.408611

Ranking by average polars time (ascending):

,host_cpu_mem,polars_avg_time
0,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 61.68GB,0.671769
1,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 63.73GB,0.709344
2,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 31.61GB,0.772193
3,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 31.19GB,0.783669
4,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 63.7GB,0.799042
5,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 63.7GB,0.812354
6,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 63.17GB,0.825626
7,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 63.31GB,0.843877
8,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 31.46GB,0.851036
9,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 31.43GB,0.883038
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | 127.71GB,0.901357
11,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 63.7GB,0.904037
12,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 63.21GB,0.934359
13,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 31.21GB,0.954984
14,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.73GB,0.961613
15,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 23.69GB,1.033573
16,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 63.71GB,1.069344
17,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.67GB,1.088293
18,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 63.67GB,1.089643
19,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 15.17GB,1.100012
20,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 63.73GB,1.205978
21,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 15.31GB,1.235530
22,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.67GB,1.291333
23,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 31.28GB,1.445962
24,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.72GB,1.505774
25,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.63GB,1.578317
26,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | 31.12GB,1.760348
27,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 63.69GB,1.889734
28,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.81GB,2.132537
29,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 63.82GB,2.245336
30,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | 19.78GB,2.273989
31,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.81GB,2.419061
32,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 63.82GB,2.429050
33,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | 15.69GB,3.323331
34,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.88GB,3.513165

Ranking by average duckdb time (ascending):

,host_cpu_mem,duckdb_avg_time
0,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 63.7GB,2.333418
1,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 61.68GB,2.555037
2,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 63.7GB,2.704064
3,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 63.73GB,2.796437
4,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 31.19GB,2.823045
5,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 63.17GB,2.852833
6,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 63.21GB,2.886513
7,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | 127.71GB,2.991300
8,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 63.31GB,3.051821
9,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 63.7GB,3.059756
10,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 31.21GB,3.134389
11,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 63.71GB,3.158985
12,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | 31.12GB,3.188277
13,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 31.61GB,3.355343
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 31.46GB,3.511506
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 31.43GB,3.873748
16,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 63.73GB,4.055661
17,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 63.67GB,4.129771
18,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.67GB,4.135346
19,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.73GB,4.179913
20,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 23.69GB,4.290595
21,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.67GB,4.709456
22,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 15.17GB,4.897220
23,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 15.31GB,5.148900
24,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.72GB,5.212134
25,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 31.28GB,5.468166
26,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.63GB,6.429801
27,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 63.82GB,6.951640
28,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 63.69GB,7.451571
29,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.81GB,8.051619
30,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 63.82GB,9.097915
31,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | 19.78GB,9.858046
32,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | 15.69GB,11.993303
33,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.88GB,12.402753
34,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.81GB,16.960324

====================
Platform: WSL2
====================
Ranking by average pandas time (ascending):

,host_cpu_mem,pandas_avg_time
0,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 15.22GB,0.689159
1,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 31.19GB,0.728984
2,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,0.785434
3,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 31.2GB,0.828231
4,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 15.35GB,0.839367
5,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 31.19GB,0.853110
6,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 15.21GB,0.872365
7,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 11.44GB,0.883562
8,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 15.34GB,0.906213
9,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 31.21GB,0.939625
10,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 30.2GB,0.961443
11,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 30.95GB,0.992301
12,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 31.21GB,1.031235
13,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 31.19GB,1.076431
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 31.2GB,1.083468
15,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.45GB,1.098229
16,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 15.52GB,1.119797
17,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.49GB,1.127908
18,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 31.0GB,1.174671
19,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 31.18GB,1.237555
20,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.25GB,1.292812
21,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 15.26GB,1.340711
22,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.25GB,1.978228
23,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 15.52GB,2.045975

Ranking by average polars time (ascending):

,host_cpu_mem,polars_avg_time
0,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 31.21GB,0.719946
1,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 31.19GB,0.742445
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 31.19GB,0.770126
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,0.784100
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 15.34GB,0.792830
5,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 15.35GB,0.797536
6,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 30.2GB,0.846254
7,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 30.95GB,0.852107
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 31.2GB,0.869688
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 31.19GB,0.876530
10,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 11.44GB,0.880961
11,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 31.0GB,0.910013
12,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 15.22GB,0.936078
13,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 31.18GB,0.950398
14,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 31.21GB,1.069611
15,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 15.21GB,1.184756
16,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.45GB,1.236139
17,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.49GB,1.310720
18,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 31.2GB,1.512683
19,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 15.26GB,1.694340
20,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 15.52GB,1.736730
21,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.25GB,1.880185
22,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.25GB,1.914736
23,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 15.52GB,3.154671

Ranking by average duckdb time (ascending):

,host_cpu_mem,duckdb_avg_time
0,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,3.000192
1,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 31.21GB,3.040607
2,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 31.2GB,3.155746
3,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 31.19GB,3.167542
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 31.19GB,3.258649
5,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 30.2GB,3.299193
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 15.35GB,3.636347
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 31.19GB,3.711097
8,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 31.18GB,3.871603
9,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 11.44GB,3.992685
10,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 15.34GB,4.006463
11,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 30.95GB,4.279586
12,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 31.21GB,4.330357
13,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 15.22GB,4.759404
14,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 31.0GB,4.885168
15,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.45GB,5.087844
16,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.49GB,5.198686
17,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 15.21GB,6.473828
18,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 31.2GB,6.655530
19,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 15.52GB,7.171884
20,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.25GB,7.832607
21,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.25GB,7.991622
22,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 15.26GB,8.588737
23,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 15.52GB,13.486665

Ranking by average fireducks time (ascending):

,host_cpu_mem,fireducks_avg_time
0,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 31.2GB,0.156754
1,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 31.19GB,0.158445
2,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,0.167420
3,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 31.19GB,0.175636
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 15.34GB,0.199306
5,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 11.44GB,0.202127
6,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 15.22GB,0.203477
7,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 31.21GB,0.239988
8,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.49GB,0.271662
9,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 15.35GB,0.283810
10,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 31.2GB,0.313481
11,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 15.21GB,0.359409
12,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.45GB,0.383598
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 15.52GB,0.396031
14,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.25GB,0.403118
15,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 30.2GB,0.493129
16,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 31.21GB,0.515272
17,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 31.19GB,0.528912
18,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 30.95GB,0.565733
19,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 31.0GB,0.612096
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 15.52GB,0.695349
21,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 31.18GB,0.701282
22,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 15.26GB,0.780069
23,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.25GB,1.062613

====================
Platform: Linux
====================
Ranking by average pandas time (ascending):

,host_cpu_mem,pandas_avg_time
0,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 62.11GB,0.593089
1,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,0.622011
2,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 30.8GB,0.634074
3,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 62.47GB,0.671866
4,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.01GB,0.743535
5,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.34GB,0.787330
6,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 30.78GB,0.831400
7,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 62.49GB,0.859686
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 62.5GB,1.023193
9,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,1.024209
10,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,1.089557
11,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,1.172261
12,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.02GB,1.239831
13,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,1.491011

Ranking by average polars time (ascending):

,host_cpu_mem,polars_avg_time
0,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 30.78GB,0.626101
1,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,0.668237
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 62.49GB,0.680239
3,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 30.8GB,0.712760
4,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 62.11GB,0.797963
5,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 62.5GB,0.809536
6,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 62.47GB,0.821663
7,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.01GB,0.867076
8,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,0.880083
9,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.34GB,0.906222
10,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.02GB,1.107845
11,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,1.981489
12,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,2.013492
13,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,2.576411

Ranking by average duckdb time (ascending):

,host_cpu_mem,duckdb_avg_time
0,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 30.78GB,2.363975
1,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 62.49GB,2.427523
2,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,2.462287
3,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 30.8GB,2.622088
4,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 62.11GB,2.736482
5,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 62.5GB,2.746406
6,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 62.47GB,2.868149
7,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.01GB,3.115216
8,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,3.179870
9,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.02GB,4.088932
10,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.34GB,5.643569
11,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,9.127482
12,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,9.242403
13,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,11.192535

Ranking by average fireducks time (ascending):

,host_cpu_mem,fireducks_avg_time
0,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,0.187208
1,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 30.8GB,0.196529
2,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 62.11GB,0.196769
3,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 62.47GB,0.210179
4,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.01GB,0.230130
5,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.34GB,0.240043
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,0.370742
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,0.378425
8,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 30.78GB,0.408981
9,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 62.49GB,0.412192
10,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 62.5GB,0.493435
11,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,0.520348
12,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.02GB,0.627516
13,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,0.794866

In [15]:
# Rank hosts (host + CPU) by the average time across all libraries (pandas, polars, duckdb)
#all_lib_time_cols = [col for col in b_df.columns if col.endswith('_pandas_seconds') or col.endswith('_polars_seconds') or col.endswith('_duckdb_seconds')]

b_df['all_libs_avg_time'] = b_df[time_cols].mean(axis=1)

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)+ ' | ' + b_df['system'].astype(str)

# Group by host+cpu and get the mean
host_alllibs_avg = b_df.groupby('host_cpu')['all_libs_avg_time'].mean().reset_index()

# Sort to get the fastest overall
host_alllibs_avg_sorted = host_alllibs_avg.sort_values('all_libs_avg_time', ascending=True).reset_index(drop=True)

# Combine hostname and cpu_brand for unique identification
#b_df['host'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)+ ' | ' + b_df['system'].astype(str)

system_type = b_df['system'].drop_duplicates()

#display(system_type)

print("Ranking by average time across all libraries (fastest PC overall):")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    #pass
    display(host_alllibs_avg_sorted)

Ranking by average time across all libraries (fastest PC overall):

,host_cpu,all_libs_avg_time
0,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.984936
1,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,1.041363
2,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,1.057614
3,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,1.081076
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,1.094910
5,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,1.142964
6,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,1.184287
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,1.199354
8,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,1.238989
9,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,1.252605
10,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,1.268143
11,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,1.326765
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,1.389265
13,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,1.400005
14,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.401128
15,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,1.404093
16,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,1.408530
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,1.476203
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,1.489834
19,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.600826
20,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.644896
21,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.655497
22,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,1.690209
23,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.766031
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.771101
25,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.841325
26,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,1.894291
27,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,1.895082
28,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,1.895487
29,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,1.928372
30,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.946110
31,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.951453
32,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.977244
33,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.998400
34,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,2.013783
35,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,2.099882
36,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,2.222590
37,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,2.225630
38,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,2.295866
39,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.334309
40,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,2.352285
41,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,2.391290
42,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,2.393767
43,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,2.398192
44,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,2.541353
45,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.606110
46,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.750609
47,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.893920
48,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.900572
49,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.901292
50,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,3.100964
51,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.171048
52,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.172915
53,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.188409
54,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,3.218299
55,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,3.384055
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.901221
57,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,3.973162
58,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,4.013706
59,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,4.038031
60,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.306442
61,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,4.845665
62,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,5.087752
63,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,5.172890
64,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,6.332776
65,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,6.341653
66,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.785746
67,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,7.449210

In [10]:
# Fastest PC overall (hostname + CPU + memory) split by platform (Windows / WSL2 / Linux)

# Ensure we have a per-row average time metric (NaN/zero-safe).
if 'all_libs_avg_time' not in b_df.columns:
    timings_numeric = b_df[time_cols].apply(pd.to_numeric, errors='coerce')
    timings_nonzero = timings_numeric.mask(timings_numeric <= 0)
    b_df['all_libs_avg_time'] = timings_nonzero.mean(axis=1, skipna=True)

# Host identifier (exclude platform, include memory for fairness when RAM differs)
b_df['host_cpu_mem'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['memory_total_gb'].astype(str) + 'GB'
 )

# Average across runs per (platform, host+cpu+mem)
host_by_platform = (
    b_df.groupby(['system', 'host_cpu_mem'])['all_libs_avg_time']
    .mean()
    .reset_index()
    .sort_values(['system', 'all_libs_avg_time'], ascending=[True, True])
    .reset_index(drop=True)
 )

print("Fastest host+CPU+memory per platform (top = fastest within platform):")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    for system in host_by_platform['system'].dropna().unique():
        print(f"\nPlatform: {system}")
        display(
            host_by_platform[host_by_platform['system'] == system]
            .reset_index(drop=True)
        )

# Optional: just the single fastest per platform
fastest_per_platform = (
    host_by_platform.sort_values(['system', 'all_libs_avg_time'], ascending=[True, True])
    .groupby('system', as_index=False)
    .first()
 )
print("\nSingle fastest host+CPU+memory per platform:")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(fastest_per_platform)

Fastest host+CPU+memory per platform (top = fastest within platform):

Platform: Linux

,system,host_cpu_mem,all_libs_avg_time
0,Linux,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,0.984936
1,Linux,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 30.8GB,1.041363
2,Linux,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 30.78GB,1.057614
3,Linux,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 62.11GB,1.081076
4,Linux,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 62.49GB,1.094910
5,Linux,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 62.47GB,1.142964
6,Linux,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.01GB,1.238989
7,Linux,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 62.5GB,1.268143
8,Linux,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,1.401128
9,Linux,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.02GB,1.766031
10,Linux,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.34GB,1.894291
11,Linux,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,3.171048
12,Linux,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,3.172915
13,Linux,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,4.013706

Platform: WSL2

,system,host_cpu_mem,all_libs_avg_time
0,WSL2,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,1.184287
1,WSL2,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 31.19GB,1.199354
2,WSL2,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 31.2GB,1.252605
3,WSL2,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 31.21GB,1.326765
4,WSL2,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 15.35GB,1.389265
5,WSL2,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 30.2GB,1.400005
6,WSL2,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 31.19GB,1.404093
7,WSL2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 31.19GB,1.408530
8,WSL2,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 15.34GB,1.476203
9,WSL2,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 11.44GB,1.489834
10,WSL2,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 31.21GB,1.644896
11,WSL2,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 15.22GB,1.647029
12,WSL2,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 30.95GB,1.672432
13,WSL2,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 31.18GB,1.690209
14,WSL2,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 31.0GB,1.895487
15,WSL2,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.45GB,1.951453
16,WSL2,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.49GB,1.977244
17,WSL2,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 15.21GB,2.222590
18,WSL2,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 31.2GB,2.391290
19,WSL2,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 15.52GB,2.606110
20,WSL2,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.25GB,2.900572
21,WSL2,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 15.26GB,3.100964
22,WSL2,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.25GB,3.188409
23,WSL2,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 15.52GB,4.845665

Platform: Windows

,system,host_cpu_mem,all_libs_avg_time
0,Windows,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 61.68GB,1.600826
1,Windows,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 63.17GB,1.699869
2,Windows,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 63.73GB,1.708745
3,Windows,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 31.19GB,1.771101
4,Windows,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 31.21GB,1.831225
5,Windows,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 63.21GB,1.861526
6,Windows,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | 63.7GB,1.895082
7,Windows,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 31.61GB,1.946110
8,Windows,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 63.31GB,1.991617
9,Windows,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 63.7GB,1.998400
10,Windows,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 31.46GB,2.013783
11,Windows,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.73GB,2.147999
12,Windows,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.67GB,2.295866
13,Windows,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | 127.71GB,2.334309
14,Windows,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 23.69GB,2.352285
15,Windows,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 31.43GB,2.393767
16,Windows,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 63.73GB,2.398192
17,Windows,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 15.17GB,2.499896
18,Windows,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 63.67GB,2.541353
19,Windows,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 15.31GB,2.693656
20,Windows,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.67GB,2.750609
21,Windows,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 63.7GB,2.893920
22,Windows,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.72GB,2.901292
23,Windows,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 31.28GB,3.218299
24,Windows,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.63GB,3.384055
25,Windows,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 63.82GB,3.901221
26,Windows,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 63.69GB,3.973162
27,Windows,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 63.71GB,4.038031
28,Windows,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.81GB,4.306442
29,Windows,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | 19.78GB,5.087752
30,Windows,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 63.82GB,5.172890
31,Windows,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | 15.69GB,6.332776
32,Windows,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.88GB,6.341653
33,Windows,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | 31.12GB,6.785746
34,Windows,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.81GB,7.449210

Single fastest host+CPU+memory per platform:

,system,host_cpu_mem,all_libs_avg_time
0,Linux,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,0.984936
1,WSL2,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,1.184287
2,Windows,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 61.68GB,1.600826

In [11]:
# Rank platforms (Windows / WSL2 / Linux) by average processing time

# Compute a row-wise average across all timing columns, treating 0s as missing (NaN)
timings_numeric = b_df[time_cols].apply(pd.to_numeric, errors='coerce')
timings_nonzero = timings_numeric.mask(timings_numeric <= 0)
b_df['all_timings_avg_time'] = timings_nonzero.mean(axis=1, skipna=True)

# Group by platform and get the mean
platform_avg = (
    b_df.groupby('system')['all_timings_avg_time']
    .mean()
    .reset_index()
    .sort_values('all_timings_avg_time', ascending=True)
    .reset_index(drop=True)
)
print("Ranking by average processing time across all benchmarks (fastest platform overall):")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(platform_avg)

Ranking by average processing time across all benchmarks (fastest platform overall):

    system  all_timings_avg_time
0     WSL2              1.867838
1    Linux              2.175557
2  Windows              3.038833

In [12]:
# Calculate the average operation time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  # Fixed: startswith
    b_df[f'{test}_avg_time'] = b_df[test_cols].mean(axis=1)  # Fixed: use test, not lib

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each test
test_avg_cols = [f'{test}_avg_time' for test in test_prefixes]
host_test_avg = b_df.groupby('host_cpu')[test_avg_cols].mean().reset_index()

# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by average {test} time (ascending):")
    with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
        display(host_test_avg[['host_cpu', f'{test}_avg_time']].sort_values(f'{test}_avg_time'))
    print("\n")

# Display the full table
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(host_test_avg)

Ranking by average filter_group time (ascending):

,host_cpu,filter_group_avg_time
31,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.153555
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.160398
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.163065
61,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.178403
52,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.186782
29,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.199375
34,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.201356
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.209489
9,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.210105
40,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.224723
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.227449
26,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.232272
48,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.235091
45,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.242138
39,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.245565
50,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.255735
38,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.257783
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.260246
27,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.264002
35,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.265074
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.269770
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.271585
47,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.271687
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.277032
36,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.294546
8,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.296259
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.300022
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.305850
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.308836
25,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.315131
43,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.320177
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.322511
57,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.325251
62,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.332087
33,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.334513
32,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.350148
53,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.358023
42,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.366369
37,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.368343
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.392711
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.417065
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.438459
60,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.442778
18,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.463158
54,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.475525
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.477886
58,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.480865
55,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.513317
59,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.550806
46,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.597730
14,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.609594
13,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.611797
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.693557
11,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.694441
19,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.746890
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.749385
22,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.804758
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.812564
5,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.821436
16,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.831888
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.036371
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.072774
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.135896
30,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.287018
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.342407
41,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.508202
51,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.823748

Ranking by average statistics time (ascending):

,host_cpu,statistics_avg_time
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.135124
9,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.141072
40,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.147452
29,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.149658
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.150017
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.150956
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.160059
31,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.164831
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.168026
47,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.172467
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.176746
26,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.180325
45,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.182122
61,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.185310
34,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.185441
52,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.193030
35,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.197254
48,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.203319
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.206597
39,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.207104
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.207238
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.216774
50,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.225698
38,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.225851
8,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.229776
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.237845
43,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.238860
32,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.243413
37,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.256736
27,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.258530
25,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.260196
57,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.261445
36,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.263565
62,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.271939
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.275028
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.282742
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.289064
33,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.297120
42,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.332374
53,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.335869
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.368919
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.387384
59,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395596
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.396304
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.415645
54,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.430578
58,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.440528
18,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.459804
55,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.534456
60,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.578091
46,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.588329
11,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.624623
14,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.662899
13,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.669798
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.689494
16,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.791946
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.861385
5,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.869160
22,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.908945
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.914073
19,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.931412
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.097377
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.140910
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.163339
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.360749
30,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.448765
41,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,2.612892
51,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,4.208320

Ranking by average complex_join time (ascending):

,host_cpu,complex_join_avg_time
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,2.893357
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,3.043056
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,3.093814
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,3.139065
31,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,3.174487
61,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,3.359158
39,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,3.500320
9,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,3.604662
29,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,3.682625
52,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,3.699045
40,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,3.750240
35,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,3.870069
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,3.961250
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,4.136510
47,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,4.218467
45,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,4.271681
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,4.335345
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,4.544823
26,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,4.637280
48,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,4.897682
62,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,4.902261
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,5.005017
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,5.125440
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,5.223634
38,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,5.350801
46,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,5.362735
50,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,5.567900
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,5.638994
32,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,5.858662
36,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,5.947107
57,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,5.981846
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,6.091291
34,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,6.142236
27,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,6.190292
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,6.302954
30,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,6.342929
8,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,6.396985
43,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,6.425067
33,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,6.829715
37,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,7.040301
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,7.085135
42,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,7.117847
53,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,7.136965
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,7.248586
25,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,7.622959
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,7.659173
18,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.756925
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,8.375969
41,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,8.456072
55,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,8.619418
58,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,8.817132
11,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,9.057651
13,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.301819
14,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.384543
59,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,9.791986
60,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,9.969111
54,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,10.487334
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,10.943079
22,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,11.430337
5,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.718066
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,12.467298
51,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,13.052801
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,14.181277
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,14.193325
16,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,14.483172
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,17.847316
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,18.834236
19,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,24.791240

Ranking by average timeseries time (ascending):

,host_cpu,timeseries_avg_time
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.730865
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.733304
29,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.768042
9,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.781308
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.826957
31,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.831431
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.834206
61,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.848986
52,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.877100
40,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.888004
26,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.909459
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.909704
45,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.920432
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.931719
47,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.937399
35,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.974662
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.980473
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,1.019426
34,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,1.048131
48,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.067212
27,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.071617
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.080760
39,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,1.119582
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.125433
32,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,1.129725
8,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,1.132113
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.135645
36,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,1.208271
37,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.224979
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.235237
38,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.249969
62,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,1.254550
50,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.315969
57,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.340433
53,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.352606
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,1.360454
25,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,1.376781
43,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,1.415426
33,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,1.441172
46,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.444806
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.582553
42,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,1.592549
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.645263
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,1.651231
59,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.665469
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,1.701790
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.732938
18,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.744553
58,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.866644
60,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.883217
55,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.935096
14,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.027155
13,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.108246
54,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.142782
11,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,2.376920
30,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.496969
5,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.646161
22,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.748607
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,3.031831
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.051035
16,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.275654
19,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.327298
41,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.574959
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,3.880878
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.310571
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,4.326716
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,4.816141
51,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.058113

,host_cpu,filter_group_avg_time,statistics_avg_time,complex_join_avg_time,timeseries_avg_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.277032,0.216774,5.005017,1.080760
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.392711,0.368919,7.248586,1.582553
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.199375,0.176746,3.093814,0.909704
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.271585,0.206597,4.136510,1.019426
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.305850,0.275028,5.638994,1.360454
5,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.821436,0.869160,11.718066,2.646161
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.160398,0.135124,3.139065,0.730865
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.227449,0.160059,4.335345,0.834206
8,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.296259,0.229776,6.396985,1.132113
9,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.210105,0.141072,3.604662,0.781308
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.693557,0.689494,6.302954,1.651231
11,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.694441,0.624623,9.057651,2.376920
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.036371,1.163339,14.181277,4.310571
13,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.611797,0.669798,9.301819,2.108246
14,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.609594,0.662899,9.384543,2.027155
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.342407,1.360749,17.847316,4.816141
16,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.831888,0.791946,14.483172,3.275654
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.812564,0.914073,12.467298,3.031831
18,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.463158,0.459804,7.756925,1.744553
19,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.746890,0.931412,24.791240,3.327298
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.072774,1.097377,18.834236,4.326716
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.438459,0.396304,7.085135,1.645263
22,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.804758,0.908945,11.430337,2.748607
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.209489,0.150956,3.043056,0.826957
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.260246,0.168026,4.544823,0.931719
25,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.315131,0.260196,7.622959,1.376781
26,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.232272,0.180325,4.637280,0.909459
27,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.264002,0.258530,6.190292,1.071617
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.135896,1.140910,14.193325,3.880878
29,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090,0.149658,3.682625,0.768042
30,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.287018,1.448765,6.342929,2.496969
31,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.153555,0.164831,3.174487,0.831431
32,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.350148,0.243413,5.858662,1.129725
33,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.334513,0.297120,6.829715,1.441172
34,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.201356,0.185441,6.142236,1.048131
35,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.265074,0.197254,3.870069,0.974662
36,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.294546,0.263565,5.947107,1.208271
37,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.368343,0.256736,7.040301,1.224979
38,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.257783,0.225851,5.350801,1.249969
39,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.245565,0.207104,3.500320,1.119582
40,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.224723,0.147452,3.750240,0.888004
41,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.508202,2.612892,8.456072,3.574959
42,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.366369,0.332374,7.117847,1.592549
43,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.320177,0.238860,6.425067,1.415426
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.163065,0.150017,2.893357,0.733304
45,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.242138,0.182122,4.271681,0.920432
46,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.597730,0.588329,5.362735,1.444806
47,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.271687,0.172467,4.218467,0.937399
48,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.235091,0.203319,4.897682,1.067212
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.308836,0.207238,5.125440,0.980473
50,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.255735,0.225698,5.567900,1.315969
51,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.823748,4.208320,13.052801,6.058113
52,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.186782,0.193030,3.699045,0.877100
53,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.358023,0.335869,7.136965,1.352606
54,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.475525,0.430578,10.487334,2.142782
55,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.513317,0.534456,8.619418,1.935096
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.749385,0.861385,10.943079,3.051035
57,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.325251,0.261445,5.981846,1.340433
58,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.480865,0.440528,8.817132,1.866644
59,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.550806,0.395596,9.791986,1.665469
60,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.442778,0.578091,9.969111,1.883217
61,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.178403,0.185310,3.359158,0.848986
62,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.332087,0.271939,4.902261,1.254550
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.417065,0.387384,7.659173,1.701790
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.322511,0.282742,5.223634,1.235237
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.300022,0.289064,6.091291,1.125433
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.477886,0.415645,8.375969,1.732938
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.269770,0.237845,3.961250,1.135645

In [13]:
# Calculate the minumum time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  
    b_df[f'{test}_min_time'] = b_df[test_cols].min(axis=1)  

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the min per host+cpu for each test
test_min_cols = [f'{test}_min_time' for test in test_prefixes]
host_test_min = b_df.groupby('host_cpu')[test_min_cols].min().reset_index()

# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by minimum time {test} time (ascending):")
    with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
        display(host_test_min[['host_cpu', f'{test}_min_time']].sort_values(f'{test}_min_time'))
    print("\n")

# Display the full table
host_test_min

Ranking by minimum time filter_group time (ascending):

,host_cpu,filter_group_min_time
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.001211
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.001347
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.001348
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.001393
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.001396
61,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.001407
31,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.001445
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.001484
29,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497
9,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.001589
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001595
35,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.001598
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001606
52,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.001639
32,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.001644
39,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.001654
40,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.001698
45,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.001743
47,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.001753
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.001840
26,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.001853
62,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.001858
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.001937
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.001940
34,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.001991
37,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.002106
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002165
57,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002401
14,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002427
13,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002445
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.002453
18,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002678
55,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002809
5,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029
59,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.003122
11,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003213
16,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003474
25,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.031890
48,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.031958
46,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.032062
30,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242
38,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.034698
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815
36,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.035718
8,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.036018
43,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.036321
50,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.036903
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.039799
33,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.040865
42,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.041897
41,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.042423
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.046270
27,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.047376
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.048940
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.056555
53,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058446
51,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.073407
58,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.080767
22,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105
60,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551
19,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.113281
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.128099
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.133032
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.141584
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650
54,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.173585
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558

Ranking by minimum time statistics time (ascending):

,host_cpu,statistics_min_time
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000125
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.000136
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000140
31,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.000142
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000145
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.000152
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.000157
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.000176
61,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.000176
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000182
52,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.000183
45,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000187
35,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.000188
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000191
40,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000193
9,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000195
47,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000197
26,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000204
29,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000213
34,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.000218
39,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.000221
62,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.000222
37,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000227
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.000235
32,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.000258
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000271
57,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000283
59,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000289
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000291
14,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000338
13,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000347
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000381
18,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000420
5,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484
16,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000490
55,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000549
11,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000564
25,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.048504
38,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.058021
8,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.058166
30,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392
48,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.059756
46,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.061105
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178
41,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.068152
36,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.068492
50,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.075092
43,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.075277
33,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.081412
27,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.081498
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.085934
53,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.089539
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.090133
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.090168
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.099953
42,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.103255
51,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.109509
54,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574
58,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.164641
60,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.167851
22,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529
19,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.304877
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.328502
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.344468
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.352225
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.355642
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830

Ranking by minimum time complex_join time (ascending):

,host_cpu,complex_join_min_time
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000377
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000384
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.000385
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000400
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.000409
31,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.000410
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.000435
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.000456
29,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000457
61,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.000484
35,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.000499
47,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000505
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000507
45,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000508
40,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000517
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000520
9,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000524
52,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.000549
26,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000562
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.000578
62,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.000581
34,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.000593
39,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.000610
37,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000614
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000653
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000680
32,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.000684
59,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000744
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000854
57,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000859
14,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000936
13,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000962
18,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001124
5,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163
55,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001273
11,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001411
16,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001499
25,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.450646
41,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.459607
48,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.460579
33,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.466874
36,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.470777
46,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.476298
30,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777
38,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.483583
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.496640
50,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.506174
43,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.507359
27,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.511853
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.544344
8,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.658748
53,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.736094
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.797163
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.802114
42,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.893444
54,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909
60,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715
58,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.029172
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.079245
22,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325
19,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.338042
51,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.390336
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.451908
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.510888
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.544476
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.646886
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631

Ranking by minimum time timeseries time (ascending):

,host_cpu,timeseries_min_time
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.098952
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.104968
47,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.110413
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.111030
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.111596
25,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.113430
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.118026
50,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.137403
48,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.140360
35,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.140363
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.140741
37,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.141526
30,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.144755
31,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.146148
8,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.147645
9,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.147814
46,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826
41,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.148341
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.150845
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.151960
29,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.152020
40,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.152933
36,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.161141
52,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.167849
61,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.169566
45,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.170429
39,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.175164
32,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.175907
38,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.179042
33,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.180224
43,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.184264
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.185991
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.186022
34,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.188238
42,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.191223
27,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.195624
53,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.205268
51,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.205527
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.210747
62,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.213198
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.214164
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.216630
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.230046
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.235709
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.263333
26,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.268142
58,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.362893
57,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.374270
60,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.377764
54,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797
59,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395654
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.464249
14,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.501116
18,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.503815
55,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.544602
11,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.557196
13,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.574874
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.592204
22,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427
5,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.726991
19,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.741153
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055
16,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.851114
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.986644
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.063147
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530

,host_cpu,filter_group_min_time,statistics_min_time,complex_join_min_time,timeseries_min_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.001940,0.000291,0.000653,0.210747
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.056555,0.099953,0.797163,0.263333
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM)...,0.001393,0.000176,0.000456,0.150845
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM)...,0.001840,0.000235,0.000578,0.151960
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM)...,0.039799,0.085934,0.544344,0.186022
...,...,...,...,...,...
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11...,0.046270,0.090168,0.802114,0.235709
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.001606,0.000191,0.000520,0.185991
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.002165,0.000271,0.000680,0.230046
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.048940,0.090133,1.079245,0.216630
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) ...,0.001595,0.000182,0.000507,0.214164

In [14]:
# Calculate the minimum time per row for each test and annotate which library achieved it (NaN-safe)

test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries']

for test in test_prefixes:
    # Raw timing columns only
    test_cols = [
        col for col in b_df.columns
        if col.startswith(f'{test}_') and col.endswith('_seconds')
    ]
    if not test_cols:
        b_df[f'{test}_min_time'] = float('nan')
        b_df[f'{test}_min_library'] = None
        continue

    # Convert to numeric (coerce 'N/A', blanks, etc. to NaN)
    numeric = b_df[test_cols].apply(pd.to_numeric, errors='coerce')

    # Row-wise min ignoring NaNs
    min_times = numeric.min(axis=1, skipna=True)

    # Identify the column name (library) producing the min ignoring NaNs.
    # pandas idxmin(skipna=True) returns NaN if the entire row is NaN.
    min_cols = numeric.idxmin(axis=1, skipna=True)

    suffix_len = len('_seconds')
    min_libs = []
    for col_name, all_nan in zip(min_cols, numeric.isna().all(axis=1)):
        if all_nan or pd.isna(col_name):
            min_libs.append(None)
        else:
            # column pattern: <test>_<library>_seconds
            lib_name = col_name[len(test) + 1: -suffix_len]
            min_libs.append(lib_name)

    b_df[f'{test}_min_time'] = min_times
    b_df[f'{test}_min_library'] = min_libs

# Unique host identifier
b_df['host_cpu'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['system'].astype(str)
)

# Aggregate: pick min time & corresponding library per host
host_rows = []
for host, g in b_df.groupby('host_cpu'):
    row = {'host_cpu': host}
    for test in test_prefixes:
        time_col = f'{test}_min_time'
        lib_col = f'{test}_min_library'
        if time_col not in g.columns or lib_col not in g.columns:
            row[time_col] = float('nan')
            row[lib_col] = None
            continue
        # valid rows for this test
        g_valid = g.dropna(subset=[time_col])
        if g_valid.empty:
            row[time_col] = float('nan')
            row[lib_col] = None
        else:
            # take the first row with minimal time
            min_idx = g_valid[time_col].idxmin()
            row[time_col] = g_valid.loc[min_idx, time_col]
            row[lib_col] = g_valid.loc[min_idx, lib_col]
    host_rows.append(row)

host_test_min = pd.DataFrame(host_rows)

# Display rankings per test including which library produced the min
for test in test_prefixes:
    time_col = f'{test}_min_time'
    lib_col = f'{test}_min_library'
    if time_col not in host_test_min.columns:
        continue
    print(f"Ranking by minimum {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(
            host_test_min[['host_cpu', time_col, lib_col]]
            .sort_values(time_col, na_position='last')
        )
    print("\n")

# Optional summary: frequency of fastest library per test
summary_rows = []
for test in test_prefixes:
    lib_col = f'{test}_min_library'
    if lib_col in host_test_min.columns:
        counts = host_test_min[lib_col].value_counts(dropna=True)
        for lib, cnt in counts.items():
            summary_rows.append({'test': test, 'library': lib, 'wins': cnt})
fastest_summary = pd.DataFrame(summary_rows).sort_values(['test', 'wins'], ascending=[True, False])
print("Fastest library counts per test:")
display(fastest_summary)

# Full aggregated table (one row per host with min times + libraries per test)
host_test_min

Ranking by minimum filter_group time (ascending):

,host_cpu,filter_group_min_time,filter_group_min_library
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.001211,fireducks
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.001347,fireducks
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.001348,fireducks
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.001393,fireducks
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.001396,fireducks
...,...,...,...
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.141584,duckdb
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650,duckdb
54,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057,duckdb
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.173585,duckdb
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558,duckdb

Ranking by minimum statistics time (ascending):

,host_cpu,statistics_min_time,statistics_min_library
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000125,fireducks
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.000136,fireducks
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000140,fireducks
31,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.000142,fireducks
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000145,fireducks
...,...,...,...
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.344468,duckdb
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.352225,duckdb
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.355642,duckdb
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730,duckdb
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830,polars

Ranking by minimum complex_join time (ascending):

,host_cpu,complex_join_min_time,complex_join_min_library
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000377,fireducks
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000384,fireducks
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.000385,fireducks
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000400,fireducks
44,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.000409,fireducks
...,...,...,...
56,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.510888,polars
28,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.544476,polars
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.646886,polars
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724,polars
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631,polars

Ranking by minimum timeseries time (ascending):

,host_cpu,timeseries_min_time,timeseries_min_library
24,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.098952,duckdb
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.104968,duckdb
47,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.110413,duckdb
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.111030,duckdb
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.111596,duckdb
...,...,...,...
20,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055,duckdb
16,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.851114,pandas
17,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.986644,duckdb
12,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.063147,duckdb
15,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530,duckdb

Fastest library counts per test:

           test    library  wins
5  complex_join  fireducks    37
6  complex_join     polars    31
0  filter_group  fireducks    37
1  filter_group     duckdb    31
2    statistics  fireducks    37
3    statistics     duckdb    28
4    statistics     polars     3
7    timeseries     duckdb    60
8    timeseries     pandas     5
9    timeseries  fireducks     3

,host_cpu,filter_group_min_time,filter_group_min_library,statistics_min_time,statistics_min_library,complex_join_min_time,complex_join_min_library,timeseries_min_time,timeseries_min_library
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.001940,fireducks,0.000291,fireducks,0.000653,fireducks,0.210747,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.056555,duckdb,0.099953,duckdb,0.797163,polars,0.263333,duckdb
2,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM)...,0.001393,fireducks,0.000176,fireducks,0.000456,fireducks,0.150845,duckdb
3,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM)...,0.001840,fireducks,0.000235,fireducks,0.000578,fireducks,0.151960,duckdb
4,DellOpt7010-i5-13 | 13th Gen Intel(R) Core(TM)...,0.039799,duckdb,0.085934,duckdb,0.544344,polars,0.186022,duckdb
...,...,...,...,...,...,...,...,...,...
63,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11...,0.046270,duckdb,0.090168,duckdb,0.802114,polars,0.235709,duckdb
64,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.001606,fireducks,0.000191,fireducks,0.000520,fireducks,0.185991,duckdb
65,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.002165,fireducks,0.000271,fireducks,0.000680,fireducks,0.230046,duckdb
66,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7...,0.048940,duckdb,0.090133,duckdb,1.079245,polars,0.216630,duckdb
67,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) ...,0.001595,fireducks,0.000182,fireducks,0.000507,fireducks,0.214164,duckdb