In [1]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [2]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       96 non-null     object
 1   hostname                        96 non-null     object
 2   platform                        96 non-null     object
 3   system                          96 non-null     object
 4   release                         96 non-null     int64
 5   version                         96 non-null     object
 6   machine                         96 non-null     object
 7   processor                       96 non-null     object
 8   cpu_count_logical               96 non-null     int64
 9   cpu_count_physical              96 non-null     int64
 10  cpu_freq_max                    96 non-null     float64
 11  cpu_freq_current                96 non-null     float64
 12  memory_total_gb                 96 non-null     float64
 13  memory_available_gb             96 non-null     float64
 14  python_version                  96 non-null     object
 15  python_implementation           96 non-null     object
 16  cpu_brand                       96 non-null     object
 17  cpu_arch                        96 non-null     object
 18  dataset_size                    96 non-null     int64
 19  dataset_name                    96 non-null     object
 20  dataset_format                  96 non-null     object
 21  filter_group_pandas_seconds     96 non-null     float64
 22  filter_group_polars_seconds     96 non-null     float64
 23  filter_group_duckdb_seconds     96 non-null     float64
 24  filter_group_fireducks_seconds  0 non-null      float64
 25  statistics_pandas_seconds       96 non-null     float64
 26  statistics_polars_seconds       96 non-null     float64
 27  statistics_duckdb_seconds       96 non-null     float64
 28  statistics_fireducks_seconds    0 non-null      float64
 29  complex_join_pandas_seconds     96 non-null     float64
 30  complex_join_polars_seconds     96 non-null     float64
 31  complex_join_duckdb_seconds     96 non-null     float64
 32  complex_join_fireducks_seconds  0 non-null      float64
 33  timeseries_pandas_seconds       96 non-null     float64
 34  timeseries_polars_seconds       96 non-null     float64
 35  timeseries_duckdb_seconds       96 non-null     float64
 36  timeseries_fireducks_seconds    0 non-null      float64
 37  script_name                     96 non-null     object
dtypes: float64(20), int64(4), object(14)
memory usage: 28.6+ KB

In [3]:
# Removing fireduck for now because there is not data(yet)
fireduck_columns = [col for col in b_df.columns if 'fireducks_' in col]
b_df.drop(columns=fireduck_columns, inplace=True)

b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   timestamp                    96 non-null     object
 1   hostname                     96 non-null     object
 2   platform                     96 non-null     object
 3   system                       96 non-null     object
 4   release                      96 non-null     int64
 5   version                      96 non-null     object
 6   machine                      96 non-null     object
 7   processor                    96 non-null     object
 8   cpu_count_logical            96 non-null     int64
 9   cpu_count_physical           96 non-null     int64
 10  cpu_freq_max                 96 non-null     float64
 11  cpu_freq_current             96 non-null     float64
 12  memory_total_gb              96 non-null     float64
 13  memory_available_gb          96 non-null     float64
 14  python_version               96 non-null     object
 15  python_implementation        96 non-null     object
 16  cpu_brand                    96 non-null     object
 17  cpu_arch                     96 non-null     object
 18  dataset_size                 96 non-null     int64
 19  dataset_name                 96 non-null     object
 20  dataset_format               96 non-null     object
 21  filter_group_pandas_seconds  96 non-null     float64
 22  filter_group_polars_seconds  96 non-null     float64
 23  filter_group_duckdb_seconds  96 non-null     float64
 24  statistics_pandas_seconds    96 non-null     float64
 25  statistics_polars_seconds    96 non-null     float64
 26  statistics_duckdb_seconds    96 non-null     float64
 27  complex_join_pandas_seconds  96 non-null     float64
 28  complex_join_polars_seconds  96 non-null     float64
 29  complex_join_duckdb_seconds  96 non-null     float64
 30  timeseries_pandas_seconds    96 non-null     float64
 31  timeseries_polars_seconds    96 non-null     float64
 32  timeseries_duckdb_seconds    96 non-null     float64
 33  script_name                  96 non-null     object
dtypes: float64(16), int64(4), object(14)
memory usage: 25.6+ KB

In [4]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(92, 34)

In [5]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(2)
b_df.head(3)

,timestamp,hostname,platform,system,release,version,machine,processor,cpu_count_logical,cpu_count_physical,...,statistics_pandas_seconds,statistics_polars_seconds,statistics_duckdb_seconds,complex_join_pandas_seconds,complex_join_polars_seconds,complex_join_duckdb_seconds,timeseries_pandas_seconds,timeseries_polars_seconds,timeseries_duckdb_seconds,script_name
0,2025-08-20T22:58:21.887566,TS-P350-01,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"Intel64 Family 6 Model 167 Stepping 1, Genuine...",16,8,...,21.27,1.26,1.03,37.76,2.78,10.72,25.64,3.35,1.01,benchmark.py
1,2025-08-21T15:09:54.202383,WL5022,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"Intel64 Family 6 Model 140 Stepping 1, Genuine...",8,4,...,44.53,4.28,4.18,75.80,6.49,22.18,48.58,8.04,4.26,benchmark.py
2,2025-08-21T18:10:27.497627,MSI,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,17.39,1.08,0.99,34.04,1.77,7.44,21.02,4.07,0.77,benchmark.py

In [8]:
def rank_methods(df, operation_col_prefix):
    time_cols = [col for col in df.columns if col.startswith(operation_col_prefix) and col.endswith('_seconds')]
    rank_df = pd.DataFrame()
    rank_df['hostname'] = df['hostname']
    rank_df['cpu_brand'] = df['cpu_brand'] 
    rank_df['dataset_size'] = df['dataset_size']
    rank_df['dataset_format'] = df['dataset_format']
    
    for col in time_cols:
        rank_col = f"rank_{col}"
        # Only rank non-zero values, assign max rank to zeros
        mask = df[col] > 0
        rank_df[rank_col] = df[col].where(mask).rank(method='min')
        max_rank = rank_df[rank_col].max()
        rank_df[rank_col] = rank_df[rank_col].fillna(max_rank + 1)
    
    return rank_df

In [9]:
filter_group_ranks = rank_methods(b_df, 'filter_group_')
sort_values_cols = [col for col in filter_group_ranks.columns if col.startswith('rank_filter_group_')]
filter_group_ranks[sort_values_cols] = filter_group_ranks[sort_values_cols].astype(int)
filter_group_ranks = filter_group_ranks.sort_values(by=sort_values_cols + ['hostname', 'dataset_format'])
filter_group_ranks

,hostname,cpu_brand,dataset_size,dataset_format,rank_filter_group_pandas_seconds,rank_filter_group_modin_seconds,rank_filter_group_polars_seconds,rank_filter_group_duckdb_seconds
56,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,1,3,5,9
46,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,2,6,15,1
25,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,3,20,17,5
50,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,4,1,2,5
55,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,4,19,7,9
...,...,...,...,...,...,...,...,...
72,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,80,81,78,73
73,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,81,69,58,56
19,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,82,71,75,76
81,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,83,70,60,57
4,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,10000000,csv,84,75,84,83

In [6]:
def get_df_by_test(df: pd.DataFrame, cols_to_group: list, metric: str) -> pd.DataFrame:
    # Properly combine columns - create a new list instead of using append
    columns_to_select = cols_to_group + [metric]
    
    # Select the relevant columns
    df_subset = df[columns_to_select]
    
    # Remove rows where the metric is null/zero (assuming you want valid measurements)
    df_filtered = df_subset[df_subset[metric] > 0]  # or use .notna() if you want non-null values
    
    # Group by the specified columns and get minimum values
    grouped = df_filtered.groupby(cols_to_group)
    return grouped.min().reset_index().sort_values(by=metric)

In [7]:
cols_to_group = [ "dataset_format","hostname", "cpu_brand"]
for col_to_rank in time_cols:
    print(f"Ranking by: {col_to_rank}")
    df_by_test = get_df_by_test(b_df, cols_to_group, col_to_rank)
    display(df_by_test)
    print("\n")

Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,filter_group_pandas_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.29
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.31
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.54
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,5.03
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,5.36
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,6.10
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,6.30
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,8.66
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10.41
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,10.67
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,11.96
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,12.34
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,13.57
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,14.23
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,14.73
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.10
9,csv,WL5022,Unknown (cpuinfo not available),22.84
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,23.82

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,filter_group_polars_seconds
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.07
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.08
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.09
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.09
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.10
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.16
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.34
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.49
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.51
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.52
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.62
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.80
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.83
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,0.95
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.04
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,1.31
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,1.96
9,csv,WL5022,Unknown (cpuinfo not available),2.82

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,filter_group_duckdb_seconds
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.03
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.04
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.04
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.06
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.06
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.07
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.13
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.14
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.50
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.56
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.58
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.67
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.76
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.78
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.95
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,1.09
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,1.60
9,csv,WL5022,Unknown (cpuinfo not available),3.97

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,statistics_pandas_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.22
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.22
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.71
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,5.36
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,6.13
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,6.42
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,7.00
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10.16
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10.38
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,11.55
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,12.60
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,16.37
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,17.39
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.42
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,19.77
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,20.10
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,29.12
9,csv,WL5022,Unknown (cpuinfo not available),44.53

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,statistics_polars_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.06
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.06
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.25
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.29
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.31
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.40
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.50
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.65
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.71
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.72
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.90
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.92
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.98
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,1.26
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.33
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,1.46
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,1.56
9,csv,WL5022,Unknown (cpuinfo not available),4.28

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,statistics_duckdb_seconds
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.05
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.06
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.11
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.11
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.14
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.15
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.28
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.30
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.57
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.67
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.68
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.78
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.86
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,1.03
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,1.07
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.22
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,1.91
9,csv,WL5022,Unknown (cpuinfo not available),4.18

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,complex_join_pandas_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,2.50
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,2.57
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,7.56
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,8.09
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.35
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10.24
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,11.51
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,16.44
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,16.47
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,22.59
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,23.24
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,24.86
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,29.20
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,32.43
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,34.15
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,35.25
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,51.72
9,csv,WL5022,Unknown (cpuinfo not available),75.80

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,complex_join_polars_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.48
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.50
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.85
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.94
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,1.23
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,1.26
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,1.30
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,1.39
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,1.43
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,1.50
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,1.64
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.73
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,1.92
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,2.35
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,3.40
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,3.65
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,4.04
9,csv,WL5022,Unknown (cpuinfo not available),6.49

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,complex_join_duckdb_seconds
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,3.20
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,3.29
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,3.58
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.60
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,4.72
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,4.87
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,4.91
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,6.12
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,6.22
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,7.16
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,8.19
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.43
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,9.13
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,9.52
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,12.95
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,19.63
9,csv,WL5022,Unknown (cpuinfo not available),22.18
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,24.73

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,timeseries_pandas_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.60
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.60
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,7.08
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,7.89
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.82
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,8.90
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10.43
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,12.86
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,13.26
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,14.28
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,15.08
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,18.41
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,19.61
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,21.25
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,22.30
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,25.47
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,33.33
9,csv,WL5022,Unknown (cpuinfo not available),48.58

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,timeseries_polars_seconds
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,1.92
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,1.93
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,1.94
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,2.22
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,2.40
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,2.40
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,2.41
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.52
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,2.66
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,2.84
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,3.35
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,3.49
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,3.65
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,3.79
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,4.24
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,4.54
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,4.70
9,csv,WL5022,Unknown (cpuinfo not available),8.04

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,timeseries_duckdb_seconds
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.11
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.13
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.19
15,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.21
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.24
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.32
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.35
17,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.43
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.56
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.63
5,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.64
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.67
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.83
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,1.00
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,1.01
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.14
2,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,2.23
9,csv,WL5022,Unknown (cpuinfo not available),4.26

In [ ]:
# Filter Group Pandas
fg_p = b_df[["hostname", "cpu_brand","dataset_size", "dataset_format", "filter_group_pandas_seconds"]]
fg_p = fg_p.groupby(by=["hostname", "cpu_brand","dataset_size", "dataset_format"]).min().reset_index()
fg_p = fg_p.rename(columns={"filter_group_pandas_seconds": "min_time_seconds"})
fg_p = fg_p.sort_values(by=["dataset_size","min_time_seconds", "hostname",  "dataset_format"])
fg_p

In [ ]:
print(f"The fastest filter_group_pandas_seconds is {filter_group_df['filter_group_pandas_seconds'].min()} seconds")