In [1]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [2]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       112 non-null    object
 1   hostname                        112 non-null    object
 2   platform                        112 non-null    object
 3   system                          112 non-null    object
 4   release                         112 non-null    int64
 5   version                         112 non-null    object
 6   machine                         112 non-null    object
 7   processor                       112 non-null    object
 8   cpu_count_logical               112 non-null    int64
 9   cpu_count_physical              112 non-null    int64
 10  cpu_freq_max                    112 non-null    float64
 11  cpu_freq_current                112 non-null    float64
 12  memory_total_gb                 112 non-null    float64
 13  memory_available_gb             112 non-null    float64
 14  python_version                  112 non-null    object
 15  python_implementation           112 non-null    object
 16  cpu_brand                       112 non-null    object
 17  cpu_arch                        112 non-null    object
 18  dataset_size                    112 non-null    int64
 19  dataset_name                    112 non-null    object
 20  dataset_format                  112 non-null    object
 21  filter_group_pandas_seconds     112 non-null    float64
 22  filter_group_polars_seconds     112 non-null    float64
 23  filter_group_duckdb_seconds     112 non-null    float64
 24  filter_group_fireducks_seconds  0 non-null      float64
 25  statistics_pandas_seconds       112 non-null    float64
 26  statistics_polars_seconds       112 non-null    float64
 27  statistics_duckdb_seconds       112 non-null    float64
 28  statistics_fireducks_seconds    0 non-null      float64
 29  complex_join_pandas_seconds     112 non-null    float64
 30  complex_join_polars_seconds     112 non-null    float64
 31  complex_join_duckdb_seconds     112 non-null    float64
 32  complex_join_fireducks_seconds  0 non-null      float64
 33  timeseries_pandas_seconds       112 non-null    float64
 34  timeseries_polars_seconds       112 non-null    float64
 35  timeseries_duckdb_seconds       112 non-null    float64
 36  timeseries_fireducks_seconds    0 non-null      float64
 37  script_name                     112 non-null    object
dtypes: float64(20), int64(4), object(14)
memory usage: 33.4+ KB

In [3]:
# Removing fireduck for now because there is not data(yet)
fireduck_columns = [col for col in b_df.columns if 'fireducks_' in col]
b_df.drop(columns=fireduck_columns, inplace=True)

b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   timestamp                    112 non-null    object
 1   hostname                     112 non-null    object
 2   platform                     112 non-null    object
 3   system                       112 non-null    object
 4   release                      112 non-null    int64
 5   version                      112 non-null    object
 6   machine                      112 non-null    object
 7   processor                    112 non-null    object
 8   cpu_count_logical            112 non-null    int64
 9   cpu_count_physical           112 non-null    int64
 10  cpu_freq_max                 112 non-null    float64
 11  cpu_freq_current             112 non-null    float64
 12  memory_total_gb              112 non-null    float64
 13  memory_available_gb          112 non-null    float64
 14  python_version               112 non-null    object
 15  python_implementation        112 non-null    object
 16  cpu_brand                    112 non-null    object
 17  cpu_arch                     112 non-null    object
 18  dataset_size                 112 non-null    int64
 19  dataset_name                 112 non-null    object
 20  dataset_format               112 non-null    object
 21  filter_group_pandas_seconds  112 non-null    float64
 22  filter_group_polars_seconds  112 non-null    float64
 23  filter_group_duckdb_seconds  112 non-null    float64
 24  statistics_pandas_seconds    112 non-null    float64
 25  statistics_polars_seconds    112 non-null    float64
 26  statistics_duckdb_seconds    112 non-null    float64
 27  complex_join_pandas_seconds  112 non-null    float64
 28  complex_join_polars_seconds  112 non-null    float64
 29  complex_join_duckdb_seconds  112 non-null    float64
 30  timeseries_pandas_seconds    112 non-null    float64
 31  timeseries_polars_seconds    112 non-null    float64
 32  timeseries_duckdb_seconds    112 non-null    float64
 33  script_name                  112 non-null    object
dtypes: float64(16), int64(4), object(14)
memory usage: 29.9+ KB

In [4]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(108, 34)

In [5]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(4)
b_df.head(3)

,timestamp,hostname,platform,system,release,version,machine,processor,cpu_count_logical,cpu_count_physical,...,statistics_pandas_seconds,statistics_polars_seconds,statistics_duckdb_seconds,complex_join_pandas_seconds,complex_join_polars_seconds,complex_join_duckdb_seconds,timeseries_pandas_seconds,timeseries_polars_seconds,timeseries_duckdb_seconds,script_name
0,2025-08-28T19:37:29.241650,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,16.8421,2.4087,3.5528,44.7432,6.0378,26.7368,22.6562,7.0202,3.8950,benchmark_01.py
1,2025-08-28T21:16:05.419895,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,10.3763,0.7842,0.5777,23.2358,1.4264,4.8354,12.8615,2.4257,0.6142,benchmark.py
2,2025-08-28T21:25:30.654371,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,14.1847,0.9119,0.6312,28.5303,1.4829,5.4315,16.9948,2.9021,0.5955,benchmark_02.py

In [6]:
def rank_methods(df, operation_col_prefix):
    time_cols = [col for col in df.columns if col.startswith(operation_col_prefix) and col.endswith('_seconds')]
    rank_df = pd.DataFrame()
    rank_df['hostname'] = df['hostname']
    rank_df['cpu_brand'] = df['cpu_brand'] 
    rank_df['dataset_size'] = df['dataset_size']
    rank_df['dataset_format'] = df['dataset_format']
    
    for col in time_cols:
        rank_col = f"rank_{col}"
        # Only rank non-zero values, assign max rank to zeros
        mask = df[col] > 0
        rank_df[rank_col] = df[col].where(mask).rank(method='min')
        max_rank = rank_df[rank_col].max()
        rank_df[rank_col] = rank_df[rank_col].fillna(max_rank + 1)
    
    return rank_df

In [7]:
filter_group_ranks = rank_methods(b_df, 'filter_group_')
sort_values_cols = [col for col in filter_group_ranks.columns if col.startswith('rank_filter_group_')]
filter_group_ranks[sort_values_cols] = filter_group_ranks[sort_values_cols].astype(int)
filter_group_ranks = filter_group_ranks.sort_values(by=sort_values_cols + ['hostname', 'dataset_format'])
filter_group_ranks

,hostname,cpu_brand,dataset_size,dataset_format,rank_filter_group_pandas_seconds,rank_filter_group_polars_seconds,rank_filter_group_duckdb_seconds
45,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,1,20,72
49,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,2,11,17
47,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,3,16,71
44,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,4,25,65
37,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,5,5,57
...,...,...,...,...,...,...,...
16,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,104,97,70
54,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,105,105,87
32,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,106,98,85
33,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,107,103,88
0,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,108,108,103

In [8]:
def get_df_by_test(df: pd.DataFrame, cols_to_group: list, metric: str) -> pd.DataFrame:
    # Properly combine columns - create a new list instead of using append
    columns_to_select = cols_to_group + [metric]
    
    # Select the relevant columns
    df_subset = df[columns_to_select]
    
    # Remove rows where the metric is null/zero (assuming you want valid measurements)
    df_filtered = df_subset[df_subset[metric] > 0]  # or use .notna() if you want non-null values
    
    # Group by the specified columns and get minimum values
    grouped = df_filtered.groupby(cols_to_group)
    return grouped.min().reset_index().sort_values(by=metric)

In [9]:
cols_to_group = [ "dataset_format","hostname", "cpu_brand"]
for col_to_rank in time_cols:
    print(f"Ranking by: {col_to_rank}")
    df_by_test = get_df_by_test(b_df, cols_to_group, col_to_rank)
    display(df_by_test)
    print("\n")

Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,filter_group_pandas_seconds
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.2705
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.2947
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.2991
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.3015
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.3077
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.3208
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.3829
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.4166
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.4258
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.4282
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.4341
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.4686
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.4934
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.5351
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.7320
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.9623
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.5351
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,5.0307
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,5.3583
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10.4113
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,10.7735
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,11.9636

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,filter_group_polars_seconds
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.0715
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0849
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0889
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.0950
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1375
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1406
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1411
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1557
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1808
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.1954
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.1990
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.2016
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.2032
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.2045
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.2082
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.2168
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3067
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.3406
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3553
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.4887
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.5050
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.6154

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,filter_group_duckdb_seconds
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0338
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0348
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0356
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.0419
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0430
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0481
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0524
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.0585
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.0629
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.0734
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.0835
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.0841
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.0946
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.1245
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.1372
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1731
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1943
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.2386
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3376
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.5018
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.5556
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.7791

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,statistics_pandas_seconds
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.2192
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.2242
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.2246
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.2270
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.2342
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.2445
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.3039
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.3362
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.3390
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.3707
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.3963
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.4077
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.6260
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.7525
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.8374
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.8503
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.7148
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,5.3573
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,6.4237
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10.3763
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,11.5511
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,16.3682

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,statistics_polars_seconds
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0601
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0639
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0959
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1046
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1210
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1214
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1406
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1456
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.2054
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.2101
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.2258
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.2282
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.2328
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.2497
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.2566
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.2887
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.3147
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3835
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3985
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.6457
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.7322
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.9183

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,statistics_duckdb_seconds
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0505
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0611
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0622
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0641
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0776
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0810
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.0936
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.1095
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.1146
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.1409
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1494
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.1503
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.1679
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.2101
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.2115
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.2224
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.2527
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3587
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.4987
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.5730
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.6790
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.8558

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,complex_join_pandas_seconds
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,2.2346
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,2.3353
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.5018
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,2.5049
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.5058
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,2.5658
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,2.7691
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,3.0525
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,3.2264
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,3.3289
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,3.5342
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,3.6183
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,4.1491
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,4.1554
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,5.8222
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,6.0528
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,7.5601
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,8.0883
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.3534
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,16.4438
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,23.2358
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,29.2015

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,complex_join_polars_seconds
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.4833
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.5019
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.5207
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.5228
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5432
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5550
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.8486
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.8504
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.8533
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.8969
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.9217
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.9389
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.9540
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.0040
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,1.1443
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,1.2282
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,1.2649
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,1.2842
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,1.3903
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,1.4264
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,1.8697
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,2.0621

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,complex_join_duckdb_seconds
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,3.1954
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,3.2853
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,3.5813
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,3.5945
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,4.2374
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.5955
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,4.7151
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,4.7469
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,4.8746
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,5.1401
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,6.2196
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.4259
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,13.4392
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,14.7696
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,17.2615
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,17.4457
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,17.4896
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,17.8054
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,21.5964
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,21.9246
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,37.6711
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,41.2920

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,timeseries_pandas_seconds
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.4935
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.5183
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5674
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5731
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.5954
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.6008
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.6892
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.7095
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.7510
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.7692
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.8325
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.8805
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.9062
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.9248
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,1.3838
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,1.5243
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,7.0802
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,7.8940
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.8249
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,12.8615
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,14.2759
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,19.6064

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,timeseries_polars_seconds
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,1.9154
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,1.9309
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,1.9436
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,1.9651
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,2.0356
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.1359
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.1381
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,2.2170
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,2.3974
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,2.4011
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,2.4089
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,2.6311
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,2.6612
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,2.8262
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,3.5394
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,3.7786
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,3.7949
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,3.8976
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,4.2613
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,4.3044
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,8.1785
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,8.3001

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,timeseries_duckdb_seconds
14,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.1140
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.1271
11,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1442
17,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1478
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1697
15,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.1864
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1962
18,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.2055
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.2387
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.2427
8,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.3133
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.3778
20,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.3868
9,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.4084
10,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.4514
7,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.5615
13,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.6044
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.6392
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.6735
5,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.8311
12,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.8441
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.9877

In [10]:
# Filter Group Pandas
fg_p = b_df[["hostname", "cpu_brand","dataset_size", "dataset_format", "filter_group_pandas_seconds"]]
fg_p = fg_p.groupby(by=["hostname", "cpu_brand","dataset_size", "dataset_format"]).min().reset_index()
fg_p = fg_p.rename(columns={"filter_group_pandas_seconds": "min_time_seconds"})
fg_p = fg_p.sort_values(by=["dataset_size","min_time_seconds", "hostname",  "dataset_format"])
fg_p

,hostname,cpu_brand,dataset_size,dataset_format,min_time_seconds
12,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,0.2705
6,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,0.2947
1,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,parquet,0.2991
13,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,parquet,0.3015
7,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,parquet,0.3077
0,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,0.3208
17,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,parquet,0.3829
18,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,csv,0.4166
19,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,parquet,0.4258
16,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,csv,0.4282
4,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,csv,0.4341
5,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,parquet,0.4686
21,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,parquet,0.4934
20,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,0.5351
2,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,csv,0.7320
3,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,parquet,0.9623
9,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,4.5351
11,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,parquet,5.0307
15,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,parquet,5.3583
14,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,10.4113
8,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,csv,10.7735
10,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,11.9636

In [11]:
print(f"The fastest filter_group_pandas_seconds is {fg_p['min_time_seconds'].min()} seconds")

The fastest filter_group_pandas_seconds is 0.2705 seconds

In [12]:
# Calculate the average operation time per row for each library
library_suffixes = ['pandas', 'polars', 'duckdb']  # Add 'fireducks' if/when data is available

for lib in library_suffixes:
    lib_cols = [col for col in b_df.columns if col.endswith(f'_{lib}_seconds')]
    b_df[f'{lib}_avg_time'] = b_df[lib_cols].mean(axis=1)

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each library
host_lib_avg = b_df.groupby('host_cpu')[[f'{lib}_avg_time' for lib in library_suffixes]].mean().reset_index()

# Sort each library's ranking and display
for lib in library_suffixes:
    print(f"Ranking by average {lib} time (ascending):")
    display(host_lib_avg[['host_cpu', f'{lib}_avg_time']].sort_values(f'{lib}_avg_time'))
    print("\n")

# Optionally, display the full table
host_lib_avg

Ranking by average pandas time (ascending):

                                             host_cpu  pandas_avg_time
8   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...         1.787119
9   VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...         2.144053
2   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...         2.578175
10  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...         2.740778
1   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...         3.681687
6   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...         3.707178
3      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX         3.961241
0    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900         4.299193
4          Inspiron3030S | Intel(R) Core(TM) i7-14700        11.492784
7     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M        15.408617
5       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX        20.426591

Ranking by average polars time (ascending):

                                             host_cpu  polars_avg_time
3      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX         0.766991
6   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...         0.848284
0    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900         0.966041
4          Inspiron3030S | Intel(R) Core(TM) i7-14700         1.156470
8   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...         1.160128
10  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...         1.445963
5       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX         1.487788
9   VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...         1.578309
7     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M         1.760348
2   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...         1.889731
1   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...         3.323328

Ranking by average duckdb time (ascending):

                                             host_cpu  duckdb_avg_time
4          Inspiron3030S | Intel(R) Core(TM) i7-14700         1.629052
6   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...         2.441453
0    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900         3.009408
5       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX         3.028197
7     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M         3.188273
8   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...         4.469484
10  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...         5.468172
9   VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...         6.429816
2   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...         7.451569
1   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...        11.993300
3      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX        15.853503

,host_cpu,pandas_avg_time,polars_avg_time,duckdb_avg_time
0,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900,4.299193,0.966041,3.009408
1,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,3.681687,3.323328,11.993300
2,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,2.578175,1.889731,7.451569
3,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX,3.961241,0.766991,15.853503
4,Inspiron3030S | Intel(R) Core(TM) i7-14700,11.492784,1.156470,1.629052
5,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX,20.426591,1.487788,3.028197
6,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,3.707178,0.848284,2.441453
7,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M,15.408617,1.760348,3.188273
8,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,1.787119,1.160128,4.469484
9,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,2.144053,1.578309,6.429816
10,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,2.740778,1.445963,5.468172

In [13]:
# Rank hosts (host + CPU) by the average time across all libraries (pandas, polars, duckdb)
#all_lib_time_cols = [col for col in b_df.columns if col.endswith('_pandas_seconds') or col.endswith('_polars_seconds') or col.endswith('_duckdb_seconds')]

b_df['all_libs_avg_time'] = b_df[time_cols].mean(axis=1)

# Group by host+cpu and get the mean
host_alllibs_avg = b_df.groupby('host_cpu')['all_libs_avg_time'].mean().reset_index()

# Sort to get the fastest overall
host_alllibs_avg_sorted = host_alllibs_avg.sort_values('all_libs_avg_time', ascending=True).reset_index(drop=True)

print("Ranking by average time across all libraries (fastest PC overall):")
display(host_alllibs_avg_sorted)

Ranking by average time across all libraries (fastest PC overall):

                                             host_cpu  all_libs_avg_time
0   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...           2.332305
1   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...           2.472244
2    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900           2.758214
3   WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...           3.218304
4   VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...           3.384059
5   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...           3.973158
6          Inspiron3030S | Intel(R) Core(TM) i7-14700           4.759436
7   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...           6.332772
8     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M           6.785746
9      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX           6.860578
10      Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX           8.314192