In [1]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [2]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       139 non-null    object
 1   hostname                        139 non-null    object
 2   platform                        139 non-null    object
 3   system                          139 non-null    object
 4   release                         139 non-null    int64
 5   version                         139 non-null    object
 6   machine                         139 non-null    object
 7   processor                       139 non-null    object
 8   cpu_count_logical               139 non-null    int64
 9   cpu_count_physical              139 non-null    int64
 10  cpu_freq_max                    139 non-null    float64
 11  cpu_freq_current                139 non-null    float64
 12  memory_total_gb                 139 non-null    float64
 13  memory_available_gb             139 non-null    float64
 14  python_version                  139 non-null    object
 15  python_implementation           139 non-null    object
 16  cpu_brand                       139 non-null    object
 17  cpu_arch                        139 non-null    object
 18  dataset_size                    139 non-null    int64
 19  dataset_name                    139 non-null    object
 20  dataset_format                  139 non-null    object
 21  filter_group_pandas_seconds     139 non-null    float64
 22  filter_group_polars_seconds     139 non-null    float64
 23  filter_group_duckdb_seconds     139 non-null    float64
 24  filter_group_fireducks_seconds  0 non-null      float64
 25  statistics_pandas_seconds       139 non-null    float64
 26  statistics_polars_seconds       139 non-null    float64
 27  statistics_duckdb_seconds       139 non-null    float64
 28  statistics_fireducks_seconds    0 non-null      float64
 29  complex_join_pandas_seconds     139 non-null    float64
 30  complex_join_polars_seconds     139 non-null    float64
 31  complex_join_duckdb_seconds     139 non-null    float64
 32  complex_join_fireducks_seconds  0 non-null      float64
 33  timeseries_pandas_seconds       139 non-null    float64
 34  timeseries_polars_seconds       139 non-null    float64
 35  timeseries_duckdb_seconds       139 non-null    float64
 36  timeseries_fireducks_seconds    0 non-null      float64
 37  script_name                     139 non-null    object
dtypes: float64(20), int64(4), object(14)
memory usage: 41.4+ KB

In [3]:
# Removing fireduck for now because there is not data(yet)
fireduck_columns = [col for col in b_df.columns if 'fireducks_' in col]
b_df.drop(columns=fireduck_columns, inplace=True)

b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   timestamp                    139 non-null    object
 1   hostname                     139 non-null    object
 2   platform                     139 non-null    object
 3   system                       139 non-null    object
 4   release                      139 non-null    int64
 5   version                      139 non-null    object
 6   machine                      139 non-null    object
 7   processor                    139 non-null    object
 8   cpu_count_logical            139 non-null    int64
 9   cpu_count_physical           139 non-null    int64
 10  cpu_freq_max                 139 non-null    float64
 11  cpu_freq_current             139 non-null    float64
 12  memory_total_gb              139 non-null    float64
 13  memory_available_gb          139 non-null    float64
 14  python_version               139 non-null    object
 15  python_implementation        139 non-null    object
 16  cpu_brand                    139 non-null    object
 17  cpu_arch                     139 non-null    object
 18  dataset_size                 139 non-null    int64
 19  dataset_name                 139 non-null    object
 20  dataset_format               139 non-null    object
 21  filter_group_pandas_seconds  139 non-null    float64
 22  filter_group_polars_seconds  139 non-null    float64
 23  filter_group_duckdb_seconds  139 non-null    float64
 24  statistics_pandas_seconds    139 non-null    float64
 25  statistics_polars_seconds    139 non-null    float64
 26  statistics_duckdb_seconds    139 non-null    float64
 27  complex_join_pandas_seconds  139 non-null    float64
 28  complex_join_polars_seconds  139 non-null    float64
 29  complex_join_duckdb_seconds  139 non-null    float64
 30  timeseries_pandas_seconds    139 non-null    float64
 31  timeseries_polars_seconds    139 non-null    float64
 32  timeseries_duckdb_seconds    139 non-null    float64
 33  script_name                  139 non-null    object
dtypes: float64(16), int64(4), object(14)
memory usage: 37.1+ KB

In [4]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(135, 34)

In [5]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(4)
b_df.head(3)

,timestamp,hostname,platform,system,release,version,machine,processor,cpu_count_logical,cpu_count_physical,...,statistics_pandas_seconds,statistics_polars_seconds,statistics_duckdb_seconds,complex_join_pandas_seconds,complex_join_polars_seconds,complex_join_duckdb_seconds,timeseries_pandas_seconds,timeseries_polars_seconds,timeseries_duckdb_seconds,script_name
0,2025-08-21T15:09:54.202383,WL5022,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"Intel64 Family 6 Model 140 Stepping 1, Genuine...",8,4,...,44.5267,4.2818,4.1815,75.8036,6.4908,22.1753,48.5759,8.0436,4.2604,benchmark.py
1,2025-08-21T18:10:27.497627,MSI,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,17.3882,1.0778,0.9855,34.0420,1.7733,7.4427,21.0240,4.0653,0.7738,benchmark.py
2,2025-08-21T19:31:51.731157,MSI,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,32.4747,0.9779,0.7805,32.4280,1.6359,7.1560,18.4051,3.4880,0.6399,benchmark.py

In [6]:
def rank_methods(df, operation_col_prefix):
    time_cols = [col for col in df.columns if col.startswith(operation_col_prefix) and col.endswith('_seconds')]
    rank_df = pd.DataFrame()
    rank_df['hostname'] = df['hostname']
    rank_df['cpu_brand'] = df['cpu_brand'] 
    rank_df['dataset_size'] = df['dataset_size']
    rank_df['dataset_format'] = df['dataset_format']
    
    for col in time_cols:
        rank_col = f"rank_{col}"
        # Only rank non-zero values, assign max rank to zeros
        mask = df[col] > 0
        rank_df[rank_col] = df[col].where(mask).rank(method='min')
        max_rank = rank_df[rank_col].max()
        rank_df[rank_col] = rank_df[rank_col].fillna(max_rank + 1)
    
    return rank_df

In [7]:
filter_group_ranks = rank_methods(b_df, 'filter_group_')
sort_values_cols = [col for col in filter_group_ranks.columns if col.startswith('rank_filter_group_')]
filter_group_ranks[sort_values_cols] = filter_group_ranks[sort_values_cols].astype(int)
filter_group_ranks = filter_group_ranks.sort_values(by=sort_values_cols + ['hostname', 'dataset_format'])
filter_group_ranks

,hostname,cpu_brand,dataset_size,dataset_format,rank_filter_group_pandas_seconds,rank_filter_group_polars_seconds,rank_filter_group_duckdb_seconds
80,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,1,20,78
84,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,2,11,17
82,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,3,16,77
79,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,4,26,70
72,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,5,5,61
...,...,...,...,...,...,...,...
55,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,131,131,116
56,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,132,114,98
16,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,133,128,122
64,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,134,116,99
3,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,10000000,csv,135,135,133

In [8]:
def get_df_by_test(df: pd.DataFrame, cols_to_group: list, metric: str) -> pd.DataFrame:
    # Properly combine columns - create a new list instead of using append
    columns_to_select = cols_to_group + [metric]
    
    # Select the relevant columns
    df_subset = df[columns_to_select]
    
    # Remove rows where the metric is null/zero (assuming you want valid measurements)
    df_filtered = df_subset[df_subset[metric] > 0]  # or use .notna() if you want non-null values
    
    # Group by the specified columns and get minimum values
    grouped = df_filtered.groupby(cols_to_group)
    return grouped.min().reset_index().sort_values(by=metric)

In [9]:
cols_to_group = [ "dataset_format","hostname", "cpu_brand"]
for col_to_rank in time_cols:
    print(f"Ranking by: {col_to_rank}")
    df_by_test = get_df_by_test(b_df, cols_to_group, col_to_rank)
    display(df_by_test)
    print("\n")

Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,filter_group_pandas_seconds
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.2705
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.2947
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.2991
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.3015
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.3077
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.3208
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.3829
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.4166
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.4258
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.4282
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.4341
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.4686
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.7320
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.9623
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.5351
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,5.0307
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,5.3583
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,8.6615
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10.4113
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,10.6675
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,11.9636
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,14.7335
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.0980
12,csv,WL5022,Unknown (cpuinfo not available),22.8431
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,23.8160

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,filter_group_polars_seconds
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.0715
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0849
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0889
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.0950
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1375
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1406
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1411
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1557
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.1603
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1808
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.1954
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.1990
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.2045
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.2082
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.2168
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3067
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.3406
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3553
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.4887
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.5050
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.6154
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.8318
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,0.9487
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.0421
12,csv,WL5022,Unknown (cpuinfo not available),2.8214

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,filter_group_duckdb_seconds
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0338
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0348
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0356
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.0419
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0430
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0481
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0524
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.0585
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.0629
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.0734
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.0835
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.0841
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.1245
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.1433
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1731
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1943
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.2386
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3376
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.5018
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.5556
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.6685
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.7791
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.9475
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,1.5988
12,csv,WL5022,Unknown (cpuinfo not available),3.9740

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,statistics_pandas_seconds
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.2192
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.2242
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.2246
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.2270
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.2342
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.2445
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.3039
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.3362
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.3390
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.3707
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.3963
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.4077
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.6260
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.7525
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.7148
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,5.3573
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,6.4237
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10.1561
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10.3763
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,11.5511
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,16.3682
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,17.3882
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.4169
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,29.1227
12,csv,WL5022,Unknown (cpuinfo not available),44.5267

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,statistics_polars_seconds
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0601
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0639
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0959
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1046
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1210
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1214
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1406
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1456
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.2054
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.2101
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.2282
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.2497
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.2566
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.2887
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.3147
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3835
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3985
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.4998
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.6457
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.7147
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.9183
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.9779
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.3273
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,1.4594
12,csv,WL5022,Unknown (cpuinfo not available),4.2818

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,statistics_duckdb_seconds
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0505
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.0611
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0622
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0641
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.0776
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.0810
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.0936
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.1095
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.1146
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.1409
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.1494
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.1503
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.2115
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.2224
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.2527
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.2756
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.3587
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.4987
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.5730
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.6790
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.7805
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.8558
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.2164
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,1.9137
12,csv,WL5022,Unknown (cpuinfo not available),4.1815

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,complex_join_pandas_seconds
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,2.2346
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,2.3353
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.5018
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,2.5049
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.5058
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,2.5658
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,2.7691
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,3.0525
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,3.2264
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,3.5342
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,3.6183
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,4.1554
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,5.8222
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,6.0528
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,7.5601
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,8.0883
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.3534
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,16.4438
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,16.4700
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,23.2358
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,29.2015
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,32.4280
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,35.2504
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,51.7238
12,csv,WL5022,Unknown (cpuinfo not available),75.8036

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,complex_join_polars_seconds
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.4833
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.5019
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.5207
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.5228
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5432
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5550
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.8486
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.8504
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.8533
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.8969
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.9389
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.9540
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,1.1443
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,1.2282
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,1.2649
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,1.2842
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,1.3903
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,1.4264
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,1.6359
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.7277
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,1.8697
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,2.0621
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,2.3456
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,3.3951
12,csv,WL5022,Unknown (cpuinfo not available),6.4908

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,complex_join_duckdb_seconds
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,3.1954
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,3.2853
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,3.5813
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,3.5945
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,4.2374
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,4.5955
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,4.7151
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,4.7469
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,4.8746
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,5.1401
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,6.2196
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,7.1560
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,8.1853
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.4259
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,9.5153
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,12.9485
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,13.4392
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,14.7696
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,17.4457
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,17.4896
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,21.5964
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,21.9246
12,csv,WL5022,Unknown (cpuinfo not available),22.1753
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,37.6711
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,41.2920

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,timeseries_pandas_seconds
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.4935
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.5183
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5674
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.5731
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.5954
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.6008
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.6892
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.7095
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.7510
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.8805
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.9062
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.9248
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,1.3838
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,1.5243
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,7.0802
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,7.8940
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,8.8249
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,12.8615
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,13.2594
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,14.2759
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,18.4051
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,19.6064
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,22.3014
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,33.3294
12,csv,WL5022,Unknown (cpuinfo not available),48.5759

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,timeseries_polars_seconds
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,1.9154
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,1.9309
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,1.9436
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,1.9651
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,2.0356
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.1359
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,2.1381
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,2.2170
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,2.3974
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,2.4011
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,2.4089
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,2.6311
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,2.6612
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,2.8262
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,3.4880
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,3.5394
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,3.8976
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,4.2395
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,4.2613
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,4.3044
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,4.5425
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,4.7033
12,csv,WL5022,Unknown (cpuinfo not available),8.0436
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,8.1785
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,8.3001

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,timeseries_duckdb_seconds
17,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.1140
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,0.1271
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1442
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1478
0,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,0.1697
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.1864
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,0.1962
21,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.2055
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.2387
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.2427
10,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,0.3133
23,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.3868
11,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,0.4084
24,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,0.4278
9,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,0.5615
16,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.6044
2,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,0.6392
7,csv,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,0.6399
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,0.6735
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,0.8311
15,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.8441
1,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,0.9877
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,1.1351
4,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,2.2325
12,csv,WL5022,Unknown (cpuinfo not available),4.2604

In [10]:
# Filter Group Pandas
fg_p = b_df[["hostname", "cpu_brand","dataset_size", "dataset_format", "filter_group_pandas_seconds"]]
fg_p = fg_p.groupby(by=["hostname", "cpu_brand","dataset_size", "dataset_format"]).min().reset_index()
fg_p = fg_p.rename(columns={"filter_group_pandas_seconds": "min_time_seconds"})
fg_p = fg_p.sort_values(by=["dataset_size","min_time_seconds", "hostname",  "dataset_format"])
fg_p

,hostname,cpu_brand,dataset_size,dataset_format,min_time_seconds
14,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,0.2705
6,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,0.2947
1,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,parquet,0.2991
15,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,parquet,0.3015
7,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,parquet,0.3077
0,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,0.3208
19,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,parquet,0.3829
20,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,csv,0.4166
21,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,parquet,0.4258
18,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,csv,0.4282
4,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,csv,0.4341
5,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,parquet,0.4686
2,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,csv,0.7320
3,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,parquet,0.9623
10,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,4.5351
12,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,parquet,5.0307
17,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,parquet,5.3583
24,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,parquet,8.6615
16,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,10.4113
9,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,csv,10.6675
11,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,11.9636
13,MSI,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,14.7335
8,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,10000000,csv,19.0980
22,WL5022,Unknown (cpuinfo not available),10000000,csv,22.8431
23,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,23.8160

In [11]:
print(f"The fastest filter_group_pandas_seconds is {fg_p['min_time_seconds'].min()} seconds")

The fastest filter_group_pandas_seconds is 0.2705 seconds

In [13]:
# Calculate the average operation time per row for each library
library_suffixes = ['pandas', 'polars', 'duckdb']  # Add 'fireducks' if/when data is available

for lib in library_suffixes:
    lib_cols = [col for col in b_df.columns if col.endswith(f'_{lib}_seconds')]
    b_df[f'{lib}_avg_time'] = b_df[lib_cols].mean(axis=1)

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each library
host_lib_avg = b_df.groupby('host_cpu')[[f'{lib}_avg_time' for lib in library_suffixes]].mean().reset_index()

# Sort each library's ranking and display
for lib in library_suffixes:
    print(f"Ranking by average {lib} time (ascending):")
    display(host_lib_avg[['host_cpu', f'{lib}_avg_time']].sort_values(f'{lib}_avg_time'))
    print("\n")

# Optionally, display the full table
host_lib_avg

Ranking by average pandas time (ascending):

                                             host_cpu  pandas_avg_time
10  TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...         1.787119
11  VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...         2.144053
2   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...         2.578175
1   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...         3.681687
8   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...         3.707178
3      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX         3.961241
0    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900         4.299193
5          Inspiron3030S | Intel(R) Core(TM) i7-14700        11.654007
9     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M        15.408617
6       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX        20.426591
7             MSI | AMD Ryzen AI 9 365 w/ Radeon 880M        23.316975
4   IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU ...        32.781177
12           WL5022 | Unknown (cpuinfo not available)        47.937325
13  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...        49.700094

Ranking by average polars time (ascending):

                                             host_cpu  polars_avg_time
3      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX         0.766991
8   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...         0.848284
0    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900         0.966041
10  TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...         1.160128
5          Inspiron3030S | Intel(R) Core(TM) i7-14700         1.198157
6       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX         1.487788
11  VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...         1.578309
9     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M         1.760348
7             MSI | AMD Ryzen AI 9 365 w/ Radeon 880M         1.856012
2   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...         1.889731
13  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...         2.450186
1   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...         3.323328
4   IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU ...         4.992346
12           WL5022 | Unknown (cpuinfo not available)         5.409400

Ranking by average duckdb time (ascending):

                                             host_cpu  duckdb_avg_time
5          Inspiron3030S | Intel(R) Core(TM) i7-14700         1.856052
7             MSI | AMD Ryzen AI 9 365 w/ Radeon 880M         2.397238
8   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...         2.441453
0    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900         3.009408
6       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX         3.028197
9     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M         3.188273
10  TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...         4.469484
13  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...         6.200414
11  VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...         6.429816
2   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...         7.451569
12           WL5022 | Unknown (cpuinfo not available)         8.647800
4   IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU ...         8.749475
1   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...        11.993300
3      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX        15.853503

,host_cpu,pandas_avg_time,polars_avg_time,duckdb_avg_time
0,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900,4.299193,0.966041,3.009408
1,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,3.681687,3.323328,11.993300
2,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,2.578175,1.889731,7.451569
3,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX,3.961241,0.766991,15.853503
4,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU ...,32.781177,4.992346,8.749475
5,Inspiron3030S | Intel(R) Core(TM) i7-14700,11.654007,1.198157,1.856052
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX,20.426591,1.487788,3.028197
7,MSI | AMD Ryzen AI 9 365 w/ Radeon 880M,23.316975,1.856012,2.397238
8,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,3.707178,0.848284,2.441453
9,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M,15.408617,1.760348,3.188273
10,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,1.787119,1.160128,4.469484
11,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,2.144053,1.578309,6.429816
12,WL5022 | Unknown (cpuinfo not available),47.937325,5.409400,8.647800
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,49.700094,2.450186,6.200414

In [ ]:
# Rank hosts (host + CPU) by the average time across all libraries (pandas, polars, duckdb)
all_lib_time_cols = [col for col in b_df.columns if col.endswith('_pandas_seconds') or col.endswith('_polars_seconds') or col.endswith('_duckdb_seconds')]
b_df['all_libs_avg_time'] = b_df[all_lib_time_cols].mean(axis=1)

# Group by host+cpu and get the mean
host_alllibs_avg = b_df.groupby('host_cpu')['all_libs_avg_time'].mean().reset_index()

# Sort to get the fastest overall
host_alllibs_avg_sorted = host_alllibs_avg.sort_values('all_libs_avg_time', ascending=True).reset_index(drop=True)

print("Ranking by average time across all libraries (fastest PC overall):")
display(host_alllibs_avg_sorted)

Ranking by average time across all libraries (fastest PC overall):

                                             host_cpu  all_libs_avg_time
0   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...           2.332305
1   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...           2.472244
2    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900           2.758214
3   VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...           3.384059
4   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...           3.973158
5          Inspiron3030S | Intel(R) Core(TM) i7-14700           4.902739
6   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...           6.332772
7     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M           6.785746
8      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX           6.860578
9       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX           8.314192
10            MSI | AMD Ryzen AI 9 365 w/ Radeon 880M           9.190075
11  IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU ...          15.507666
12  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...          19.450231
13           WL5022 | Unknown (cpuinfo not available)          20.664842

                                             host_cpu  all_libs_avg_time
0   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...           2.332305
1   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...           2.472244
2    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900           2.758214
3   VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...           3.384059
4   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...           3.973158
5          Inspiron3030S | Intel(R) Core(TM) i7-14700           4.902739
6   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...           6.332772
7     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M           6.785746
8      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX           6.860578
9       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX           8.314192
10            MSI | AMD Ryzen AI 9 365 w/ Radeon 880M           9.190075
11  IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU ...          15.507666
12  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...          19.450231
13           WL5022 | Unknown (cpuinfo not available)          20.664842