In [17]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [18]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588 entries, 0 to 587
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       588 non-null    object
 1   hostname                        588 non-null    object
 2   platform                        588 non-null    object
 3   system                          588 non-null    object
 4   release                         588 non-null    object
 5   version                         588 non-null    object
 6   machine                         588 non-null    object
 7   processor                       588 non-null    object
 8   cpu_count_logical               588 non-null    int64
 9   cpu_count_physical              588 non-null    int64
 10  cpu_freq_max                    588 non-null    float64
 11  cpu_freq_current                588 non-null    float64
 12  memory_total_gb                 588 non-null    float64
 13  memory_available_gb             588 non-null    float64
 14  python_version                  588 non-null    object
 15  python_implementation           588 non-null    object
 16  cpu_brand                       588 non-null    object
 17  cpu_arch                        588 non-null    object
 18  dataset_size                    588 non-null    int64
 19  dataset_name                    588 non-null    object
 20  dataset_format                  588 non-null    object
 21  filter_group_pandas_seconds     588 non-null    float64
 22  filter_group_polars_seconds     588 non-null    float64
 23  filter_group_duckdb_seconds     588 non-null    float64
 24  filter_group_fireducks_seconds  302 non-null    float64
 25  statistics_pandas_seconds       588 non-null    float64
 26  statistics_polars_seconds       588 non-null    float64
 27  statistics_duckdb_seconds       588 non-null    float64
 28  statistics_fireducks_seconds    302 non-null    float64
 29  complex_join_pandas_seconds     588 non-null    float64
 30  complex_join_polars_seconds     588 non-null    float64
 31  complex_join_duckdb_seconds     588 non-null    float64
 32  complex_join_fireducks_seconds  302 non-null    float64
 33  timeseries_pandas_seconds       588 non-null    float64
 34  timeseries_polars_seconds       588 non-null    float64
 35  timeseries_duckdb_seconds       588 non-null    float64
 36  timeseries_fireducks_seconds    302 non-null    float64
 37  script_name                     588 non-null    object
dtypes: float64(20), int64(3), object(15)
memory usage: 174.7+ KB

In [19]:
# Removing fireduck for now because there is not data(yet)
#fireduck_columns = [col for col in b_df.columns if 'fireducks_' in col]
#b_df.drop(columns=fireduck_columns, inplace=True)

#b_df.info()

In [20]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(584, 38)

In [21]:
# Clean platform-based analysis now possible
wsl2_data = b_df[b_df['system'] == 'WSL2']
native_linux = b_df[b_df['system'] == 'Linux'] 
windows_data = b_df[b_df['system'] == 'Windows']

# Example: Compare FireDucks performance
fireducks_wsl2 = wsl2_data['filter_group_fireducks_seconds']
fireducks_linux = native_linux['filter_group_fireducks_seconds']

In [22]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(6)
b_df.head(3)

,timestamp,hostname,platform,system,release,version,machine,processor,cpu_count_logical,cpu_count_physical,...,statistics_fireducks_seconds,complex_join_pandas_seconds,complex_join_polars_seconds,complex_join_duckdb_seconds,complex_join_fireducks_seconds,timeseries_pandas_seconds,timeseries_polars_seconds,timeseries_duckdb_seconds,timeseries_fireducks_seconds,script_name
0,2025-08-28T19:37:29.241650,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,44.743244,6.037812,26.736806,NaN,22.656234,7.020198,3.894986,NaN,benchmark_01.py
1,2025-08-28T21:16:05.419895,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,23.235775,1.426380,4.835438,NaN,12.861529,2.425745,0.614240,NaN,benchmark.py
2,2025-08-28T21:25:30.654371,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,28.530276,1.482855,5.431484,NaN,16.994786,2.902070,0.595494,NaN,benchmark_02.py

In [23]:
def rank_methods(df, operation_col_prefix):
    time_cols = [col for col in df.columns if col.startswith(operation_col_prefix) and col.endswith('_seconds')]
    rank_df = pd.DataFrame()
    rank_df['hostname'] = df['hostname']
    rank_df['cpu_brand'] = df['cpu_brand'] 
    rank_df['dataset_size'] = df['dataset_size']
    rank_df['dataset_format'] = df['dataset_format']
    
    for col in time_cols:
        rank_col = f"rank_{col}"
        # Only rank non-zero values, assign max rank to zeros
        mask = df[col] > 0
        rank_df[rank_col] = df[col].where(mask).rank(method='min')
        max_rank = rank_df[rank_col].max()
        rank_df[rank_col] = rank_df[rank_col].fillna(max_rank + 1)
    
    return rank_df

In [24]:
filter_group_ranks = rank_methods(b_df, 'filter_group_')
sort_values_cols = [col for col in filter_group_ranks.columns if col.startswith('rank_filter_group_')]
filter_group_ranks[sort_values_cols] = filter_group_ranks[sort_values_cols].astype(int)
filter_group_ranks = filter_group_ranks.sort_values(by=sort_values_cols + ['hostname', 'dataset_format'])
filter_group_ranks

,hostname,cpu_brand,dataset_size,dataset_format,rank_filter_group_pandas_seconds,rank_filter_group_polars_seconds,rank_filter_group_duckdb_seconds,rank_filter_group_fireducks_seconds
585,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,csv,1,163,124,41
587,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,parquet,2,202,106,123
586,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,parquet,3,212,53,69
574,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,csv,4,50,291,303
578,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,parquet,5,30,6,303
...,...,...,...,...,...,...,...,...
16,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,580,556,371,303
46,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,581,579,441,303
32,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,582,557,434,303
33,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,583,574,444,303
0,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,584,583,553,303

In [25]:
def get_df_by_test(df: pd.DataFrame, cols_to_group: list, metric: str) -> pd.DataFrame:
    # Properly combine columns - create a new list instead of using append
    columns_to_select = cols_to_group + [metric]
    
    # Select the relevant columns
    df_subset = df[columns_to_select]
    
    # Remove rows where the metric is null/zero 
    df_filtered = df_subset[df_subset[metric] > 0]  # or use .notna() 
    
    # Group by the specified columns and get minimum values
    grouped = df_filtered.groupby(cols_to_group)
    return grouped.min().reset_index().sort_values(by=metric)

In [26]:
cols_to_group = [ "dataset_format","hostname", "cpu_brand", "system", "memory_total_gb"]
with pd.option_context('display.max_rows', None):
    for col_to_rank in time_cols:
        print(f"Ranking by: {col_to_rank}")
        df_by_test = get_df_by_test(b_df, cols_to_group, col_to_rank).reset_index(drop=True)
        display(df_by_test)
        print("\n")

Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.176201
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.188335
2,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.194035
3,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.194325
4,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.204102
5,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.210462
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.214854
7,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.236677
8,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.239222
9,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.239936
10,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.252882
11,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.255371
12,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.257193
13,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.257924
14,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.259799
15,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.260106
16,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.269150
17,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.269462
18,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.269707
19,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.270451
20,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.270499
21,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.271542
22,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.273162
23,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.273861
24,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.274816
25,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.275933
26,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.283666
27,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.284732
28,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.293107
29,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.294839
30,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.295494
31,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.296013
32,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.300393
33,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.304917
34,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.307013
35,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.307098
36,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.307888
37,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.312222
38,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.315864
39,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.316038
40,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.320001
41,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.321065
42,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.325910
43,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.335269
44,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.335481
45,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.365571
46,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.367142
47,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.372711
48,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.374583
49,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.379735
50,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.380978
51,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.382879
52,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.389362
53,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.393282
54,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.397570
55,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.409041
56,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.409166
57,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.415871
58,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.416637
59,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.421023
60,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.425848
61,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.428233
62,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.434067
63,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.447669
64,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.461787
65,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.463888
66,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.465891
67,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.468646
68,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.475752
69,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.475849
70,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.493353
71,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.514984
72,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.528547
73,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.535098
74,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.555320
75,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.583145
76,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.591544
77,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.617913
78,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.637270
79,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.641110
80,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.663562
81,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.692138
82,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.702786
83,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.703566
84,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.731955
85,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.962332
86,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,5.358341
87,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,10.411298

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_polars_seconds
0,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.071505
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.090605
2,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.094960
3,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.098239
4,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.098410
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.098412
6,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.105863
7,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.113670
8,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.118766
9,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.119589
10,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.125012
11,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.125330
12,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.126928
13,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.127720
14,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.128240
15,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.129033
16,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.133582
17,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.134381
18,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.136902
19,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.139211
20,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.140502
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.144457
22,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.147632
23,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.148480
24,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.152259
25,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.153641
26,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.154450
27,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.157515
28,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.160666
29,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.165737
30,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.165866
31,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.180809
32,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.183723
33,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.188349
34,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.191101
35,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.194010
36,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.194452
37,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.195381
38,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.199044
39,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.201567
40,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.203178
41,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.204266
42,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.204483
43,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.208076
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.208222
45,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.216848
46,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.218959
47,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.219885
48,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.226329
49,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.230266
50,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.239710
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.243947
52,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.253067
53,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.264340
54,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.267077
55,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.268869
56,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.269017
57,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.273836
58,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.275828
59,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.281430
60,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.286957
61,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.291214
62,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.294835
63,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.297577
64,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.302873
65,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.306664
66,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.330961
67,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.332424
68,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.340602
69,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.345873
70,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.355334
71,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.376640
72,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.394636
73,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.431944
74,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.432383
75,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.433407
76,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.445868
77,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.447058
78,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.486967
79,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.488726
80,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.510137
81,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.542422
82,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.553279
83,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.565336
84,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.614996
85,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.625782
86,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.690226
87,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.823694

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.031890
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.031958
2,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.032062
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.032623
4,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.033242
5,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.034698
6,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.034815
7,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.036903
8,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.036922
9,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.039717
10,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.041783
11,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.042423
12,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.042528
13,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.045527
14,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.046066
15,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.046697
16,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.047376
17,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.047544
18,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.047966
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.047970
20,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.048604
21,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.048618
22,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.049567
23,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.049598
24,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.049785
25,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.049786
26,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.050001
27,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.050120
28,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.053021
29,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.053767
30,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.055147
31,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.055306
32,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.056555
33,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.057113
34,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.057115
35,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.058527
36,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.058952
37,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.061755
38,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.065795
39,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.066707
40,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.066937
41,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.067097
42,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.068272
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.068845
44,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.073407
45,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.075990
46,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.080767
47,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.082814
48,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.083453
49,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.084105
50,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.086627
51,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.092058
52,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.094551
53,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.095555
54,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.096380
55,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.113281
56,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.115737
57,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.116693
58,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.116821
59,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.119607
60,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.119977
61,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.122297
62,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.124491
63,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.126611
64,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.128099
65,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.133032
66,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.136810
67,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.137175
68,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.139353
69,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.141584
70,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.143259
71,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.146962
72,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.155095
73,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.156793
74,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.160650
75,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.168784
76,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.173057
77,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.173424
78,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.175472
79,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.194292
80,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.217084
81,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.224818
82,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.233033
83,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.238558
84,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.239716
85,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.261815
86,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.337646
87,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.501835

Ranking by: filter_group_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,filter_group_fireducks_seconds
0,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.001396
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.001484
2,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.001497
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.001519
4,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.001550
5,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.001573
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.001586
7,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.001589
8,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.001609
9,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.001656
10,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.001698
11,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.001743
12,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.001753
13,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.001776
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.001779
15,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.001853
16,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.001923
17,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.001940
18,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.002106
19,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.002271
20,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.002401
21,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.002427
22,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.002445
23,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.002453
24,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.002483
25,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.002592
26,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.002678
27,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.002729
28,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.002809
29,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.002961
30,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.002979
31,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.003022
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.003029
33,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.003122
34,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.003213
35,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.003224
36,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.003372
37,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.003474
38,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.003905
39,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.003935
40,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.004023
41,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.010577

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.148611
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.156536
2,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.160063
3,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.167602
4,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.168088
5,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.169622
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.171951
7,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.172934
8,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.178686
9,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.180947
10,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.182035
11,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.186431
12,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.187811
13,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.192725
14,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.201684
15,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.203179
16,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.207913
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.208207
18,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.213067
19,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.215019
20,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.215042
21,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.216869
22,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.218891
23,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.219370
24,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.219511
25,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.219855
26,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.221023
27,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.222419
28,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.222962
29,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.224219
30,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.224676
31,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.227811
32,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.231631
33,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.232281
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.234241
35,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.238018
36,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.240540
37,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.241225
38,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.241319
39,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.252322
40,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.254285
41,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.261322
42,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.265091
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.268410
44,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.268450
45,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.277762
46,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.291042
47,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.303906
48,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.312264
49,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.336234
50,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.338446
51,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.339025
52,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.339472
53,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.340918
54,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.343622
55,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.359289
56,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.360390
57,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.361939
58,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.367291
59,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.370749
60,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.371494
61,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.375648
62,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.377876
63,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.387176
64,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.391305
65,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.396269
66,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.397330
67,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.407656
68,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.465929
69,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.471190
70,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.474622
71,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.479291
72,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.502419
73,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.513319
74,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.524030
75,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.580449
76,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.600673
77,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.625986
78,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.652209
79,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.669447
80,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.673124
81,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.676553
82,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.684314
83,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.752458
84,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.837387
85,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.850339
86,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,6.423730
87,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,10.376254

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.057959
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.061096
2,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.061169
3,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.066585
4,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.072699
5,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.081498
6,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.085318
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.087296
8,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.087507
9,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.088249
10,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.089538
11,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.091074
12,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.092394
13,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.093786
14,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.093914
15,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.094802
16,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.095288
17,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.095524
18,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.095885
19,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.096383
20,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.097667
21,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.098535
22,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.098646
23,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.101301
24,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.101981
25,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.104160
26,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.104290
27,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.108512
28,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.109605
29,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.110336
30,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.110767
31,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.112284
32,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.112821
33,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.116079
34,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.116513
35,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.121048
36,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.134709
37,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.135417
38,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.136704
39,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.139852
40,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.140574
41,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.145582
42,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.175646
43,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.181394
44,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.188093
45,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.191556
46,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.199275
47,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.201458
48,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.205388
49,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.207037
50,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.210085
51,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.225668
52,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.225771
53,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.228205
54,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.228700
55,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.232830
56,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.234784
57,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.238894
58,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.248640
59,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.256583
60,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.303131
61,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.307027
62,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.311508
63,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.314736
64,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.319131
65,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.330587
66,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.332090
67,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.339440
68,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.357911
69,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.363951
70,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.365960
71,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.373520
72,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.375136
73,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.383513
74,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.383970
75,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.392614
76,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.398507
77,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.404778
78,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.418672
79,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.425459
80,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.438670
81,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.443669
82,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.450185
83,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.480064
84,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.510830
85,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.516206
86,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.516427
87,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.645693

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.038060
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.048504
2,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.051478
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.051746
4,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.052067
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.054845
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.055085
7,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.057667
8,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.058021
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.058118
10,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.059392
11,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.059756
12,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.061105
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.062178
14,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.066542
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.066727
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.067506
17,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.068152
18,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.069108
19,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.069300
20,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.070140
21,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.070597
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.071951
23,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.072261
24,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.073422
25,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.073689
26,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.074120
27,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.075092
28,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.076049
29,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.079360
30,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.080334
31,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.081314
32,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.081628
33,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.083700
34,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.085688
35,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.088910
36,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.089430
37,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.090312
38,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.092868
39,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.093565
40,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.095846
41,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.096858
42,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.099953
43,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.109509
44,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.110594
45,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.118487
46,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.131306
47,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.134772
48,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.140150
49,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.143583
50,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.149406
51,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.150332
52,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.164641
53,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.167851
54,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.195986
55,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.196961
56,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.198998
57,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.210103
58,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.211529
59,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.222407
60,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.251149
61,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.252737
62,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.252801
63,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.253880
64,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.295498
65,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.304877
66,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.323197
67,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.328502
68,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.329382
69,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.332450
70,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.352225
71,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.354550
72,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.355642
73,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.358730
74,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.370384
75,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.375684
76,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.382014
77,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.382476
78,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.445769
79,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.447324
80,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.460195
81,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.494045
82,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.498727
83,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.536384
84,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.572973
85,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,0.574453
86,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.660862
87,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,0.673051

Ranking by: statistics_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,statistics_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000140
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000141
2,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000145
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000146
4,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000148
5,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000152
6,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000187
7,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000193
8,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000195
9,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000197
10,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000204
11,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000205
12,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000213
13,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000220
14,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000227
15,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000232
16,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000239
17,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000246
18,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000249
19,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000250
20,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.000283
21,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000289
22,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000291
23,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000309
24,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000312
25,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000338
26,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000347
27,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000364
28,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000381
29,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.000384
30,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000414
31,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.000420
32,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000469
33,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000484
34,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.000490
35,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000491
36,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.000549
37,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.000555
38,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.000564
39,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.000571
40,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.000573
41,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.000893

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,1.600232
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,1.686373
2,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.703667
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,1.738139
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,1.740872
5,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,1.741788
6,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,1.743906
7,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.783565
8,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.812609
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.826722
10,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.845459
11,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,1.867475
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.885700
13,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.032971
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,2.039433
15,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.063363
16,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,2.086920
17,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.143273
18,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.148765
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,2.156851
20,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,2.157476
21,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.159110
22,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.190334
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,2.195587
24,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.295366
25,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.309064
26,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.310993
27,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.313880
28,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.321239
29,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.337842
30,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.399702
31,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.419912
32,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,2.436286
33,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.460799
34,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.486614
35,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.501646
36,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.599806
37,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.681270
38,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.690762
39,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,2.704473
40,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,2.710402
41,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,2.731822
42,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,2.745317
43,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,2.769056
44,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,2.772811
45,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,2.799186
46,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,2.836061
47,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.862606
48,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,2.920474
49,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,2.937153
50,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,3.039260
51,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,3.052452
52,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.101532
53,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,3.175220
54,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.193744
55,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,3.226381
56,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,3.328890
57,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.379374
58,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,3.404619
59,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,3.418511
60,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,3.425977
61,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,3.534181
62,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,3.618343
63,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,3.637755
64,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,3.735163
65,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,3.748340
66,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,3.944685
67,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.956058
68,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,3.981980
69,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,3.982410
70,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,4.149068
71,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,4.155437
72,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,4.253906
73,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,4.425937
74,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,4.435003
75,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,4.466859
76,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,4.541414
77,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,4.933718
78,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,5.147182
79,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,5.252674
80,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,5.558602
81,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,5.822155
82,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,6.052842
83,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,6.501427
84,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,8.353409
85,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,8.903364
86,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,9.781901
87,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,23.235775

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.440721
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.450646
2,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.459607
3,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.460579
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.460666
5,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.476298
6,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.479752
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.482777
8,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.483583
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.491799
10,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.495044
11,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.496640
12,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.497127
13,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.499025
14,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.506174
15,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.511116
16,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.511853
17,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.515251
18,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.516911
19,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.522545
20,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.536883
21,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.537555
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.541118
23,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.543734
24,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.563187
25,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.571349
26,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.575433
27,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.591883
28,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.680029
29,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.682576
30,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.688653
31,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.703326
32,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.706446
33,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.707446
34,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.711675
35,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.719540
36,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.731640
37,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.772013
38,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.793599
39,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.797163
40,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.798026
41,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.825475
42,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.850386
43,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.853281
44,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.857206
45,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.896909
46,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.896957
47,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.921715
48,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.954018
49,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.982904
50,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.988101
51,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.990866
52,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.997258
53,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,1.004030
54,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,1.029172
55,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,1.043388
56,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,1.144325
57,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,1.165587
58,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,1.166113
59,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,1.284159
60,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.338042
61,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,1.344523
62,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,1.390336
63,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.394849
64,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,1.424004
65,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,1.426380
66,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.451908
67,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.453339
68,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,1.469501
69,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.510888
70,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,1.530308
71,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.530371
72,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.550958
73,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,1.555928
74,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,1.566457
75,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.603825
76,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.618368
77,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.646886
78,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.673843
79,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.794887
80,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.805672
81,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.848436
82,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,1.869724
83,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,2.062053
84,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,2.212631
85,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,2.232569
86,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,2.617505
87,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,2.735544

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_duckdb_seconds
0,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,3.285292
1,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,3.594456
2,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,4.237417
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,4.595454
4,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,4.715118
5,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,4.746880
6,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,4.874635
7,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,5.140088
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,6.219584
9,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,8.425919
10,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,9.107234
11,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,9.114352
12,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,9.572599
13,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,9.602663
14,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,9.626689
15,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,9.906787
16,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,10.091561
17,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,10.099078
18,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,10.123247
19,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,10.282482
20,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,10.311187
21,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,10.624296
22,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,10.729680
23,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,10.849791
24,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,10.860894
25,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,10.972182
26,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,10.989343
27,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,11.087266
28,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,11.249223
29,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,11.251413
30,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,11.430921
31,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,12.164969
32,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,12.372747
33,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,12.757002
34,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,12.812437
35,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,13.439244
36,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,13.766659
37,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,14.045449
38,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,14.325541
39,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,14.327818
40,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,14.769567
41,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,14.798437
42,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,15.041581
43,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,15.266155
44,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,15.683895
45,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,16.000711
46,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,16.771762
47,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,17.002785
48,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,17.261537
49,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,17.445712
50,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,17.489565
51,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,17.644917
52,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,17.805404
53,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,18.515142
54,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,19.050351
55,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,19.524039
56,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,20.342126
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,21.596404
58,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,21.775294
59,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,21.924554
60,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,22.506948
61,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,22.578155
62,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,22.634748
63,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,22.790639
64,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,23.239070
65,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,23.916556
66,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,24.085375
67,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,25.211426
68,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,25.560013
69,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,25.567625
70,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,25.815095
71,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,26.185457
72,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,26.225853
73,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,26.324829
74,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,26.952746
75,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,27.339530
76,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,27.425043
77,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,27.868051
78,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,28.009790
79,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,30.442195
80,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,31.624210
81,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,32.850278
82,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,36.837714
83,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,37.671142
84,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,37.993901
85,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,41.291982
86,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,43.052157
87,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,43.799303

Ranking by: complex_join_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,complex_join_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000384
1,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000400
2,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000409
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.000413
4,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.000456
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000457
6,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.000482
7,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000505
8,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000508
9,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000517
10,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.000522
11,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000524
12,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.000532
13,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.000539
14,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.000556
15,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000562
16,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.000571
17,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000614
18,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000653
19,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.000663
20,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.000702
21,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.000707
22,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000744
23,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.000801
24,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000854
25,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.000859
26,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000936
27,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.000946
28,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000962
29,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.000969
30,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.001120
31,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.001124
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.001163
33,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.001174
34,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.001273
35,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.001411
36,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.001441
37,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.001456
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.001499
39,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.001595
40,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.001850
41,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.001865

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_pandas_seconds
0,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.311347
1,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.322537
2,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.328552
3,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.333227
4,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.335873
5,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.339370
6,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.349165
7,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.351937
8,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.357184
9,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.358497
10,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.358569
11,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.360182
12,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.360459
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.360709
14,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.403801
15,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.410205
16,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.414054
17,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.414082
18,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.419210
19,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.421920
20,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.427478
21,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.442156
22,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.455722
23,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.461030
24,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.461086
25,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.465839
26,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.467282
27,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.467711
28,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.478672
29,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.487813
30,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.493485
31,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.499842
32,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.503815
33,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.508836
34,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.508849
35,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.508894
36,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.511875
37,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.516602
38,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.517817
39,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.518303
40,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.520747
41,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.525932
42,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.532064
43,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.544533
44,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.544602
45,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.552929
46,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.557196
47,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.561544
48,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.566226
49,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.574874
50,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.582320
51,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.585583
52,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.590429
53,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.594944
54,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.618460
55,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.627129
56,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.634316
57,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.647076
58,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.689184
59,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.693135
60,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.701162
61,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.709507
62,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.735251
63,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.748335
64,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.751010
65,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.769225
66,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.778732
67,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.832497
68,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.835348
69,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.851114
70,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.880524
71,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.906153
72,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.924786
73,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.937737
74,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.010463
75,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.022419
76,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.205137
77,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.270681
78,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.311182
79,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.345003
80,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,1.383846
81,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.411530
82,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,1.438896
83,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.468229
84,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,1.524298
85,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.528268
86,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,8.824875
87,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,12.861529

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_polars_seconds
0,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,1.835762
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.836724
2,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,1.848299
3,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,1.858462
4,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.899370
5,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,1.899804
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,1.916424
7,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,1.916629
8,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,1.928277
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,1.930856
10,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.951676
11,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,1.965067
12,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,1.967512
13,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.019306
14,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,2.035647
15,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,2.036167
16,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.066553
17,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,2.070447
18,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,2.080549
19,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,2.081131
20,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,2.099917
21,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.110350
22,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,2.115645
23,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,2.131042
24,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,2.168447
25,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,2.168542
26,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,2.177278
27,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,2.179002
28,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,2.201313
29,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,2.205108
30,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.216953
31,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.224582
32,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,2.225481
33,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,2.243550
34,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,2.397435
35,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,2.408907
36,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.442789
37,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,2.447037
38,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.505193
39,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,2.582026
40,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,2.631081
41,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,2.683827
42,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,2.699992
43,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,2.774699
44,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.793840
45,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,2.826220
46,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,2.842163
47,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,3.202793
48,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,3.217056
49,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,3.243892
50,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,3.291802
51,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,3.539412
52,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,3.595803
53,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.607012
54,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,3.646706
55,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.677016
56,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,3.686936
57,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,3.778609
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,3.794873
59,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,3.878324
60,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,3.897610
61,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,3.960917
62,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.260854
63,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,4.261347
64,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,4.268188
65,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,4.303385
66,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,4.304416
67,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.347602
68,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,4.352973
69,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.393107
70,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.532263
71,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,4.544037
72,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,4.750237
73,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.928691
74,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,4.979773
75,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,5.020040
76,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,5.045245
77,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,5.156621
78,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,6.247831
79,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,6.251081
80,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,6.260561
81,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,6.267411
82,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,6.761818
83,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,7.017137
84,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,7.324557
85,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,8.000622
86,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,8.178485
87,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,8.300135

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.098952
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.110413
2,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.111596
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.113430
4,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.113817
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.122152
6,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.123296
7,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,31.43,0.125199
8,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.126457
9,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.127927
10,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.137403
11,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.140360
12,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.140741
13,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.141526
14,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.142895
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.147814
16,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.147826
17,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.148341
18,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.152020
19,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,63.70,0.152542
20,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.152933
21,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,63.70,0.154963
22,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.156028
23,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,127.71,0.156701
24,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.160707
25,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,63.71,0.169913
26,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.170429
27,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,Windows,61.68,0.170882
28,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.175055
29,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.179042
30,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.181075
31,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.19,0.193187
32,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.195624
33,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.196289
34,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.205527
35,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,63.21,0.207283
36,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.210747
37,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,31.61,0.228301
38,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.231962
39,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,Windows,31.21,0.234352
40,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.238715
41,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.263333
42,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.268142
43,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.271172
44,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,63.73,0.277293
45,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.294979
46,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,31.67,0.313320
47,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.362893
48,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.374270
49,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.377764
50,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.381150
51,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.386797
52,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.395654
53,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.396655
54,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,Windows,31.72,0.400789
55,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,15.63,0.408385
56,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,31.28,0.451360
57,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.501223
58,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,31.12,0.561461
59,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.579472
60,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,0.592204
61,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.604427
62,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,63.69,0.639191
63,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.674492
64,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.679273
65,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.709106
66,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.741153
67,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.757588
68,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.809643
69,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.829284
70,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.844055
71,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,31.81,0.850289
72,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.899609
73,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,0.986644
74,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,15.69,0.987728
75,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.991282
76,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.043566
77,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.050404
78,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.063147
79,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,63.82,1.145382
80,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,31.81,1.178603
81,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.187024
82,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,1.253193
83,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,63.82,1.270166
84,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.321530
85,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,15.88,1.425144
86,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,1.461500
87,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,1.522405

Ranking by: timeseries_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,memory_total_gb,timeseries_fireducks_seconds
0,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.273113
1,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.301512
2,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,62.66,0.302325
3,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.306496
4,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,31.20,0.312555
5,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.315209
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,31.19,0.338578
7,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.343629
8,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,WSL2,30.20,0.345705
9,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.367393
10,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,15.34,0.381611
11,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,31.19,0.395374
12,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.416866
13,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.418874
14,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.21,0.421610
15,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.424503
16,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.425058
17,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,30.95,0.448926
18,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.462007
19,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.464249
20,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,31.21,0.483188
21,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.501116
22,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,WSL2,15.22,0.510475
23,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.529562
24,csv,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.542455
25,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,31.20,0.564873
26,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,11.44,0.577054
27,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.583606
28,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.585731
29,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.592294
30,parquet,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,WSL2,15.49,0.595607
31,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.622113
32,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.651473
33,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.667169
34,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,31.25,0.682481
35,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,15.50,0.745909
36,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,15.26,0.777140
37,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,15.52,0.936820
38,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.942361
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,0.983110
40,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,31.25,0.986897
41,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,15.52,1.421789

In [27]:
# Filter Group Pandas
fg_p = b_df[["hostname", "cpu_brand","dataset_size", "dataset_format", "filter_group_pandas_seconds"]]
fg_p = fg_p.groupby(by=["hostname", "cpu_brand","dataset_size", "dataset_format"]).min().reset_index()
fg_p = fg_p.rename(columns={"filter_group_pandas_seconds": "min_time_seconds"})
fg_p = fg_p.sort_values(by=["dataset_size","min_time_seconds", "hostname",  "dataset_format"])
fg_p

,hostname,cpu_brand,dataset_size,dataset_format,min_time_seconds
32,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,csv,0.176201
33,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,10000000,parquet,0.188335
35,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,10000000,parquet,0.204102
34,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,10000000,csv,0.210462
26,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,10000000,csv,0.239222
27,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,10000000,parquet,0.239936
20,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,0.252882
25,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,0.255371
28,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,0.269462
5,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,parquet,0.269707
30,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,0.270499
24,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,csv,0.271542
31,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,parquet,0.273162
4,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,0.274816
29,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,parquet,0.275933
22,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,10000000,csv,0.283666
23,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,10000000,parquet,0.284732
21,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,parquet,0.296013
1,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,10000000,parquet,0.307013
19,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,parquet,0.316038
0,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,10000000,csv,0.325910
10,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,csv,0.335269
11,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,parquet,0.335481
18,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,csv,0.365571
14,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,10000000,csv,0.367142
15,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,10000000,parquet,0.372711
8,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,csv,0.374583
47,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,parquet,0.379735
9,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,parquet,0.380978
39,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,parquet,0.382879
46,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,0.389362
42,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,10000000,csv,0.397570
6,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,10000000,csv,0.409041
43,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,10000000,parquet,0.409166
44,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,10000000,csv,0.415871
40,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,csv,0.416637
7,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,10000000,parquet,0.421023
41,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,parquet,0.425848
38,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,csv,0.428233
3,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,parquet,0.447669
2,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,csv,0.461787
45,WL3066,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,10000000,parquet,0.475752
12,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,10000000,csv,0.528547
13,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,10000000,parquet,0.583145
16,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,csv,0.731955
17,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,parquet,0.962332
37,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,parquet,5.358341
36,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,10.411298

In [28]:
# Calculate the average operation time per row for each library
library_suffixes = ['pandas', 'polars', 'duckdb', 'fireducks']  # Add 'fireducks' if/when data is available

for lib in library_suffixes:
    lib_cols = [col for col in b_df.columns if col.endswith(f'_{lib}_seconds')]
    b_df[f'{lib}_avg_time'] = b_df[lib_cols].mean(axis=1)

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)+ ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each library
host_lib_avg = b_df.groupby('host_cpu')[[f'{lib}_avg_time' for lib in library_suffixes]].mean().reset_index()

# Sort each library's ranking and display
with pd.option_context('display.max_colwidth', None):
    for lib in library_suffixes:
        print(f"Ranking by average {lib} time (ascending):")
        display(host_lib_avg[['host_cpu', f'{lib}_avg_time']].sort_values(f'{lib}_avg_time'))
        print("\n")
# Optionally, display the full table
host_lib_avg

Ranking by average pandas time (ascending):

,host_cpu,pandas_avg_time
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.728984
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.785434
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.790206
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.828231
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.853110
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.872365
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.883562
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.906213
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.939625
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.961443
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.083468
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.089557
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.119797
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.127908
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.172261
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.292812
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.340711
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.491011
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.524103
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.575672
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.706588
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.710795
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.787122
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.932938
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,1.978228
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.985968
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,2.045975
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.144046
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,2.492094
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.506687
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.578181
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,2.581373
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.735169
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,2.740769
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.968245
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,3.109042
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,3.110269
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,3.681693
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,3.991704
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,5.444306
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,7.885764
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,15.408611

Ranking by average polars time (ascending):

,host_cpu,polars_avg_time
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.671769
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.742445
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.772193
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.783669
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.784100
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.792830
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.799042
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.846254
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.869688
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.876530
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.880961
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.901357
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.904037
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.908087
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.948109
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.948394
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.069344
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.069611
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.160133
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.184756
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.205978
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.310720
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.445962
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.505774
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.512683
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,1.578317
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.694340
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.736730
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.760348
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,1.880185
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.889734
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.914736
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.981489
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.013492
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.132537
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.245336
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.419061
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.429050
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.576411
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.154671
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,3.323331
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,3.513165

Ranking by average duckdb time (ascending):

,host_cpu,duckdb_avg_time
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.333418
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,2.555037
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,2.704064
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,2.823045
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.991300
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,3.000192
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,3.051764
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,3.155746
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.158985
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,3.167542
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.188277
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,3.299193
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,3.355343
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,3.711097
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,3.992685
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,4.006463
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,4.055661
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,4.235221
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,4.330357
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,4.469477
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,4.599465
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,5.198686
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,5.212134
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,5.468166
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,6.429801
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,6.473828
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,6.655530
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,6.951640
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.171884
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,7.451571
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,7.832607
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.991622
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,8.051619
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,8.588737
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,9.097915
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.127482
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.242403
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.192535
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,11.993303
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,12.402753
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,13.486665
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,16.960324

Ranking by average fireducks time (ascending):

,host_cpu,fireducks_avg_time
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.156754
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.158445
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.167420
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.175636
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.199306
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.202127
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.239988
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.271662
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.313481
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.324229
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.359409
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.370742
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.378425
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.396031
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.403118
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.493129
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.695349
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.780069
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.794866
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,1.062613
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,NaN
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,NaN
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,NaN
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,NaN
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,NaN
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,NaN
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,NaN
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,NaN
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,NaN
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,NaN
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,NaN
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,NaN
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,NaN
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,NaN
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,NaN
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,NaN
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,NaN
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,NaN
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,NaN
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,NaN
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,NaN
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,NaN

,host_cpu,pandas_avg_time,polars_avg_time,duckdb_avg_time,fireducks_avg_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.939625,1.069611,4.330357,0.239988
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,1.932938,1.205978,4.055661,NaN
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,1.491011,2.576411,11.192535,0.794866
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.785434,0.784100,3.000192,0.167420
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,3.110269,0.901357,2.991300,NaN
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,1.978228,1.880185,7.832607,1.062613
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,3.991704,2.429050,9.097915,NaN
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,1.172261,2.013492,9.127482,0.378425
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,1.089557,1.981489,9.242403,0.370742
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,3.109042,3.513165,12.402753,NaN
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,2.045975,3.154671,13.486665,0.695349
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,2.735169,2.132537,8.051619,NaN
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,1.119797,1.736730,7.171884,0.396031
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,2.968245,2.419061,16.960324,NaN
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,3.681693,3.323331,11.993303,NaN
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,1.083468,1.512683,6.655530,0.313481
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,2.578181,1.889734,7.451571,NaN
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.906213,0.792830,4.006463,0.199306
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,2.581373,0.948394,4.235221,NaN
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.883562,0.880961,3.992685,0.202127
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,1.710795,0.772193,3.355343,NaN
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.728984,0.742445,3.167542,0.158445
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,5.444306,0.904037,2.333418,NaN
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.872365,1.184756,6.473828,0.359409
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,1.706588,0.783669,2.823045,NaN
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.828231,0.869688,3.155746,0.156754
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,7.885764,1.069344,3.158985,NaN
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.853110,0.876530,3.711097,0.175636
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,2.492094,0.799042,2.704064,NaN
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.961443,0.846254,3.299193,0.493129
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,1.575672,0.671769,2.555037,NaN
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.790206,0.908087,4.599465,0.324229
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,1.524103,0.948109,3.051764,NaN
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,15.408611,1.760348,3.188277,NaN
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,1.787122,1.160133,4.469477,NaN
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,2.144046,1.578317,6.429801,NaN
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,1.292812,1.914736,7.991622,0.403118
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,2.506687,2.245336,6.951640,NaN
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,1.127908,1.310720,5.198686,0.271662
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,1.985968,1.505774,5.212134,NaN
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,1.340711,1.694340,8.588737,0.780069
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,2.740769,1.445962,5.468166,NaN

In [29]:
# Rank hosts (host + CPU) by the average time across all libraries (pandas, polars, duckdb)
#all_lib_time_cols = [col for col in b_df.columns if col.endswith('_pandas_seconds') or col.endswith('_polars_seconds') or col.endswith('_duckdb_seconds')]

b_df['all_libs_avg_time'] = b_df[time_cols].mean(axis=1)

# Group by host+cpu and get the mean
host_alllibs_avg = b_df.groupby('host_cpu')['all_libs_avg_time'].mean().reset_index()

# Sort to get the fastest overall
host_alllibs_avg_sorted = host_alllibs_avg.sort_values('all_libs_avg_time', ascending=True).reset_index(drop=True)

print("Ranking by average time across all libraries (fastest PC overall):")
with pd.option_context('display.max_colwidth', None):
    display(host_alllibs_avg_sorted)

Ranking by average time across all libraries (fastest PC overall):

,host_cpu,all_libs_avg_time
0,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,1.184287
1,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,1.199354
2,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,1.252605
3,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,1.400005
4,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,1.404093
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,1.476203
6,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,1.489834
7,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.600826
8,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.644896
9,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.655497
10,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.771101
11,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.841325
12,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.946110
13,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.977244
14,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.998400
15,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,2.222590
16,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.334309
17,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,2.391290
18,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,2.398192
19,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,2.472244
20,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,2.588329
21,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.606110
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.893920
23,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.900572
24,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.901292
25,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,3.100964
26,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.171048
27,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.172915
28,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.188409
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,3.218299
30,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,3.384055
31,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.901221
32,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,3.973162
33,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,4.013706
34,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,4.038031
35,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.306442
36,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,4.845665
37,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,5.172890
38,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,6.332776
39,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,6.341653
40,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.785746
41,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,7.449210

In [30]:
# Calculate the average operation time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  # Fixed: startswith
    b_df[f'{test}_avg_time'] = b_df[test_cols].mean(axis=1)  # Fixed: use test, not lib

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each test
test_avg_cols = [f'{test}_avg_time' for test in test_prefixes]
host_test_avg = b_df.groupby('host_cpu')[test_avg_cols].mean().reset_index()

# Sort each test's ranking and display
# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by average {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_avg[['host_cpu', f'{test}_avg_time']].sort_values(f'{test}_avg_time'))
    print("\n")

# Display the full table
host_test_avg

Ranking by average filter_group time (ascending):

,host_cpu,filter_group_avg_time
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.210105
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.224723
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.232272
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.235091
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.242138
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.255735
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.257783
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.260246
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.264002
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.271687
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.277032
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.308836
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.324235
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.325251
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.368343
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.382449
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.392711
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.438459
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.442778
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.463158
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.475525
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.480865
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.513317
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.550806
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.597730
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.609594
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.611797
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.693557
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.694441
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.746890
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.749385
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.804758
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.812564
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.821436
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.831888
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.036371
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.072774
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.287018
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.342407
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.508202
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.823748

Ranking by average statistics time (ascending):

,host_cpu,statistics_avg_time
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.141072
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.147452
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.149658
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.168026
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.172467
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.180325
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.182122
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.203319
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.207238
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.216774
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.225698
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.225851
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.256736
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.258530
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.261445
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.273173
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.351958
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.368919
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395596
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.396304
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.430578
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.440528
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.459804
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.534456
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.578091
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.588329
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.624623
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.662899
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.669798
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.689494
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.791946
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.861385
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.869160
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.908945
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.914073
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.931412
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.097377
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.163339
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.360749
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.448765
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,2.612892
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,4.208320

Ranking by average complex_join time (ascending):

,host_cpu,complex_join_avg_time
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,3.604662
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,3.682625
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,3.750240
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,4.218467
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,4.271681
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,4.544823
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,4.637280
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,4.897682
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,5.005017
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,5.125440
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,5.350801
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,5.362735
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,5.567900
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,5.981846
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,6.190292
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,6.302954
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,6.342929
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,7.040301
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,7.085135
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,7.248586
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,7.703487
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.756925
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,8.338663
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,8.456072
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,8.619418
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,8.817132
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,9.057651
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.301819
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.384543
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,9.791986
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,9.969111
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,10.487334
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,10.943079
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,11.430337
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.718066
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,12.467298
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,13.052801
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,14.181277
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,14.483172
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,17.847316
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,18.834236
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,24.791240

Ranking by average timeseries time (ascending):

,host_cpu,timeseries_avg_time
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.768042
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.781308
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.888004
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.909459
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.920432
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.931719
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.937399
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.980473
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.067212
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.071617
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.080760
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.224979
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.249969
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.315969
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.340433
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,1.417247
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.444806
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.451081
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.582553
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.645263
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,1.651231
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.665469
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.744553
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.866644
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.883217
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.935096
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.027155
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.108246
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.142782
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,2.376920
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.496969
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.646161
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.748607
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,3.031831
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.051035
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.275654
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.327298
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.574959
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.310571
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,4.326716
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,4.816141
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.058113

,host_cpu,filter_group_avg_time,statistics_avg_time,complex_join_avg_time,timeseries_avg_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.277032,0.216774,5.005017,1.080760
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.392711,0.368919,7.248586,1.582553
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.821436,0.869160,11.718066,2.646161
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.210105,0.141072,3.604662,0.781308
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.693557,0.689494,6.302954,1.651231
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,0.694441,0.624623,9.057651,2.376920
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,1.036371,1.163339,14.181277,4.310571
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,0.611797,0.669798,9.301819,2.108246
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.609594,0.662899,9.384543,2.027155
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,1.342407,1.360749,17.847316,4.816141
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.831888,0.791946,14.483172,3.275654
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.812564,0.914073,12.467298,3.031831
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.463158,0.459804,7.756925,1.744553
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.746890,0.931412,24.791240,3.327298
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,1.072774,1.097377,18.834236,4.326716
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.438459,0.396304,7.085135,1.645263
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.804758,0.908945,11.430337,2.748607
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.260246,0.168026,4.544823,0.931719
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.324235,0.273173,8.338663,1.417247
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.232272,0.180325,4.637280,0.909459
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.264002,0.258530,6.190292,1.071617
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090,0.149658,3.682625,0.768042
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,1.287018,1.448765,6.342929,2.496969
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.368343,0.256736,7.040301,1.224979
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.257783,0.225851,5.350801,1.249969
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.224723,0.147452,3.750240,0.888004
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,1.508202,2.612892,8.456072,3.574959
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.242138,0.182122,4.271681,0.920432
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.597730,0.588329,5.362735,1.444806
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.271687,0.172467,4.218467,0.937399
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.235091,0.203319,4.897682,1.067212
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.308836,0.207238,5.125440,0.980473
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.255735,0.225698,5.567900,1.315969
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,3.823748,4.208320,13.052801,6.058113
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.382449,0.351958,7.703487,1.451081
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.475525,0.430578,10.487334,2.142782
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.513317,0.534456,8.619418,1.935096
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.749385,0.861385,10.943079,3.051035
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.325251,0.261445,5.981846,1.340433
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.480865,0.440528,8.817132,1.866644
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.550806,0.395596,9.791986,1.665469
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.442778,0.578091,9.969111,1.883217

In [31]:
# Calculate the minumum time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  
    b_df[f'{test}_min_time'] = b_df[test_cols].min(axis=1)  

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the min per host+cpu for each test
test_min_cols = [f'{test}_min_time' for test in test_prefixes]
host_test_min = b_df.groupby('host_cpu')[test_min_cols].min().reset_index()

# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by minimum time {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_min[['host_cpu', f'{test}_min_time']].sort_values(f'{test}_min_time'))
    print("\n")

# Display the full table
host_test_min

Ranking by minimum time filter_group time (ascending):

,host_cpu,filter_group_min_time
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.001396
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.001484
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.001589
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.001698
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.001743
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.001753
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.001853
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.001940
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.002106
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002401
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002427
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002445
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.002453
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002678
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002809
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.003122
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003213
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003474
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.031890
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.031958
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.032062
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.034698
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.036903
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.042423
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.047376
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.056555
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058527
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.073407
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.080767
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.113281
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.128099
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.133032
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.141584
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558

Ranking by minimum time statistics time (ascending):

,host_cpu,statistics_min_time
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000140
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000145
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000187
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000193
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000195
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000197
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000204
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000213
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000227
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000283
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000289
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000291
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000338
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000347
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000381
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000420
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000490
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000549
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000564
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.048504
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.058021
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.059756
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.061105
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.068152
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.075092
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.081498
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.093565
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.099953
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.109509
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.164641
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.167851
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.304877
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.328502
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.352225
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.355642
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830

Ranking by minimum time complex_join time (ascending):

,host_cpu,complex_join_min_time
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000384
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000400
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000457
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000505
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000508
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000517
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000524
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000562
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000614
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000653
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000744
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000854
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000859
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000936
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000962
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001124
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001273
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001411
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001499
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.450646
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.459607
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.460579
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.476298
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.483583
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.496640
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.506174
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.511853
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.797163
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.850386
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.029172
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.338042
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.390336
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.451908
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.510888
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.646886
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631

Ranking by minimum time timeseries time (ascending):

,host_cpu,timeseries_min_time
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.098952
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.110413
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.111596
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.113430
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.137403
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.140360
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.140741
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.141526
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.147814
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.148341
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.152020
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.152933
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.170429
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.179042
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.195624
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.205527
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.210747
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.238715
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.263333
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.268142
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.362893
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.374270
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.377764
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395654
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.464249
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.501116
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.503815
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.544602
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.557196
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.574874
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.592204
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.741153
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.851114
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.986644
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.063147
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530

,host_cpu,filter_group_min_time,statistics_min_time,complex_join_min_time,timeseries_min_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.001940,0.000291,0.000653,0.210747
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.056555,0.099953,0.797163,0.263333
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.003029,0.000484,0.001163,0.667169
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.001589,0.000195,0.000524,0.147814
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.034815,0.062178,0.496640,0.140741
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,0.003213,0.000564,0.001411,0.557196
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,0.141584,0.352225,1.646886,1.063147
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,0.002445,0.000347,0.000962,0.574874
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.002427,0.000338,0.000936,0.501116
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.160650,0.510830,2.212631,1.321530
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.003474,0.000490,0.001499,0.851114
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.133032,0.355642,1.451908,0.986644
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.002678,0.000420,0.001124,0.503815
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.113281,0.304877,1.338042,0.741153
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,0.238558,0.358730,1.869724,0.844055
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.002453,0.000381,0.000854,0.464249
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.084105,0.211529,1.144325,0.604427
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.001484,0.000140,0.000384,0.098952
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.031890,0.048504,0.450646,0.113430
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.001853,0.000204,0.000562,0.268142
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.047376,0.081498,0.511853,0.195624
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497,0.000213,0.000457,0.152020
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,0.033242,0.059392,0.482777,0.142895
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.002106,0.000227,0.000614,0.141526
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.034698,0.058021,0.483583,0.179042
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.001698,0.000193,0.000517,0.152933
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.042423,0.068152,0.459607,0.148341
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.001743,0.000187,0.000508,0.170429
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.032062,0.061105,0.476298,0.147826
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.001753,0.000197,0.000505,0.110413
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.031958,0.059756,0.460579,0.140360
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.001396,0.000145,0.000400,0.111596
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.036903,0.075092,0.506174,0.137403
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,0.073407,0.109509,1.390336,0.205527
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.058527,0.093565,0.850386,0.238715
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.173057,0.140574,0.896909,0.386797
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.002809,0.000549,0.001273,0.544602
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.128099,0.328502,1.510888,0.592204
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.002401,0.000283,0.000859,0.374270
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.080767,0.164641,1.029172,0.362893
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.003122,0.000289,0.000744,0.395654
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.094551,0.167851,0.921715,0.377764

In [32]:
# Calculate the minimum time per row for each test and annotate which library achieved it (NaN-safe)

test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries']

for test in test_prefixes:
    # Raw timing columns only
    test_cols = [
        col for col in b_df.columns
        if col.startswith(f'{test}_') and col.endswith('_seconds')
    ]
    if not test_cols:
        b_df[f'{test}_min_time'] = float('nan')
        b_df[f'{test}_min_library'] = None
        continue

    # Convert to numeric (coerce 'N/A', blanks, etc. to NaN)
    numeric = b_df[test_cols].apply(pd.to_numeric, errors='coerce')

    # Row-wise min ignoring NaNs
    min_times = numeric.min(axis=1, skipna=True)

    # Identify the column name (library) producing the min ignoring NaNs.
    # pandas idxmin(skipna=True) returns NaN if the entire row is NaN.
    min_cols = numeric.idxmin(axis=1, skipna=True)

    suffix_len = len('_seconds')
    min_libs = []
    for col_name, all_nan in zip(min_cols, numeric.isna().all(axis=1)):
        if all_nan or pd.isna(col_name):
            min_libs.append(None)
        else:
            # column pattern: <test>_<library>_seconds
            lib_name = col_name[len(test) + 1: -suffix_len]
            min_libs.append(lib_name)

    b_df[f'{test}_min_time'] = min_times
    b_df[f'{test}_min_library'] = min_libs

# Unique host identifier
b_df['host_cpu'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['system'].astype(str)
)

# Aggregate: pick min time & corresponding library per host
host_rows = []
for host, g in b_df.groupby('host_cpu'):
    row = {'host_cpu': host}
    for test in test_prefixes:
        time_col = f'{test}_min_time'
        lib_col = f'{test}_min_library'
        if time_col not in g.columns or lib_col not in g.columns:
            row[time_col] = float('nan')
            row[lib_col] = None
            continue
        # valid rows for this test
        g_valid = g.dropna(subset=[time_col])
        if g_valid.empty:
            row[time_col] = float('nan')
            row[lib_col] = None
        else:
            # take the first row with minimal time
            min_idx = g_valid[time_col].idxmin()
            row[time_col] = g_valid.loc[min_idx, time_col]
            row[lib_col] = g_valid.loc[min_idx, lib_col]
    host_rows.append(row)

host_test_min = pd.DataFrame(host_rows)

# Display rankings per test including which library produced the min
for test in test_prefixes:
    time_col = f'{test}_min_time'
    lib_col = f'{test}_min_library'
    if time_col not in host_test_min.columns:
        continue
    print(f"Ranking by minimum {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(
            host_test_min[['host_cpu', time_col, lib_col]]
            .sort_values(time_col, na_position='last')
        )
    print("\n")

# Optional summary: frequency of fastest library per test
summary_rows = []
for test in test_prefixes:
    lib_col = f'{test}_min_library'
    if lib_col in host_test_min.columns:
        counts = host_test_min[lib_col].value_counts(dropna=True)
        for lib, cnt in counts.items():
            summary_rows.append({'test': test, 'library': lib, 'wins': cnt})
fastest_summary = pd.DataFrame(summary_rows).sort_values(['test', 'wins'], ascending=[True, False])
print("Fastest library counts per test:")
display(fastest_summary)

# Full aggregated table (one row per host with min times + libraries per test)
host_test_min

Ranking by minimum filter_group time (ascending):

,host_cpu,filter_group_min_time,filter_group_min_library
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.001396,fireducks
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.001484,fireducks
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.001589,fireducks
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.001698,fireducks
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.001743,fireducks
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.001753,fireducks
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.001853,fireducks
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.001940,fireducks
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.002106,fireducks
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002401,fireducks
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002427,fireducks
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002445,fireducks
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.002453,fireducks
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002678,fireducks
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002809,fireducks
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029,fireducks
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.003122,fireducks
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003213,fireducks
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003474,fireducks
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.031890,duckdb
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.031958,duckdb
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.032062,duckdb
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242,duckdb
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.034698,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815,duckdb
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.036903,duckdb
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.042423,duckdb
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.047376,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.056555,duckdb
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058527,duckdb
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.073407,duckdb
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.080767,duckdb
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105,duckdb
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551,duckdb
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.113281,duckdb
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.128099,duckdb
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.133032,duckdb
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.141584,duckdb
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650,duckdb
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057,duckdb
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558,duckdb

Ranking by minimum statistics time (ascending):

,host_cpu,statistics_min_time,statistics_min_library
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000140,fireducks
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000145,fireducks
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000187,fireducks
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000193,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000195,fireducks
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000197,fireducks
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000204,fireducks
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000213,fireducks
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000227,fireducks
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000283,fireducks
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000289,fireducks
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000291,fireducks
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000338,fireducks
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000347,fireducks
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000381,fireducks
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000420,fireducks
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484,fireducks
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000490,fireducks
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000549,fireducks
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000564,fireducks
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.048504,duckdb
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.058021,duckdb
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392,duckdb
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.059756,duckdb
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.061105,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178,duckdb
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.068152,duckdb
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.075092,duckdb
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.081498,polars
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.093565,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.099953,duckdb
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.109509,duckdb
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574,polars
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.164641,duckdb
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.167851,duckdb
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529,duckdb
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.304877,duckdb
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.328502,duckdb
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.352225,duckdb
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.355642,duckdb
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730,duckdb
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830,polars

Ranking by minimum complex_join time (ascending):

,host_cpu,complex_join_min_time,complex_join_min_library
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000384,fireducks
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000400,fireducks
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000457,fireducks
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000505,fireducks
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000508,fireducks
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000517,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000524,fireducks
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000562,fireducks
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000614,fireducks
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000653,fireducks
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000744,fireducks
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000854,fireducks
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000859,fireducks
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000936,fireducks
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000962,fireducks
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001124,fireducks
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163,fireducks
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001273,fireducks
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001411,fireducks
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001499,fireducks
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.450646,polars
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.459607,polars
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.460579,polars
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.476298,polars
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777,polars
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.483583,polars
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.496640,polars
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.506174,polars
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.511853,polars
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.797163,polars
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.850386,polars
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909,polars
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715,polars
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.029172,polars
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325,polars
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.338042,polars
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.390336,polars
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.451908,polars
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.510888,polars
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.646886,polars
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724,polars
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631,polars

Ranking by minimum timeseries time (ascending):

,host_cpu,timeseries_min_time,timeseries_min_library
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.098952,duckdb
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.110413,duckdb
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.111596,duckdb
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.113430,duckdb
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.137403,duckdb
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.140360,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.140741,duckdb
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.141526,duckdb
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895,duckdb
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.147814,duckdb
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826,duckdb
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.148341,duckdb
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.152020,duckdb
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.152933,duckdb
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.170429,duckdb
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.179042,duckdb
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.195624,duckdb
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.205527,duckdb
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.210747,duckdb
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.238715,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.263333,duckdb
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.268142,duckdb
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.362893,duckdb
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.374270,duckdb
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.377764,duckdb
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797,duckdb
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395654,duckdb
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.464249,fireducks
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.501116,fireducks
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.503815,pandas
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.544602,pandas
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.557196,pandas
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.574874,pandas
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.592204,duckdb
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427,duckdb
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169,fireducks
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.741153,duckdb
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055,duckdb
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.851114,pandas
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.986644,duckdb
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.063147,duckdb
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530,duckdb

Fastest library counts per test:

           test    library  wins
5  complex_join     polars    22
6  complex_join  fireducks    20
0  filter_group     duckdb    22
1  filter_group  fireducks    20
2    statistics  fireducks    20
3    statistics     duckdb    19
4    statistics     polars     3
7    timeseries     duckdb    34
8    timeseries     pandas     5
9    timeseries  fireducks     3

,host_cpu,filter_group_min_time,filter_group_min_library,statistics_min_time,statistics_min_library,complex_join_min_time,complex_join_min_library,timeseries_min_time,timeseries_min_library
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.001940,fireducks,0.000291,fireducks,0.000653,fireducks,0.210747,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.056555,duckdb,0.099953,duckdb,0.797163,polars,0.263333,duckdb
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.003029,fireducks,0.000484,fireducks,0.001163,fireducks,0.667169,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.001589,fireducks,0.000195,fireducks,0.000524,fireducks,0.147814,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.034815,duckdb,0.062178,duckdb,0.496640,polars,0.140741,duckdb
5,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,0.003213,fireducks,0.000564,fireducks,0.001411,fireducks,0.557196,pandas
6,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @...,0.141584,duckdb,0.352225,duckdb,1.646886,polars,1.063147,duckdb
7,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,0.002445,fireducks,0.000347,fireducks,0.000962,fireducks,0.574874,pandas
8,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.002427,fireducks,0.000338,fireducks,0.000936,fireducks,0.501116,fireducks
9,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.160650,duckdb,0.510830,polars,2.212631,polars,1.321530,duckdb
10,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.003474,fireducks,0.000490,fireducks,0.001499,fireducks,0.851114,pandas
11,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.133032,duckdb,0.355642,duckdb,1.451908,polars,0.986644,duckdb
12,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.002678,fireducks,0.000420,fireducks,0.001124,fireducks,0.503815,pandas
13,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.113281,duckdb,0.304877,duckdb,1.338042,polars,0.741153,duckdb
14,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,0.238558,duckdb,0.358730,duckdb,1.869724,polars,0.844055,duckdb
15,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.002453,fireducks,0.000381,fireducks,0.000854,fireducks,0.464249,fireducks
16,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.084105,duckdb,0.211529,duckdb,1.144325,polars,0.604427,duckdb
17,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.001484,fireducks,0.000140,fireducks,0.000384,fireducks,0.098952,duckdb
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.031890,duckdb,0.048504,duckdb,0.450646,polars,0.113430,duckdb
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.001853,fireducks,0.000204,fireducks,0.000562,fireducks,0.268142,duckdb
20,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.047376,duckdb,0.081498,polars,0.511853,polars,0.195624,duckdb
21,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497,fireducks,0.000213,fireducks,0.000457,fireducks,0.152020,duckdb
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,0.033242,duckdb,0.059392,duckdb,0.482777,polars,0.142895,duckdb
23,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.002106,fireducks,0.000227,fireducks,0.000614,fireducks,0.141526,duckdb
24,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Rade...,0.034698,duckdb,0.058021,duckdb,0.483583,polars,0.179042,duckdb
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.001698,fireducks,0.000193,fireducks,0.000517,fireducks,0.152933,duckdb
26,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.042423,duckdb,0.068152,duckdb,0.459607,polars,0.148341,duckdb
27,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.001743,fireducks,0.000187,fireducks,0.000508,fireducks,0.170429,duckdb
28,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.032062,duckdb,0.061105,duckdb,0.476298,polars,0.147826,duckdb
29,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.001753,fireducks,0.000197,fireducks,0.000505,fireducks,0.110413,duckdb
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Pro...,0.031958,duckdb,0.059756,duckdb,0.460579,polars,0.140360,duckdb
31,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.001396,fireducks,0.000145,fireducks,0.000400,fireducks,0.111596,duckdb
32,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon...,0.036903,duckdb,0.075092,duckdb,0.506174,polars,0.137403,duckdb
33,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,0.073407,duckdb,0.109509,duckdb,1.390336,polars,0.205527,duckdb
34,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.058527,duckdb,0.093565,duckdb,0.850386,polars,0.238715,duckdb
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.173057,duckdb,0.140574,polars,0.896909,polars,0.386797,duckdb
36,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.002809,fireducks,0.000549,fireducks,0.001273,fireducks,0.544602,pandas
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90...,0.128099,duckdb,0.328502,duckdb,1.510888,polars,0.592204,duckdb
38,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.002401,fireducks,0.000283,fireducks,0.000859,fireducks,0.374270,duckdb
39,WL3066 | 11th Gen Intel(R) Core(TM) i7-11850H ...,0.080767,duckdb,0.164641,duckdb,1.029172,polars,0.362893,duckdb
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.003122,fireducks,0.000289,fireducks,0.000744,fireducks,0.395654,duckdb
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.094551,duckdb,0.167851,duckdb,0.921715,polars,0.377764,duckdb