In [1]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [2]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       1277 non-null   object
 1   hostname                        1277 non-null   object
 2   platform                        1277 non-null   object
 3   system                          1277 non-null   object
 4   release                         1277 non-null   object
 5   version                         1277 non-null   object
 6   machine                         1277 non-null   object
 7   processor                       1277 non-null   object
 8   cpu_count_logical               1277 non-null   int64
 9   cpu_count_physical              1277 non-null   int64
 10  cpu_freq_max                    1277 non-null   float64
 11  cpu_freq_current                1277 non-null   float64
 12  memory_total_gb                 1277 non-null   float64
 13  memory_available_gb             1277 non-null   float64
 14  python_version                  1277 non-null   object
 15  python_implementation           1277 non-null   object
 16  cpu_brand                       1277 non-null   object
 17  cpu_arch                        1277 non-null   object
 18  dataset_size                    1277 non-null   int64
 19  dataset_name                    1277 non-null   object
 20  dataset_format                  1277 non-null   object
 21  filter_group_pandas_seconds     1277 non-null   float64
 22  filter_group_polars_seconds     1277 non-null   float64
 23  filter_group_duckdb_seconds     1277 non-null   float64
 24  filter_group_fireducks_seconds  716 non-null    float64
 25  statistics_pandas_seconds       1277 non-null   float64
 26  statistics_polars_seconds       1277 non-null   float64
 27  statistics_duckdb_seconds       1277 non-null   float64
 28  statistics_fireducks_seconds    716 non-null    float64
 29  complex_join_pandas_seconds     1277 non-null   float64
 30  complex_join_polars_seconds     1277 non-null   float64
 31  complex_join_duckdb_seconds     1277 non-null   float64
 32  complex_join_fireducks_seconds  716 non-null    float64
 33  timeseries_pandas_seconds       1277 non-null   float64
 34  timeseries_polars_seconds       1277 non-null   float64
 35  timeseries_duckdb_seconds       1277 non-null   float64
 36  timeseries_fireducks_seconds    715 non-null    float64
 37  script_name                     1277 non-null   object
dtypes: float64(20), int64(3), object(15)
memory usage: 379.2+ KB

In [3]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(1277, 38)

In [4]:
# Filtering by platform
#b_df = windows_data # Focus on Windows data for now

In [5]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(6) # Round to microseconds for better readability
#b_df.head(3)

In [6]:
def get_df_by_test(
    df: pd.DataFrame,
    cols_to_group: list,
    metric: str,
    dedupe_on: list | None = None,
) -> pd.DataFrame:
    """
    Returns the fastest rows for a given metric.

    - If dedupe_on is None: returns one row per cols_to_group (min metric).
    - If dedupe_on is provided: returns one row per dedupe_on group,
      keeping the other columns (e.g., dataset_format) from the winning row.
    """
    # Select only needed columns
    columns_to_select = list(dict.fromkeys(cols_to_group + [metric]))
    df_subset = df[columns_to_select].copy()

    # Coerce metric to numeric and treat <=0 as missing
    df_subset[metric] = pd.to_numeric(df_subset[metric], errors="coerce")
    df_subset.loc[df_subset[metric] <= 0, metric] = pd.NA

    # Keep only rows with valid metric
    df_filtered = df_subset.dropna(subset=[metric])
    if df_filtered.empty:
        return df_filtered

    # If requested, dedupe across formats (or any other dimension) by picking the minimal row
    if dedupe_on:
        idx = df_filtered.groupby(dedupe_on)[metric].idxmin()
        result = df_filtered.loc[idx].copy()
    else:
        # One row per group: minimal metric
        result = df_filtered.groupby(cols_to_group, as_index=False)[metric].min()

    return result.sort_values(by=metric, ascending=True)

In [7]:
# Show rankings segregated by platform (fair comparison)
# Also de-duplicates CSV vs Parquet per host+cpu+mem by keeping only the fastest format.
cols_to_group = ["dataset_format", "hostname", "cpu_brand", "memory_total_gb"]

# Use a stable preferred order, but only keep platforms that exist in the data
preferred_system_order = ["Windows", "WSL2", "Linux"]
systems_present = [s for s in preferred_system_order if s in set(b_df["system"].dropna().unique())]

with pd.option_context("display.max_rows", None):
    for system in systems_present:
        print(f"\n====================\nPlatform: {system}\n====================")
        df_sys = b_df[b_df["system"] == system].copy()

        for col_to_rank in time_cols:
            # Make sure this metric actually has data on this platform
            metric_series = pd.to_numeric(df_sys[col_to_rank], errors="coerce").mask(lambda s: s <= 0)
            if metric_series.notna().sum() == 0:
                # No timings recorded for this library/test on this platform (e.g., FireDucks on Windows)
                continue

            # Use the cleaned numeric series for ranking
            df_sys[col_to_rank] = metric_series

            # Keep only ONE row per host+cpu+mem (but keep the winning dataset_format in the output)
            df_by_test = get_df_by_test(
                df_sys,
                cols_to_group,
                col_to_rank,
                dedupe_on=["hostname", "cpu_brand", "memory_total_gb"],
            ).reset_index(drop=True)

            if df_by_test.empty:
                continue

            print(f"Ranking by: {col_to_rank}")
            display(df_by_test)
            print("\n")

====================
Platform: Windows
====================
Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.194035
1,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.239222
2,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.246244
3,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.249029
4,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,0.253508
5,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,0.255594
6,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,0.255830
7,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.257193
8,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,0.257679
9,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.259799
10,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,0.261865
11,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.264174
12,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.264356
13,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,0.266829
14,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.269150
15,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,0.269462
16,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.270499
17,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,0.273668
18,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,0.275231
19,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,0.276603
20,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.278784
21,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.278926
22,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.279343
23,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.283666
24,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,0.284164
25,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,0.286095
26,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.293107
27,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.296013
28,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,0.298419
29,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,0.303699
30,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.304548
31,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.307098
32,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.307101
33,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,0.311811
34,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,0.315094
35,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,0.317776
36,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.360832
37,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.369146
38,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.383956
39,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.393282
40,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.416637
41,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.434067
42,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.453049
43,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.463888
44,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.465891
45,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.475299
46,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,0.514906
47,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.528547
48,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,0.573630
49,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.617913
50,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.663562
51,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.692138
52,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.731955

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.086000
1,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.094960
2,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.098239
3,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.099523
4,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,0.100452
5,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,0.101329
6,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,0.104970
7,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,0.107466
8,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,0.107871
9,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.113670
10,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.117693
11,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,0.118075
12,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.118990
13,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.125330
14,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,0.125674
15,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.128240
16,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.128621
17,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.129033
18,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,0.129676
19,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,0.130960
20,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.131098
21,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,0.136210
22,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.136902
23,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,0.140306
24,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,0.151274
25,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.151938
26,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.152259
27,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,0.162391
28,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,0.164704
29,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,0.178158
30,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.178636
31,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.180809
32,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,0.180915
33,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.185390
34,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.188720
35,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.191101
36,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.192195
37,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.195381
38,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.200289
39,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.214153
40,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,0.215628
41,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.245735
42,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.264340
43,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.268869
44,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.273836
45,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.275828
46,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.286957
47,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.306664
48,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.315507
49,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.331924
50,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,0.402877
51,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,0.411598
52,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.542422

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.031890
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.031958
2,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.032062
3,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.033242
4,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,0.033673
5,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.034698
6,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.034815
7,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,0.034849
8,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.035718
9,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.036018
10,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.036321
11,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,0.036595
12,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.036850
13,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.036903
14,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.039717
15,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,0.039774
16,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.039799
17,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,0.040170
18,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,0.040718
19,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.040865
20,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.041897
21,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,0.042288
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.042423
23,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,0.043970
24,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,0.044178
25,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,0.045534
26,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.046270
27,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,0.046693
28,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.047376
29,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,0.048131
30,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,0.048200
31,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.048940
32,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,0.053748
33,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,0.056317
34,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.056555
35,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,0.058221
36,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.058446
37,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.062731
38,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.073608
39,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,0.078268
40,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.080767
41,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.084105
42,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,0.091840
43,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.094551
44,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.113281
45,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,0.125038
46,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.128099
47,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.133032
48,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.141584
49,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.160650
50,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.173057
51,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.173585
52,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.238558

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.167602
1,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.204128
2,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.207913
3,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.208003
4,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.208207
5,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.216158
6,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,0.217184
7,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,0.218041
8,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,0.218281
9,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.219370
10,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,0.219468
11,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.219855
12,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.222419
13,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.222874
14,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.224219
15,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,0.224597
16,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.224676
17,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.225344
18,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,0.226658
19,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,0.230753
20,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.232309
21,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.233630
22,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.234241
23,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,0.235941
24,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,0.236691
25,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,0.237887
26,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.238547
27,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,0.240731
28,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.241225
29,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,0.244354
30,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.254285
31,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,0.254770
32,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,0.257220
33,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,0.263950
34,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,0.268623
35,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,0.286992
36,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.287178
37,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.287674
38,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.324660
39,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.338446
40,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.339025
41,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.343622
42,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.396269
43,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,0.426001
44,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.432261
45,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,0.436552
46,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.474622
47,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.513319
48,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.580449
49,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.625986
50,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.652209
51,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.673124
52,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.837387

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.061096
1,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.072699
2,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.081498
3,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,0.083137
4,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.085318
5,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.086847
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.087507
7,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.087829
8,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.091074
9,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,0.091223
10,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,0.092884
11,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.093786
12,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,0.094269
13,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.095288
14,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.095885
15,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.101770
16,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,0.104092
17,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,0.106937
18,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.108512
19,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,0.109531
20,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,0.116420
21,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.116968
22,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,0.117039
23,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,0.121739
24,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,0.123038
25,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.127979
26,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.134935
27,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.140574
28,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,0.145946
29,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,0.153874
30,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,0.157936
31,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.164934
32,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.168137
33,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,0.181688
34,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.188093
35,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.190012
36,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.191556
37,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.195593
38,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,0.197656
39,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,0.206195
40,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.225771
41,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.228205
42,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.273801
43,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.275371
44,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.339440
45,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.363951
46,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.375136
47,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,0.376795
48,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.383513
49,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.395479
50,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,0.431933
51,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.443669
52,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.510830

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.048504
1,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.058021
2,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.058166
3,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.059392
4,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.059756
5,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.061105
6,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,0.061309
7,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.062178
8,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,0.065095
9,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,0.067649
10,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.068152
11,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.068492
12,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.068837
13,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,0.071364
14,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,0.074070
15,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,0.074150
16,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.075092
17,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.075277
18,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,0.076928
19,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,0.078521
20,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,0.080303
21,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.081412
22,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.081628
23,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.085688
24,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.085934
25,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,0.087770
26,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,0.089172
27,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,0.089443
28,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.089539
29,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.090133
30,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.090168
31,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,0.090588
32,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,0.090630
33,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.090960
34,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,0.092191
35,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.097058
36,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.099953
37,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.103255
38,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,0.119347
39,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,0.145645
40,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.149406
41,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.155662
42,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.164641
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.211529
44,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,0.233142
45,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,0.258121
46,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.304877
47,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.328502
48,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.344468
49,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,0.352225
50,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.355642
51,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.358730
52,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,0.536384

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_pandas_seconds
0,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,2.068496
1,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,2.069021
2,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,2.086920
3,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,2.111866
4,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,2.117035
5,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,2.126383
6,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,2.143273
7,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,2.150761
8,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,2.155096
9,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,2.156264
10,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,2.157476
11,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,2.158367
12,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,2.162555
13,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,2.185188
14,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,2.252767
15,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,2.295366
16,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,2.310737
17,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,2.317377
18,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,2.321854
19,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,2.364362
20,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,2.389288
21,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,2.410965
22,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,2.414823
23,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,2.419912
24,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,2.481452
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,2.497151
26,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,2.502459
27,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,2.594047
28,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,2.599806
29,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,2.710402
30,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,2.756285
31,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,2.920474
32,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,3.226381
33,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,3.328890
34,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,3.379374
35,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,3.404619
36,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,3.534181
37,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,3.709300
38,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,3.735163
39,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,3.981980
40,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,4.005578
41,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,4.253906
42,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,4.321507
43,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,4.384282
44,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,4.393550
45,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,4.466859
46,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,4.933718
47,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,5.443431
48,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,5.558602
49,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,5.688737
50,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,5.822155
51,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,6.842711
52,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,8.903364

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_polars_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.450646
1,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.459607
2,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.460579
3,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,0.466328
4,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.466874
5,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.470777
6,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.476298
7,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,0.481997
8,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.482777
9,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.483583
10,csv,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.496640
11,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,0.505853
12,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.506174
13,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.507359
14,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,0.508859
15,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.511853
16,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,0.515636
17,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,0.523552
18,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.543734
19,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.544344
20,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,0.548337
21,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,0.549224
22,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,0.572802
23,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,0.588109
24,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,0.596053
25,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,0.630006
26,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.634905
27,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.658748
28,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,0.659083
29,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.663780
30,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,0.688937
31,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,0.689733
32,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,0.701233
33,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.736094
34,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.797163
35,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.802114
36,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,0.815949
37,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.862862
38,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.893444
39,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.896909
40,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.921715
41,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,1.029172
42,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,1.079245
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,1.144325
44,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,1.338042
45,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,1.451908
46,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,1.462724
47,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,1.510888
48,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,1.544476
49,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,1.646886
50,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,1.705417
51,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,1.869724
52,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,2.212631

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_duckdb_seconds
0,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,3.285292
1,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,3.594456
2,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,4.237417
3,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,9.107234
4,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,9.305867
5,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,9.387503
6,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,9.528923
7,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,9.552460
8,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,9.572599
9,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,9.602663
10,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,9.850003
11,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,9.906787
12,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,9.962906
13,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,9.969575
14,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,10.099406
15,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,10.282482
16,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,10.303500
17,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,10.323153
18,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,10.348733
19,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,10.391632
20,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,10.421291
21,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,10.788641
22,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,10.860894
23,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,11.189073
24,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,11.566980
25,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,11.667055
26,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,11.733306
27,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,12.022990
28,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,12.659947
29,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,13.602092
30,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,13.723165
31,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,13.766659
32,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,14.022108
33,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,14.205708
34,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,14.232566
35,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,14.293079
36,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,14.581394
37,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,15.070528
38,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,15.141552
39,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,15.756632
40,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,16.771762
41,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,17.261537
42,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,17.445712
43,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,19.524039
44,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,21.596404
45,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,21.718529
46,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,22.578155
47,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,24.085375
48,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,24.754321
49,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,25.388939
50,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,25.567625
51,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,36.837714
52,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,37.671142

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.421920
1,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.453116
2,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.461030
3,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.465839
4,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.467186
5,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.478672
6,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,0.487874
7,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.488623
8,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,0.490637
9,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,0.491062
10,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.493485
11,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.496890
12,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.499842
13,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,0.500277
14,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.502207
15,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,0.505335
16,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.508849
17,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,0.509486
18,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.517817
19,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,0.519777
20,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.521243
21,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,0.527172
22,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,0.531133
23,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,0.542662
24,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,0.543071
25,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,0.548484
26,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.563131
27,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,0.568075
28,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,0.571045
29,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.571089
30,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,0.574969
31,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.585583
32,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,0.588632
33,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.592101
34,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.598866
35,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.618460
36,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.653648
37,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.654633
38,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,0.690841
39,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.701162
40,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.748335
41,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.751010
42,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.769225
43,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.880524
44,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,1.010463
45,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,1.052686
46,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,1.151448
47,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,1.196930
48,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,1.205137
49,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,1.270681
50,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,1.345003
51,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,1.383846
52,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,1.411530

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_polars_seconds
0,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,1.835762
1,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,1.914749
2,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,1.916424
3,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,1.916629
4,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,1.951312
5,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,1.965067
6,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,1.965723
7,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,2.066553
8,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,2.104798
9,csv,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,2.110350
10,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,2.117955
11,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,2.130288
12,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,2.135119
13,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,2.145743
14,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,2.168447
15,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,2.176932
16,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,2.179515
17,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,2.222237
18,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,2.225871
19,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,2.232287
20,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,2.235696
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,2.243550
22,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,2.254405
23,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,2.254815
24,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,2.258394
25,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,2.267195
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,2.310581
27,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,2.356656
28,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,2.389331
29,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,2.442789
30,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,2.445297
31,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,2.476689
32,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,2.504260
33,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,2.540311
34,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,2.571500
35,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,2.601538
36,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,2.683827
37,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,2.718911
38,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,2.774699
39,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,2.883438
40,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,3.539412
41,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,3.677016
42,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,3.778609
43,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,4.250181
44,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,4.261347
45,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,4.322725
46,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,4.750237
47,csv,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,4.836412
48,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,5.020040
49,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,6.247831
50,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,6.260561
51,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,7.324557
52,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,8.178485

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,31.43,0.113430
1,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,31.21,0.137403
2,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,61.68,0.140360
3,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,127.71,0.140741
4,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,63.70,0.142895
5,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,63.64,0.144650
6,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,63.69,0.145004
7,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,31.46,0.147645
8,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,63.70,0.147826
9,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,63.71,0.148341
10,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,63.69,0.158680
11,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,15.69,0.159408
12,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,63.73,0.161141
13,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.76,0.165347
14,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,63.49,0.172420
15,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,63.65,0.177192
16,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,31.19,0.179042
17,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.73,0.179130
18,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,63.31,0.180224
19,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,15.69,0.183698
20,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,63.17,0.184264
21,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,63.70,0.186022
22,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.68,0.186129
23,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,63.69,0.186529
24,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,63.72,0.188754
25,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,23.69,0.191223
26,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,63.68,0.195565
27,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,31.61,0.195624
28,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,63.21,0.196289
29,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.69,0.198928
30,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.67,0.205268
31,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.67,0.216630
32,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,63.61,0.224173
33,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,15.31,0.231366
34,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,63.68,0.233836
35,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,63.67,0.235709
36,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,63.67,0.243107
37,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,63.73,0.263333
38,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,15.17,0.341499
39,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,31.28,0.350482
40,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.72,0.362893
41,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.78,0.369914
42,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,15.63,0.386797
43,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,63.82,0.592204
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,63.69,0.604427
45,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.89,0.665525
46,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.89,0.707010
47,parquet,IdeaPadS340,Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz,19.78,0.726991
48,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.81,0.741153
49,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,15.69,0.844055
50,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.81,0.986644
51,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,63.82,1.063147
52,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.88,1.321530

====================
Platform: WSL2
====================
Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.176201
1,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.204102
2,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.214854
3,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.228661
4,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.230018
5,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.249063
6,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.250272
7,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.252775
8,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.252882
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.255371
10,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.258756
11,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.261258
12,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.263911
13,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.267274
14,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.267586
15,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.269462
16,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.269707
17,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.270244
18,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.270451
19,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.271845
20,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.276595
21,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.276940
22,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.284936
23,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.287715
24,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.289995
25,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.291865
26,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.296844
27,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.304917
28,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.307013
29,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.315864
30,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.316038
31,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.320730
32,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.324401
33,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.359498
34,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.367142
35,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.379735
36,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.387605
37,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.397570
38,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.409041
39,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.415871
40,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.436930
41,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.583145

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_polars_seconds
0,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.088689
1,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.105725
2,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.105863
3,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.114818
4,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.116799
5,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.120097
6,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.133921
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.134381
8,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.140347
9,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.140502
10,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.141459
11,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.142032
12,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.147632
13,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.149425
14,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.149898
15,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.154450
16,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.157515
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.160666
18,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.161578
19,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.163005
20,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.163870
21,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.165737
22,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.167133
23,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.168699
24,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.174320
25,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.180044
26,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.183723
27,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.186667
28,csv,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.208076
29,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.226329
30,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.247205
31,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.253067
32,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.280271
33,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.284965
34,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.292222
35,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.294835
36,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.312607
37,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.330961
38,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.345873
39,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.433407
40,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.445868
41,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.690226

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_duckdb_seconds
0,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.031109
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.032623
2,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.036465
3,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.036922
4,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.037994
5,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.038249
6,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.038939
7,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.039224
8,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.039974
9,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.040564
10,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.041450
11,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.041783
12,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.041816
13,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.042528
14,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.043016
15,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.043635
16,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.044396
17,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.045527
18,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.046914
19,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.047970
20,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.049256
21,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.049430
22,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.049433
23,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.049567
24,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.049785
25,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.049786
26,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.051320
27,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.052844
28,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.054384
29,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.055306
30,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.057080
31,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.057115
32,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.065795
33,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.066855
34,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.068845
35,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.082814
36,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.088993
37,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.095555
38,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.115737
39,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.119977
40,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.139353
41,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.904467

Ranking by: filter_group_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_fireducks_seconds
0,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.001394
1,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.001396
2,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.001469
3,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.001473
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.001484
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.001497
6,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.001519
7,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.001537
8,csv,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.001589
9,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.001598
10,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.001639
11,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.001644
12,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.001646
13,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.001698
14,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.001724
15,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.001743
16,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.001753
17,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.001831
18,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.001840
19,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.001853
20,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.001858
21,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.001875
22,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.001937
23,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.001940
24,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.001956
25,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.001970
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.001995
27,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.001997
28,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.001999
29,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.002052
30,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.002106
31,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.002165
32,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.002197
33,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.002401
34,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.002453
35,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.002453
36,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.002678
37,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.002809
38,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.003122
39,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.003159
40,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.003213
41,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.003474

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.148611
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.160063
2,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.163560
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.168088
4,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.170981
5,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.171951
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.180947
7,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.182844
8,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.184407
9,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.187811
10,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.188091
11,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.189353
12,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.191251
13,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.195378
14,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.196042
15,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.197287
16,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.199262
17,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.201684
18,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.204514
19,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.207530
20,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.212758
21,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.213067
22,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.213415
23,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.215324
24,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.217047
25,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.218891
26,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.226260
27,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.227811
28,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.232281
29,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.233132
30,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.247730
31,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.251238
32,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.255541
33,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.265091
34,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.268450
35,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.270173
36,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.291042
37,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.339472
38,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.362990
39,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.375648
40,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.377876
41,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.502419

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.057959
1,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.075282
2,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.078411
3,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.090949
4,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.094251
5,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.094802
6,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.097667
7,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.101301
8,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.101981
9,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.103395
10,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.104290
11,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.107975
12,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.109380
13,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.110336
14,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.111178
15,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.112284
16,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.113239
17,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.114769
18,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.117172
19,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.118002
20,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.119723
21,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.128306
22,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.131684
23,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.134709
24,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.135417
25,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.137581
26,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.143918
27,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.154213
28,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.169353
29,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.175646
30,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.198276
31,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.201458
32,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.205776
33,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.216131
34,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.225668
35,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.228700
36,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.303131
37,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.307027
38,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.330587
39,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.339904
40,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.365672
41,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.373520

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.038060
1,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.045760
2,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.049280
3,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.051478
4,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.051746
5,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.052067
6,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.052469
7,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.054279
8,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.054510
9,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.055085
10,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.056900
11,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.057525
12,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.057667
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.058118
14,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.059679
15,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.059971
16,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.061115
17,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.061271
18,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.062075
19,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.062213
20,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.066727
21,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.067213
22,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.068737
23,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.070130
24,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.072261
25,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.073599
26,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.073689
27,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.074120
28,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.078281
29,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.079261
30,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.079484
31,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.096849
32,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.101829
33,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.110594
34,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.118487
35,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.143583
36,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.170942
37,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.195986
38,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.252801
39,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.253880
40,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.382476
41,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.625383

Ranking by: statistics_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.000140
1,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.000145
2,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.000148
3,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.000148
4,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.000152
5,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.000155
6,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.000165
7,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.000171
8,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.000187
9,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.000188
10,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.000193
11,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.000195
12,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.000197
13,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.000204
14,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.000206
15,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.000211
16,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.000213
17,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.000215
18,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.000216
19,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.000217
20,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.000220
21,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.000222
22,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.000224
23,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.000227
24,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.000227
25,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.000235
26,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.000235
27,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.000258
28,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.000271
29,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.000283
30,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.000284
31,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.000289
32,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.000291
33,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.000312
34,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.000321
35,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.000333
36,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.000381
37,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.000420
38,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.000469
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.000490
40,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.000549
41,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.000564

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_pandas_seconds
0,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,1.600232
1,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,1.614699
2,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,1.668676
3,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,1.702642
4,csv,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,1.703667
5,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,1.738139
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,1.740872
7,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,1.741788
8,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,1.812609
9,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,1.826722
10,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,1.831775
11,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,1.859085
12,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,1.893809
13,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,1.912097
14,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,2.032971
15,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,2.034020
16,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,2.056388
17,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,2.082020
18,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,2.146466
19,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,2.156918
20,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,2.159110
21,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,2.192101
22,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,2.200266
23,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,2.207379
24,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,2.212902
25,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,2.221370
26,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,2.277500
27,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,2.291780
28,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,2.310993
29,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,2.313880
30,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,2.335720
31,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,2.436286
32,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,2.436749
33,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,2.599715
34,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,2.731822
35,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,2.744304
36,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,2.745317
37,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,3.039260
38,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,3.101532
39,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,3.233583
40,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,3.637755
41,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,4.435003

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_polars_seconds
0,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.408910
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.440721
2,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.503293
3,csv,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.511116
4,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.511848
5,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.513071
6,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.526179
7,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.529869
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.541118
9,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.566642
10,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.568130
11,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.575433
12,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.577800
13,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.596546
14,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.599055
15,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.633127
16,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.653290
17,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.669629
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.680029
19,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.681872
20,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.682576
21,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.685736
22,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.688653
23,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.703326
24,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.706446
25,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.713558
26,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.731640
27,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.738676
28,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.752159
29,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.775720
30,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.857206
31,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.891508
32,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.982904
33,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.985538
34,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.988101
35,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.997258
36,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,1.008530
37,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,1.344523
38,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,1.401137
39,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,1.424004
40,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,1.555928
41,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,2.232569

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_duckdb_seconds
0,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,9.849744
1,csv,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,10.099078
2,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,10.311187
3,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,10.433864
4,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,10.585936
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,10.624296
6,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,10.729680
7,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,10.989343
8,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,11.271776
9,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,11.385188
10,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,11.499978
11,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,11.663811
12,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,12.110937
13,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,12.164969
14,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,12.292970
15,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,12.345718
16,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,12.379231
17,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,12.501459
18,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,12.777906
19,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,12.812437
20,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,12.963672
21,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,13.110190
22,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,13.504328
23,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,13.521331
24,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,13.971501
25,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,14.325541
26,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,14.327818
27,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,15.683895
28,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,15.984706
29,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,17.248082
30,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,17.334267
31,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,17.644917
32,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,18.121879
33,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,18.515142
34,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,21.686513
35,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,21.775294
36,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,22.964619
37,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,23.239070
38,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,25.211426
39,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,26.225853
40,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,27.868051
41,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,43.052157

Ranking by: complex_join_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.000384
1,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.000400
2,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.000409
3,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.000427
4,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.000435
5,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.000449
6,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.000456
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.000457
8,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.000471
9,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.000499
10,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.000505
11,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.000508
12,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.000517
13,csv,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.000524
14,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.000538
15,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.000544
16,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.000551
17,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.000554
18,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.000562
19,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.000573
20,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.000578
21,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.000581
22,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.000588
23,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.000611
24,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.000614
25,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.000644
26,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.000653
27,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.000665
28,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.000680
29,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.000684
30,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.000706
31,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.000710
32,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.000720
33,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.000744
34,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.000767
35,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.000854
36,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.000859
37,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.001124
38,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.001193
39,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.001273
40,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.001411
41,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.001499

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_pandas_seconds
0,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.311347
1,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.322537
2,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.328151
3,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.328552
4,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.345379
5,csv,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.349165
6,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.349745
7,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.351937
8,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.357184
9,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.358497
10,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.361539
11,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.368509
12,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.386752
13,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.390826
14,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.392796
15,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.400673
16,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.402182
17,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.403657
18,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.403801
19,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.408165
20,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.410205
21,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.410970
22,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.413858
23,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.414082
24,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.418780
25,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.420687
26,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.427611
27,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.435340
28,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.436658
29,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.438297
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.455722
31,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.467426
32,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.503815
33,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.508894
34,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.520747
35,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.531754
36,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.539807
37,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.544602
38,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.557196
39,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.561544
40,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.665118
41,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.851114

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_polars_seconds
0,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,1.697160
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,1.836724
2,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,1.879104
3,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,1.899370
4,csv,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,1.951676
5,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,1.967703
6,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,1.968246
7,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,1.970017
8,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,1.978925
9,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,1.980122
10,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,2.019306
11,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,2.031511
12,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,2.036167
13,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,2.044196
14,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,2.049551
15,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,2.080549
16,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,2.099917
17,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,2.152715
18,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,2.155240
19,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,2.173161
20,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,2.179002
21,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,2.180967
22,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,2.183050
23,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,2.224582
24,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,2.261237
25,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,2.309980
26,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,2.401860
27,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,2.500225
28,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,2.505193
29,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,2.646084
30,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,2.670815
31,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,2.775093
32,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,2.793840
33,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,3.140785
34,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,3.202793
35,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,3.243892
36,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,3.607012
37,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,3.878324
38,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,4.214237
39,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,4.268188
40,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,4.303385
41,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,6.761818

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.098952
1,parquet,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.110413
2,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.111596
3,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.113817
4,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.118026
5,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.126166
6,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.134601
7,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.140363
8,parquet,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.141526
9,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.141836
10,parquet,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.145966
11,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.147814
12,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.151960
13,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.152020
14,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.152933
15,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.158153
16,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.170429
17,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.170503
18,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.171355
19,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.173158
20,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.173654
21,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.175907
22,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.185553
23,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.205499
24,parquet,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.205787
25,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.210747
26,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.213198
27,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.230046
28,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.231959
29,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.232552
30,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.239510
31,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.268142
32,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.274185
33,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.374270
34,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.395654
35,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.473878
36,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.501223
37,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.579472
38,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.626180
39,parquet,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.679273
40,parquet,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.709106
41,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,1.461500

Ranking by: timeseries_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_fireducks_seconds
0,parquet,HP-Z2-G9,12th Gen Intel(R) Core(TM) i9-12900,62.66,0.273113
1,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,31.20,0.301512
2,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,31.19,0.306496
3,csv,ROG-Strix-G16,AMD Ryzen 9 9955HX 16-Core Processor,30.20,0.315209
4,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,31.19,0.325419
5,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,30.93,0.341617
6,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,15.34,0.343629
7,csv,VivoBookPro,13th Gen Intel(R) Core(TM) i9-13980HX,31.16,0.360655
8,csv,HP-ProMini400,Intel(R) Core(TM) i5-14500T,23.47,0.362770
9,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,31.21,0.362805
10,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,31.19,0.367393
11,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,15.50,0.373307
12,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,31.19,0.377237
13,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,15.46,0.380441
14,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,31.09,0.383600
15,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,23.47,0.389028
16,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,15.35,0.389086
17,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,31.21,0.391479
18,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,31.19,0.392499
19,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.18,0.404732
20,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,31.15,0.408584
21,csv,Legion7-16ARX8H,AMD Ryzen 9 7945HX with Radeon Graphics,15.21,0.416866
22,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,11.44,0.418874
23,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,31.18,0.421252
24,parquet,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,30.95,0.424503
25,csv,ROG-Strix-G17,AMD Ryzen 9 7945HX with Radeon Graphics,15.22,0.425058
26,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,31.17,0.432044
27,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,15.01,0.440635
28,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,15.46,0.451836
29,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,31.21,0.462007
30,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,31.20,0.464249
31,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,31.00,0.464570
32,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,31.18,0.467681
33,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.45,0.537955
34,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,15.49,0.542455
35,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,31.19,0.546467
36,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,15.26,0.583606
37,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,15.52,0.585731
38,csv,WL1030,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,31.25,0.651473
39,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,15.57,0.695851
40,csv,HP-EB-G6-SJ,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,31.25,0.942361
41,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,15.52,0.983110

====================
Platform: Linux
====================
Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_pandas_seconds
0,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.161334
1,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.178515
2,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.189167
3,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.189203
4,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.191695
5,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.200073
6,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.204257
7,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.204512
8,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.205159
9,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.205537
10,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.206417
11,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.206965
12,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.220117
13,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.225984
14,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.226379
15,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.226849
16,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.228742
17,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.230181
18,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.238439
19,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.239010
20,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.245038
21,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.249021
22,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.253416
23,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.298231
24,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.305297
25,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.310985
26,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.335269
27,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.341882
28,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.343580
29,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.374583
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.447669

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_polars_seconds
0,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.076315
1,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.081248
2,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.082303
3,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.084799
4,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.085730
5,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.085799
6,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.086587
7,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.089377
8,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.089495
9,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.090282
10,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.093371
11,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.095369
12,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.101135
13,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.103200
14,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.112257
15,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.112919
16,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.121813
17,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.131677
18,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.132462
19,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.132514
20,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.136461
21,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.139682
22,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.144622
23,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.152007
24,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.158360
25,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.161183
26,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.250173
27,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.267565
28,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.431944
29,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.432383
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.614996

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.026820
1,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.028233
2,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.028719
3,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.029495
4,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.030477
5,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.030484
6,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.030600
7,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.031740
8,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.032152
9,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.032236
10,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.032342
11,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.032669
12,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.032795
13,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.033185
14,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.033227
15,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.033619
16,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.034329
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.034566
18,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.035646
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.035930
20,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.036168
21,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.037508
22,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.038045
23,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.042002
24,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.043937
25,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.055523
26,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.069039
27,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.072746
28,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.116693
29,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.122297
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.156793

Ranking by: filter_group_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,filter_group_fireducks_seconds
0,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.001211
1,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.001269
2,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.001273
3,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.001346
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.001347
5,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.001348
6,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.001384
7,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.001393
8,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.001393
9,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.001407
10,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.001422
11,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.001423
12,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.001445
13,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.001453
14,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.001456
15,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.001486
16,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.001510
17,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.001575
18,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.001595
19,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.001606
20,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.001631
21,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.001639
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.001654
23,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.001712
24,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.001991
25,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.002012
26,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.002117
27,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.002427
28,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.002445
29,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.002685
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.003029

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_pandas_seconds
0,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.158388
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.161277
2,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.166625
3,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.174536
4,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.178267
5,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.180868
6,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.182168
7,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.184661
8,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.187116
9,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.192739
10,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.199154
11,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.208524
12,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.210814
13,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.211416
14,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.215204
15,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.217734
16,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.220628
17,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.221441
18,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.223908
19,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.224155
20,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.225383
21,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.227073
22,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.246312
23,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.277282
24,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.320864
25,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.325768
26,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.334646
27,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.355977
28,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.359289
29,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.371494
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.465929

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.054323
1,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.063687
2,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.068017
3,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.071838
4,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.075363
5,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.076348
6,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.083366
7,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.088038
8,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.089034
9,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.090632
10,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.090955
11,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.091560
12,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.095397
13,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.095517
14,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.104672
15,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.123976
16,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.124513
17,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.133953
18,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.142213
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.143676
20,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.148805
21,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.161809
22,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.171966
23,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.190132
24,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.203138
25,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.206492
26,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.322771
27,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.349359
28,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.392614
29,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.418672
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.480064

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.036783
1,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.039666
2,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.044687
3,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.045018
4,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.049224
5,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.050027
6,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.051173
7,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.051412
8,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.051679
9,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.052661
10,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.053194
11,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.054491
12,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.055872
13,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.056093
14,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.056630
15,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.057358
16,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.058070
17,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.059486
18,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.059655
19,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.059968
20,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.062714
21,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.065039
22,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.065852
23,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.067360
24,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.080198
25,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.082534
26,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.116613
27,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.155957
28,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.329382
29,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.332450
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.447324

Ranking by: statistics_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,statistics_fireducks_seconds
0,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.000125
1,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.000131
2,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.000136
3,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.000140
4,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.000142
5,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.000156
6,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.000156
7,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.000157
8,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.000166
9,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.000168
10,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.000176
11,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.000176
12,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.000180
13,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.000181
14,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.000182
15,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.000183
16,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.000187
17,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.000188
18,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.000191
19,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.000191
20,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.000194
21,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.000194
22,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.000209
23,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.000218
24,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.000221
25,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.000223
26,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.000338
27,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.000347
28,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.000368
29,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.000390
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.000484

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_pandas_seconds
0,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,1.294415
1,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,1.377735
2,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,1.379487
3,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,1.403472
4,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,1.407236
5,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,1.415272
6,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,1.421409
7,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,1.425085
8,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,1.498394
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,1.564431
10,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,1.565279
11,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,1.573029
12,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,1.683118
13,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,1.691183
14,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,1.693742
15,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,1.750485
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,1.756985
17,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,1.788894
18,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,1.858019
19,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,1.980257
20,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,2.068671
21,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,2.115950
22,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,2.189990
23,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,2.205681
24,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,2.309064
25,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,2.318065
26,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,2.371793
27,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,2.501646
28,csv,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,2.536141
29,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,2.570981
30,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,2.862606

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_polars_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.351187
1,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.352712
2,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.382982
3,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.388581
4,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.392026
5,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.403157
6,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.409692
7,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.409842
8,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.410883
9,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.427306
10,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.431141
11,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.433622
12,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.441096
13,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.442042
14,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.466258
15,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.482611
16,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.484981
17,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.486167
18,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.489516
19,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.539736
20,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.549700
21,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.558314
22,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.607961
23,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.631154
24,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.646625
25,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.832765
26,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.875540
27,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,1.100433
28,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,1.530371
29,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,1.603825
30,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,1.794887

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_duckdb_seconds
0,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,7.732954
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,8.127482
2,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,8.517030
3,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,8.574022
4,csv,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,8.593845
5,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,8.651267
6,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,8.929135
7,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,9.243219
8,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,9.315462
9,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,9.330056
10,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,9.526837
11,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,9.712315
12,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,9.728686
13,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,9.753387
14,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,10.004580
15,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,10.254478
16,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,10.605488
17,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,10.664287
18,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,10.901250
19,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,11.082227
20,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,11.268036
21,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,11.664028
22,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,11.701880
23,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,11.788498
24,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,13.477096
25,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,14.920127
26,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,15.385397
27,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,19.118766
28,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,26.185457
29,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,27.339530
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,31.624210

Ranking by: complex_join_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,complex_join_fireducks_seconds
0,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.000375
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.000377
2,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.000385
3,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.000409
4,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.000410
5,parquet,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.000425
6,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.000429
7,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.000439
8,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.000443
9,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.000447
10,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.000456
11,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.000476
12,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.000478
13,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.000484
14,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.000507
15,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.000509
16,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.000514
17,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.000518
18,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.000518
19,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.000520
20,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.000549
21,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.000549
22,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.000558
23,parquet,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.000593
24,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.000609
25,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.000610
26,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.000924
27,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.000936
28,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.000962
29,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.001064
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.001163

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_pandas_seconds
0,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.300144
1,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.300633
2,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.306460
3,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.325612
4,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.325803
5,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.328195
6,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.331649
7,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.332970
8,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.334269
9,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.337438
10,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.343386
11,csv,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.364259
12,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.367771
13,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.369769
14,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.372943
15,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.387767
16,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.390335
17,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.392871
18,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.395478
19,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.395914
20,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.406380
21,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.414989
22,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.447061
23,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.496995
24,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.544533
25,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.554725
26,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.574874
27,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.576736
28,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.579211
29,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.614184
30,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.693135

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_polars_seconds
0,csv,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,1.820332
1,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,1.848274
2,csv,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,1.891680
3,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,1.910617
4,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,1.919128
5,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,1.945292
6,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,1.974526
7,csv,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,2.052332
8,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,2.061647
9,csv,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,2.176913
10,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,2.205589
11,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,2.216032
12,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,2.227703
13,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,2.228500
14,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,2.251292
15,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,2.312265
16,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,2.346289
17,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,2.365781
18,csv,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,2.416930
19,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,2.450257
20,csv,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,2.460190
21,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,2.493247
22,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,2.518807
23,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,2.541366
24,csv,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,2.826967
25,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,3.630264
26,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,3.865680
27,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,3.966252
28,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,4.260854
29,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,4.347602
30,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,4.928691

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_duckdb_seconds
0,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.104968
1,parquet,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.111030
2,parquet,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.115453
3,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.144755
4,parquet,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.146148
5,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.148428
6,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.149619
7,parquet,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.150845
8,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.150902
9,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.163267
10,parquet,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.165733
11,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.166123
12,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.167849
13,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.169566
14,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.174492
15,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.175164
16,parquet,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.183436
17,parquet,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.184204
18,parquet,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.185991
19,parquet,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.186161
20,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.188238
21,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.188773
22,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.203027
23,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.204379
24,parquet,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.214164
25,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.225218
26,parquet,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.324323
27,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.461786
28,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.899609
29,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,1.043566
30,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,1.187024

Ranking by: timeseries_fireducks_seconds

,dataset_format,hostname,cpu_brand,memory_total_gb,timeseries_fireducks_seconds
0,parquet,OptPlexMicro-7020,Intel(R) Core(TM) i5-14600,62.49,0.255466
1,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,30.78,0.258856
2,csv,OptPlex-7010-2,13th Gen Intel(R) Core(TM) i5-13500,62.49,0.261453
3,parquet,OptPlex-7020,Intel(R) Core(TM) i5-14500,62.49,0.264686
4,csv,LnvThkCtr-01,12th Gen Intel(R) Core(TM) i7-12700T,62.48,0.268342
5,csv,Precision-7670,12th Gen Intel(R) Core(TM) i9-12950HX,31.03,0.268788
6,csv,MSI-VectorA16HX,AMD Ryzen 9 8940HX with Radeon Graphics,61.97,0.271301
7,parquet,OptPlex-7010-1,13th Gen Intel(R) Core(TM) i9-13900,62.49,0.275695
8,parquet,ZBookPowerG9,12th Gen Intel(R) Core(TM) i7-12700H,62.44,0.275730
9,csv,Precision-7770,12th Gen Intel(R) Core(TM) i7-12850HX,31.10,0.277108
10,parquet,DELL-XPS-9520,12th Gen Intel(R) Core(TM) i7-12700H,62.47,0.287679
11,csv,ECT1250-AMZN,Intel(R) Core(TM) Ultra 7 265,30.80,0.291786
12,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,30.96,0.294471
13,csv,ThinkBook,Intel(R) Core(TM) Ultra 7 255H,62.29,0.295955
14,csv,Legion5-15AHP10,AMD Ryzen 7 260 w/ Radeon 780M Graphics,62.11,0.303971
15,parquet,ZBookFuryG9,12th Gen Intel(R) Core(TM) i7-12850HX,62.40,0.307217
16,csv,LnvTCi5-12400,12th Gen Intel(R) Core(TM) i5-12400,62.52,0.307695
17,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,62.47,0.310010
18,parquet,ZBookFuryG8,11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz,62.47,0.312615
19,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,62.50,0.312878
20,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,31.01,0.330067
21,csv,ZBookStudioG8-UB,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.334185
22,parquet,ZBookStudioG8,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.06,0.336106
23,parquet,ThinkPadE16G2,AMD Ryzen 7 7735HS with Radeon Graphics,30.12,0.352359
24,csv,Legion5-15IRX10,Intel(R) Core(TM) i7-14700HX,15.34,0.362512
25,csv,ZBookFuryG8-17,11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz,31.02,0.425627
26,csv,DELL-XPS15-9530,13th Gen Intel(R) Core(TM) i9-13900H,31.02,0.440394
27,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.501116
28,parquet,E32-PC,Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz,31.24,0.533345
29,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.592294
30,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,15.50,0.667169

In [8]:
# Average performance per library, split by platform (avoid cross-platform comparisons)
library_suffixes = ['pandas', 'polars', 'duckdb', 'fireducks']  # fireducks may be missing on some platforms

# Stable preferred platform order
preferred_system_order = ["Windows", "WSL2", "Linux"]
systems_present = [s for s in preferred_system_order if s in set(b_df['system'].dropna().unique())]

# Host identifier excluding platform, including memory for fairness
b_df['host_cpu_mem'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['memory_total_gb'].astype(str) + 'GB'
 )

with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    for system in systems_present:
        print(f"\n====================\nPlatform: {system}\n====================")
        df_sys = b_df[b_df['system'] == system].copy()

        # Compute per-row average for each library (NaN/zero-safe)
        computed_avg_cols = []
        for lib in library_suffixes:
            lib_cols = [col for col in df_sys.columns if col.endswith(f'_{lib}_seconds')]
            if not lib_cols:
                continue
            numeric = df_sys[lib_cols].apply(pd.to_numeric, errors='coerce')
            numeric = numeric.mask(numeric <= 0)
            avg_col = f'{lib}_avg_time'
            df_sys[avg_col] = numeric.mean(axis=1, skipna=True)
            # Skip libs with no valid timings for this platform (e.g., FireDucks on Windows)
            if df_sys[avg_col].notna().any():
                computed_avg_cols.append(avg_col)
            else:
                df_sys.drop(columns=[avg_col], inplace=True)

        if not computed_avg_cols:
            print("No valid library timing data available for this platform.")
            continue

        # Aggregate per host+cpu+mem
        host_lib_avg = df_sys.groupby('host_cpu_mem')[computed_avg_cols].mean().reset_index()

        # Display per-library rankings within platform
        for avg_col in computed_avg_cols:
            lib = avg_col.replace('_avg_time', '')
            print(f"Ranking by average {lib} time (ascending):")
            display(host_lib_avg[['host_cpu_mem', avg_col]].sort_values(avg_col, na_position='last').reset_index(drop=True))
            print("\n")

====================
Platform: Windows
====================
Ranking by average pandas time (ascending):

,host_cpu_mem,pandas_avg_time
0,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | 63.64GB,1.246065
1,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 31.69GB,1.277228
2,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.73GB,1.302471
3,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 63.69GB,1.315110
4,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 63.69GB,1.332079
5,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 63.69GB,1.352743
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 31.68GB,1.357804
7,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 15.69GB,1.370140
8,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.76GB,1.380589
9,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | 63.68GB,1.382587
10,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 63.72GB,1.388029
11,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 63.65GB,1.393152
12,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 31.21GB,1.404302
13,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 63.17GB,1.421150
14,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 15.69GB,1.430300
15,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 63.67GB,1.472742
16,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 63.68GB,1.491034
17,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 15.17GB,1.502454
18,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 61.68GB,1.575672
19,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 63.61GB,1.598271
20,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 63.71GB,1.615348
21,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 63.73GB,1.620455
22,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.67GB,1.663958
23,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 31.46GB,1.678807
24,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 15.31GB,1.696537
25,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 31.19GB,1.706588
26,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 31.61GB,1.710795
27,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 23.69GB,1.732686
28,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 63.21GB,1.763706
29,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 30.78GB,1.791679
30,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 63.7GB,1.813134
31,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 63.49GB,1.832165
32,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 63.73GB,1.932938
33,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.72GB,1.985968
34,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 63.31GB,2.079153
35,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.63GB,2.144046
36,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.67GB,2.251039
37,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 63.67GB,2.404644
38,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 15.89GB,2.419895
39,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 31.43GB,2.424514
40,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 63.7GB,2.492094
41,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 63.82GB,2.506687
42,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 63.69GB,2.578181
43,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 31.89GB,2.630860
44,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.81GB,2.735169
45,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 31.28GB,2.905702
46,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.81GB,2.968245
47,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.88GB,3.109042
48,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | 127.71GB,3.110269
49,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | 19.78GB,3.131222
50,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | 15.69GB,3.681693
51,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 63.82GB,3.991704
52,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 63.7GB,5.444306

Ranking by average polars time (ascending):

,host_cpu_mem,polars_avg_time
0,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 61.68GB,0.671769
1,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 63.73GB,0.709344
2,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | 63.64GB,0.715861
3,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 63.69GB,0.739045
4,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 31.61GB,0.772193
5,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 31.19GB,0.783669
6,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 63.7GB,0.799042
7,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 63.69GB,0.800828
8,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.76GB,0.803636
9,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 31.68GB,0.805110
10,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 63.65GB,0.807932
11,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 31.69GB,0.810978
12,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 63.7GB,0.812354
13,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 63.17GB,0.825626
14,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | 63.68GB,0.831405
15,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 63.31GB,0.843877
16,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 31.46GB,0.851036
17,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 63.71GB,0.860127
18,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 63.61GB,0.866453
19,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 31.43GB,0.883038
20,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 63.68GB,0.886952
21,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | 127.71GB,0.901357
22,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 63.7GB,0.904037
23,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 63.69GB,0.907171
24,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 63.21GB,0.934359
25,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 63.67GB,0.942621
26,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 15.69GB,0.948404
27,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 31.21GB,0.954984
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.73GB,0.961613
29,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 63.72GB,0.974764
30,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 23.69GB,1.033573
31,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 15.69GB,1.056406
32,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.67GB,1.088293
33,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 63.67GB,1.089643
34,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 15.17GB,1.100012
35,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 30.78GB,1.150388
36,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 63.49GB,1.199851
37,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 63.73GB,1.205978
38,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 15.31GB,1.235530
39,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.67GB,1.291333
40,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.72GB,1.505774
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 31.28GB,1.523702
42,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.63GB,1.578317
43,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 63.69GB,1.889734
44,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 31.89GB,2.031972
45,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 15.89GB,2.049647
46,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.81GB,2.132537
47,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 63.82GB,2.245336
48,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | 19.78GB,2.273989
49,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.81GB,2.419061
50,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 63.82GB,2.429050
51,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | 15.69GB,3.323331
52,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.88GB,3.513165

Ranking by average duckdb time (ascending):

,host_cpu_mem,duckdb_avg_time
0,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 63.7GB,2.333418
1,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 61.68GB,2.555037
2,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 63.7GB,2.704064
3,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 63.69GB,2.733107
4,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 63.69GB,2.733142
5,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | 63.64GB,2.733367
6,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 63.73GB,2.796437
7,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 31.19GB,2.823045
8,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 63.65GB,2.848338
9,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 63.17GB,2.852833
10,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 63.21GB,2.886513
11,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.76GB,2.988898
12,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | 127.71GB,2.991300
13,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 63.68GB,3.028468
14,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 63.31GB,3.051821
15,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 63.7GB,3.059756
16,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 31.21GB,3.134389
17,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 31.68GB,3.163223
18,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 63.69GB,3.204554
19,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 63.71GB,3.224381
20,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 31.69GB,3.237597
21,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 63.72GB,3.340845
22,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 31.61GB,3.355343
23,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 31.46GB,3.511506
24,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 63.61GB,3.518031
25,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | 63.68GB,3.660292
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 63.67GB,3.731869
27,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 31.43GB,3.873748
28,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 63.73GB,4.055661
29,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 63.67GB,4.129771
30,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.67GB,4.135346
31,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.73GB,4.179913
32,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 30.78GB,4.262957
33,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 23.69GB,4.290595
34,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 15.69GB,4.343505
35,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 63.49GB,4.602622
36,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.67GB,4.709456
37,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 15.69GB,4.743003
38,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 15.17GB,4.897220
39,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 15.31GB,5.148900
40,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.72GB,5.212134
41,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 31.28GB,5.686984
42,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.63GB,6.429801
43,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 63.82GB,6.951640
44,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 31.89GB,7.181761
45,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 63.69GB,7.451571
46,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.81GB,8.051619
47,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 15.89GB,8.970996
48,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 63.82GB,9.097915
49,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | 19.78GB,9.858046
50,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | 15.69GB,11.993303
51,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.88GB,12.402753
52,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.81GB,16.960324

====================
Platform: WSL2
====================
Ranking by average pandas time (ascending):

,host_cpu_mem,pandas_avg_time
0,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 15.22GB,0.689159
1,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 31.19GB,0.694818
2,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 31.19GB,0.728984
3,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 30.93GB,0.729324
4,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 15.5GB,0.764467
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.46GB,0.779546
6,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,0.785434
7,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 23.47GB,0.789675
8,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | 31.16GB,0.801615
9,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 31.2GB,0.828231
10,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | 23.47GB,0.836894
11,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 15.35GB,0.839367
12,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 31.09GB,0.849066
13,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 31.19GB,0.853110
14,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 15.46GB,0.855019
15,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.15GB,0.858335
16,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 15.21GB,0.872365
17,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.18GB,0.882672
18,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 31.19GB,0.882848
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 11.44GB,0.883562
20,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 15.01GB,0.885016
21,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 31.17GB,0.894197
22,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 31.21GB,0.895126
23,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 15.34GB,0.906213
24,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 31.21GB,0.939625
25,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 30.2GB,0.961443
26,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 31.18GB,0.989179
27,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 30.95GB,0.992301
28,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 31.21GB,1.031235
29,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 31.19GB,1.076431
30,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 31.2GB,1.083468
31,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.45GB,1.098229
32,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 15.52GB,1.119797
33,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.49GB,1.127908
34,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 31.19GB,1.162392
35,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 31.0GB,1.174671
36,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 31.18GB,1.237555
37,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.25GB,1.292812
38,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 15.26GB,1.340711
39,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 15.57GB,1.351738
40,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.25GB,1.978228
41,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 15.52GB,2.045975

Ranking by average polars time (ascending):

,host_cpu_mem,polars_avg_time
0,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 31.19GB,0.655365
1,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 31.21GB,0.719946
2,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 31.19GB,0.742445
3,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 23.47GB,0.768205
4,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 31.19GB,0.770126
5,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 15.5GB,0.771945
6,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,0.784100
7,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 15.34GB,0.792830
8,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.46GB,0.797416
9,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 15.35GB,0.797536
10,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 31.19GB,0.804403
11,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 30.2GB,0.846254
12,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 30.95GB,0.852107
13,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 31.09GB,0.856685
14,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 31.17GB,0.861515
15,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.15GB,0.864040
16,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 31.2GB,0.869688
17,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 31.19GB,0.876530
18,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 15.46GB,0.878467
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 11.44GB,0.880961
20,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 30.93GB,0.887373
21,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 31.0GB,0.910013
22,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 31.21GB,0.922894
23,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 15.22GB,0.936078
24,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 31.18GB,0.950398
25,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | 23.47GB,0.972084
26,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 31.18GB,1.036350
27,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 31.21GB,1.069611
28,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.18GB,1.120586
29,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | 31.16GB,1.146548
30,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 31.19GB,1.154616
31,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 15.21GB,1.184756
32,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.45GB,1.236139
33,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.49GB,1.310720
34,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 15.01GB,1.317470
35,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 31.2GB,1.512683
36,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 15.26GB,1.694340
37,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 15.52GB,1.736730
38,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.25GB,1.880185
39,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.25GB,1.914736
40,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 15.57GB,1.925246
41,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 15.52GB,3.154671

Ranking by average duckdb time (ascending):

,host_cpu_mem,duckdb_avg_time
0,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 31.19GB,2.897648
1,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,3.000192
2,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 31.21GB,3.040607
3,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 31.2GB,3.155746
4,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 31.19GB,3.167542
5,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 31.19GB,3.258649
6,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 30.2GB,3.299193
7,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 15.5GB,3.370554
8,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.46GB,3.380206
9,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 31.19GB,3.550924
10,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 31.17GB,3.574105
11,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.15GB,3.578423
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 15.35GB,3.636347
13,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 23.47GB,3.655568
14,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 31.19GB,3.711097
15,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 31.21GB,3.727329
16,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 31.18GB,3.871603
17,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 31.09GB,3.883764
18,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 15.46GB,3.934346
19,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 11.44GB,3.992685
20,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 15.34GB,4.006463
21,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | 23.47GB,4.048998
22,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 31.18GB,4.065672
23,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | 31.16GB,4.192997
24,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 30.95GB,4.279586
25,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 31.21GB,4.330357
26,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 30.93GB,4.628309
27,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 15.22GB,4.759404
28,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.18GB,4.771396
29,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 31.0GB,4.885168
30,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 31.19GB,5.012837
31,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.45GB,5.087844
32,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.49GB,5.198686
33,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 15.21GB,6.473828
34,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 15.01GB,6.487310
35,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 31.2GB,6.655530
36,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 15.57GB,7.085057
37,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 15.52GB,7.171884
38,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.25GB,7.832607
39,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.25GB,7.991622
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 15.26GB,8.588737
41,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 15.52GB,13.486665

Ranking by average fireducks time (ascending):

,host_cpu_mem,fireducks_avg_time
0,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 15.46GB,0.115995
1,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 31.2GB,0.156754
2,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 31.19GB,0.158445
3,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,0.167420
4,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 31.19GB,0.175636
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 15.34GB,0.199306
6,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 11.44GB,0.202127
7,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 15.22GB,0.203477
8,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 31.19GB,0.217562
9,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 31.21GB,0.239988
10,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.46GB,0.255070
11,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 23.47GB,0.257453
12,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 15.5GB,0.259705
13,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 30.93GB,0.266084
14,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.49GB,0.271662
15,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 31.19GB,0.274761
16,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.15GB,0.278272
17,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 15.35GB,0.283810
18,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 31.17GB,0.286655
19,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 31.09GB,0.287031
20,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | 23.47GB,0.290111
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 31.2GB,0.313481
22,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 31.18GB,0.324049
23,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 31.21GB,0.334655
24,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.18GB,0.355650
25,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 15.01GB,0.355660
26,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 15.21GB,0.359409
27,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 31.19GB,0.363629
28,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.45GB,0.383598
29,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 15.52GB,0.396031
30,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.25GB,0.403118
31,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | 31.16GB,0.417301
32,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 30.2GB,0.493129
33,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 15.57GB,0.496764
34,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 31.21GB,0.515272
35,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 31.19GB,0.528912
36,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 30.95GB,0.565733
37,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 31.0GB,0.612096
38,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 15.52GB,0.695349
39,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 31.18GB,0.701282
40,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 15.26GB,0.780069
41,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.25GB,1.062613

====================
Platform: Linux
====================
Ranking by average pandas time (ascending):

,host_cpu_mem,pandas_avg_time
0,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 61.97GB,0.546683
1,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 62.49GB,0.585988
2,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 62.11GB,0.593089
3,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 62.48GB,0.608071
4,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 62.49GB,0.618312
5,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,0.622011
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 30.8GB,0.634074
7,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 62.44GB,0.637022
8,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 62.47GB,0.659222
9,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 62.47GB,0.671866
10,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 62.47GB,0.681442
11,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 30.12GB,0.689689
12,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 30.96GB,0.728179
13,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.01GB,0.743535
14,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 62.4GB,0.753551
15,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,0.754322
16,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 62.52GB,0.767604
17,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.34GB,0.787330
18,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 30.78GB,0.831400
19,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 62.49GB,0.859686
20,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 31.03GB,0.979842
21,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.1GB,0.992184
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 62.5GB,1.023193
23,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,1.024209
24,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 62.29GB,1.044855
25,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 31.24GB,1.081617
26,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,1.089557
27,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 31.02GB,1.095820
28,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,1.172261
29,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.02GB,1.239831
30,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,1.491011

Ranking by average polars time (ascending):

,host_cpu_mem,polars_avg_time
0,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 30.78GB,0.626101
1,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 62.49GB,0.650847
2,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 62.49GB,0.664109
3,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,0.668237
4,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 62.49GB,0.680239
5,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 30.96GB,0.687623
6,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 30.8GB,0.712760
7,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 62.44GB,0.717138
8,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 62.48GB,0.745924
9,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 62.47GB,0.751092
10,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 61.97GB,0.785599
11,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 62.11GB,0.797963
12,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 62.47GB,0.808769
13,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 62.5GB,0.809536
14,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 62.47GB,0.821663
15,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 62.4GB,0.823986
16,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.01GB,0.867076
17,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,0.880083
18,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.34GB,0.906222
19,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 62.52GB,0.906995
20,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,0.942750
21,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 31.03GB,1.009825
22,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.1GB,1.039130
23,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 30.12GB,1.071820
24,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.02GB,1.107845
25,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 62.29GB,1.202835
26,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 31.02GB,1.368412
27,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 31.24GB,1.600144
28,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,1.981489
29,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,2.013492
30,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,2.576411

Ranking by average duckdb time (ascending):

,host_cpu_mem,duckdb_avg_time
0,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 62.49GB,2.216036
1,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 30.78GB,2.363975
2,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 62.49GB,2.388061
3,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 62.49GB,2.427523
4,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 62.44GB,2.428677
5,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,2.462287
6,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 62.47GB,2.558498
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 30.8GB,2.622088
8,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 30.96GB,2.654634
9,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 61.97GB,2.719822
10,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 62.4GB,2.721967
11,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 62.11GB,2.736482
12,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 62.5GB,2.746406
13,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 62.48GB,2.756833
14,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 62.47GB,2.767108
15,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 62.47GB,2.868149
16,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.01GB,3.115216
17,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,3.179870
18,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 62.52GB,3.204872
19,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 31.03GB,3.291617
20,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,3.308718
21,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 62.29GB,3.330918
22,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.1GB,3.374369
23,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 30.12GB,3.865337
24,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.02GB,4.088932
25,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 31.02GB,4.439546
26,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.34GB,5.643569
27,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 31.24GB,5.806548
28,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,9.127482
29,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,9.242403
30,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,11.192535

Ranking by average fireducks time (ascending):

,host_cpu_mem,fireducks_avg_time
0,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 62.49GB,0.172736
1,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 62.48GB,0.183208
2,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 61.97GB,0.183803
3,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 62.49GB,0.185508
4,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,0.187208
5,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 62.44GB,0.190281
6,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 62.47GB,0.196184
7,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 30.8GB,0.196529
8,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 62.11GB,0.196769
9,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 62.47GB,0.210179
10,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 62.47GB,0.210439
11,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 30.96GB,0.217812
12,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 62.4GB,0.219480
13,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 30.12GB,0.223752
14,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.01GB,0.230130
15,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,0.231792
16,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.34GB,0.240043
17,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 62.29GB,0.287744
18,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 31.03GB,0.295756
19,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.1GB,0.298350
20,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 31.02GB,0.316002
21,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 31.24GB,0.351667
22,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 62.52GB,0.365081
23,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,0.370742
24,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,0.378425
25,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 30.78GB,0.408981
26,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 62.49GB,0.412192
27,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 62.5GB,0.493435
28,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,0.520348
29,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.02GB,0.627516
30,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,0.794866

In [9]:
# Rank hosts (host + CPU) by the average time across all libraries (pandas, polars, duckdb)
#all_lib_time_cols = [col for col in b_df.columns if col.endswith('_pandas_seconds') or col.endswith('_polars_seconds') or col.endswith('_duckdb_seconds')]

b_df['all_libs_avg_time'] = b_df[time_cols].mean(axis=1)

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)+ ' | ' + b_df['system'].astype(str)

# Group by host+cpu and get the mean
host_alllibs_avg = b_df.groupby('host_cpu')['all_libs_avg_time'].mean().reset_index()

# Sort to get the fastest overall
host_alllibs_avg_sorted = host_alllibs_avg.sort_values('all_libs_avg_time', ascending=True).reset_index(drop=True)

# Combine hostname and cpu_brand for unique identification
#b_df['host'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)+ ' | ' + b_df['system'].astype(str)

system_type = b_df['system'].drop_duplicates()

#display(system_type)

print("Ranking by average time across all libraries (fastest PC overall):")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    #pass
    display(host_alllibs_avg_sorted)

Ranking by average time across all libraries (fastest PC overall):

,host_cpu,all_libs_avg_time
0,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.906402
1,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.963997
2,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.984936
3,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.993279
4,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,1.041249
5,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,1.041363
6,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,1.057614
7,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,1.058977
8,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,1.072062
9,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,1.073509
10,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,1.081076
11,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,1.094910
12,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,1.116348
13,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,1.129746
14,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,1.142964
15,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,1.177964
16,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,1.184287
17,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,1.199354
18,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,1.252605
19,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,1.268143
20,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,1.291668
21,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,1.303059
22,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.309396
23,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,1.319959
24,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,1.326765
25,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,1.378234
26,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,1.383371
27,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,1.389265
28,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,1.394260
29,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,1.394768
30,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,1.400005
31,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.401128
32,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,1.404093
33,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,1.404118
34,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,1.408530
35,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,1.426008
36,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,1.462649
37,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,1.466588
38,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,1.469137
39,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,1.470001
40,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,1.476203
41,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,1.489834
42,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,1.537022
43,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,1.565098
44,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.600826
45,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,1.603812
46,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,1.627772
47,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,1.639615
48,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.644896
49,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.655497
50,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,1.683140
51,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,1.690209
52,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,1.724374
53,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.766031
54,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.771101
55,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,1.775268
56,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,1.775379
57,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,1.782576
58,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,1.802151
59,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,1.804945
60,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.841325
61,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,1.894291
62,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,1.895082
63,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,1.895487
64,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.899952
65,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,1.901213
66,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,1.908224
67,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,1.923369
68,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,1.928372
69,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.946110
70,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.951453
71,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,1.958095
72,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.977244
73,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,1.994251
74,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.998400
75,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,2.013783
76,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,2.019398
77,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,2.083443
78,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,2.099882
79,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,2.209994
80,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,2.213603
81,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,2.222590
82,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,2.225630
83,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,2.261364
84,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.334309
85,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,2.391290
86,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,2.393767
87,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,2.398192
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,2.401675
89,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,2.541353
90,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,2.544879
91,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.606110
92,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,2.714701
93,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.750609
94,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.893920
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.900572
96,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,2.901292
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,3.100964
98,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.171048
99,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.172915
100,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.188409
101,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,3.372129
102,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,3.384055
103,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.901221
104,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,3.973162
105,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,4.013706
106,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,4.214188
107,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.306442
108,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,4.845665
109,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,5.087752
110,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,5.172890
111,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,6.332776
112,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,6.341653
113,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,7.449210

In [10]:
# Fastest PC overall (hostname + CPU + memory) split by platform (Windows / WSL2 / Linux)

# Ensure we have a per-row average time metric (NaN/zero-safe).
if 'all_libs_avg_time' not in b_df.columns:
    timings_numeric = b_df[time_cols].apply(pd.to_numeric, errors='coerce')
    timings_nonzero = timings_numeric.mask(timings_numeric <= 0)
    b_df['all_libs_avg_time'] = timings_nonzero.mean(axis=1, skipna=True)

# Host identifier (exclude platform, include memory for fairness when RAM differs)
b_df['host_cpu_mem'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['memory_total_gb'].astype(str) + 'GB'
 )

# Average across runs per (platform, host+cpu+mem)
host_by_platform = (
    b_df.groupby(['system', 'host_cpu_mem'])['all_libs_avg_time']
    .mean()
    .reset_index()
    .sort_values(['system', 'all_libs_avg_time'], ascending=[True, True])
    .reset_index(drop=True)
 )

print("Fastest host+CPU+memory per platform (top = fastest within platform):")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    for system in host_by_platform['system'].dropna().unique():
        print(f"\nPlatform: {system}")
        display(
            host_by_platform[host_by_platform['system'] == system]
            .reset_index(drop=True)
        )

# Optional: just the single fastest per platform
fastest_per_platform = (
    host_by_platform.sort_values(['system', 'all_libs_avg_time'], ascending=[True, True])
    .groupby('system', as_index=False)
    .first()
 )
print("\nSingle fastest host+CPU+memory per platform:")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(fastest_per_platform)

Fastest host+CPU+memory per platform (top = fastest within platform):

Platform: Linux

,system,host_cpu_mem,all_libs_avg_time
0,Linux,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 62.49GB,0.906402
1,Linux,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 62.49GB,0.963997
2,Linux,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 62.49GB,0.984936
3,Linux,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 62.44GB,0.993279
4,Linux,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 62.47GB,1.041249
5,Linux,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 30.8GB,1.041363
6,Linux,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 30.78GB,1.057614
7,Linux,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 61.97GB,1.058977
8,Linux,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 30.96GB,1.072062
9,Linux,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 62.48GB,1.073509
10,Linux,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 62.11GB,1.081076
11,Linux,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 62.49GB,1.094910
12,Linux,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 62.47GB,1.116939
13,Linux,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 62.4GB,1.129746
14,Linux,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 62.47GB,1.142964
15,Linux,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.01GB,1.238989
16,Linux,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 62.5GB,1.268143
17,Linux,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,1.309396
18,Linux,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 62.52GB,1.319959
19,Linux,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 31.03GB,1.394260
20,Linux,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.06GB,1.401128
21,Linux,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.1GB,1.426008
22,Linux,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 30.12GB,1.462649
23,Linux,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 62.29GB,1.466588
24,Linux,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.02GB,1.766031
25,Linux,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 31.02GB,1.804945
26,Linux,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.34GB,1.894291
27,Linux,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 31.24GB,2.209994
28,Linux,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,3.171048
29,Linux,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,3.172915
30,Linux,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.5GB,4.013706

Platform: WSL2

,system,host_cpu_mem,all_libs_avg_time
0,WSL2,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 31.19GB,1.116348
1,WSL2,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | 62.66GB,1.184287
2,WSL2,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 31.19GB,1.199354
3,WSL2,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 31.2GB,1.252605
4,WSL2,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 15.5GB,1.291668
5,WSL2,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.46GB,1.303059
6,WSL2,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 31.21GB,1.326765
7,WSL2,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 23.47GB,1.367725
8,WSL2,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 31.19GB,1.378234
9,WSL2,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 15.35GB,1.389265
10,WSL2,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.15GB,1.394768
11,WSL2,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 30.2GB,1.400005
12,WSL2,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 31.19GB,1.404093
13,WSL2,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 31.17GB,1.404118
14,WSL2,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 31.19GB,1.408530
15,WSL2,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 15.46GB,1.445957
16,WSL2,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 31.09GB,1.469137
17,WSL2,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 31.21GB,1.470001
18,WSL2,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 15.34GB,1.476203
19,WSL2,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 11.44GB,1.489834
20,WSL2,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | 23.47GB,1.537022
21,WSL2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 31.18GB,1.603812
22,WSL2,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 30.93GB,1.627772
23,WSL2,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | 31.16GB,1.639615
24,WSL2,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 31.21GB,1.644896
25,WSL2,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 15.22GB,1.647029
26,WSL2,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 30.95GB,1.672432
27,WSL2,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 31.18GB,1.690209
28,WSL2,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.18GB,1.782576
29,WSL2,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 31.0GB,1.895487
30,WSL2,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 31.19GB,1.923369
31,WSL2,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.45GB,1.951453
32,WSL2,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 15.49GB,1.977244
33,WSL2,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 15.21GB,2.222590
34,WSL2,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 15.01GB,2.261364
35,WSL2,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 31.2GB,2.391290
36,WSL2,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 15.52GB,2.606110
37,WSL2,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 15.57GB,2.714701
38,WSL2,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.25GB,2.900572
39,WSL2,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 15.26GB,3.100964
40,WSL2,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.25GB,3.188409
41,WSL2,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 15.52GB,4.845665

Platform: Windows

,system,host_cpu_mem,all_libs_avg_time
0,Windows,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | 63.64GB,1.565098
1,Windows,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 63.69GB,1.595766
2,Windows,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | 61.68GB,1.600826
3,Windows,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 63.69GB,1.628893
4,Windows,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | 63.65GB,1.683140
5,Windows,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 63.17GB,1.699869
6,Windows,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 63.73GB,1.708745
7,Windows,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | 31.76GB,1.724374
8,Windows,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | 31.19GB,1.771101
9,Windows,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | 31.69GB,1.775268
10,Windows,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | 31.68GB,1.775379
11,Windows,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | 63.68GB,1.802151
12,Windows,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 63.69GB,1.814602
13,Windows,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 31.21GB,1.831225
14,Windows,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | 63.21GB,1.861526
15,Windows,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | 63.7GB,1.895082
16,Windows,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | 63.71GB,1.899952
17,Windows,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | 63.72GB,1.901213
18,Windows,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | 31.61GB,1.946110
19,Windows,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | 63.68GB,1.958095
20,Windows,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 63.31GB,1.991617
21,Windows,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | 63.61GB,1.994251
22,Windows,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | 63.7GB,1.998400
23,Windows,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | 31.46GB,2.013783
24,Windows,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 63.67GB,2.049077
25,Windows,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | 15.73GB,2.147999
26,Windows,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 15.69GB,2.220683
27,Windows,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | 31.67GB,2.295866
28,Windows,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | 127.71GB,2.334309
29,Windows,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | 23.69GB,2.352285
30,Windows,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | 31.43GB,2.393767
31,Windows,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | 63.73GB,2.398192
32,Windows,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | 30.78GB,2.401675
33,Windows,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | 15.69GB,2.409903
34,Windows,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | 15.17GB,2.499896
35,Windows,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | 63.67GB,2.541353
36,Windows,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | 63.49GB,2.544879
37,Windows,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | 15.31GB,2.693656
38,Windows,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.67GB,2.750609
39,Windows,Inspiron3030S | Intel(R) Core(TM) i7-14700 | 63.7GB,2.893920
40,Windows,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | 31.72GB,2.901292
41,Windows,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | 31.28GB,3.372129
42,Windows,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | 15.63GB,3.384055
43,Windows,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 63.82GB,3.901221
44,Windows,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 31.89GB,3.948197
45,Windows,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | 63.69GB,3.973162
46,Windows,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 31.81GB,4.306442
47,Windows,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | 15.89GB,4.480179
48,Windows,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | 19.78GB,5.087752
49,Windows,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | 63.82GB,5.172890
50,Windows,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | 15.69GB,6.332776
51,Windows,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | 15.88GB,6.341653
52,Windows,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | 31.81GB,7.449210

Single fastest host+CPU+memory per platform:

,system,host_cpu_mem,all_libs_avg_time
0,Linux,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 62.49GB,0.906402
1,WSL2,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | 31.19GB,1.116348
2,Windows,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | 63.64GB,1.565098

In [11]:
# Rank platforms (Windows / WSL2 / Linux) by average processing time

# Compute a row-wise average across all timing columns, treating 0s as missing (NaN)
timings_numeric = b_df[time_cols].apply(pd.to_numeric, errors='coerce')
timings_nonzero = timings_numeric.mask(timings_numeric <= 0)
b_df['all_timings_avg_time'] = timings_nonzero.mean(axis=1, skipna=True)

# Group by platform and get the mean
platform_avg = (
    b_df.groupby('system')['all_timings_avg_time']
    .mean()
    .reset_index()
    .sort_values('all_timings_avg_time', ascending=True)
    .reset_index(drop=True)
)
print("Ranking by average processing time across all benchmarks (fastest platform overall):")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(platform_avg)

Ranking by average processing time across all benchmarks (fastest platform overall):

    system  all_timings_avg_time
0    Linux              1.747925
1     WSL2              1.778968
2  Windows              2.633518

In [12]:
# Calculate the average operation time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  # Fixed: startswith
    b_df[f'{test}_avg_time'] = b_df[test_cols].mean(axis=1)  # Fixed: use test, not lib

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each test
test_avg_cols = [f'{test}_avg_time' for test in test_prefixes]
host_test_avg = b_df.groupby('host_cpu')[test_avg_cols].mean().reset_index()

# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by average {test} time (ascending):")
    with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
        display(host_test_avg[['host_cpu', f'{test}_avg_time']].sort_values(f'{test}_avg_time'))
    print("\n")

# Display the full table
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    #display(host_test_avg)
    pass

Ranking by average filter_group time (ascending):

,host_cpu,filter_group_avg_time
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.142528
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.147020
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.151983
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.153555
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.155525
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.160398
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.161773
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.161918
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.163065
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.165648
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.174198
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.178403
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.178905
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.184984
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.199375
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.201356
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.205408
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.206584
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.209489
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.210105
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,0.210401
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,0.212222
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.219461
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.220191
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,0.220560
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.222454
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.224723
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.227449
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.229844
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.232272
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.235091
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.239863
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.242138
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.242555
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.245565
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.245988
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.246987
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.250913
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.255735
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.256065
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.257783
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,0.259046
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.260246
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.260343
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.264002
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.264494
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.265074
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.266733
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.267400
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.267666
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.269770
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,0.270840
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.271585
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.271687
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,0.273295
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,0.274220
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.276860
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.277032
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,0.288106
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,0.290282
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,0.290515
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.291473
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.291605
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.294546
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.296259
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,0.296945
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.297816
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.300022
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.305850
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.308836
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.315131
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.319901
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.320177
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.322511
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.325251
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.332087
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.334513
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,0.335495
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,0.336168
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,0.338668
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.339161
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.350148
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.368343
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,0.375010
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,0.379503
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.392711
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.417065
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.438459
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.450385
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.463158
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.475525
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.477886
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.480865
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,0.481653
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.513317
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.550806
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.597730
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.609594
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.611797
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.693557
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.694441
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.746890
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.749385
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.804758
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.812564
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.821436
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,0.827289
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.831888
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.036371
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.072774
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.135896
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.287018
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.342407

Ranking by average statistics time (ascending):

,host_cpu,statistics_avg_time
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.135124
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.137825
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.141072
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.143350
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.144062
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.147452
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.149658
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.150017
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.150956
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.151160
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.154322
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.160059
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.160734
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.164831
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.165953
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.166395
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.166518
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.168026
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.171291
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.171604
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.172467
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.176155
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.176746
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.180325
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.180413
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.182122
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.185310
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.185441
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.186418
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.187274
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.188467
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.189246
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.190619
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,0.193534
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.197254
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.203319
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,0.205908
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.206597
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.207104
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.207238
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.209018
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.211742
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.212357
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.216774
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,0.217486
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.219704
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.225610
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.225698
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.225851
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.226276
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,0.226649
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.229776
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.230398
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.237845
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.238860
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.243413
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.247764
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,0.248467
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,0.252699
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,0.253875
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.256554
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.256736
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.258530
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.258697
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.260196
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.261445
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.261492
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.263565
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.264598
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,0.265253
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,0.267550
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.271939
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.275028
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.281112
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.282742
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,0.288462
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.289064
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,0.289747
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.297120
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,0.299462
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.300612
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,0.304271
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.329655
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.368919
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,0.377999
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,0.380780
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.387384
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395596
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.396304
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.415645
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,0.421603
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.430578
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.440528
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.459804
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,0.476837
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.534456
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.588329
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.594203
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.624623
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.662899
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.669798
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.689494
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.791946
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,0.814071
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.861385
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.869160
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.908945
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.914073
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.931412
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.097377
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.140910
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.163339
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.360749
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.448765

Ranking by average complex_join time (ascending):

,host_cpu,complex_join_avg_time
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,2.638049
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,2.850362
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,2.880609
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,2.893357
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,3.016199
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,3.043056
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,3.093814
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,3.117687
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,3.139065
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,3.174487
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,3.188131
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,3.216045
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,3.277967
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,3.359158
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,3.416013
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,3.487927
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,3.500320
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,3.604662
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,3.682625
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,3.750240
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,3.870069
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,3.890208
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,3.894547
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,3.921480
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,3.956929
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,3.961250
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,3.977967
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,4.079600
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,4.085986
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,4.136510
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,4.149288
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,4.218467
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,4.236931
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,4.246322
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,4.253549
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,4.271681
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,4.309034
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,4.335345
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,4.470320
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,4.544823
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,4.575648
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,4.637280
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,4.651404
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,4.797647
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,4.840828
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,4.897682
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,4.902261
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,4.947536
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,5.005017
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,5.105900
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,5.125440
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,5.138336
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,5.223634
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,5.237106
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,5.287912
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,5.350801
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,5.362735
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,5.447562
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,5.489812
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,5.506571
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,5.548716
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,5.567900
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,5.638994
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,5.800627
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,5.834663
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,5.858662
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,5.918052
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,5.947107
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,5.970477
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,5.981846
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,6.077468
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,6.091291
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,6.142236
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,6.190292
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,6.210260
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,6.302954
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,6.342929
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,6.346878
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,6.396985
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,6.399921
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,6.425067
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,6.467469
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,6.829715
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,6.865348
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,7.040301
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,7.078609
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,7.085135
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,7.248586
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,7.366866
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,7.622959
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,7.659173
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.756925
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,7.916106
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,8.107443
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,8.375969
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,8.619418
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,8.817132
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,9.057651
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.301819
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.384543
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,9.791986
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,10.454544
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,10.487334
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,10.943079
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,11.430337
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.718066
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,12.338501
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,12.467298
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,14.181277
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,14.193325
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,14.483172
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,17.847316
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,18.834236
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,24.791240

Ranking by average timeseries time (ascending):

,host_cpu,timeseries_avg_time
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.707206
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.714546
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.721045
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.730865
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.733304
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.761732
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.768042
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.772390
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.781308
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.786204
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.801411
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.820361
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.826957
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.831431
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.834206
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.848986
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.853397
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.855435
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.857752
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.870005
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.884319
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.888004
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.891948
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.895528
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.899241
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.909459
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.909704
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.913058
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.920432
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.924094
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.931719
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.933917
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.933918
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.937399
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.944816
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.974662
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.979468
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.980473
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.986357
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,1.019426
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,1.048131
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,1.057994
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,1.067212
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,1.069514
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.071617
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,1.072537
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.080760
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,1.085264
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,1.094422
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,1.098185
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,1.109765
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,1.119582
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,1.122947
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.125433
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,1.129725
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,1.132113
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.135645
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,1.152955
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,1.158346
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,1.160357
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,1.172376
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,1.182763
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,1.194161
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,1.208271
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,1.210007
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,1.214247
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.223688
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,1.224979
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,1.231884
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,1.235237
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.249969
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,1.254550
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,1.298882
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,1.315969
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.320247
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,1.340433
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,1.350658
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,1.360454
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,1.366382
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,1.376781
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,1.404821
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,1.415426
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,1.441172
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.444806
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,1.523166
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,1.546463
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,1.575893
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.582553
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.645263
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,1.651231
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.665469
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,1.701790
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.732938
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.744553
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,1.792872
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.866644
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.935096
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.989385
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.027155
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.108246
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.142782
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,2.376920
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.496969
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.646161
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.748607
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,2.876893
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,3.031831
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.051035
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.275654
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.327298
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,3.880878
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.310571
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,4.326716
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,4.816141

In [13]:
# Calculate the minumum time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  
    b_df[f'{test}_min_time'] = b_df[test_cols].min(axis=1)  

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the min per host+cpu for each test
test_min_cols = [f'{test}_min_time' for test in test_prefixes]
host_test_min = b_df.groupby('host_cpu')[test_min_cols].min().reset_index()

# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by minimum time {test} time (ascending):")
    with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
        display(host_test_min[['host_cpu', f'{test}_min_time']].sort_values(f'{test}_min_time'))
    print("\n")

# Display the full table
host_test_min

Ranking by minimum time filter_group time (ascending):

,host_cpu,filter_group_min_time
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.001211
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.001269
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.001273
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.001346
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.001347
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.001348
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.001384
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.001393
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.001393
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.001394
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.001396
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.001407
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,0.001422
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.001423
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.001445
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.001453
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.001456
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.001469
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,0.001473
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.001484
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.001486
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001510
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.001537
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.001575
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.001589
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001595
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.001598
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001606
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,0.001631
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.001639
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.001644
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.001646
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.001654
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.001698
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,0.001712
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.001724
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.001743
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.001753
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.001831
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.001840
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.001853
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.001858
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.001875
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.001937
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.001940
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.001956
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.001970
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.001991
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,0.001995
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,0.001997
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.001999
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.002012
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.002052
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.002106
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,0.002117
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002165
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002401
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002427
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002445
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,0.002453
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.002453
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002678
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,0.002685
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002809
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.003122
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,0.003159
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003213
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003474
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.031890
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.031958
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.032062
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.033673
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.034698
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,0.034849
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.035718
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.036018
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.036321
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.036903
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.039774
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.039799
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.040170
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,0.040718
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.040865
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.041897
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.042288
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.042423
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,0.043970
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.045534
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.046270
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,0.046693
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.047376
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.048200
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.048940
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,0.053748
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,0.056317
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.056555
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,0.058221
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058446
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.080767
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,0.091840
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.113281
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.128099
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.133032
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.141584
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.173585
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558

Ranking by minimum time statistics time (ascending):

,host_cpu,statistics_min_time
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000125
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.000131
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.000136
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000140
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,0.000140
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.000142
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000145
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.000148
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.000152
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.000155
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.000156
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.000156
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.000157
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,0.000165
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.000166
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,0.000168
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.000171
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.000176
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.000176
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.000180
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.000181
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000182
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.000183
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000187
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000187
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.000188
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.000188
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000191
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.000191
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000193
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.000194
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000195
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000197
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000204
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.000206
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,0.000209
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.000211
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000213
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,0.000215
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.000216
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.000217
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.000218
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.000220
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.000221
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.000222
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.000223
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.000224
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,0.000227
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000227
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.000235
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.000235
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.000258
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000271
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000283
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.000284
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000289
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000291
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.000321
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,0.000333
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000338
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000347
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,0.000368
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000381
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,0.000390
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000420
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,0.000469
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000490
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000549
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000564
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.048504
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.058021
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.058166
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.059756
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.061105
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.061309
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.065095
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,0.067649
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.068152
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.068492
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,0.071364
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.074070
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.075092
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.075277
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.076928
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,0.078521
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,0.080303
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.081412
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.081498
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.085934
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.087770
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.089443
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.089539
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.090133
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.090168
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.090588
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,0.090630
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,0.092191
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.099953
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,0.145645
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.155662
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.164641
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,0.233142
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.304877
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.328502
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.344468
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.352225
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.355642
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830

Ranking by minimum time complex_join time (ascending):

,host_cpu,complex_join_min_time
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.000375
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000377
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000384
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.000385
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000400
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.000409
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.000410
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,0.000425
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,0.000427
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.000429
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.000435
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.000439
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.000443
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,0.000447
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.000449
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.000456
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.000456
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000457
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.000471
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.000476
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.000478
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.000484
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.000499
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000505
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000507
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000508
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000509
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.000514
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000517
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.000518
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.000518
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000520
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000524
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.000538
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.000544
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,0.000549
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.000549
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.000551
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.000554
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000562
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.000573
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.000578
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.000581
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.000588
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.000593
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.000609
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.000610
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,0.000611
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000614
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000653
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.000665
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000680
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.000684
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.000706
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.000710
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,0.000720
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000744
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,0.000767
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000854
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000859
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,0.000924
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000936
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000962
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,0.001064
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001124
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,0.001193
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001273
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001411
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001499
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.450646
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.459607
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.460579
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.466328
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.466874
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.470777
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.476298
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.481997
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.483583
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.496640
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.505853
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.506174
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.507359
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,0.508859
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.511853
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,0.515636
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.523552
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.544344
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,0.548337
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,0.549224
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.572802
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.588109
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,0.596053
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.630006
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.658748
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.659083
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,0.688937
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,0.689733
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.797163
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.802114
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.029172
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.079245
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.338042
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.451908
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,1.462724
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.510888
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.544476
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.646886
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631

Ranking by minimum time timeseries time (ascending):

,host_cpu,timeseries_min_time
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.098952
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.104968
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.110413
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.111030
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.111596
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.113430
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.115453
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.118026
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.126166
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.134601
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.137403
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.140360
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.140363
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.140741
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.141526
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.141836
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.144650
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.144755
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,0.145004
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,0.145966
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.146148
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.147645
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.147814
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.148341
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.148428
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.149619
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.150845
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.150902
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.151960
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.152020
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.152933
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.158153
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,0.158680
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.161141
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.163267
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.165347
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.165733
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.166123
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.169566
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.170429
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.170503
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.171355
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,0.172420
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.173158
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.173654
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.174492
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.175164
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.175907
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.177192
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.179042
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.180224
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.183436
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,0.184204
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.184264
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.185553
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.185991
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.186022
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.186129
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.186161
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.186529
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.188238
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,0.188754
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.188773
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.195565
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.195624
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,0.198928
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,0.203027
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.204379
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.205268
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.205499
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.205787
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.210747
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.213198
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.214164
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.216630
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.224173
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,0.225218
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.230046
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,0.231959
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.232552
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,0.233836
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.235709
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,0.239510
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.263333
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.268142
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,0.274185
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,0.324323
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.350482
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.362893
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,0.369914
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.374270
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395654
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,0.461786
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.464249
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,0.473878
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.501116
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.503815
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.544602
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.557196
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.574874
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.592204
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,0.665525
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.726991
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.741153
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.851114
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.986644
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.063147
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530

,host_cpu,filter_group_min_time,statistics_min_time,complex_join_min_time,timeseries_min_time
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-...,0.001486,0.000181,0.000518,0.188773
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-...,0.002052,0.000284,0.000706,0.232552
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-...,0.040170,0.074070,0.481997,0.195565
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.001940,0.000291,0.000653,0.210747
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.056555,0.099953,0.797163,0.263333
...,...,...,...,...,...
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-1...,0.045534,0.076928,0.505853,0.177192
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-...,0.001510,0.000187,0.000509,0.204379
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-...,0.002401,0.000283,0.000859,0.374270
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-...,0.080767,0.164641,1.029172,0.362893
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) ...,0.001595,0.000182,0.000507,0.214164

In [14]:
# Calculate the minimum time per row for each test and annotate which library achieved it (NaN-safe)

test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries']

for test in test_prefixes:
    # Raw timing columns only
    test_cols = [
        col for col in b_df.columns
        if col.startswith(f'{test}_') and col.endswith('_seconds')
    ]
    if not test_cols:
        b_df[f'{test}_min_time'] = float('nan')
        b_df[f'{test}_min_library'] = None
        continue

    # Convert to numeric (coerce 'N/A', blanks, etc. to NaN)
    numeric = b_df[test_cols].apply(pd.to_numeric, errors='coerce')

    # Row-wise min ignoring NaNs
    min_times = numeric.min(axis=1, skipna=True)

    # Identify the column name (library) producing the min ignoring NaNs.
    # pandas idxmin(skipna=True) returns NaN if the entire row is NaN.
    min_cols = numeric.idxmin(axis=1, skipna=True)

    suffix_len = len('_seconds')
    min_libs = []
    for col_name, all_nan in zip(min_cols, numeric.isna().all(axis=1)):
        if all_nan or pd.isna(col_name):
            min_libs.append(None)
        else:
            # column pattern: <test>_<library>_seconds
            lib_name = col_name[len(test) + 1: -suffix_len]
            min_libs.append(lib_name)

    b_df[f'{test}_min_time'] = min_times
    b_df[f'{test}_min_library'] = min_libs

# Unique host identifier
b_df['host_cpu'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['system'].astype(str)
)

# Aggregate: pick min time & corresponding library per host
host_rows = []
for host, g in b_df.groupby('host_cpu'):
    row = {'host_cpu': host}
    for test in test_prefixes:
        time_col = f'{test}_min_time'
        lib_col = f'{test}_min_library'
        if time_col not in g.columns or lib_col not in g.columns:
            row[time_col] = float('nan')
            row[lib_col] = None
            continue
        # valid rows for this test
        g_valid = g.dropna(subset=[time_col])
        if g_valid.empty:
            row[time_col] = float('nan')
            row[lib_col] = None
        else:
            # take the first row with minimal time
            min_idx = g_valid[time_col].idxmin()
            row[time_col] = g_valid.loc[min_idx, time_col]
            row[lib_col] = g_valid.loc[min_idx, lib_col]
    host_rows.append(row)

host_test_min = pd.DataFrame(host_rows)

# Display rankings per test including which library produced the min
for test in test_prefixes:
    time_col = f'{test}_min_time'
    lib_col = f'{test}_min_library'
    if time_col not in host_test_min.columns:
        continue
    print(f"Ranking by minimum {test} time (ascending):")
    with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
        display(
            host_test_min[['host_cpu', time_col, lib_col]]
            .sort_values(time_col, na_position='last')
        )
    print("\n")

# Optional summary: frequency of fastest library per test
summary_rows = []
for test in test_prefixes:
    lib_col = f'{test}_min_library'
    if lib_col in host_test_min.columns:
        counts = host_test_min[lib_col].value_counts(dropna=True)
        for lib, cnt in counts.items():
            summary_rows.append({'test': test, 'library': lib, 'wins': cnt})
fastest_summary = pd.DataFrame(summary_rows).sort_values(['test', 'wins'], ascending=[True, False])
print("Fastest library counts per test:")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(fastest_summary)

# Full aggregated table (one row per host with min times + libraries per test)
#host_test_min

Ranking by minimum filter_group time (ascending):

,host_cpu,filter_group_min_time,filter_group_min_library
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.001211,fireducks
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.001269,fireducks
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.001273,fireducks
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.001346,fireducks
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.001347,fireducks
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.001348,fireducks
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.001384,fireducks
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.001393,fireducks
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.001393,fireducks
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.001394,fireducks
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.001396,fireducks
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.001407,fireducks
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,0.001422,fireducks
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.001423,fireducks
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.001445,fireducks
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.001453,fireducks
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.001456,fireducks
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.001469,fireducks
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,0.001473,fireducks
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.001484,fireducks
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.001486,fireducks
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497,fireducks
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001510,fireducks
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.001537,fireducks
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.001575,fireducks
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.001589,fireducks
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001595,fireducks
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.001598,fireducks
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.001606,fireducks
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,0.001631,fireducks
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.001639,fireducks
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.001644,fireducks
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.001646,fireducks
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.001654,fireducks
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.001698,fireducks
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,0.001712,fireducks
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.001724,fireducks
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.001743,fireducks
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.001753,fireducks
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.001831,fireducks
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.001840,fireducks
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.001853,fireducks
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.001858,fireducks
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.001875,fireducks
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.001937,fireducks
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.001940,fireducks
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.001956,fireducks
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.001970,fireducks
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.001991,fireducks
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,0.001995,fireducks
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,0.001997,fireducks
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.001999,fireducks
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.002012,fireducks
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.002052,fireducks
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.002106,fireducks
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,0.002117,fireducks
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002165,fireducks
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.002401,fireducks
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002427,fireducks
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002445,fireducks
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,0.002453,fireducks
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.002453,fireducks
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002678,fireducks
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,0.002685,fireducks
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002809,fireducks
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029,fireducks
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.003122,fireducks
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,0.003159,fireducks
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003213,fireducks
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003474,fireducks
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.031890,duckdb
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.031958,duckdb
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.032062,duckdb
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242,duckdb
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.033673,duckdb
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.034698,duckdb
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815,duckdb
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,0.034849,duckdb
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.035718,duckdb
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.036018,duckdb
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.036321,duckdb
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.036903,duckdb
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.039774,duckdb
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.039799,duckdb
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.040170,duckdb
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,0.040718,duckdb
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.040865,duckdb
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.041897,duckdb
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.042288,duckdb
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.042423,duckdb
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,0.043970,duckdb
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.045534,duckdb
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.046270,duckdb
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,0.046693,duckdb
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.047376,duckdb
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.048200,duckdb
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.048940,duckdb
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,0.053748,duckdb
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,0.056317,duckdb
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.056555,duckdb
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,0.058221,duckdb
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058446,duckdb
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.080767,duckdb
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105,duckdb
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,0.091840,duckdb
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551,duckdb
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.113281,duckdb
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.128099,duckdb
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.133032,duckdb
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.141584,duckdb
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650,duckdb
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057,duckdb
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.173585,duckdb
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558,duckdb

Ranking by minimum statistics time (ascending):

,host_cpu,statistics_min_time,statistics_min_library
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000125,fireducks
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.000131,fireducks
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.000136,fireducks
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000140,fireducks
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,0.000140,fireducks
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.000142,fireducks
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000145,fireducks
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.000148,fireducks
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.000152,fireducks
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.000155,fireducks
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.000156,fireducks
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.000156,fireducks
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.000157,fireducks
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,0.000165,fireducks
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.000166,fireducks
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,0.000168,fireducks
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.000171,fireducks
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.000176,fireducks
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.000176,fireducks
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.000180,fireducks
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.000181,fireducks
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000182,fireducks
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.000183,fireducks
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000187,fireducks
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000187,fireducks
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.000188,fireducks
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.000188,fireducks
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000191,fireducks
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.000191,fireducks
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000193,fireducks
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.000194,fireducks
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000195,fireducks
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000197,fireducks
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000204,fireducks
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.000206,fireducks
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,0.000209,fireducks
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.000211,fireducks
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000213,fireducks
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,0.000215,fireducks
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.000216,fireducks
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.000217,fireducks
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.000218,fireducks
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.000220,fireducks
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.000221,fireducks
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.000222,fireducks
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.000223,fireducks
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.000224,fireducks
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,0.000227,fireducks
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000227,fireducks
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.000235,fireducks
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.000235,fireducks
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.000258,fireducks
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000271,fireducks
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000283,fireducks
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.000284,fireducks
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000289,fireducks
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000291,fireducks
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.000321,fireducks
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,0.000333,fireducks
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000338,fireducks
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000347,fireducks
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,0.000368,fireducks
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000381,fireducks
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,0.000390,fireducks
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000420,fireducks
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,0.000469,fireducks
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484,fireducks
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000490,fireducks
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000549,fireducks
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000564,fireducks
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.048504,duckdb
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.058021,duckdb
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.058166,duckdb
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392,duckdb
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.059756,duckdb
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.061105,duckdb
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.061309,duckdb
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178,duckdb
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.065095,duckdb
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,0.067649,duckdb
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.068152,duckdb
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.068492,duckdb
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,0.071364,duckdb
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.074070,duckdb
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.075092,duckdb
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.075277,duckdb
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.076928,duckdb
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,0.078521,duckdb
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,0.080303,duckdb
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.081412,duckdb
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.081498,polars
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.085934,duckdb
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.087770,duckdb
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.089443,duckdb
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.089539,duckdb
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.090133,duckdb
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.090168,duckdb
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.090588,duckdb
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,0.090630,duckdb
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,0.092191,duckdb
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.099953,duckdb
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574,polars
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,0.145645,duckdb
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.155662,duckdb
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.164641,duckdb
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529,duckdb
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,0.233142,duckdb
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.304877,duckdb
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.328502,duckdb
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.344468,duckdb
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.352225,duckdb
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.355642,duckdb
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730,duckdb
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830,polars

Ranking by minimum complex_join time (ascending):

,host_cpu,complex_join_min_time,complex_join_min_library
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.000375,fireducks
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.000377,fireducks
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000384,fireducks
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.000385,fireducks
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000400,fireducks
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.000409,fireducks
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.000410,fireducks
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,0.000425,fireducks
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,0.000427,fireducks
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.000429,fireducks
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.000435,fireducks
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.000439,fireducks
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.000443,fireducks
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,0.000447,fireducks
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.000449,fireducks
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.000456,fireducks
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.000456,fireducks
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000457,fireducks
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.000471,fireducks
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.000476,fireducks
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.000478,fireducks
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.000484,fireducks
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.000499,fireducks
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.000505,fireducks
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000507,fireducks
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000508,fireducks
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000509,fireducks
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.000514,fireducks
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000517,fireducks
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.000518,fireducks
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.000518,fireducks
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.000520,fireducks
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000524,fireducks
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.000538,fireducks
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.000544,fireducks
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,0.000549,fireducks
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.000549,fireducks
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.000551,fireducks
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.000554,fireducks
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000562,fireducks
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.000573,fireducks
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.000578,fireducks
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.000581,fireducks
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.000588,fireducks
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.000593,fireducks
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.000609,fireducks
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.000610,fireducks
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,0.000611,fireducks
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.000614,fireducks
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000653,fireducks
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.000665,fireducks
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000680,fireducks
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.000684,fireducks
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.000706,fireducks
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.000710,fireducks
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,0.000720,fireducks
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000744,fireducks
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,0.000767,fireducks
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000854,fireducks
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.000859,fireducks
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,0.000924,fireducks
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000936,fireducks
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000962,fireducks
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,0.001064,fireducks
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001124,fireducks
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163,fireducks
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,0.001193,fireducks
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001273,fireducks
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001411,fireducks
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001499,fireducks
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.450646,polars
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.459607,polars
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.460579,polars
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.466328,polars
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.466874,polars
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.470777,polars
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.476298,polars
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.481997,polars
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777,polars
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.483583,polars
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.496640,polars
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.505853,polars
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.506174,polars
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.507359,polars
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,0.508859,polars
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.511853,polars
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,0.515636,polars
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.523552,polars
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.544344,polars
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,0.548337,polars
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,0.549224,polars
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.572802,polars
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.588109,polars
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,0.596053,polars
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.630006,polars
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.658748,polars
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.659083,polars
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,0.688937,polars
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,0.689733,polars
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.797163,polars
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.802114,polars
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909,polars
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715,polars
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.029172,polars
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,1.079245,polars
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325,polars
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.338042,polars
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.451908,polars
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,1.462724,polars
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.510888,polars
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,1.544476,polars
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.646886,polars
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724,polars
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631,polars

Ranking by minimum timeseries time (ascending):

,host_cpu,timeseries_min_time,timeseries_min_library
32,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.098952,duckdb
31,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Linux,0.104968,duckdb
78,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | WSL2,0.110413,duckdb
12,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Linux,0.111030,duckdb
80,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.111596,duckdb
33,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.113430,duckdb
57,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Linux,0.115453,duckdb
13,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | WSL2,0.118026,duckdb
58,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | WSL2,0.126166,duckdb
86,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | WSL2,0.134601,duckdb
81,ROG-Strix-G17 | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.137403,duckdb
79,ROG-Strix-G16 | AMD Ryzen 9 9955HX 16-Core Processor | Windows,0.140360,duckdb
44,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | WSL2,0.140363,duckdb
30,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.140741,duckdb
46,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | WSL2,0.141526,duckdb
70,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | WSL2,0.141836,duckdb
39,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895,duckdb
93,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | Windows,0.144650,duckdb
60,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Linux,0.144755,duckdb
68,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Windows,0.145004,duckdb
92,VivoBookPro | 13th Gen Intel(R) Core(TM) i9-13980HX | WSL2,0.145966,duckdb
40,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Linux,0.146148,duckdb
14,ECT1250-AMZN | Intel(R) Core(TM) Ultra 7 265 | Windows,0.147645,duckdb
29,HP-Z2-G9 | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.147814,duckdb
62,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826,duckdb
50,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.148341,duckdb
34,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Linux,0.148428,duckdb
69,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Linux,0.149619,duckdb
63,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Linux,0.150845,duckdb
66,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | Linux,0.150902,duckdb
64,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | WSL2,0.151960,duckdb
38,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.152020,duckdb
49,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.152933,duckdb
73,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | WSL2,0.158153,duckdb
71,OptPlexMicro-7020 | Intel(R) Core(TM) i5-14600 | Windows,0.158680,duckdb
45,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Windows,0.161141,duckdb
82,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Linux,0.163267,duckdb
77,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.165347,duckdb
54,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Linux,0.165733,duckdb
107,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.166123,duckdb
98,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Linux,0.169566,duckdb
61,OptPlex-7010-1 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.170429,duckdb
6,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | WSL2,0.170503,duckdb
76,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.171355,duckdb
87,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Windows,0.172420,duckdb
105,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | WSL2,0.173158,duckdb
67,OptPlex-7020 | Intel(R) Core(TM) i5-14500 | WSL2,0.173654,duckdb
104,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.174492,duckdb
48,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Linux,0.175164,duckdb
41,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | WSL2,0.175907,duckdb
109,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.177192,duckdb
47,Legion7-16ARX8H | AMD Ryzen 9 7945HX with Radeon Graphics | Windows,0.179042,duckdb
42,Legion5-15AHP10 | AMD Ryzen 7 260 w/ Radeon 780M Graphics | Windows,0.180224,duckdb
51,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Linux,0.183436,duckdb
72,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Linux,0.184204,duckdb
59,MSI-VectorA16HX | AMD Ryzen 9 8940HX with Radeon Graphics | Windows,0.184264,duckdb
52,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | WSL2,0.185553,duckdb
101,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.185991,duckdb
65,OptPlex-7010-2 | 13th Gen Intel(R) Core(TM) i5-13500 | Windows,0.186022,duckdb
7,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.186129,duckdb
75,Precision-7770 | 12th Gen Intel(R) Core(TM) i7-12850HX | Linux,0.186161,duckdb
56,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | Windows,0.186529,duckdb
43,Legion5-15IRX10 | Intel(R) Core(TM) i7-14700HX | Linux,0.188238,duckdb
53,LnvTCi5-12400 | 12th Gen Intel(R) Core(TM) i5-12400 | Windows,0.188754,duckdb
0,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Linux,0.188773,duckdb
2,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | Windows,0.195565,duckdb
36,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.195624,duckdb
74,Precision-7670 | 12th Gen Intel(R) Core(TM) i9-12950HX | Windows,0.198928,duckdb
85,ThinkBook | Intel(R) Core(TM) Ultra 7 255H | Linux,0.203027,duckdb
110,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.204379,duckdb
84,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.205268,duckdb
108,ZBookPowerG9 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.205499,duckdb
27,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | WSL2,0.205787,duckdb
3,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.210747,duckdb
99,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | WSL2,0.213198,duckdb
113,ZBookStudioG8-UB | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Linux,0.214164,duckdb
103,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.216630,duckdb
106,ZBookFuryG9 | 12th Gen Intel(R) Core(TM) i7-12850HX | Windows,0.224173,duckdb
88,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Linux,0.225218,duckdb
102,ZBookFuryG8-17 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.230046,duckdb
83,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | WSL2,0.231959,duckdb
1,DELL-XPS-9520 | 12th Gen Intel(R) Core(TM) i7-12700H | WSL2,0.232552,duckdb
28,HP-ProMini400 | Intel(R) Core(TM) i5-14500T | Windows,0.233836,duckdb
100,ZBookFuryG8 | 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz | Windows,0.235709,duckdb
55,LnvThkCtr-01 | 12th Gen Intel(R) Core(TM) i7-12700T | WSL2,0.239510,duckdb
4,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.263333,duckdb
35,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.268142,duckdb
89,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | WSL2,0.274185,duckdb
5,DELL-XPS15-9530 | 13th Gen Intel(R) Core(TM) i9-13900H | Linux,0.324323,duckdb
97,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.350482,duckdb
112,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | Windows,0.362893,duckdb
90,ThinkPadE16G2 | AMD Ryzen 7 7735HS with Radeon Graphics | Windows,0.369914,duckdb
111,ZBookStudioG8 | 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz | WSL2,0.374270,duckdb
91,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797,duckdb
96,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395654,duckdb
8,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Linux,0.461786,duckdb
25,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.464249,fireducks
9,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | WSL2,0.473878,duckdb
18,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.501116,fireducks
22,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.503815,pandas
94,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.544602,pandas
15,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.557196,pandas
17,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.574874,pandas
95,WL1030 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.592204,duckdb
26,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427,duckdb
10,E32-PC | Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz | Windows,0.665525,duckdb
11,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169,fireducks
37,IdeaPadS340 | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz | Windows,0.726991,duckdb
23,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.741153,duckdb
24,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055,duckdb
20,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.851114,pandas
21,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.986644,duckdb
16,HP-EB-G6-SJ | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.063147,duckdb
19,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530,duckdb

Fastest library counts per test:

           test    library  wins
5  complex_join  fireducks    70
6  complex_join     polars    44
0  filter_group  fireducks    70
1  filter_group     duckdb    44
2    statistics  fireducks    70
3    statistics     duckdb    41
4    statistics     polars     3
7    timeseries     duckdb   106
8    timeseries     pandas     5
9    timeseries  fireducks     3