In [1]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [2]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       170 non-null    object
 1   hostname                        170 non-null    object
 2   platform                        170 non-null    object
 3   system                          170 non-null    object
 4   release                         170 non-null    object
 5   version                         170 non-null    object
 6   machine                         170 non-null    object
 7   processor                       170 non-null    object
 8   cpu_count_logical               170 non-null    int64
 9   cpu_count_physical              170 non-null    int64
 10  cpu_freq_max                    170 non-null    float64
 11  cpu_freq_current                170 non-null    float64
 12  memory_total_gb                 170 non-null    float64
 13  memory_available_gb             170 non-null    float64
 14  python_version                  170 non-null    object
 15  python_implementation           170 non-null    object
 16  cpu_brand                       170 non-null    object
 17  cpu_arch                        170 non-null    object
 18  dataset_size                    170 non-null    int64
 19  dataset_name                    170 non-null    object
 20  dataset_format                  170 non-null    object
 21  filter_group_pandas_seconds     170 non-null    float64
 22  filter_group_polars_seconds     170 non-null    float64
 23  filter_group_duckdb_seconds     170 non-null    float64
 24  filter_group_fireducks_seconds  34 non-null     float64
 25  statistics_pandas_seconds       170 non-null    float64
 26  statistics_polars_seconds       170 non-null    float64
 27  statistics_duckdb_seconds       170 non-null    float64
 28  statistics_fireducks_seconds    34 non-null     float64
 29  complex_join_pandas_seconds     170 non-null    float64
 30  complex_join_polars_seconds     170 non-null    float64
 31  complex_join_duckdb_seconds     170 non-null    float64
 32  complex_join_fireducks_seconds  34 non-null     float64
 33  timeseries_pandas_seconds       170 non-null    float64
 34  timeseries_polars_seconds       170 non-null    float64
 35  timeseries_duckdb_seconds       170 non-null    float64
 36  timeseries_fireducks_seconds    34 non-null     float64
 37  script_name                     170 non-null    object
dtypes: float64(20), int64(3), object(15)
memory usage: 50.6+ KB

In [3]:
# Removing fireduck for now because there is not data(yet)
#fireduck_columns = [col for col in b_df.columns if 'fireducks_' in col]
#b_df.drop(columns=fireduck_columns, inplace=True)

#b_df.info()

In [4]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(166, 38)

In [5]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(6)
b_df.head(3)

,timestamp,hostname,platform,system,release,version,machine,processor,cpu_count_logical,cpu_count_physical,...,statistics_fireducks_seconds,complex_join_pandas_seconds,complex_join_polars_seconds,complex_join_duckdb_seconds,complex_join_fireducks_seconds,timeseries_pandas_seconds,timeseries_polars_seconds,timeseries_duckdb_seconds,timeseries_fireducks_seconds,script_name
0,2025-08-28T19:37:29.241650,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,44.743244,6.037812,26.736806,NaN,22.656234,7.020198,3.894986,NaN,benchmark_01.py
1,2025-08-28T21:16:05.419895,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,23.235775,1.426380,4.835438,NaN,12.861529,2.425745,0.614240,NaN,benchmark.py
2,2025-08-28T21:25:30.654371,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,28.530276,1.482855,5.431484,NaN,16.994786,2.902070,0.595494,NaN,benchmark_02.py

In [6]:
def rank_methods(df, operation_col_prefix):
    time_cols = [col for col in df.columns if col.startswith(operation_col_prefix) and col.endswith('_seconds')]
    rank_df = pd.DataFrame()
    rank_df['hostname'] = df['hostname']
    rank_df['cpu_brand'] = df['cpu_brand'] 
    rank_df['dataset_size'] = df['dataset_size']
    rank_df['dataset_format'] = df['dataset_format']
    
    for col in time_cols:
        rank_col = f"rank_{col}"
        # Only rank non-zero values, assign max rank to zeros
        mask = df[col] > 0
        rank_df[rank_col] = df[col].where(mask).rank(method='min')
        max_rank = rank_df[rank_col].max()
        rank_df[rank_col] = rank_df[rank_col].fillna(max_rank + 1)
    
    return rank_df

In [7]:
filter_group_ranks = rank_methods(b_df, 'filter_group_')
sort_values_cols = [col for col in filter_group_ranks.columns if col.startswith('rank_filter_group_')]
filter_group_ranks[sort_values_cols] = filter_group_ranks[sort_values_cols].astype(int)
filter_group_ranks = filter_group_ranks.sort_values(by=sort_values_cols + ['hostname', 'dataset_format'])
filter_group_ranks

,hostname,cpu_brand,dataset_size,dataset_format,rank_filter_group_pandas_seconds,rank_filter_group_polars_seconds,rank_filter_group_duckdb_seconds,rank_filter_group_fireducks_seconds
169,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,1,27,13,2
168,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,2,26,16,5
158,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,3,13,34,35
45,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,4,40,107,35
49,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,5,22,24,35
...,...,...,...,...,...,...,...,...
16,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,162,144,105,35
54,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,163,162,128,35
32,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,164,145,126,35
33,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,165,159,129,35
0,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,166,165,144,35

In [8]:
def get_df_by_test(df: pd.DataFrame, cols_to_group: list, metric: str) -> pd.DataFrame:
    # Properly combine columns - create a new list instead of using append
    columns_to_select = cols_to_group + [metric]
    
    # Select the relevant columns
    df_subset = df[columns_to_select]
    
    # Remove rows where the metric is null/zero (assuming you want valid measurements)
    df_filtered = df_subset[df_subset[metric] > 0]  # or use .notna() if you want non-null values
    
    # Group by the specified columns and get minimum values
    grouped = df_filtered.groupby(cols_to_group)
    return grouped.min().reset_index().sort_values(by=metric)

In [9]:
cols_to_group = [ "dataset_format","hostname", "cpu_brand", "system"]
for col_to_rank in time_cols:
    print(f"Ranking by: {col_to_rank}")
    df_by_test = get_df_by_test(b_df, cols_to_group, col_to_rank)
    display(df_by_test)
    print("\n")

Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_pandas_seconds
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.255371
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.269150
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.270499
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.271542
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.273861
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.294695
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.299070
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.301545
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.307721
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.320752
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.382879
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.416637
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.425848
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.428233
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.434067
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.447669
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.461787
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.468646
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.493353
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.535098
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.663562
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.702786
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.731955
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.962332
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,5.030746
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,5.358341
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,10.411298
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,11.963554

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_polars_seconds
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.071505
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.084910
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.088948
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.094960
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.118766
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.134381
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.137532
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.140645
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.141072
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.144457
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.155707
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.180809
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.195381
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.199044
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.201567
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.203178
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.204483
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.208222
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.216848
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.306664
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.340602
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.355334
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.488726
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.542422
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.565336
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.614996
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.615354
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.625782

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_duckdb_seconds
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.033242
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.033806
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.034815
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.035578
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.041783
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.043035
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.047966
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.048145
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.052390
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.055147
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.058527
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.062853
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.073407
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.083453
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.084105
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.094551
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.124491
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.137175
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.156793
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.160650
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.173057
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.173424
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.194292
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.224818
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.238558
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.337646
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.501835
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.779136

Ranking by: filter_group_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_fireducks_seconds
1,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.001497
3,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.001550
2,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.003029
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.003224

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,system,statistics_pandas_seconds
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.180947
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.186431
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.208207
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.216869
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.219204
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.224237
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.224567
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.227019
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.234241
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.244498
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.303906
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.336234
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.339025
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.370749
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.396269
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.407656
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.465929
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.471190
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.580449
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.625986
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.676553
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.752458
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.837387
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.850339
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,5.357317
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,6.423730
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,10.376254
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,16.368223

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,system,statistics_polars_seconds
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.060096
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.063914
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.085318
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.087296
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.095885
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.101301
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.104566
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.109605
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.121048
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.121391
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.140574
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.145582
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.205388
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.210085
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.225771
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.228205
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.232830
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.256583
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.288694
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.314736
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.383513
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.398507
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.480064
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.510830
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.516206
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.516427
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.645693
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.918267

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,statistics_duckdb_seconds
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.050525
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.058118
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.059392
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.061123
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.062178
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.064059
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.077605
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.079360
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.080986
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.081314
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.093565
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.109509
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.140855
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.149406
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.150332
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.167851
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.210103
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.211529
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.222407
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.252737
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.358730
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.447324
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.494045
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.498727
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.536384
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.572973
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.673051
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.855804

Ranking by: statistics_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,statistics_fireducks_seconds
1,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.000213
3,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.000250
2,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000484
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000491

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_pandas_seconds
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,1.826722
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,1.845459
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,2.086920
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,2.156851
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,2.234629
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,2.335326
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.501844
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,2.504857
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.505848
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,2.565839
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,2.769056
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,2.862606
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,2.937153
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,3.052452
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,3.226381
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,3.328890
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,3.534181
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,3.618343
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,4.149068
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,4.155437
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,5.558602
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,5.822155
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,6.052842
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,6.501427
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,8.088280
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,8.353409
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,23.235775
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,29.201547

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_polars_seconds
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.482777
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.483308
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.491799
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.501921
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.520723
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.522786
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.543240
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.555005
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.575433
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.591883
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.850386
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.853281
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.896909
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.921715
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.938912
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.954018
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,1.004030
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,1.144325
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,1.228163
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,1.284159
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,1.390336
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,1.426380
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.794887
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.805672
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,1.869724
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,2.062053
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,2.212631
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,2.617505

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_duckdb_seconds
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,3.195443
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,3.285292
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,3.581286
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,3.594456
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,4.237417
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,4.595454
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,4.715118
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,4.746880
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,4.874635
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,5.140088
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,6.219584
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,8.425919
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,10.624296
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,11.430921
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,13.439244
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,14.769567
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,17.261537
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,17.445712
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,17.489565
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,17.805404
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,21.596404
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,21.924554
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,31.624210
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,32.850278
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,36.837714
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,37.671142
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,37.993901
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,41.291982

Ranking by: complex_join_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_fireducks_seconds
1,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.000457
3,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.000522
2,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.001163
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.001865

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_pandas_seconds
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.358497
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.360709
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.493485
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.499842
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.508836
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.518303
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.567358
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.573071
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.595449
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.600759
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.689184
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.693135
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.709507
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.735251
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.751010
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.769225
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.832497
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.880524
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.906153
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.924786
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,1.383846
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,1.411530
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,1.468229
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,1.524298
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,7.893992
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,8.824875
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,12.861529
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,19.606401

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_polars_seconds
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,1.899370
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,1.899804
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,1.915359
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,1.916424
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,1.930856
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,1.943624
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,1.965067
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,2.035647
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.135860
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.138136
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,2.216953
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,2.397435
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,2.408907
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,2.631081
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,2.661209
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,2.826220
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,3.539412
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,3.778609
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,3.794873
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,3.897610
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,4.261347
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,4.304416
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,4.928691
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,4.979773
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,7.324557
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,8.000622
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,8.178485
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,8.300135

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_duckdb_seconds
19,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.114004
5,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.127095
21,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.142895
15,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.144168
23,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.147826
20,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.152020
7,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.154963
6,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.160707
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.169678
9,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.196162
24,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.205527
25,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.238715
22,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.242685
11,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.313320
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.377764
26,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.386797
12,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.408385
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.451360
10,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.561461
18,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.604427
4,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.639191
8,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.831122
17,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.844055
3,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.987728
14,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.187024
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.253193
16,parquet,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,1.321530
2,csv,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,1.425144

Ranking by: timeseries_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_fireducks_seconds
3,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.306496
1,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Linux,0.338578
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.667169
2,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.745909

In [10]:
# Filter Group Pandas
fg_p = b_df[["hostname", "cpu_brand","dataset_size", "dataset_format", "filter_group_pandas_seconds"]]
fg_p = fg_p.groupby(by=["hostname", "cpu_brand","dataset_size", "dataset_format"]).min().reset_index()
fg_p = fg_p.rename(columns={"filter_group_pandas_seconds": "min_time_seconds"})
fg_p = fg_p.sort_values(by=["dataset_size","min_time_seconds", "hostname",  "dataset_format"])
fg_p

,hostname,cpu_brand,dataset_size,dataset_format,min_time_seconds
13,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,0.255371
16,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,0.270499
12,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,csv,0.271542
10,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,0.294695
3,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,parquet,0.299070
17,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,parquet,0.301545
11,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,parquet,0.307721
2,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,0.320752
21,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,parquet,0.382879
22,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,csv,0.416637
23,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,parquet,0.425848
20,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,csv,0.428233
8,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,csv,0.434067
1,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,parquet,0.447669
0,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,csv,0.461787
9,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,parquet,0.468646
25,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,parquet,0.493353
24,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,0.535098
5,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,parquet,0.663562
4,HP-EB1030G2-02,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,csv,0.702786
6,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,csv,0.731955
7,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,parquet,0.962332
15,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,parquet,5.030746
19,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,parquet,5.358341
18,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,10.411298
14,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,11.963554

In [11]:
print(f"The fastest filter_group_pandas_seconds is {fg_p['min_time_seconds'].min()} seconds")

The fastest filter_group_pandas_seconds is 0.255371 seconds

In [12]:
# Calculate the average operation time per row for each library
library_suffixes = ['pandas', 'polars', 'duckdb', 'fireducks']  # Add 'fireducks' if/when data is available

for lib in library_suffixes:
    lib_cols = [col for col in b_df.columns if col.endswith(f'_{lib}_seconds')]
    b_df[f'{lib}_avg_time'] = b_df[lib_cols].mean(axis=1)

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)+ ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each library
host_lib_avg = b_df.groupby('host_cpu')[[f'{lib}_avg_time' for lib in library_suffixes]].mean().reset_index()

# Sort each library's ranking and display
with pd.option_context('display.max_colwidth', None):
    for lib in library_suffixes:
        print(f"Ranking by average {lib} time (ascending):")
        display(host_lib_avg[['host_cpu', f'{lib}_avg_time']].sort_values(f'{lib}_avg_time'))
        print("\n")
# Optionally, display the full table
host_lib_avg

Ranking by average pandas time (ascending):

,host_cpu,pandas_avg_time
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.728984
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.491011
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.787122
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.144046
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.578181
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,2.740769
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,3.109042
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,3.681693
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,3.707179
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,3.961236
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,4.299194
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,5.444306
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,15.408611
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,20.426597

Ranking by average polars time (ascending):

,host_cpu,polars_avg_time
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.742445
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.766998
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.848281
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.904037
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.966045
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.160133
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.445962
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.487777
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,1.578317
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.760348
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.889734
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.576411
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,3.323331
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,3.513165

Ranking by average duckdb time (ascending):

,host_cpu,duckdb_avg_time
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.333418
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,2.441456
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,3.009408
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.028193
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,3.167542
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.188277
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,4.469477
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,5.468166
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,6.429801
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,7.451571
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.192535
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,11.993303
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,12.402753
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,15.853511

Ranking by average fireducks time (ascending):

,host_cpu,fireducks_avg_time
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.158445
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.794866
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,NaN
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,NaN
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,NaN
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,NaN
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,NaN
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,NaN
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,NaN
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,NaN
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,NaN
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,NaN
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,NaN
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,NaN

,host_cpu,pandas_avg_time,polars_avg_time,duckdb_avg_time,fireducks_avg_time
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,1.491011,2.576411,11.192535,0.794866
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,4.299194,0.966045,3.009408,NaN
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CP...,3.109042,3.513165,12.402753,NaN
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,3.681693,3.323331,11.993303,NaN
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,2.578181,1.889734,7.451571,NaN
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,3.961236,0.766998,15.853511,NaN
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | L...,0.728984,0.742445,3.167542,0.158445
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,5.444306,0.904037,2.333418,NaN
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,20.426597,1.487777,3.028193,NaN
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,3.707179,0.848281,2.441456,NaN
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,15.408611,1.760348,3.188277,NaN
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,1.787122,1.160133,4.469477,NaN
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,2.144046,1.578317,6.429801,NaN
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,2.740769,1.445962,5.468166,NaN

In [13]:
# Rank hosts (host + CPU) by the average time across all libraries (pandas, polars, duckdb)
#all_lib_time_cols = [col for col in b_df.columns if col.endswith('_pandas_seconds') or col.endswith('_polars_seconds') or col.endswith('_duckdb_seconds')]

b_df['all_libs_avg_time'] = b_df[time_cols].mean(axis=1)

# Group by host+cpu and get the mean
host_alllibs_avg = b_df.groupby('host_cpu')['all_libs_avg_time'].mean().reset_index()

# Sort to get the fastest overall
host_alllibs_avg_sorted = host_alllibs_avg.sort_values('all_libs_avg_time', ascending=True).reset_index(drop=True)

print("Ranking by average time across all libraries (fastest PC overall):")
with pd.option_context('display.max_colwidth', None):
    display(host_alllibs_avg_sorted)

Ranking by average time across all libraries (fastest PC overall):

,host_cpu,all_libs_avg_time
0,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,1.199354
1,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,2.332305
2,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,2.472244
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.758216
4,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.893920
5,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,3.218299
6,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,3.384055
7,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,3.973162
8,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,4.013706
9,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,6.332776
10,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,6.341653
11,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.785746
12,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,6.860582
13,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,8.314189

In [14]:
# Calculate the average operation time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  # Fixed: startswith
    b_df[f'{test}_avg_time'] = b_df[test_cols].mean(axis=1)  # Fixed: use test, not lib

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each test
test_avg_cols = [f'{test}_avg_time' for test in test_prefixes]
host_test_avg = b_df.groupby('host_cpu')[test_avg_cols].mean().reset_index()

# Sort each test's ranking and display
# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by average {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_avg[['host_cpu', f'{test}_avg_time']].sort_values(f'{test}_avg_time'))
    print("\n")

# Display the full table
host_test_avg

Ranking by average filter_group time (ascending):

,host_cpu,filter_group_avg_time
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.197090
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.382449
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.442778
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.475525
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.804758
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.821436
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.900283
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.935096
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,1.006136
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.072774
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.287018
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.342407
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.823748
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.970885

Ranking by average statistics time (ascending):

,host_cpu,statistics_avg_time
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.149658
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.351958
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.430578
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.578091
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.869160
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.895226
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.908945
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.945809
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,1.016160
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.097377
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.360749
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.448765
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,4.208320
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,7.309481

Ranking by average complex_join time (ascending):

,host_cpu,complex_join_avg_time
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,3.682625
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,5.574418
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,6.342929
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,6.935108
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,7.703487
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,9.969111
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,10.487334
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,11.430337
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.718066
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,13.052801
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,13.698890
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,17.847316
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,18.834236
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,23.890014

Ranking by average timeseries time (ascending):

,host_cpu,timeseries_avg_time
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.768042
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.451081
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,1.756804
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.873898
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.883217
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.075459
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.142782
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.496969
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.646161
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.748607
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,4.326716
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,4.816141
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.058113
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,8.277500

,host_cpu,filter_group_avg_time,statistics_avg_time,complex_join_avg_time,timeseries_avg_time
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.821436,0.869160,11.718066,2.646161
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,1.006136,1.016160,6.935108,2.075459
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CP...,1.342407,1.360749,17.847316,4.816141
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,1.072774,1.097377,18.834236,4.326716
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.804758,0.908945,11.430337,2.748607
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.900283,0.895226,23.890014,1.756804
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | L...,0.197090,0.149658,3.682625,0.768042
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,1.287018,1.448765,6.342929,2.496969
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,3.970885,7.309481,13.698890,8.277500
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.935096,0.945809,5.574418,1.873898
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,3.823748,4.208320,13.052801,6.058113
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.382449,0.351958,7.703487,1.451081
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.475525,0.430578,10.487334,2.142782
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.442778,0.578091,9.969111,1.883217

In [15]:
# Calculate the minumum time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  
    b_df[f'{test}_min_time'] = b_df[test_cols].min(axis=1)  

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the min per host+cpu for each test
test_min_cols = [f'{test}_min_time' for test in test_prefixes]
host_test_min = b_df.groupby('host_cpu')[test_min_cols].min().reset_index()

# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by minimum time {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_min[['host_cpu', f'{test}_min_time']].sort_values(f'{test}_min_time'))
    print("\n")

# Display the full table
host_test_min

Ranking by minimum time filter_group time (ascending):

,host_cpu,filter_group_min_time
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.001497
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.033806
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.035578
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058527
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.062853
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.073407
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558

Ranking by minimum time statistics time (ascending):

,host_cpu,statistics_min_time
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.000213
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.050525
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.064059
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.093565
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.109509
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.140855
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.167851
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830

Ranking by minimum time complex_join time (ascending):

,host_cpu,complex_join_min_time
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.000457
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.483308
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.520723
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.543240
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.850386
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.938912
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.390336
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631

Ranking by minimum time timeseries time (ascending):

,host_cpu,timeseries_min_time
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.114004
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.144168
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.152020
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.205527
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.238715
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.242685
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.377764
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530

,host_cpu,filter_group_min_time,statistics_min_time,complex_join_min_time,timeseries_min_time
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.003029,0.000484,0.001163,0.667169
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.034815,0.062178,0.543240,0.144168
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CP...,0.160650,0.510830,2.212631,1.321530
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,0.238558,0.358730,1.869724,0.844055
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.084105,0.211529,1.144325,0.604427
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.033806,0.050525,0.483308,0.114004
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | L...,0.001497,0.000213,0.000457,0.152020
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,0.033242,0.059392,0.482777,0.142895
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.062853,0.140855,0.938912,0.242685
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.035578,0.064059,0.520723,0.147826
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,0.073407,0.109509,1.390336,0.205527
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.058527,0.093565,0.850386,0.238715
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.173057,0.140574,0.896909,0.386797
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.094551,0.167851,0.921715,0.377764

In [16]:
# Calculate the minimum time per row for each test and annotate which library achieved it (NaN-safe)

test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries']

for test in test_prefixes:
    # Raw timing columns only
    test_cols = [
        col for col in b_df.columns
        if col.startswith(f'{test}_') and col.endswith('_seconds')
    ]
    if not test_cols:
        b_df[f'{test}_min_time'] = float('nan')
        b_df[f'{test}_min_library'] = None
        continue

    # Convert to numeric (coerce 'N/A', blanks, etc. to NaN)
    numeric = b_df[test_cols].apply(pd.to_numeric, errors='coerce')

    # Row-wise min ignoring NaNs
    min_times = numeric.min(axis=1, skipna=True)

    # Identify the column name (library) producing the min ignoring NaNs.
    # pandas idxmin(skipna=True) returns NaN if the entire row is NaN.
    min_cols = numeric.idxmin(axis=1, skipna=True)

    suffix_len = len('_seconds')
    min_libs = []
    for col_name, all_nan in zip(min_cols, numeric.isna().all(axis=1)):
        if all_nan or pd.isna(col_name):
            min_libs.append(None)
        else:
            # column pattern: <test>_<library>_seconds
            lib_name = col_name[len(test) + 1: -suffix_len]
            min_libs.append(lib_name)

    b_df[f'{test}_min_time'] = min_times
    b_df[f'{test}_min_library'] = min_libs

# Unique host identifier
b_df['host_cpu'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['system'].astype(str)
)

# Aggregate: pick min time & corresponding library per host
host_rows = []
for host, g in b_df.groupby('host_cpu'):
    row = {'host_cpu': host}
    for test in test_prefixes:
        time_col = f'{test}_min_time'
        lib_col = f'{test}_min_library'
        if time_col not in g.columns or lib_col not in g.columns:
            row[time_col] = float('nan')
            row[lib_col] = None
            continue
        # valid rows for this test
        g_valid = g.dropna(subset=[time_col])
        if g_valid.empty:
            row[time_col] = float('nan')
            row[lib_col] = None
        else:
            # take the first row with minimal time
            min_idx = g_valid[time_col].idxmin()
            row[time_col] = g_valid.loc[min_idx, time_col]
            row[lib_col] = g_valid.loc[min_idx, lib_col]
    host_rows.append(row)

host_test_min = pd.DataFrame(host_rows)

# Display rankings per test including which library produced the min
for test in test_prefixes:
    time_col = f'{test}_min_time'
    lib_col = f'{test}_min_library'
    if time_col not in host_test_min.columns:
        continue
    print(f"Ranking by minimum {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(
            host_test_min[['host_cpu', time_col, lib_col]]
            .sort_values(time_col, na_position='last')
        )
    print("\n")

# Optional summary: frequency of fastest library per test
summary_rows = []
for test in test_prefixes:
    lib_col = f'{test}_min_library'
    if lib_col in host_test_min.columns:
        counts = host_test_min[lib_col].value_counts(dropna=True)
        for lib, cnt in counts.items():
            summary_rows.append({'test': test, 'library': lib, 'wins': cnt})
fastest_summary = pd.DataFrame(summary_rows).sort_values(['test', 'wins'], ascending=[True, False])
print("Fastest library counts per test:")
display(fastest_summary)

# Full aggregated table (one row per host with min times + libraries per test)
host_test_min

Ranking by minimum filter_group time (ascending):

,host_cpu,filter_group_min_time,filter_group_min_library
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.001497,fireducks
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029,fireducks
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242,duckdb
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.033806,duckdb
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815,duckdb
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.035578,duckdb
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058527,duckdb
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.062853,duckdb
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.073407,duckdb
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105,duckdb
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551,duckdb
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650,duckdb
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057,duckdb
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558,duckdb

Ranking by minimum statistics time (ascending):

,host_cpu,statistics_min_time,statistics_min_library
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.000213,fireducks
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484,fireducks
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.050525,duckdb
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392,duckdb
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178,duckdb
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.064059,duckdb
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.093565,duckdb
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.109509,duckdb
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574,polars
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.140855,duckdb
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.167851,duckdb
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529,duckdb
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730,duckdb
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830,polars

Ranking by minimum complex_join time (ascending):

,host_cpu,complex_join_min_time,complex_join_min_library
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.000457,fireducks
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163,fireducks
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777,polars
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.483308,polars
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.520723,polars
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.543240,polars
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.850386,polars
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909,polars
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715,polars
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.938912,polars
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325,polars
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.390336,polars
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724,polars
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631,polars

Ranking by minimum timeseries time (ascending):

,host_cpu,timeseries_min_time,timeseries_min_library
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.114004,duckdb
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895,duckdb
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.144168,duckdb
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826,duckdb
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Linux,0.152020,duckdb
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.205527,duckdb
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.238715,duckdb
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.242685,duckdb
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.377764,duckdb
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797,duckdb
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427,duckdb
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169,fireducks
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055,duckdb
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530,duckdb

Fastest library counts per test:

           test    library  wins
5  complex_join     polars    12
6  complex_join  fireducks     2
0  filter_group     duckdb    12
1  filter_group  fireducks     2
2    statistics     duckdb    10
3    statistics  fireducks     2
4    statistics     polars     2
7    timeseries     duckdb    13
8    timeseries  fireducks     1

,host_cpu,filter_group_min_time,filter_group_min_library,statistics_min_time,statistics_min_library,complex_join_min_time,complex_join_min_library,timeseries_min_time,timeseries_min_library
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.003029,fireducks,0.000484,fireducks,0.001163,fireducks,0.667169,fireducks
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.034815,duckdb,0.062178,duckdb,0.543240,polars,0.144168,duckdb
2,HP-EB1030G2-02 | Intel(R) Core(TM) i7-7600U CP...,0.160650,duckdb,0.510830,polars,2.212631,polars,1.321530,duckdb
3,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,0.238558,duckdb,0.358730,duckdb,1.869724,polars,0.844055,duckdb
4,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.084105,duckdb,0.211529,duckdb,1.144325,polars,0.604427,duckdb
5,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.033806,duckdb,0.050525,duckdb,0.483308,polars,0.114004,duckdb
6,Inspiron3030S | Intel(R) Core(TM) i7-14700 | L...,0.001497,fireducks,0.000213,fireducks,0.000457,fireducks,0.152020,duckdb
7,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,0.033242,duckdb,0.059392,duckdb,0.482777,polars,0.142895,duckdb
8,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.062853,duckdb,0.140855,duckdb,0.938912,polars,0.242685,duckdb
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.035578,duckdb,0.064059,duckdb,0.520723,polars,0.147826,duckdb
10,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,0.073407,duckdb,0.109509,duckdb,1.390336,polars,0.205527,duckdb
11,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.058527,duckdb,0.093565,duckdb,0.850386,polars,0.238715,duckdb
12,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.173057,duckdb,0.140574,polars,0.896909,polars,0.386797,duckdb
13,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.094551,duckdb,0.167851,duckdb,0.921715,polars,0.377764,duckdb