In [14]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [15]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       138 non-null    object
 1   hostname                        138 non-null    object
 2   platform                        138 non-null    object
 3   system                          138 non-null    object
 4   release                         138 non-null    object
 5   version                         138 non-null    object
 6   machine                         138 non-null    object
 7   processor                       138 non-null    object
 8   cpu_count_logical               138 non-null    int64
 9   cpu_count_physical              138 non-null    int64
 10  cpu_freq_max                    138 non-null    float64
 11  cpu_freq_current                138 non-null    float64
 12  memory_total_gb                 138 non-null    float64
 13  memory_available_gb             138 non-null    float64
 14  python_version                  138 non-null    object
 15  python_implementation           138 non-null    object
 16  cpu_brand                       138 non-null    object
 17  cpu_arch                        138 non-null    object
 18  dataset_size                    138 non-null    int64
 19  dataset_name                    138 non-null    object
 20  dataset_format                  138 non-null    object
 21  filter_group_pandas_seconds     138 non-null    float64
 22  filter_group_polars_seconds     138 non-null    float64
 23  filter_group_duckdb_seconds     138 non-null    float64
 24  filter_group_fireducks_seconds  26 non-null     float64
 25  statistics_pandas_seconds       138 non-null    float64
 26  statistics_polars_seconds       138 non-null    float64
 27  statistics_duckdb_seconds       138 non-null    float64
 28  statistics_fireducks_seconds    26 non-null     float64
 29  complex_join_pandas_seconds     138 non-null    float64
 30  complex_join_polars_seconds     138 non-null    float64
 31  complex_join_duckdb_seconds     138 non-null    float64
 32  complex_join_fireducks_seconds  26 non-null     float64
 33  timeseries_pandas_seconds       138 non-null    float64
 34  timeseries_polars_seconds       138 non-null    float64
 35  timeseries_duckdb_seconds       138 non-null    float64
 36  timeseries_fireducks_seconds    26 non-null     float64
 37  script_name                     138 non-null    object
dtypes: float64(20), int64(3), object(15)
memory usage: 41.1+ KB

In [16]:
# Removing fireduck for now because there is not data(yet)
#fireduck_columns = [col for col in b_df.columns if 'fireducks_' in col]
#b_df.drop(columns=fireduck_columns, inplace=True)

#b_df.info()

In [17]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(134, 38)

In [18]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(6)
b_df.head(3)

,timestamp,hostname,platform,system,release,version,machine,processor,cpu_count_logical,cpu_count_physical,...,statistics_fireducks_seconds,complex_join_pandas_seconds,complex_join_polars_seconds,complex_join_duckdb_seconds,complex_join_fireducks_seconds,timeseries_pandas_seconds,timeseries_polars_seconds,timeseries_duckdb_seconds,timeseries_fireducks_seconds,script_name
0,2025-08-28T19:37:29.241650,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,44.743244,6.037812,26.736806,NaN,22.656234,7.020198,3.894986,NaN,benchmark_01.py
1,2025-08-28T21:16:05.419895,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,23.235775,1.426380,4.835438,NaN,12.861529,2.425745,0.614240,NaN,benchmark.py
2,2025-08-28T21:25:30.654371,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,28.530276,1.482855,5.431484,NaN,16.994786,2.902070,0.595494,NaN,benchmark_02.py

In [19]:
def rank_methods(df, operation_col_prefix):
    time_cols = [col for col in df.columns if col.startswith(operation_col_prefix) and col.endswith('_seconds')]
    rank_df = pd.DataFrame()
    rank_df['hostname'] = df['hostname']
    rank_df['cpu_brand'] = df['cpu_brand'] 
    rank_df['dataset_size'] = df['dataset_size']
    rank_df['dataset_format'] = df['dataset_format']
    
    for col in time_cols:
        rank_col = f"rank_{col}"
        # Only rank non-zero values, assign max rank to zeros
        mask = df[col] > 0
        rank_df[rank_col] = df[col].where(mask).rank(method='min')
        max_rank = rank_df[rank_col].max()
        rank_df[rank_col] = rank_df[rank_col].fillna(max_rank + 1)
    
    return rank_df

In [20]:
filter_group_ranks = rank_methods(b_df, 'filter_group_')
sort_values_cols = [col for col in filter_group_ranks.columns if col.startswith('rank_filter_group_')]
filter_group_ranks[sort_values_cols] = filter_group_ranks[sort_values_cols].astype(int)
filter_group_ranks = filter_group_ranks.sort_values(by=sort_values_cols + ['hostname', 'dataset_format'])
filter_group_ranks

,hostname,cpu_brand,dataset_size,dataset_format,rank_filter_group_pandas_seconds,rank_filter_group_polars_seconds,rank_filter_group_duckdb_seconds,rank_filter_group_fireducks_seconds
45,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,1,20,85,27
49,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,2,11,17,27
47,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,3,16,84,27
44,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,4,25,78,27
37,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,5,5,70,27
...,...,...,...,...,...,...,...,...
16,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,130,113,83,27
54,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,131,130,100,27
32,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,132,114,98,27
33,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,133,128,101,27
0,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,134,133,116,27

In [21]:
def get_df_by_test(df: pd.DataFrame, cols_to_group: list, metric: str) -> pd.DataFrame:
    # Properly combine columns - create a new list instead of using append
    columns_to_select = cols_to_group + [metric]
    
    # Select the relevant columns
    df_subset = df[columns_to_select]
    
    # Remove rows where the metric is null/zero (assuming you want valid measurements)
    df_filtered = df_subset[df_subset[metric] > 0]  # or use .notna() if you want non-null values
    
    # Group by the specified columns and get minimum values
    grouped = df_filtered.groupby(cols_to_group)
    return grouped.min().reset_index().sort_values(by=metric)

In [22]:
cols_to_group = [ "dataset_format","hostname", "cpu_brand", "system"]
for col_to_rank in time_cols:
    print(f"Ranking by: {col_to_rank}")
    df_by_test = get_df_by_test(b_df, cols_to_group, col_to_rank)
    display(df_by_test)
    print("\n")

Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_pandas_seconds
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.270499
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.294695
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.299070
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.301545
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.307721
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.320752
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.382879
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.416637
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.425848
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.428233
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.434067
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.447669
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.461787
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.468646
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.493353
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.535098
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.731955
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.962332
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,4.535108
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,5.030746
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,5.358341
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,10.411298
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,10.773492
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,11.963554

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_polars_seconds
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.071505
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.084910
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.088948
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.094960
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.137532
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.140645
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.141072
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.155707
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.180809
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.195381
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.199044
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.201567
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.203178
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.204483
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.208222
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.216848
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.306664
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.340602
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.355334
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.488726
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.505032
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.614996
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.615354
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.625782

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_duckdb_seconds
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.033806
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.034815
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.035578
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.041874
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.043035
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.048145
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.052390
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.058527
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.062853
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.073407
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.083453
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.084105
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.094551
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.124491
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.137175
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.156793
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.173057
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.194292
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.224818
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.238558
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.337646
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.501835
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.555641
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.779136

Ranking by: filter_group_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_fireducks_seconds
1,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.003029
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.003224

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,system,statistics_pandas_seconds
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.219204
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.224237
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.224567
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.227019
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.234241
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.244498
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.303906
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.336234
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.339025
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.370749
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.396269
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.407656
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.465929
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.471190
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.625986
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.752458
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.837387
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.850339
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,4.714796
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,5.357317
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,6.423730
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,10.376254
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,11.551054
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,16.368223

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,system,statistics_polars_seconds
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.060096
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.063914
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.095885
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.104566
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.121048
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.121391
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.140574
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.145582
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.205388
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.210085
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.225771
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.228205
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.232830
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.249715
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.256583
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.288694
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.314736
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.383513
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.398507
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.480064
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.516427
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.645693
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.732186
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.918267

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,statistics_duckdb_seconds
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.050525
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.061123
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.062178
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.064059
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.077605
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.080986
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.093565
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.109509
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.114555
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.140855
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.149406
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.150332
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.167851
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.210103
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.211529
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.222407
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.252737
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.358730
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.447324
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.494045
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.498727
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.572973
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.679022
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.855804

Ranking by: statistics_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,statistics_fireducks_seconds
1,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000484
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000491

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_pandas_seconds
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,2.234629
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,2.335326
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.501844
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,2.504857
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.505848
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,2.565839
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,2.769056
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,2.862606
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,2.937153
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,3.052452
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,3.226381
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,3.328890
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,3.534181
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,3.618343
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,4.149068
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,4.155437
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,5.822155
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,6.052842
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,7.560121
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,8.088280
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,8.353409
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,16.443824
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,23.235775
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,29.201547

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_polars_seconds
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.483308
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.501921
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.520723
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.522786
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.543240
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.555005
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.848587
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.850386
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.853281
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.896909
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.921715
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.938912
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.954018
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,1.004030
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,1.144325
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,1.228163
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,1.264944
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,1.284159
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,1.390336
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,1.426380
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.794887
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.805672
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,1.869724
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,2.062053

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_duckdb_seconds
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,3.195443
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,3.285292
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,3.581286
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,3.594456
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,4.237417
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,4.595454
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,4.715118
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,4.746880
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,4.874635
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,5.140088
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,6.219584
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,8.425919
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,13.439244
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,14.769567
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,17.261537
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,17.445712
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,17.489565
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,17.805404
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,21.596404
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,21.924554
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,31.624210
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,32.850278
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,37.671142
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,41.291982

Ranking by: complex_join_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_fireducks_seconds
1,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.001163
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.001865

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_pandas_seconds
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.493485
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.518303
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.567358
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.573071
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.595449
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.600759
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.689184
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.693135
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.709507
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.735251
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.751010
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.769225
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.832497
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.880524
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.906153
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.924786
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,1.383846
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,1.524298
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,7.080207
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,7.893992
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,8.824875
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,12.861529
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,14.275908
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,19.606401

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_polars_seconds
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,1.915359
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,1.930856
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,1.943624
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,1.965067
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,2.035647
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.135860
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.138136
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,2.216953
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,2.397435
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,2.401134
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,2.408907
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,2.631081
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,2.661209
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,2.826220
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,3.539412
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,3.778609
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,3.794873
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,3.897610
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,4.261347
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,4.304416
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,4.928691
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,4.979773
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,8.178485
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,8.300135

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_duckdb_seconds
16,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.114004
4,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.127095
13,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.144168
19,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.147826
1,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.169678
17,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.186427
7,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.196162
20,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.205527
21,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.238715
18,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.242685
9,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.313320
23,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.377764
22,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.386797
10,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.408385
11,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.451360
8,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.561461
15,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.604427
3,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.639191
5,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.673473
6,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.831122
14,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.844055
2,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.987728
12,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.187024
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.253193

Ranking by: timeseries_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_fireducks_seconds
0,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.667169
1,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.745909

In [23]:
# Filter Group Pandas
fg_p = b_df[["hostname", "cpu_brand","dataset_size", "dataset_format", "filter_group_pandas_seconds"]]
fg_p = fg_p.groupby(by=["hostname", "cpu_brand","dataset_size", "dataset_format"]).min().reset_index()
fg_p = fg_p.rename(columns={"filter_group_pandas_seconds": "min_time_seconds"})
fg_p = fg_p.sort_values(by=["dataset_size","min_time_seconds", "hostname",  "dataset_format"])
fg_p

,hostname,cpu_brand,dataset_size,dataset_format,min_time_seconds
14,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,0.270499
8,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,0.294695
3,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,parquet,0.299070
15,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,parquet,0.301545
9,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,parquet,0.307721
2,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,0.320752
19,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,parquet,0.382879
20,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,csv,0.416637
21,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,parquet,0.425848
18,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,csv,0.428233
6,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,csv,0.434067
1,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,parquet,0.447669
0,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,csv,0.461787
7,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,parquet,0.468646
23,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,parquet,0.493353
22,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,0.535098
4,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,csv,0.731955
5,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,parquet,0.962332
11,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,4.535108
13,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,parquet,5.030746
17,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,parquet,5.358341
16,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,10.411298
10,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,csv,10.773492
12,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,11.963554

In [24]:
print(f"The fastest filter_group_pandas_seconds is {fg_p['min_time_seconds'].min()} seconds")

The fastest filter_group_pandas_seconds is 0.270499 seconds

In [29]:
# Calculate the average operation time per row for each library
library_suffixes = ['pandas', 'polars', 'duckdb', 'fireducks']  # Add 'fireducks' if/when data is available

for lib in library_suffixes:
    lib_cols = [col for col in b_df.columns if col.endswith(f'_{lib}_seconds')]
    b_df[f'{lib}_avg_time'] = b_df[lib_cols].mean(axis=1)

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each library
host_lib_avg = b_df.groupby('host_cpu')[[f'{lib}_avg_time' for lib in library_suffixes]].mean().reset_index()

# Sort each library's ranking and display
for lib in library_suffixes:
    print(f"Ranking by average {lib} time (ascending):")
    display(host_lib_avg[['host_cpu', f'{lib}_avg_time']].sort_values(f'{lib}_avg_time'))
    print("\n")

# Optionally, display the full table
host_lib_avg

Ranking by average pandas time (ascending):

                                             host_cpu  pandas_avg_time
0   EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz         1.491011
9   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...         1.787122
10  VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...         2.144046
3   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...         2.578181
11  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...         2.740769
2   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...         3.681693
7   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...         3.707179
4      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX         3.961236
1    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900         4.299194
5          Inspiron3030S | Intel(R) Core(TM) i7-14700        11.492783
8     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M        15.408611
6       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX        20.426597

Ranking by average polars time (ascending):

                                             host_cpu  polars_avg_time
4      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX         0.766998
7   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...         0.848281
1    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900         0.966045
5          Inspiron3030S | Intel(R) Core(TM) i7-14700         1.156464
9   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...         1.160133
11  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...         1.445962
6       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX         1.487777
10  VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...         1.578317
8     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M         1.760348
3   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...         1.889734
0   EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz         2.576411
2   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...         3.323331

Ranking by average duckdb time (ascending):

                                             host_cpu  duckdb_avg_time
5          Inspiron3030S | Intel(R) Core(TM) i7-14700         1.629051
7   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...         2.441456
1    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900         3.009408
6       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX         3.028193
8     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M         3.188277
9   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...         4.469477
11  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...         5.468166
10  VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...         6.429801
3   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...         7.451571
0   EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz        11.192535
2   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...        11.993303
4      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX        15.853511

Ranking by average fireducks time (ascending):

                                             host_cpu  fireducks_avg_time
0   EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz            0.794866
1    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900                 NaN
2   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...                 NaN
3   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...                 NaN
4      HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX                 NaN
5          Inspiron3030S | Intel(R) Core(TM) i7-14700                 NaN
6       Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX                 NaN
7   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...                 NaN
8     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M                 NaN
9   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...                 NaN
10  VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...                 NaN
11  WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...                 NaN

,host_cpu,pandas_avg_time,polars_avg_time,duckdb_avg_time,fireducks_avg_time
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,1.491011,2.576411,11.192535,0.794866
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900,4.299194,0.966045,3.009408,NaN
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,3.681693,3.323331,11.993303,NaN
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,2.578181,1.889734,7.451571,NaN
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX,3.961236,0.766998,15.853511,NaN
5,Inspiron3030S | Intel(R) Core(TM) i7-14700,11.492783,1.156464,1.629051,NaN
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX,20.426597,1.487777,3.028193,NaN
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,3.707179,0.848281,2.441456,NaN
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M,15.408611,1.760348,3.188277,NaN
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,1.787122,1.160133,4.469477,NaN
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,2.144046,1.578317,6.429801,NaN
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,2.740769,1.445962,5.468166,NaN

In [26]:
# Rank hosts (host + CPU) by the average time across all libraries (pandas, polars, duckdb)
#all_lib_time_cols = [col for col in b_df.columns if col.endswith('_pandas_seconds') or col.endswith('_polars_seconds') or col.endswith('_duckdb_seconds')]

b_df['all_libs_avg_time'] = b_df[time_cols].mean(axis=1)

# Group by host+cpu and get the mean
host_alllibs_avg = b_df.groupby('host_cpu')['all_libs_avg_time'].mean().reset_index()

# Sort to get the fastest overall
host_alllibs_avg_sorted = host_alllibs_avg.sort_values('all_libs_avg_time', ascending=True).reset_index(drop=True)

print("Ranking by average time across all libraries (fastest PC overall):")
display(host_alllibs_avg_sorted)

Ranking by average time across all libraries (fastest PC overall):

                                             host_cpu  all_libs_avg_time
0   Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...           2.332305
1   TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...           2.472244
2    HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900           2.758216
3   WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...           3.218299
4   VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...           3.384055
5   HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...           3.973162
6   EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz           4.013706
7          Inspiron3030S | Intel(R) Core(TM) i7-14700           4.759433
8   HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...           6.332776
9     StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M           6.785746
10     HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX           6.860582
11      Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX           8.314189

In [32]:
# Calculate the average operation time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  # Fixed: startswith
    b_df[f'{test}_avg_time'] = b_df[test_cols].mean(axis=1)  # Fixed: use test, not lib

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each test
test_avg_cols = [f'{test}_avg_time' for test in test_prefixes]
host_test_avg = b_df.groupby('host_cpu')[test_avg_cols].mean().reset_index()

# Sort each test's ranking and display
# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by average {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_avg[['host_cpu', f'{test}_avg_time']].sort_values(f'{test}_avg_time'))
    print("\n")

# Display the full table
host_test_avg

Ranking by average filter_group time (ascending):

,host_cpu,filter_group_avg_time
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.382449
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.442778
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.475525
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.804758
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.821436
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.900283
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.935096
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,1.006136
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.072774
5,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.789866
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.823748
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.970885

Ranking by average statistics time (ascending):

,host_cpu,statistics_avg_time
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.351958
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.430578
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.578091
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.869160
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.895226
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.908945
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.945809
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,1.016160
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.097377
5,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,3.218444
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,4.208320
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,7.309481

Ranking by average complex_join time (ascending):

,host_cpu,complex_join_avg_time
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,5.574418
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,6.935108
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,7.703487
5,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,8.334584
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,9.969111
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,10.487334
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,11.430337
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.718066
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,13.052801
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,13.698890
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,18.834236
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,23.890014

Ranking by average timeseries time (ascending):

,host_cpu,timeseries_avg_time
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.451081
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,1.756804
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.873898
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.883217
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.075459
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.142782
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.646161
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.748607
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,4.326716
5,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,4.694836
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.058113
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,8.277500

,host_cpu,filter_group_avg_time,statistics_avg_time,complex_join_avg_time,timeseries_avg_time
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.821436,0.869160,11.718066,2.646161
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,1.006136,1.016160,6.935108,2.075459
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,1.072774,1.097377,18.834236,4.326716
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.804758,0.908945,11.430337,2.748607
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.900283,0.895226,23.890014,1.756804
5,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,2.789866,3.218444,8.334584,4.694836
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,3.970885,7.309481,13.698890,8.277500
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.935096,0.945809,5.574418,1.873898
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,3.823748,4.208320,13.052801,6.058113
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.382449,0.351958,7.703487,1.451081
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.475525,0.430578,10.487334,2.142782
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.442778,0.578091,9.969111,1.883217

In [ ]:
# Calculate the minumum time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  
    b_df[f'{test}_min_time'] = b_df[test_cols].min(axis=1)  

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the min per host+cpu for each test
test_min_cols = [f'{test}_min_time' for test in test_prefixes]
host_test_min = b_df.groupby('host_cpu')[test_min_cols].min().reset_index()

# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by minimum time {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_min[['host_cpu', f'{test}_min_time']].sort_values(f'{test}_min_time'))
    print("\n")

# Display the full table
host_test_min

Ranking by minimum time filter_group time (ascending):

,host_cpu,filter_group_min_time
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.033806
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.035578
5,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.041874
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058527
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.062853
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.073407
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558

Ranking by minimum time statistics time (ascending):

,host_cpu,statistics_min_time
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.050525
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.064059
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.093565
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.109509
5,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.114555
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.140855
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.167851
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730

Ranking by minimum time complex_join time (ascending):

,host_cpu,complex_join_min_time
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.483308
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.520723
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.543240
5,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.848587
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.850386
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.938912
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.390336
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724

Ranking by minimum time timeseries time (ascending):

,host_cpu,timeseries_min_time
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.114004
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.144168
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826
5,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.186427
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.205527
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.238715
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.242685
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.377764
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055

,host_cpu,filter_group_min_time,statistics_min_time,complex_join_min_time,timeseries_min_time
0,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.003029,0.000484,0.001163,0.667169
1,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.034815,0.062178,0.543240,0.144168
2,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,0.238558,0.358730,1.869724,0.844055
3,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.084105,0.211529,1.144325,0.604427
4,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.033806,0.050525,0.483308,0.114004
5,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,0.041874,0.114555,0.848587,0.186427
6,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.062853,0.140855,0.938912,0.242685
7,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.035578,0.064059,0.520723,0.147826
8,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,0.073407,0.109509,1.390336,0.205527
9,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.058527,0.093565,0.850386,0.238715
10,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.173057,0.140574,0.896909,0.386797
11,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.094551,0.167851,0.921715,0.377764