In [17]:
import pandas as pd
CSV_PATH = "../data/benchmark_results.csv"

In [18]:
b_df = pd.read_csv(CSV_PATH)
b_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405 entries, 0 to 404
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   timestamp                       405 non-null    object
 1   hostname                        405 non-null    object
 2   platform                        405 non-null    object
 3   system                          405 non-null    object
 4   release                         405 non-null    object
 5   version                         405 non-null    object
 6   machine                         405 non-null    object
 7   processor                       405 non-null    object
 8   cpu_count_logical               405 non-null    int64
 9   cpu_count_physical              405 non-null    int64
 10  cpu_freq_max                    405 non-null    float64
 11  cpu_freq_current                405 non-null    float64
 12  memory_total_gb                 405 non-null    float64
 13  memory_available_gb             405 non-null    float64
 14  python_version                  405 non-null    object
 15  python_implementation           405 non-null    object
 16  cpu_brand                       405 non-null    object
 17  cpu_arch                        405 non-null    object
 18  dataset_size                    405 non-null    int64
 19  dataset_name                    405 non-null    object
 20  dataset_format                  405 non-null    object
 21  filter_group_pandas_seconds     405 non-null    float64
 22  filter_group_polars_seconds     405 non-null    float64
 23  filter_group_duckdb_seconds     405 non-null    float64
 24  filter_group_fireducks_seconds  207 non-null    float64
 25  statistics_pandas_seconds       405 non-null    float64
 26  statistics_polars_seconds       405 non-null    float64
 27  statistics_duckdb_seconds       405 non-null    float64
 28  statistics_fireducks_seconds    207 non-null    float64
 29  complex_join_pandas_seconds     405 non-null    float64
 30  complex_join_polars_seconds     405 non-null    float64
 31  complex_join_duckdb_seconds     405 non-null    float64
 32  complex_join_fireducks_seconds  207 non-null    float64
 33  timeseries_pandas_seconds       405 non-null    float64
 34  timeseries_polars_seconds       405 non-null    float64
 35  timeseries_duckdb_seconds       405 non-null    float64
 36  timeseries_fireducks_seconds    207 non-null    float64
 37  script_name                     405 non-null    object
dtypes: float64(20), int64(3), object(15)
memory usage: 120.4+ KB

In [19]:
# Removing fireduck for now because there is not data(yet)
#fireduck_columns = [col for col in b_df.columns if 'fireducks_' in col]
#b_df.drop(columns=fireduck_columns, inplace=True)

#b_df.info()

In [20]:
# Focus on 10 million rows for uniform comparison
b_df = b_df[b_df["dataset_size"] == 10_000_000]
b_df.shape

(401, 38)

In [21]:
# Clean platform-based analysis now possible
wsl2_data = b_df[b_df['system'] == 'WSL2']
native_linux = b_df[b_df['system'] == 'Linux'] 
windows_data = b_df[b_df['system'] == 'Windows']

# Example: Compare FireDucks performance
fireducks_wsl2 = wsl2_data['filter_group_fireducks_seconds']
fireducks_linux = native_linux['filter_group_fireducks_seconds']

In [22]:
time_cols = [col for col in b_df.columns if col.endswith('_seconds')]
b_df[time_cols] = b_df[time_cols].round(6)
b_df.head(3)

,timestamp,hostname,platform,system,release,version,machine,processor,cpu_count_logical,cpu_count_physical,...,statistics_fireducks_seconds,complex_join_pandas_seconds,complex_join_polars_seconds,complex_join_duckdb_seconds,complex_join_fireducks_seconds,timeseries_pandas_seconds,timeseries_polars_seconds,timeseries_duckdb_seconds,timeseries_fireducks_seconds,script_name
0,2025-08-28T19:37:29.241650,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,44.743244,6.037812,26.736806,NaN,22.656234,7.020198,3.894986,NaN,benchmark_01.py
1,2025-08-28T21:16:05.419895,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,23.235775,1.426380,4.835438,NaN,12.861529,2.425745,0.614240,NaN,benchmark.py
2,2025-08-28T21:25:30.654371,StealthAI16,Windows-11-10.0.26100-SP0,Windows,11,10.0.26100,AMD64,"AMD64 Family 26 Model 36 Stepping 0, AuthenticAMD",20,10,...,NaN,28.530276,1.482855,5.431484,NaN,16.994786,2.902070,0.595494,NaN,benchmark_02.py

In [23]:
def rank_methods(df, operation_col_prefix):
    time_cols = [col for col in df.columns if col.startswith(operation_col_prefix) and col.endswith('_seconds')]
    rank_df = pd.DataFrame()
    rank_df['hostname'] = df['hostname']
    rank_df['cpu_brand'] = df['cpu_brand'] 
    rank_df['dataset_size'] = df['dataset_size']
    rank_df['dataset_format'] = df['dataset_format']
    
    for col in time_cols:
        rank_col = f"rank_{col}"
        # Only rank non-zero values, assign max rank to zeros
        mask = df[col] > 0
        rank_df[rank_col] = df[col].where(mask).rank(method='min')
        max_rank = rank_df[rank_col].max()
        rank_df[rank_col] = rank_df[rank_col].fillna(max_rank + 1)
    
    return rank_df

In [24]:
filter_group_ranks = rank_methods(b_df, 'filter_group_')
sort_values_cols = [col for col in filter_group_ranks.columns if col.startswith('rank_filter_group_')]
filter_group_ranks[sort_values_cols] = filter_group_ranks[sort_values_cols].astype(int)
filter_group_ranks = filter_group_ranks.sort_values(by=sort_values_cols + ['hostname', 'dataset_format'])
filter_group_ranks

,hostname,cpu_brand,dataset_size,dataset_format,rank_filter_group_pandas_seconds,rank_filter_group_polars_seconds,rank_filter_group_duckdb_seconds,rank_filter_group_fireducks_seconds
321,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,1,92,291,201
161,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,2,70,32,5
314,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,3,82,57,2
160,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,4,69,37,21
150,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,5,40,97,208
...,...,...,...,...,...,...,...,...
16,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,397,373,257,208
46,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,398,396,315,208
32,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,399,374,311,208
33,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,400,391,317,208
0,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,401,400,374,208

In [25]:
def get_df_by_test(df: pd.DataFrame, cols_to_group: list, metric: str) -> pd.DataFrame:
    # Properly combine columns - create a new list instead of using append
    columns_to_select = cols_to_group + [metric]
    
    # Select the relevant columns
    df_subset = df[columns_to_select]
    
    # Remove rows where the metric is null/zero (assuming you want valid measurements)
    df_filtered = df_subset[df_subset[metric] > 0]  # or use .notna() if you want non-null values
    
    # Group by the specified columns and get minimum values
    grouped = df_filtered.groupby(cols_to_group)
    return grouped.min().reset_index().sort_values(by=metric)

In [26]:
cols_to_group = [ "dataset_format","hostname", "cpu_brand", "system"]
for col_to_rank in time_cols:
    print(f"Ranking by: {col_to_rank}")
    df_by_test = get_df_by_test(b_df, cols_to_group, col_to_rank)
    display(df_by_test)
    print("\n")

Ranking by: filter_group_pandas_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_pandas_seconds
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.252882
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.255371
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.269150
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.269462
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.269707
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.270499
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.271542
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.273162
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.273861
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.274816
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.275933
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.283666
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.284732
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.293107
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.295494
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.296013
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.300393
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.304917
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.307013
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.307098
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.307888
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.312222
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.315864
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.316038
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.320001
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.321065
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.325910
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.335269
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.335481
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.365571
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.367142
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.372711
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.374583
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.379735
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.380978
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.382879
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.389362
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.393282
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.416637
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.425848
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.428233
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.434067
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.447669
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.461787
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.468646
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.493353
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.514984
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.528547
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.535098
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.583145
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.591544
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.641110
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.663562
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.692138
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.702786
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.703566
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.731955
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.962332
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,5.358341
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,10.411298

Ranking by: filter_group_polars_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_polars_seconds
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.071505
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.090605
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.094960
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.098239
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.098410
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.098412
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.105863
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.118766
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.125012
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.127720
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.128240
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.133582
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.134381
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.136902
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.139211
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.140502
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.144457
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.147632
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.157515
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.160666
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.165866
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.180809
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.191101
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.194452
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.195381
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.199044
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.201567
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.203178
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.204483
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.208076
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.208222
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.216848
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.218959
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.219885
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.239710
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.243947
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.253067
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.268869
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.269017
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.273836
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.291214
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.294835
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.302873
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.306664
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.340602
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.345873
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.355334
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.376640
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.394636
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.431944
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.432383
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.486967
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.488726
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.510137
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.542422
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.565336
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.614996
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.625782
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.690226
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.823694

Ranking by: filter_group_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_duckdb_seconds
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.031890
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.032062
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.032623
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.033242
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.034815
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.036922
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.041783
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.042423
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.045527
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.046697
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.047376
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.047544
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.047966
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.047970
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.048604
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.048618
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.049567
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.053021
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.053767
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.055147
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.056555
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.057115
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.058527
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.061755
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.066707
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.066937
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.067097
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.068845
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.073407
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.075990
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.082814
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.083453
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.084105
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.092058
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.094551
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.095555
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.113281
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.116693
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.119607
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.122297
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.124491
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.126611
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.133032
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.136810
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.137175
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.139353
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.143259
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.146962
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.155095
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.156793
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.160650
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.173057
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.173424
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.194292
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.224818
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.238558
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.239716
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.261815
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.337646
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.501835

Ranking by: filter_group_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,filter_group_fireducks_seconds
8,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.001484
10,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.001497
24,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.001550
2,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.001589
22,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.001609
16,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.001656
11,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.001698
12,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.001743
26,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.001776
25,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.001779
9,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.001853
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.001940
14,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.002271
4,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.002427
3,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.002445
7,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.002453
21,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.002592
6,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.002678
17,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.002729
20,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.002979
18,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.003022
15,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.003029
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.003122
1,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.003224
19,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.003474
5,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.003935
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.004023
23,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.010577

Ranking by: statistics_pandas_seconds

,dataset_format,hostname,cpu_brand,system,statistics_pandas_seconds
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.160063
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.178686
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.180947
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.186431
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.187811
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.192725
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.203179
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.203471
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.208207
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.216869
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.218891
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.219370
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.219511
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.222419
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.222962
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.224676
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.227811
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.232281
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.234241
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.238018
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.240540
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.241225
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.241319
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.252322
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.254285
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.261322
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.265091
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.268410
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.291042
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.303906
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.312264
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.336234
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.338446
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.339025
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.339472
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.340918
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.359289
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.361939
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.367291
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.370749
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.371494
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.391305
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.396269
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.407656
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.465929
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.471190
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.502419
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.513319
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.524030
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.580449
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.600673
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.625986
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.673124
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.676553
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.684314
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.752458
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.837387
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.850339
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,6.423730
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,10.376254

Ranking by: statistics_polars_seconds

,dataset_format,hostname,cpu_brand,system,statistics_polars_seconds
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.057959
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.061096
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.061169
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.066585
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.072699
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.081498
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.085318
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.087296
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.088249
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.092394
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.094802
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.095524
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.095885
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.101301
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.104160
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.104290
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.108512
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.109605
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.112284
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.116079
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.116513
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.121048
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.134709
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.136704
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.140574
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.145582
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.175646
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.181394
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.188093
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.199275
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.201458
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.205388
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.210085
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.225771
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.228205
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.228700
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.232830
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.238894
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.248640
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.256583
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.307027
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.311508
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.314736
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.363951
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.365960
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.373520
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.375136
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.383513
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.383970
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.392614
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.398507
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.404778
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.418672
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.425459
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.438670
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.480064
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.510830
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.516206
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.516427
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.645693

Ranking by: statistics_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,statistics_duckdb_seconds
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.038060
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.048504
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.052067
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.054845
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.057667
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.058118
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.059392
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.061105
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.062178
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.066542
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.066727
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.067506
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.068152
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.069300
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.070597
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.071951
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.073689
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.074120
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.076049
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.079360
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.081314
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.085688
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.090312
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.092868
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.093565
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.096858
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.099953
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.109509
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.110594
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.131306
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.134772
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.143583
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.149406
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.150332
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.167851
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.195986
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.196961
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.210103
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.211529
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.222407
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.251149
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.252737
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.304877
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.323197
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.329382
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.332450
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.354550
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.355642
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.358730
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.370384
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.375684
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.382476
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.445769
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.447324
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.494045
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.498727
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.536384
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.572973
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.660862
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,0.673051

Ranking by: statistics_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,statistics_fireducks_seconds
8,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.000140
22,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.000141
12,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.000187
25,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.000193
16,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.000195
9,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.000204
26,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.000205
10,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.000213
2,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.000220
11,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.000232
23,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.000246
24,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.000250
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.000289
14,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.000291
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.000309
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.000312
18,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000338
17,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000347
3,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000364
7,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.000381
4,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000414
6,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.000420
21,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.000469
15,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000484
19,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.000490
1,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000491
20,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.000555
5,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.000893

Ranking by: complex_join_pandas_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_pandas_seconds
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,1.703667
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,1.740872
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,1.783565
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,1.812609
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,1.826722
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,1.845459
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,1.885700
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,2.032971
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,2.039433
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,2.063363
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,2.086920
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,2.156851
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,2.157476
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,2.159110
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,2.190334
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,2.195587
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.295366
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,2.309064
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,2.313880
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.321239
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,2.399702
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,2.419912
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,2.436286
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,2.460799
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,2.486614
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,2.501646
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,2.599806
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,2.681270
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,2.704473
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,2.710402
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,2.745317
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,2.746133
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,2.769056
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,2.772811
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,2.836061
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,2.862606
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,2.920474
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,2.937153
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,3.052452
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,3.101532
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,3.175220
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,3.193744
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,3.226381
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,3.328890
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,3.534181
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,3.618343
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,3.981980
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,3.982410
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,4.149068
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,4.155437
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,4.435003
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,4.933718
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,5.147182
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,5.252674
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,5.558602
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,5.822155
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,6.052842
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,6.501427
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,8.353409
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,23.235775

Ranking by: complex_join_polars_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_polars_seconds
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.440721
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.450646
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.459607
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.460666
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.476298
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.482777
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.491799
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.495044
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.496640
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.499025
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.511116
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.511853
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.515251
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.516911
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.536883
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.537555
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.541118
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.571349
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.575433
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.591883
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.680029
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.682576
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.706446
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.707446
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.719540
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.772013
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.797163
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.825475
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.850386
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.853281
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.896909
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.921715
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.954018
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.982904
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.997258
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,1.004030
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,1.144325
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,1.165587
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,1.166113
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,1.284159
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,1.338042
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,1.344523
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,1.390336
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,1.394849
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,1.426380
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,1.451908
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,1.453339
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,1.469501
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.530371
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.550958
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.603825
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.618368
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.794887
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.805672
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,1.869724
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,2.062053
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,2.212631
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,2.232569
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,2.617505
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,2.735544

Ranking by: complex_join_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_duckdb_seconds
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,3.285292
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,3.594456
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,4.237417
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,4.595454
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,4.715118
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,4.746880
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,4.874635
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,5.140088
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,6.219584
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,8.425919
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,9.572599
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,9.626689
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,10.099078
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,10.311187
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,10.624296
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,10.729680
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,10.860894
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,10.972182
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,11.087266
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,11.249223
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,11.251413
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,11.430921
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,12.164969
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,12.757002
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,12.812437
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,13.439244
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,13.766659
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,14.045449
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,14.327818
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,14.769567
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,15.041581
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,15.266155
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,17.261537
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,17.445712
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,17.489565
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,17.805404
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,18.515142
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,20.342126
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,21.596404
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,21.924554
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,22.578155
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,22.634748
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,23.239070
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,23.916556
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,24.085375
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,25.815095
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,26.185457
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,27.339530
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,27.425043
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,28.009790
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,28.259255
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,30.442195
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,31.624210
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,32.850278
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,36.837714
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,37.671142
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,37.993901
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,41.291982
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,43.052157
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,43.799303

Ranking by: complex_join_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,complex_join_fireducks_seconds
8,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.000384
22,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.000413
10,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.000457
12,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.000508
25,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.000517
24,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.000522
2,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.000524
16,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.000532
26,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.000556
23,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.000562
11,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.000571
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.000653
9,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.000663
14,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.000702
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.000744
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.000801
21,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.000854
18,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000936
7,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.000946
17,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000962
3,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.000969
4,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.001120
6,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.001124
15,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.001163
20,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.001441
19,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.001499
5,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.001850
1,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.001865

Ranking by: timeseries_pandas_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_pandas_seconds
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.349165
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.351937
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.357184
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.358497
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.358569
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.360182
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.360459
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.360709
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.403801
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.410205
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.414054
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.419210
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.455722
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.467282
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.493485
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.499842
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.503815
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.508836
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.508849
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.508894
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.511875
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.516602
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.517817
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.518303
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.525932
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.544533
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.552929
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.561544
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.566226
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.574874
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.585583
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.590429
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.618460
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.627129
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.634316
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.647076
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.689184
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.693135
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.701162
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.709507
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.735251
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.751010
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.769225
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.832497
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.835348
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.851114
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.880524
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.906153
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.924786
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.937737
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,1.270681
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,1.311182
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,1.345003
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,1.383846
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,1.411530
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,1.438896
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,1.468229
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,1.524298
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,8.824875
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,12.861529

Ranking by: timeseries_polars_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_polars_seconds
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,1.836724
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,1.848299
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,1.899370
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,1.899804
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,1.916424
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,1.916629
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,1.928277
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,1.930856
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,1.951676
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,1.965067
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,1.967512
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,2.019306
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,2.035647
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,2.066553
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,2.070447
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.110350
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,2.115645
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,2.177278
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,2.179002
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,2.205108
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,2.216953
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,2.224582
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,2.225481
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,2.243550
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,2.397435
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,2.408907
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,2.505193
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,2.582026
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,2.631081
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,2.774699
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,2.826220
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,3.202793
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,3.217056
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,3.539412
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,3.595803
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,3.607012
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,3.646706
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,3.778609
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,3.794873
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,3.878324
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,3.897610
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,3.960917
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,4.260854
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,4.261347
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,4.304416
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,4.347602
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,4.393107
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,4.532263
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,4.928691
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,4.979773
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,5.020040
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,5.045245
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,6.247831
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,6.251081
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,6.761818
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,7.017137
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,7.324557
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,8.000622
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,8.178485
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,8.300135

Ranking by: timeseries_duckdb_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_duckdb_seconds
45,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.098952
46,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.113430
15,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.122152
16,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,Windows,0.125199
34,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.140741
50,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.142895
33,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.147814
54,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.147826
52,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.148341
49,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.152020
24,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,Windows,0.152542
51,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.152933
20,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,Windows,0.154963
3,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.156028
4,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,Windows,0.156701
19,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.160707
22,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,Windows,0.169913
53,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.170429
23,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.181075
21,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.181262
48,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.195624
55,parquet,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.205527
30,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.210747
18,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,Windows,0.228301
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.231962
56,parquet,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.238715
31,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.263333
47,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.268142
1,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,Windows,0.277293
17,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.294979
26,csv,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,Windows,0.313320
59,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.377764
57,parquet,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.386797
58,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.395654
28,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.396655
27,csv,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,Windows,0.408385
29,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,Windows,0.451360
13,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.501223
25,csv,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,Windows,0.561461
40,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.579472
44,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.604427
14,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,Windows,0.639191
43,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.674492
41,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.741153
10,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.757588
42,parquet,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.844055
11,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,Windows,0.850289
36,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.899609
39,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,0.986644
12,csv,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,Windows,0.987728
6,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.991282
35,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.043566
5,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.050404
9,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,Windows,1.178603
32,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.187024
2,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,1.253193
37,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,1.321530
7,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Windows,1.425144
38,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,1.461500
8,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,1.522405

Ranking by: timeseries_fireducks_seconds

,dataset_format,hostname,cpu_brand,system,timeseries_fireducks_seconds
16,parquet,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.273113
25,parquet,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.301512
2,csv,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,WSL2,0.302325
24,parquet,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.306496
11,csv,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,WSL2,0.312555
10,csv,Inspiron3030S,Intel(R) Core(TM) i7-14700,WSL2,0.338578
8,csv,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.343629
26,parquet,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.367393
22,parquet,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,WSL2,0.381611
12,csv,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,WSL2,0.395374
9,csv,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.418874
14,parquet,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.462007
7,csv,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.464249
0,csv,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,WSL2,0.483188
4,csv,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.501116
18,parquet,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.529562
21,parquet,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,WSL2,0.564873
23,parquet,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,WSL2,0.577054
6,csv,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.585731
3,csv,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.592294
17,parquet,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.622113
1,csv,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.667169
13,csv,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.718543
15,parquet,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,Linux,0.745909
27,parquet,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,WSL2,0.777140
20,parquet,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,WSL2,0.936820
19,parquet,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,0.983110
5,csv,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,WSL2,1.421789

In [27]:
# Filter Group Pandas
fg_p = b_df[["hostname", "cpu_brand","dataset_size", "dataset_format", "filter_group_pandas_seconds"]]
fg_p = fg_p.groupby(by=["hostname", "cpu_brand","dataset_size", "dataset_format"]).min().reset_index()
fg_p = fg_p.rename(columns={"filter_group_pandas_seconds": "min_time_seconds"})
fg_p = fg_p.sort_values(by=["dataset_size","min_time_seconds", "hostname",  "dataset_format"])
fg_p

,hostname,cpu_brand,dataset_size,dataset_format,min_time_seconds
18,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,csv,0.252882
23,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,parquet,0.255371
24,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,csv,0.269462
5,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,parquet,0.269707
26,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,csv,0.270499
22,Inspiron3030S,Intel(R) Core(TM) i7-14700,10000000,csv,0.271542
27,Optiplex7010,13th Gen Intel(R) Core(TM) i9-13900,10000000,parquet,0.273162
4,HP-Desktop,12th Gen Intel(R) Core(TM) i9-12900,10000000,csv,0.274816
25,Legion7-16IRX9,Intel(R) Core(TM) i9-14900HX,10000000,parquet,0.275933
20,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,10000000,csv,0.283666
21,IdeaPadPro5i,Intel(R) Core(TM) Ultra 9 185H,10000000,parquet,0.284732
19,HeliosNeo16S,Intel(R) Core(TM) Ultra 9 275HX,10000000,parquet,0.296013
1,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,10000000,parquet,0.307013
17,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,parquet,0.316038
0,DELL-XPS15-9510,11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz,10000000,csv,0.325910
8,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,csv,0.335269
9,HP-EB1030G2-UB,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,parquet,0.335481
16,HP-EB840G8-01,11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz,10000000,csv,0.365571
12,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,10000000,csv,0.367142
13,HP-EB830G6-02,Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz,10000000,parquet,0.372711
6,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,csv,0.374583
35,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,parquet,0.379735
7,HP-EB-ZorinOS,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,parquet,0.380978
31,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,parquet,0.382879
34,WL5040,AMD Ryzen 9 8945HS w/ Radeon 780M Graphics,10000000,csv,0.389362
32,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,csv,0.416637
33,VivoBook-01,13th Gen Intel(R) Core(TM) i9-13900H,10000000,parquet,0.425848
30,TS-P350-01,11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz,10000000,csv,0.428233
3,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,parquet,0.447669
2,EB01LM,Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz,10000000,csv,0.461787
10,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,10000000,csv,0.528547
11,HP-EB830G6-01,Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz,10000000,parquet,0.583145
14,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,csv,0.731955
15,HP-EB830G8-01,11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz,10000000,parquet,0.962332
29,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,parquet,5.358341
28,StealthAI16,AMD Ryzen AI 9 365 w/ Radeon 880M,10000000,csv,10.411298

In [28]:
# Calculate the average operation time per row for each library
library_suffixes = ['pandas', 'polars', 'duckdb', 'fireducks']  # Add 'fireducks' if/when data is available

for lib in library_suffixes:
    lib_cols = [col for col in b_df.columns if col.endswith(f'_{lib}_seconds')]
    b_df[f'{lib}_avg_time'] = b_df[lib_cols].mean(axis=1)

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str)+ ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each library
host_lib_avg = b_df.groupby('host_cpu')[[f'{lib}_avg_time' for lib in library_suffixes]].mean().reset_index()

# Sort each library's ranking and display
with pd.option_context('display.max_colwidth', None):
    for lib in library_suffixes:
        print(f"Ranking by average {lib} time (ascending):")
        display(host_lib_avg[['host_cpu', f'{lib}_avg_time']].sort_values(f'{lib}_avg_time'))
        print("\n")
# Optionally, display the full table
host_lib_avg

Ranking by average pandas time (ascending):

,host_cpu,pandas_avg_time
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.728984
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.762654
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.785434
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.825529
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.853110
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.883562
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.939625
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.083468
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.089557
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.119797
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.170043
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.172261
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.491011
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,1.530649
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.710795
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.787122
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.932938
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,2.045975
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.144046
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,2.492094
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.578181
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.735169
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,2.740769
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.968245
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,3.109042
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,3.110269
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,3.681693
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,5.444306
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,11.000854
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,15.408611

Ranking by average polars time (ascending):

,host_cpu,polars_avg_time
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.671039
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.700399
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.742445
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.772193
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.784100
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.799042
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.832509
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.876530
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.880961
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.901357
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.904037
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.069611
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,1.149118
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.160133
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.205978
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.445962
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.512683
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.575183
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,1.578317
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.736730
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.760348
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.889734
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,1.981489
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.013492
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,2.132537
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,2.419061
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.576411
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.154671
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,3.323331
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,3.513165

Ranking by average duckdb time (ascending):

,host_cpu,duckdb_avg_time
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.333418
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,2.704064
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,2.913892
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.991300
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.000099
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,3.000192
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,3.000330
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,3.167542
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.188277
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,3.355343
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,3.454632
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,3.711097
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,3.992685
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,4.055661
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,4.330357
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,4.469477
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,5.468166
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,6.429801
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,6.655530
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.171884
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,7.451571
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,8.051619
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,8.732914
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.127482
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.242403
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.192535
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,11.993303
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,12.402753
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,13.486665
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,16.960324

Ranking by average fireducks time (ascending):

,host_cpu,fireducks_avg_time
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.153296
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.158389
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.158445
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.167420
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.175636
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.202127
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.239988
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.313481
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.370742
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.378425
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.396031
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.400305
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.695349
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.794866
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,NaN
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,NaN
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,NaN
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,NaN
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,NaN
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,NaN
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,NaN
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,NaN
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,NaN
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,NaN
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,NaN
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,NaN
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,NaN
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,NaN
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,NaN
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,NaN

,host_cpu,pandas_avg_time,polars_avg_time,duckdb_avg_time,fireducks_avg_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.939625,1.069611,4.330357,0.239988
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,1.932938,1.205978,4.055661,NaN
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,1.491011,2.576411,11.192535,0.794866
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.785434,0.784100,3.000192,0.167420
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,3.110269,0.901357,2.991300,NaN
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,1.172261,2.013492,9.127482,0.378425
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,1.089557,1.981489,9.242403,0.370742
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,3.109042,3.513165,12.402753,NaN
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,2.045975,3.154671,13.486665,0.695349
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,2.735169,2.132537,8.051619,NaN
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,1.119797,1.736730,7.171884,0.396031
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,2.968245,2.419061,16.960324,NaN
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,3.681693,3.323331,11.993303,NaN
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,1.083468,1.512683,6.655530,0.313481
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,2.578181,1.889734,7.451571,NaN
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.762654,0.700399,3.454632,0.158389
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,1.530649,0.671039,2.913892,NaN
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.883562,0.880961,3.992685,0.202127
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,1.710795,0.772193,3.355343,NaN
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.728984,0.742445,3.167542,0.158445
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,5.444306,0.904037,2.333418,NaN
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.825529,0.832509,3.000330,0.153296
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,11.000854,1.149118,3.000099,NaN
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.853110,0.876530,3.711097,0.175636
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,2.492094,0.799042,2.704064,NaN
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,15.408611,1.760348,3.188277,NaN
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,1.787122,1.160133,4.469477,NaN
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,2.144046,1.578317,6.429801,NaN
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,1.170043,1.575183,8.732914,0.400305
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,2.740769,1.445962,5.468166,NaN

In [29]:
# Rank hosts (host + CPU) by the average time across all libraries (pandas, polars, duckdb)
#all_lib_time_cols = [col for col in b_df.columns if col.endswith('_pandas_seconds') or col.endswith('_polars_seconds') or col.endswith('_duckdb_seconds')]

b_df['all_libs_avg_time'] = b_df[time_cols].mean(axis=1)

# Group by host+cpu and get the mean
host_alllibs_avg = b_df.groupby('host_cpu')['all_libs_avg_time'].mean().reset_index()

# Sort to get the fastest overall
host_alllibs_avg_sorted = host_alllibs_avg.sort_values('all_libs_avg_time', ascending=True).reset_index(drop=True)

print("Ranking by average time across all libraries (fastest PC overall):")
with pd.option_context('display.max_colwidth', None):
    display(host_alllibs_avg_sorted)

Ranking by average time across all libraries (fastest PC overall):

,host_cpu,all_libs_avg_time
0,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,1.184287
1,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,1.199354
2,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,1.202916
3,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,1.269018
4,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,1.404093
5,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,1.489834
6,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.644896
7,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,1.705193
8,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.946110
9,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.998400
10,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,2.334309
11,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,2.391290
12,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,2.398192
13,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,2.472244
14,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,2.606110
15,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.893920
16,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,2.969611
17,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.171048
18,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,3.172915
19,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,3.218299
20,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,3.384055
21,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,3.973162
22,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,4.013706
23,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,4.306442
24,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,4.845665
25,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,5.050024
26,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,6.332776
27,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,6.341653
28,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.785746
29,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,7.449210

In [30]:
# Calculate the average operation time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  # Fixed: startswith
    b_df[f'{test}_avg_time'] = b_df[test_cols].mean(axis=1)  # Fixed: use test, not lib

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the average per host+cpu for each test
test_avg_cols = [f'{test}_avg_time' for test in test_prefixes]
host_test_avg = b_df.groupby('host_cpu')[test_avg_cols].mean().reset_index()

# Sort each test's ranking and display
# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by average {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_avg[['host_cpu', f'{test}_avg_time']].sort_values(f'{test}_avg_time'))
    print("\n")

# Display the full table
host_test_avg

Ranking by average filter_group time (ascending):

,host_cpu,filter_group_avg_time
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.210105
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.216995
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.228511
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.231373
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.232272
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.242138
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.264002
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.277032
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.382449
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.392711
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.431091
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.438459
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.442778
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.463158
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.475525
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.597730
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.609594
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.611797
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.693557
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.746890
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.804758
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.812564
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.821436
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.831888
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.072774
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.287018
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.342407
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,2.115706
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,3.823748

Ranking by average statistics time (ascending):

,host_cpu,statistics_avg_time
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.141072
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.142022
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.149658
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.154959
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.180325
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.182122
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.195099
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.216774
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.258530
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.319494
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.351958
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.368919
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.396304
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.430578
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.459804
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.578091
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.588329
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.662899
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.669798
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.689494
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.791946
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.869160
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.908945
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.914073
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.931412
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.097377
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.360749
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,1.448765
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,3.776305
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,4.208320

Ranking by average complex_join time (ascending):

,host_cpu,complex_join_avg_time
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,3.596257
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,3.604662
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,3.682625
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,3.884686
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,4.271681
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,4.637280
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,5.005017
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,5.362735
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,5.414689
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,6.190292
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,6.302954
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,6.342929
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,7.085135
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,7.248586
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,7.703487
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,7.756925
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.301819
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,9.384543
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,9.573068
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,9.588665
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,9.969111
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,10.487334
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,11.430337
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,11.718066
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,12.467298
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,13.052801
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,14.483172
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,17.847316
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,18.834236
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,24.791240

Ranking by average timeseries time (ascending):

,host_cpu,timeseries_avg_time
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.768042
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.781308
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.805055
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.856388
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.909459
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.920432
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.982474
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,1.071617
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,1.080760
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,1.444806
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,1.451081
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,1.554792
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,1.582553
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,1.645263
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,1.651231
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,1.744553
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,1.883217
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.027155
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.108246
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,2.142782
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,2.496969
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,2.646161
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,2.748607
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,3.031831
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,3.275654
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,3.327298
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,4.326716
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,4.719419
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,4.816141
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,6.058113

,host_cpu,filter_group_avg_time,statistics_avg_time,complex_join_avg_time,timeseries_avg_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.277032,0.216774,5.005017,1.080760
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.392711,0.368919,7.248586,1.582553
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.821436,0.869160,11.718066,2.646161
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.210105,0.141072,3.604662,0.781308
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.693557,0.689494,6.302954,1.651231
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,0.611797,0.669798,9.301819,2.108246
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.609594,0.662899,9.384543,2.027155
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,1.342407,1.360749,17.847316,4.816141
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.831888,0.791946,14.483172,3.275654
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.812564,0.914073,12.467298,3.031831
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.463158,0.459804,7.756925,1.744553
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.746890,0.931412,24.791240,3.327298
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,1.072774,1.097377,18.834236,4.326716
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.438459,0.396304,7.085135,1.645263
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.804758,0.908945,11.430337,2.748607
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.231373,0.154959,3.884686,0.805055
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.228511,0.195099,5.414689,0.982474
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.232272,0.180325,4.637280,0.909459
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.264002,0.258530,6.190292,1.071617
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.197090,0.149658,3.682625,0.768042
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,1.287018,1.448765,6.342929,2.496969
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.216995,0.142022,3.596257,0.856388
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,2.115706,3.776305,9.588665,4.719419
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.242138,0.182122,4.271681,0.920432
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.597730,0.588329,5.362735,1.444806
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,3.823748,4.208320,13.052801,6.058113
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.382449,0.351958,7.703487,1.451081
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.475525,0.430578,10.487334,2.142782
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.431091,0.319494,9.573068,1.554792
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.442778,0.578091,9.969111,1.883217

In [31]:
# Calculate the minumum time per row for each test
test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries'] 

for test in test_prefixes:
    test_cols = [col for col in b_df.columns if col.startswith(f'{test}_')]  
    b_df[f'{test}_min_time'] = b_df[test_cols].min(axis=1)  

# Combine hostname and cpu_brand for unique identification
b_df['host_cpu'] = b_df['hostname'] + ' | ' + b_df['cpu_brand'].astype(str) + ' | ' + b_df['system'].astype(str)

# Prepare a DataFrame to hold the min per host+cpu for each test
test_min_cols = [f'{test}_min_time' for test in test_prefixes]
host_test_min = b_df.groupby('host_cpu')[test_min_cols].min().reset_index()

# Sort each test's ranking and display
for test in test_prefixes:
    print(f"Ranking by minimum time {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(host_test_min[['host_cpu', f'{test}_min_time']].sort_values(f'{test}_min_time'))
    print("\n")

# Display the full table
host_test_min

Ranking by minimum time filter_group time (ascending):

,host_cpu,filter_group_min_time
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.001484
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.001589
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.001698
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.001743
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.001853
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.001940
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002427
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002445
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.002453
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002678
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.003122
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003474
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.031890
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.032062
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.042423
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.047376
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.056555
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058527
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.073407
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.113281
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.133032
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558

Ranking by minimum time statistics time (ascending):

,host_cpu,statistics_min_time
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000140
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000187
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000193
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000195
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000204
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000213
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000289
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000291
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000338
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000347
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000381
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000420
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000490
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.048504
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.061105
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.068152
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.081498
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.093565
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.099953
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.109509
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.167851
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.304877
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.355642
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830

Ranking by minimum time complex_join time (ascending):

,host_cpu,complex_join_min_time
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000384
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000457
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000508
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000517
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000524
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000562
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000653
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000744
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000854
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000936
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000962
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001124
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001499
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.450646
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.459607
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.476298
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.496640
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.511853
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.797163
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.850386
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.338042
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.390336
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.451908
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631

Ranking by minimum time timeseries time (ascending):

,host_cpu,timeseries_min_time
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.098952
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.113430
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.140741
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.147814
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.148341
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.152020
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.152933
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.170429
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.195624
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.205527
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.210747
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.238715
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.263333
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.268142
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.377764
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395654
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.464249
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.501116
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.503815
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.574874
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.741153
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.851114
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.986644
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530

,host_cpu,filter_group_min_time,statistics_min_time,complex_join_min_time,timeseries_min_time
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.001940,0.000291,0.000653,0.210747
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.056555,0.099953,0.797163,0.263333
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.003029,0.000484,0.001163,0.667169
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.001589,0.000195,0.000524,0.147814
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.034815,0.062178,0.496640,0.140741
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,0.002445,0.000347,0.000962,0.574874
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.002427,0.000338,0.000936,0.501116
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.160650,0.510830,2.212631,1.321530
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.003474,0.000490,0.001499,0.851114
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.133032,0.355642,1.451908,0.986644
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.002678,0.000420,0.001124,0.503815
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.113281,0.304877,1.338042,0.741153
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,0.238558,0.358730,1.869724,0.844055
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.002453,0.000381,0.000854,0.464249
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.084105,0.211529,1.144325,0.604427
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.001484,0.000140,0.000384,0.098952
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.031890,0.048504,0.450646,0.113430
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.001853,0.000204,0.000562,0.268142
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.047376,0.081498,0.511853,0.195624
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497,0.000213,0.000457,0.152020
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,0.033242,0.059392,0.482777,0.142895
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.001698,0.000193,0.000517,0.152933
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.042423,0.068152,0.459607,0.148341
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.001743,0.000187,0.000508,0.170429
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.032062,0.061105,0.476298,0.147826
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,0.073407,0.109509,1.390336,0.205527
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.058527,0.093565,0.850386,0.238715
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.173057,0.140574,0.896909,0.386797
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.003122,0.000289,0.000744,0.395654
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.094551,0.167851,0.921715,0.377764

In [32]:
# Calculate the minimum time per row for each test and annotate which library achieved it (NaN-safe)

test_prefixes = ['filter_group', 'statistics', 'complex_join', 'timeseries']

for test in test_prefixes:
    # Raw timing columns only
    test_cols = [
        col for col in b_df.columns
        if col.startswith(f'{test}_') and col.endswith('_seconds')
    ]
    if not test_cols:
        b_df[f'{test}_min_time'] = float('nan')
        b_df[f'{test}_min_library'] = None
        continue

    # Convert to numeric (coerce 'N/A', blanks, etc. to NaN)
    numeric = b_df[test_cols].apply(pd.to_numeric, errors='coerce')

    # Row-wise min ignoring NaNs
    min_times = numeric.min(axis=1, skipna=True)

    # Identify the column name (library) producing the min ignoring NaNs.
    # pandas idxmin(skipna=True) returns NaN if the entire row is NaN.
    min_cols = numeric.idxmin(axis=1, skipna=True)

    suffix_len = len('_seconds')
    min_libs = []
    for col_name, all_nan in zip(min_cols, numeric.isna().all(axis=1)):
        if all_nan or pd.isna(col_name):
            min_libs.append(None)
        else:
            # column pattern: <test>_<library>_seconds
            lib_name = col_name[len(test) + 1: -suffix_len]
            min_libs.append(lib_name)

    b_df[f'{test}_min_time'] = min_times
    b_df[f'{test}_min_library'] = min_libs

# Unique host identifier
b_df['host_cpu'] = (
    b_df['hostname'].astype(str) + ' | ' +
    b_df['cpu_brand'].astype(str) + ' | ' +
    b_df['system'].astype(str)
)

# Aggregate: pick min time & corresponding library per host
host_rows = []
for host, g in b_df.groupby('host_cpu'):
    row = {'host_cpu': host}
    for test in test_prefixes:
        time_col = f'{test}_min_time'
        lib_col = f'{test}_min_library'
        if time_col not in g.columns or lib_col not in g.columns:
            row[time_col] = float('nan')
            row[lib_col] = None
            continue
        # valid rows for this test
        g_valid = g.dropna(subset=[time_col])
        if g_valid.empty:
            row[time_col] = float('nan')
            row[lib_col] = None
        else:
            # take the first row with minimal time
            min_idx = g_valid[time_col].idxmin()
            row[time_col] = g_valid.loc[min_idx, time_col]
            row[lib_col] = g_valid.loc[min_idx, lib_col]
    host_rows.append(row)

host_test_min = pd.DataFrame(host_rows)

# Display rankings per test including which library produced the min
for test in test_prefixes:
    time_col = f'{test}_min_time'
    lib_col = f'{test}_min_library'
    if time_col not in host_test_min.columns:
        continue
    print(f"Ranking by minimum {test} time (ascending):")
    with pd.option_context('display.max_colwidth', None):
        display(
            host_test_min[['host_cpu', time_col, lib_col]]
            .sort_values(time_col, na_position='last')
        )
    print("\n")

# Optional summary: frequency of fastest library per test
summary_rows = []
for test in test_prefixes:
    lib_col = f'{test}_min_library'
    if lib_col in host_test_min.columns:
        counts = host_test_min[lib_col].value_counts(dropna=True)
        for lib, cnt in counts.items():
            summary_rows.append({'test': test, 'library': lib, 'wins': cnt})
fastest_summary = pd.DataFrame(summary_rows).sort_values(['test', 'wins'], ascending=[True, False])
print("Fastest library counts per test:")
display(fastest_summary)

# Full aggregated table (one row per host with min times + libraries per test)
host_test_min

Ranking by minimum filter_group time (ascending):

,host_cpu,filter_group_min_time,filter_group_min_library
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.001484,fireducks
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.001589,fireducks
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.001698,fireducks
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.001743,fireducks
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.001853,fireducks
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.001940,fireducks
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002427,fireducks
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.002445,fireducks
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.002453,fireducks
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.002678,fireducks
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.003029,fireducks
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.003122,fireducks
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.003474,fireducks
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.031890,duckdb
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.032062,duckdb
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.033242,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.034815,duckdb
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.042423,duckdb
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.047376,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.056555,duckdb
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.058527,duckdb
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.073407,duckdb
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.084105,duckdb
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.094551,duckdb
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.113281,duckdb
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.133032,duckdb
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.160650,duckdb
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.173057,duckdb
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.238558,duckdb

Ranking by minimum statistics time (ascending):

,host_cpu,statistics_min_time,statistics_min_library
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000140,fireducks
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000187,fireducks
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000193,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000195,fireducks
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000204,fireducks
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000213,fireducks
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000289,fireducks
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000291,fireducks
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000338,fireducks
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000347,fireducks
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000381,fireducks
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.000420,fireducks
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000484,fireducks
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.000490,fireducks
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.048504,duckdb
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.059392,duckdb
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.061105,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.062178,duckdb
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.068152,duckdb
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.081498,polars
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.093565,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.099953,duckdb
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.109509,duckdb
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.140574,polars
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.167851,duckdb
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.211529,duckdb
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.304877,duckdb
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.355642,duckdb
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.358730,duckdb
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,0.510830,polars

Ranking by minimum complex_join time (ascending):

,host_cpu,complex_join_min_time,complex_join_min_library
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.000384,fireducks
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.000457,fireducks
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.000508,fireducks
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.000517,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.000524,fireducks
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.000562,fireducks
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.000653,fireducks
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.000744,fireducks
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.000854,fireducks
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000936,fireducks
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.000962,fireducks
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.001124,fireducks
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.001163,fireducks
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.001499,fireducks
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.450646,polars
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.459607,polars
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.476298,polars
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.482777,polars
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.496640,polars
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.511853,polars
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.797163,polars
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.850386,polars
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.896909,polars
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.921715,polars
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,1.144325,polars
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,1.338042,polars
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,1.390336,polars
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,1.451908,polars
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,1.869724,polars
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,2.212631,polars

Ranking by minimum timeseries time (ascending):

,host_cpu,timeseries_min_time,timeseries_min_library
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | WSL2,0.098952,duckdb
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX | Windows,0.113430,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | Windows,0.140741,duckdb
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | Windows,0.142895,duckdb
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-12900 | WSL2,0.147814,duckdb
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | Windows,0.147826,duckdb
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | Windows,0.148341,duckdb
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.152020,duckdb
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX | WSL2,0.152933,duckdb
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-13900 | WSL2,0.170429,duckdb
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | Windows,0.195624,duckdb
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880M | Windows,0.205527,duckdb
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | WSL2,0.210747,duckdb
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz | Windows,0.238715,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz | Windows,0.263333,duckdb
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H | WSL2,0.268142,duckdb
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | Windows,0.377764,duckdb
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13900H | Windows,0.386797,duckdb
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Graphics | WSL2,0.395654,duckdb
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | WSL2,0.464249,fireducks
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.501116,fireducks
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | WSL2,0.503815,pandas
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.574874,pandas
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz | Windows,0.604427,duckdb
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Linux,0.667169,fireducks
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz | Windows,0.741153,duckdb
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz | Windows,0.844055,duckdb
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | WSL2,0.851114,pandas
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz | Windows,0.986644,duckdb
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz | Windows,1.321530,duckdb

Fastest library counts per test:

           test    library  wins
5  complex_join     polars    16
6  complex_join  fireducks    14
0  filter_group     duckdb    16
1  filter_group  fireducks    14
2    statistics  fireducks    14
3    statistics     duckdb    13
4    statistics     polars     3
7    timeseries     duckdb    24
8    timeseries  fireducks     3
9    timeseries     pandas     3

,host_cpu,filter_group_min_time,filter_group_min_library,statistics_min_time,statistics_min_library,complex_join_min_time,complex_join_min_library,timeseries_min_time,timeseries_min_library
0,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.001940,fireducks,0.000291,fireducks,0.000653,fireducks,0.210747,duckdb
1,DELL-XPS15-9510 | 11th Gen Intel(R) Core(TM) i...,0.056555,duckdb,0.099953,duckdb,0.797163,polars,0.263333,duckdb
2,EB01LM | Intel(R) Core(TM) i7-7600U CPU @ 2.80...,0.003029,fireducks,0.000484,fireducks,0.001163,fireducks,0.667169,fireducks
3,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.001589,fireducks,0.000195,fireducks,0.000524,fireducks,0.147814,duckdb
4,HP-Desktop | 12th Gen Intel(R) Core(TM) i9-129...,0.034815,duckdb,0.062178,duckdb,0.496640,polars,0.140741,duckdb
5,HP-EB-ZorinOS | Intel(R) Core(TM) i7-7600U CPU...,0.002445,fireducks,0.000347,fireducks,0.000962,fireducks,0.574874,pandas
6,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.002427,fireducks,0.000338,fireducks,0.000936,fireducks,0.501116,fireducks
7,HP-EB1030G2-UB | Intel(R) Core(TM) i7-7600U CP...,0.160650,duckdb,0.510830,polars,2.212631,polars,1.321530,duckdb
8,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.003474,fireducks,0.000490,fireducks,0.001499,fireducks,0.851114,pandas
9,HP-EB830G6-01 | Intel(R) Core(TM) i5-8365U CPU...,0.133032,duckdb,0.355642,duckdb,1.451908,polars,0.986644,duckdb
10,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.002678,fireducks,0.000420,fireducks,0.001124,fireducks,0.503815,pandas
11,HP-EB830G6-02 | Intel(R) Core(TM) i7-8665U CPU...,0.113281,duckdb,0.304877,duckdb,1.338042,polars,0.741153,duckdb
12,HP-EB830G8-01 | 11th Gen Intel(R) Core(TM) i5-...,0.238558,duckdb,0.358730,duckdb,1.869724,polars,0.844055,duckdb
13,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.002453,fireducks,0.000381,fireducks,0.000854,fireducks,0.464249,fireducks
14,HP-EB840G8-01 | 11th Gen Intel(R) Core(TM) i7-...,0.084105,duckdb,0.211529,duckdb,1.144325,polars,0.604427,duckdb
15,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.001484,fireducks,0.000140,fireducks,0.000384,fireducks,0.098952,duckdb
16,HeliosNeo16S | Intel(R) Core(TM) Ultra 9 275HX...,0.031890,duckdb,0.048504,duckdb,0.450646,polars,0.113430,duckdb
17,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.001853,fireducks,0.000204,fireducks,0.000562,fireducks,0.268142,duckdb
18,IdeaPadPro5i | Intel(R) Core(TM) Ultra 9 185H ...,0.047376,duckdb,0.081498,polars,0.511853,polars,0.195624,duckdb
19,Inspiron3030S | Intel(R) Core(TM) i7-14700 | WSL2,0.001497,fireducks,0.000213,fireducks,0.000457,fireducks,0.152020,duckdb
20,Inspiron3030S | Intel(R) Core(TM) i7-14700 | W...,0.033242,duckdb,0.059392,duckdb,0.482777,polars,0.142895,duckdb
21,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.001698,fireducks,0.000193,fireducks,0.000517,fireducks,0.152933,duckdb
22,Legion7-16IRX9 | Intel(R) Core(TM) i9-14900HX ...,0.042423,duckdb,0.068152,duckdb,0.459607,polars,0.148341,duckdb
23,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.001743,fireducks,0.000187,fireducks,0.000508,fireducks,0.170429,duckdb
24,Optiplex7010 | 13th Gen Intel(R) Core(TM) i9-1...,0.032062,duckdb,0.061105,duckdb,0.476298,polars,0.147826,duckdb
25,StealthAI16 | AMD Ryzen AI 9 365 w/ Radeon 880...,0.073407,duckdb,0.109509,duckdb,1.390336,polars,0.205527,duckdb
26,TS-P350-01 | 11th Gen Intel(R) Core(TM) i7-117...,0.058527,duckdb,0.093565,duckdb,0.850386,polars,0.238715,duckdb
27,VivoBook-01 | 13th Gen Intel(R) Core(TM) i9-13...,0.173057,duckdb,0.140574,polars,0.896909,polars,0.386797,duckdb
28,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.003122,fireducks,0.000289,fireducks,0.000744,fireducks,0.395654,duckdb
29,WL5040 | AMD Ryzen 9 8945HS w/ Radeon 780M Gra...,0.094551,duckdb,0.167851,duckdb,0.921715,polars,0.377764,duckdb